### ISSUE TITLE
Simple PTT: add VOX TX control

### ISSUE THREAD

**Issue by hitsfm** [f4exb/sdrangel#1002]
It would be great to have a simple VOX transmit mode on the modulators. Where when input "mic" volume goes above X threshold the transit automatically holds, This would allow us for experimenting with repeater like setups using other sdr units and or software combos on the RX / internet links etc configured output using sound card virtual cables etc..

Thanks for this. Great work.

**Comment by f4exb** [comment]
At the risk of making the term "simple" in the SimplePTT feature plugin a bit abusive maybe this could be an addition to it as it relates closely to the same functionality. Thus this would be rather an enhancement to the PTT feature.

**Comment by f4exb** [comment]
Implemented in v6.17.7
