### ISSUE TITLE
How to connect to remote Soapy server?

### ISSUE THREAD

**Issue by synthead** [f4exb/sdrangel#1003]
I am having a hard time figuring out how to connect to my remote Soapy server.  I have SDRangel compiled with Soapy support on Arch Linux, linked to the lib provided by the `soapysdr` package.

On the client side, I can query the Soapy server just fine:

```
$ SoapySDRUtil --find="remote=<host>"
######################################################
##     Soapy SDR -- the SDR abstraction library     ##
######################################################

18:06:04.015390 WARN:   xtrxllpciev0_discovery:243 [PCIE] XTRX PCIe driver isn't loaded
Found device 0
  driver = remote
  label = SDRplay Dev0 RSP1A <serial>
  remote = tcp://<host>:55132
  remote:driver = sdrplay
  serial = <serial>
```

I can also connect to this Soapy server with gqrx without issues.  On gqrx, I am using this device string:

```
soapy=0,driver=remote,remote=tcp://<host>:55132
```

However, I can't seem to get SDRangel to connect to this server.  SoapySDR doesn't show up in the hardware list from Preferences > Devices > User arguments:

![image](https://user-images.githubusercontent.com/820984/133913187-6f2a509a-6219-46e8-a74c-0ef05e7d71b0.png)

I can kind of "force" it to use SoapySDR by typing "SoapySDR" into the "HwID" text field, clicking the "+" on the right, then changing the Arg string, like so:

![image](https://user-images.githubusercontent.com/820984/133913200-31b88813-632d-499b-8eed-aad633e9acdd.png)

From here, after restarting SDRangel, I see this in the sampling device list:

![image](https://user-images.githubusercontent.com/820984/133913224-4e614515-2ee7-4015-80a6-2679bd110fed.png)

However, I get this dialog box when clicking the "play" button with this source:

![image](https://user-images.githubusercontent.com/820984/133913230-66cfc760-b5c5-4cf3-8be4-d7543e1adb95.png)

When I click the play button, this line is displayed from the console that I started SDRangel:

```
2021-09-18 19:14:27.692 (W) FileInput::start: file not open. not starting
```

What am I doing wrong?

**Comment by synthead** [comment]
Related to https://github.com/f4exb/sdrangel/issues/583

**Comment by kevinelliott** [comment]
I can't get this to work either.
