### ISSUE TITLE
ValueDialZ::setValueRange sets value to 0

### ISSUE THREAD

**Issue by srcejon** [f4exb/sdrangel#1004]
It seems calling ValueDialZ::setValueRange clears the existing value to 0, if it is within the valid range.

	if(m_value < m_valueMin)
	{
		setValue(m_valueMin);
	}
	else if(m_value > m_valueMax)
	{
		setValue(m_valueMax);
	}
	else
	{
	    // Why this here?
            m_text = formatText(0);
	    m_textNew = m_text;
	    m_value = 0;
	    m_valueNew = m_value;
	    update();
	}

This seems like a bug, as none of the other Qt widgets change an in range value when setting the range - and 0 may be out side of the valid range.

If you try to save/restore the value around the call to setValueRange as a workaround, it results in the scrolling animation.

**Comment by f4exb** [comment]
This is old code and indeed a bit strange. If the value is in range and you don't change it there should not be the need of an animation.

**Comment by srcejon** [comment]
Another issue is that emit changed(m_valueMax/Min) isn't called when the value is clipped to be within range.

Perhaps the calls to emit should be moved inside the setValue function?
