### ISSUE TITLE
MacOS 14 Fixing error: call to 'abs' is ambiguous

### ISSUE THREAD

**Issue by Topper69** [f4exb/sdrangel#1010]
On macos 10.14, the fix to "sdrangel-6.16.7/plugins/feature/gs232controller/gs232controller.cpp:185:31: error: call to 'abs' is ambiguous" error on file "sdrangel/plugins/feature/gs232controller/gs232controller.cpp" :

modify line 185 186 by the following : 
`bool onTarget =   (abs((long)m_currentAzimuth - (long)targetAziumth) < readTolerance)
                   && (abs((long)m_currentElevation - (long)targetElevation) < readTolerance);`

Regards

**Comment by srcejon** [comment]
They're floating point values, so they shouldn't be cast to longs, as you'll lose precision.

I'd suggest instead trying to change the function from abs to std::fabs, you may need to add the header <cmath>

**Comment by Topper69** [comment]
Correct,

Cleaner fix is : 

add `#include <cmath>`
modify as following : 
`bool onTarget =   (std::fabs(m_currentAzimuth - targetAziumth) < readTolerance)
                   && (std::fabs(m_currentElevation - targetElevation) < readTolerance);`
