### ISSUE TITLE
FFmpeg too old to compile demoddatv? I don't think so...

### ISSUE THREAD

**Issue by fjl82** [f4exb/sdrangel#1015]
I'm getting this back from cmake. All the mentioned versions are higher than what they should be, so why does it decide not to build demoddatv?

```
-- Checking for module 'libavcodec'
--   Found libavcodec, version 58.134.100
-- Checking for module 'libavformat'
--   Found libavformat, version 58.76.100
-- Checking for module 'libavdevice'
--   Found libavdevice, version 58.13.100
-- Checking for module 'libavutil'
--   Found libavutil, version 56.70.100
-- Checking for module 'libavfilter'
--   Found libavfilter, version 7.110.100
-- Checking for module 'libswscale'
--   Found libswscale, version 5.9.100
-- Checking for module 'libpostproc'
--   Found libpostproc, version 55.9.100
-- Checking for module 'libswresample'
--   Found libswresample, version 3.9.100
-- Found FFmpeg: /usr/lib64/libavcodec.so;/usr/lib64/libavformat.so;/usr/lib64/libavutil.so;/usr/lib64/libswscale.so  
-- FFmpeg too old to compile demoddatv; needs at least avutil: 55.27.100, avcodec/avformat: 57.48.101
```

**Comment by srcejon** [comment]
What OS are you on?
Which version of ffmpeg do you have installed? Does it include the development header files?
Can you post your output for:

grep AVUTIL_VERSION CMakeCache.txt
grep AVCODEC_VERSION CMakeCache.txt

run in your build directory. That should tell us which versions cmake has found.

**Comment by fjl82** [comment]
Hi srcejon,

Thanks for your response. I'm on Fedora 34. I've installed the headers (ffmpeg-devel):
```
$ rpm -qa |grep ffmpeg
ffmpeg-libs-4.4-6.fc34.x86_64
ffmpeg-4.4-6.fc34.x86_64
compat-ffmpeg28-2.8.17-4.fc34.x86_64
ffmpeg-devel-4.4-6.fc34.x86_64
```

The library versions are included in the build log snippet posted above. CMakeCache.txt has the following:
```
$ grep AVUTIL_VERSION CMakeCache.txt
AVUTIL_VERSION:STRING=
//ADVANCED property for variable: AVUTIL_VERSION
AVUTIL_VERSION-ADVANCED:INTERNAL=1
PC_AVUTIL_VERSION:INTERNAL=56.70.100

$ grep AVCODEC_VERSION CMakeCache.txt
AVCODEC_VERSION:STRING=
//ADVANCED property for variable: AVCODEC_VERSION
AVCODEC_VERSION-ADVANCED:INTERNAL=1
PC_AVCODEC_VERSION:INTERNAL=58.134.100
```

My build of SDRangel works fine otherwise. I just decoded FM and ADS-B from my RTL dongle. But I would like to have the datv demod also, cause there's a transmit utility for the raspberry pi that I'd like to try out (rpidatv).

**Comment by srcejon** [comment]
The empty variable (without PC_ prefix) is what is being checked in plugins/channelrx/CMakeLists.txt, that is giving you the error message:

        if((AVUTIL_VERSION VERSION_GREATER "55.27.99") AND (AVCODEC_VERSION VERSION_GREATER "57.48.101"))
            message(STATUS "Include demoddatv")
            add_subdirectory(demoddatv)
        else()
            message(STATUS "FFmpeg too old to compile demoddatv; needs at least avutil: 55.27.100, avcodec/avformat: 57.48.101")
        endif()
