### ISSUE TITLE
Ubuntu 21.10

### ISSUE THREAD

**Issue by choupette-change** [f4exb/sdrangel#1018]
Does the latest version of Sdrangel work with Ubuntu 21.10?

**Comment by nmaster2042** [comment]
I built last version of SDRAngel on my updated kubuntu 21.10, no issue so far.

**Comment by srcejon** [comment]
Just giving this a try. It seems UHD v4.0.0.0 fails to build. v4.1.0.4 builds ok, but needs testing.

**Comment by m-anish** [comment]
I followed documentation to compile SDRAngel on Ubuntu 21.10. It did compile and runs but faces segfaults occasionally. 

What would be your suggestion @f4exb of a **stable** environment if I just want to be able to Tx WFM signals from a LimeSDR. Willing to clean install an OS and libraries.

**Comment by f4exb** [comment]
Just upgraded my dev system to Ubuntu 21.10 and I can see no issues.

**Comment by f4exb** [comment]
Wiki updated.

**Comment by f4exb** [comment]
For UHD you can stay on the 4.0 branch just taking the tip:
```sh
git clone https://github.com/EttusResearch/uhd.git
git fetch origin UHD-4.0
git checkout UHD-4.0
```
Wiki updated accordingly.
