### ISSUE TITLE
Fonctionne pas dsd 

### ISSUE THREAD

**Issue by gaspar1987** [f4exb/sdrangel#1021]
Il y a quelques temps la nouvelle version que vous avez mis ne fonctionne pas j'ai testé sur le numérique le numérique ne fonctionne pas 2 demeure il se met à avoir des erreurs et du son anormal si vous pouvez le réparer et changer la version une nouvelle version réparé le Dsd. Si cordialement

**Comment by f4exb** [comment]
1. La langue standard pour les tickets est l'anglais
2. Vos descriptions (comme d'habitude...) ne permettent pas de traiter votre requête de manière productive

**Comment by gaspar1987** [comment]
Hello I want to know if you put more accessories on the digital decoder if possible put Tetra to operate it is modulation in demodulator thank you if you can not it does not matter I will see on another thank you I wish you a good day

**Comment by gaspar1987** [comment]
Where the DSD does it with encoding with a bp code in automatic mode
