### ISSUE TITLE
Missing drop down in sources window on HDPI displays.

### ISSUE THREAD

**Issue by vsboost** [f4exb/sdrangel#103]
Hi there,
Seem to be missing the drop down window for source devices.
![image](https://user-images.githubusercontent.com/11001973/33602707-438d8064-da04-11e7-9b6b-7f60753473b6.png)

Windows 10 Surface pro.

**Comment by Daniel-dk** [comment]
I'm getting the same on a win10 pro desktop

**Comment by vsboost** [comment]
Think this is a high-dpi issue.

**Comment by f4exb** [comment]
What do you mean by "high-dpi"? Even with no devices connected you should get "FileSource" and "SDRdaemonSource" in the list so I was thinking that in your particular installation these two plugins do not load correctly for some unknown reason.

**Comment by f4exb** [comment]
If you can display it you may try to activate the log to file in debug mode with preferences -> logging menu. Then close and restart the application. On the next run it will log messages to file which may give indication if the plugins load correctly or not:
![image](https://user-images.githubusercontent.com/6192319/33803520-b82daf52-dd92-11e7-86a5-6859cb05b361.png)

**Comment by ChiliX** [comment]
Had exactly the same problem on a Retina MacBook Pro & Win10 in BootCamp. By switching screen resolution to 1920x1200 I could see the drop down list and select the source device.

**Comment by antoine-roux** [comment]
Hello, I confirm the high-DPI issue: on a given machine (ArchLinux) the dropdown is displayed correctly with a 1.0 scaling but not on a 2.0 scaled display.

Salut à toi, sur les affichages haute densité (les Surface de Microsoft ont des écrans à 267 dpi) la dropdown n'est pas affichée. Le programme se comporte différemment en fonction de la densité de pixels. Le problème est tout récent, j'ai pu l'utiliser correctement avant que je le mette à jour il y a environ une semaine.
Sur Windows, essaye de jouer sur la taille de police système (Display -> Font size). Mets la à 200% pour voir apparaître le problème.
Sur Linux essaye de changer org.gnome.desktop.interface scaling-factor ou org.gnome.desktop.interface text-scaling-factor à 2.0

Bien à toi,
Antoine

**Comment by vsboost** [comment]
![image](https://user-images.githubusercontent.com/11001973/33877872-dfffea12-df7d-11e7-9dc7-0b173d78de59.png)

Seems to fix it for me.

**Comment by antoine-roux** [comment]
Yes, but it's still an issue on Linux.

I have two different behaviors on my machine:
When my primary screen is not an HDPI one, I run sdrangel with `QT_AUTO_SCREEN_SCALE_FACTOR=0 QT_SCREEN_SCALE_FACTORS="1;1;2" sdrangel`, everything runs smoothly (3 screens: first one and second one in standard DPI and the third in HDPI). And I can move the program between my screens, the DPI changes on-the-fly.

But curiously, with only one screen and using the native HDPI scaling, I can not get the dropdown working. Even I play with `QT_*` variables...
![source-native](https://user-images.githubusercontent.com/2011328/33884919-e098b3f0-df41-11e7-84c7-dfb69233054c.png)

Cheers,
Antoine

**Comment by f4exb** [comment]
It looks like the QT variables for HDPI support were introduced in Qt 5.6 and the Xenial (Ubintu 16.04) version is compiled with Qt 5.5 so I guess you will need at least Zesty (Ubuntu 17.04) that compiles with Qt 5.7 to have it work.

**Comment by f4exb** [comment]
The source of the dialog is at sdrgui/gui/samplingdevicedialog.ui If anyone notices something missing for HDPI support they're welcome to provide a fix.

**Comment by antoine-roux** [comment]
@f4exb I'm using Qt 5.10 on ArchLinux

**Comment by f4exb** [comment]
This question would be better answered at: https://groups.io/g/sdrangel

**Comment by f4exb** [comment]
Sorry nothing I can do it seems to be Qt business.

**Comment by simonvik** [comment]
https://doc.qt.io/qt-5.6/qtlabscontrols-highdpi.html does seem to help on it, the UI renders somewhat correctly when setting that env, all icons are scaled and resolution is somewhat low but the dialog box works. Will try to play a bit more with this.

**Comment by simonvik** [comment]
Its good enough for me to set QT_SCALE_FACTOR or QT_AUTO_SCREEN_SCALE_FACTOR and i think that ubuntu might do this too globaly somewhere.

**Comment by f4exb** [comment]
I'll be adding this in the [main app code](https://github.com/f4exb/sdrangel/blob/master/app/main.cpp) for next version. It may be useful and anyway it does not seem to hurt:
```
    QApplication::setAttribute(Qt::AA_EnableHighDpiScaling); // DPI support
    QCoreApplication::setAttribute(Qt::AA_UseHighDpiPixmaps); //HiDPI pixmaps
```

**Comment by ktoksoz** [comment]
I compiled master branch right now and can say that bug does not fixed.. It stil looks funny and dropdown does not have a down arrow to select.

**Comment by f4exb** [comment]
Sorry, no issues here.

**Comment by vsboost** [comment]
Thanks for fixing this. v4.14.9

![image](https://user-images.githubusercontent.com/11001973/85193413-a1df4e80-b30b-11ea-9eaa-060960b37c45.png)
![image](https://user-images.githubusercontent.com/11001973/85193416-aa378980-b30b-11ea-94e3-1fc8b1509f10.png)
