### ISSUE TITLE
Enhancement: Add Logging to .csv File in Data Modes (AIS, APRS, ADS-B, etc)

### ISSUE THREAD

**Issue by df6dbf** [f4exb/sdrangel#1035]
Hello Edouard,
it would be nice if there was a possibility in the data modes to save the logged information with the date and time in an ASCII file. E.g. as a CSV file. Further processing would then be much easier.

73s Holger, DF6DBF

**Comment by srcejon** [comment]
Do you just want the hex values for the packets or fully decoded frames?

**Comment by df6dbf** [comment]
For me are the "human readable" data of interest. but I think there are other OM who prefer the hex values. I think both makes sense. Maybe with the capability to filter.

**Comment by f4exb** [comment]
Implemented in v6.17.3
