### ISSUE TITLE
Missing plugins for linux release vs Windows release.  

### ISSUE THREAD

**Issue by mikeream** [f4exb/sdrangel#1042]
Release 6.17.3 seems to have plugins on the Windows version that are not in the Linux version.  One specifically missing is the DSD demodulator plugin that was contained in the Windows binary and did NOT show up when I installed the Linux one.  Did I do something wrong or is it just missing?

**Comment by srcejon** [comment]
Have you set the library path as per #777

**Comment by ftcteam8645** [comment]
That was my error.  Thank you.

**Comment by mikeream** [comment]
Once I added the path "export LD_LIBRARY_PATH=/usr/lib/sdrangel", everything worked correctly.  Thank you.
