### ISSUE TITLE
airports and heliports icons

### ISSUE THREAD

**Issue by choupette-change** [f4exb/sdrangel#1044]
Hello, version 6 17 3 (Ubuntu 21.04 and Windows 10), the airports and heliports icons do not display on the ADSB Modulator plug-in map ??
![image](https://user-images.githubusercontent.com/68333247/141477166-11cfb61b-9bcf-482b-9f64-4ce5dc9822a0.png)

**Comment by choupette-change** [comment]
on the map feature too

**Comment by srcejon** [comment]
You have the airport display distance at 1km - that means it will only display airports within 1km of your antenna position - change that to 100km or so.

**Comment by srcejon** [comment]
Note that the Map feature doesn't currently display Airports - but I'm working on supporting it.

**Comment by choupette-change** [comment]
I just tried 1, 10, 100, 1000 km nothing is displayed, it worked in previous versions (including 1 km), I have an airport 12 km from my home

**Comment by srcejon** [comment]
Try redownloading the airport database

Check C:\Users\you\AppData\Roaming\f4exb\SDRangel\airportDatabase.csv - it should be about 10MB

**Comment by choupette-change** [comment]
I have done this several times already and I cannot find this airportDatabase.csv file on Ubuntu (locate airportDatabase.csv) and Windows. But I think there is a pb, pressing the icon is very short and fast and I don't think a file is actually downloaded (problem de lien URL ?)
