### ISSUE TITLE
Rotator control feature request

### ISSUE THREAD

**Issue by lrowen** [f4exb/sdrangel#1045]
Requesting that the hamlib rotctld protocol be added to the rotator controller; this would open the satellite tracker and star tracker features to many more rotators.

For settings, would need an IP address and TCP port # to connect to the rotctld daemon.

**Comment by lrowen** [comment]
Further information: I have a system here with a rotctld driver that I currently control with GPredict, and I am happy to test functionality.

**Comment by f4exb** [comment]
Implemented in v6.17.4
