### ISSUE TITLE
Reordering in preset save/load breaks links between plugins

### ISSUE THREAD

**Issue by srcejon** [f4exb/sdrangel#1051]
We have several plugins that have settings that refer to other plugins. E.g. in Rotator Controller, you can specify the source plugin as R0:0 or R1:2 etc

Currently, when presets are saved or loaded (not sure which), the channels and features are reordered alphabetically. This means that the  settings that point to other plugins may no longer be correct.

**Comment by f4exb** [comment]
This is at "save" time. For the Rx channels here: https://github.com/f4exb/sdrangel/blob/master/sdrbase/device/deviceset.cpp#L220 and similarly for Tx at line 321 and MIMO at line 424.

Similarly for features this is done here: https://github.com/f4exb/sdrangel/blob/master/sdrbase/feature/featureset.cpp#L182

So these calls have to be suppressed.

**Comment by f4exb** [comment]
Well, seems it is also somewhere else but only for the UI ...
https://github.com/f4exb/sdrangel/blob/master/sdrgui/device/deviceuiset.cpp#L226
and
https://github.com/f4exb/sdrangel/blob/master/sdrgui/feature/featureuiset.cpp#L166
