### ISSUE TITLE
About drm signal in new sdrangel software

### ISSUE THREAD

**Issue by longyucheng123** [f4exb/sdrangel#106]
I hope to add the modulation and demodulation of the Drm signal in the new version. Thank you!

**Comment by f4exb** [comment]
This is a great idea to have a DRM plugin. I hope it is not too difficult to implement a new plugin. I think it could be done along the lines of the analog voice demodulators (AM, FM, SSB or WFM) that could be used as a base. Do not hesitate to comment if you have any questions.

**Comment by mpbraendli** [comment]
Hi,
https://github.com/Opendigitalradio/qt-drmplus could maybe help.
73 HB9EGM

**Comment by f4exb** [comment]
Looks interesting thanks! Other repositories of the same author show work about DAB also.

**Comment by mpbraendli** [comment]
Otherwise there's also https://github.com/kit-cel/gr-drm

**Comment by f4exb** [comment]
dropped

**Comment by AsciiWolf** [comment]
Any chance this could be implemented? It would be really great to have [DRM](https://www.drm.org/what-is-drm/) receiver in SDRangel. It could be based on [Dream](https://sourceforge.net/projects/drm/) software receiver.
