### ISSUE TITLE
is this a bug ?? plugin ADSB

### ISSUE THREAD

**Issue by choupette-change** [f4exb/sdrangel#1062]
Hello, is this a bug ?? For example, if I position "My home" at the coordinates of Geneva airport (Geneva Cointrin International Airport) on the map "My home" is ok, but Geneva airport is badly positioned at 27.8 km from "My Home" ?? ? I took the coordinates in the "airportDatabase.csv" file. I installed SDRANGEL with the latest .deb. Several airports are positioned at the same place ?? Is it a km / mile conversion problem or Anglo-Saxon/European input (. or ,) ??? it's ok with the Windows version of SdrAngel. Thanks for your feedback.
![image](https://user-images.githubusercontent.com/68333247/143684170-799eab65-8d31-41fd-a271-3a335ddb18a4.png)
![image](https://user-images.githubusercontent.com/68333247/143684229-d53cc65e-28ec-4f97-bdcf-a672b7668952.png)
![image](https://user-images.githubusercontent.com/68333247/143684351-68646bd5-a7a1-47b4-9759-17f75b1120a9.png)

**Comment by srcejon** [comment]
There seems to be a small issue that when the map first appears, some icons are in the wrong location:

![image](https://user-images.githubusercontent.com/57259258/143763588-0597e67d-14c1-49ce-9325-2788a4234314.png)

However, if you pan or zoom, then then immediately move to the correct place:

Here's LSGG centered on the runway:

![image](https://user-images.githubusercontent.com/57259258/143763606-f3efa855-4533-4326-a403-ed0a2db8484c.png)

I can't reproduce what is in your pictures.

**Comment by srcejon** [comment]
I do notice your version of Qt is older than mine (5.12 vs 5.14) - and the mapping is part of Qt

**Comment by srcejon** [comment]
When you say you installed from the latest .deb - what's the link to the file you used? Thanks.

**Comment by f4exb** [comment]
The .deb in the "assets" section of the releases is for Ubuntu 20.04 and hence Qt 5.12.8

**Comment by srcejon** [comment]
Thanks.

Works for me with Qt 5.12.8 and Ubuntu 20.04.03 LTS as well using the 6.17.4 .deb file.

**Comment by choupette-change** [comment]
I had reinstalled a blank version of Ubuntu 20 04, .deb link : https://github.com/f4exb/sdrangel/releases/download/v6.17.4/sdrangel-1183-master.tar.gz. See my screenshots above for Ubuntu, Sdrangel and Qt versions.
I just reinstalled Sdrangel on another PC, by sources, SDRangel 6 17 4 and Qt 5 15 2 on Ubuntu 21 10 and I have exactly the same problem ???

**Comment by srcejon** [comment]
> Several airports are positioned at the same place ?? Is it a km / mile conversion problem or Anglo-Saxon/European input (. or ,) ?

Yes, looks like a , . problem due to the value of LC_NUMERIC.

**Comment by choupette-change** [comment]
I tested the latest version it's ok for me :)
![image](https://user-images.githubusercontent.com/68333247/143892860-7bdb2b5a-fb98-42fa-83b8-788796275a49.png)
