### ISSUE TITLE
No "satellite Map" on the Ubuntu 21 10 version

### ISSUE THREAD

**Issue by choupette-change** [f4exb/sdrangel#1067]
There's no "Satellite Map" on the Ubuntu version, ok Windows version.
![image](https://user-images.githubusercontent.com/68333247/143875788-541d9228-e38b-49ab-84d4-0ed4d947b9bb.png)

**Comment by srcejon** [comment]
It's working for me:

![image](https://user-images.githubusercontent.com/57259258/143881599-f6abdc31-e22d-4b1d-ad63-f9c2cb51264f.png)

Can you send a screenshot of your Map settings window?

Note that the list of maps is dynamic - so if there was a temporary problem connecting to the satellite map provider, it may not appear in the drop down. Try starting SDRangel again and see if it appears.

Also check log file for any Map/SSL messages.

**Comment by choupette-change** [comment]
I restarted SdrAngel with the last version it's ok but the display is "capricious", I have to close the feature map and reopen it to show the "satellite map" tab when I restart sdrAngel. For the map plugin it's always ok .... :(
![image](https://user-images.githubusercontent.com/68333247/143893094-af54ba14-f9e5-4648-b557-4265eb821356.png)

**Comment by protektwar** [comment]
I have a white screen where the map should be.... 
![image](https://user-images.githubusercontent.com/45262264/158048390-12b2cd86-ac17-41ff-81e4-a64fe3244f88.png)

**Comment by srcejon** [comment]
Can you post your log file? Quite possibly a missing dependency.

**Comment by protektwar** [comment]
Where do I find the log file?

**Comment by srcejon** [comment]
Preferences > Logging menu.

**Comment by protektwar** [comment]
Done, attached...
[sdrangelLog.log.zip](https://github.com/f4exb/sdrangel/files/8239306/sdrangelLog.log.zip)

**Comment by srcejon** [comment]
2022-03-13 10:59:49.444 (W) qrc:/map/map.qml:5:1: module "QtPositioning" is not installed
2022-03-13 10:59:49.444 (W) qrc:/map/map.qml:4:1: module "QtLocation" is not installed

See: https://github.com/f4exb/sdrangel/wiki/Compile-from-source-in-Linux for packages to install

**Comment by protektwar** [comment]
![image](https://user-images.githubusercontent.com/45262264/158054593-8b97b4ec-4ec7-4498-ae5c-b3ca5c64329a.png)

**Comment by srcejon** [comment]
Do you have qtlocation5 as well as qtlocation5-dev?

**Comment by protektwar** [comment]
I have copy/paste -d the long package list: the only new installed packages have been these, I think the mission was qml qtlocation and qtpositioning, now it's working.
The following NEW packages will be installed:
  doxygen libhidapi-dev libusb-dev libxml2-dev qml-module-qtlocation qml-module-qtpositioning

Thanks!
