### ISSUE TITLE
AIS and ADSB decoders: improvement proposal

### ISSUE THREAD

**Issue by choupette-change** [f4exb/sdrangel#1068]
Can we provide data output in .kml format for use with Google Earth for AIS and ADSB decoders so as to have the trajectories in 3D .. ?
![image](https://user-images.githubusercontent.com/68333247/144202300-8133f7e4-3bab-4982-a129-8a2c26f008b8.png)

**Comment by f4exb** [comment]
AIS is for ships on the sea so is 3D really useful?

**Comment by choupette-change** [comment]
Of course not, my 3d request is mainly for aircraft trajectories but I am also interested in outputting AIS data in .kml format if possible :)

**Comment by srcejon** [comment]
I guess the best place for this, would be in the Map feature, so that all the different objects the map supports can be exported, and only needs to be implemented in one plugin.

**Comment by srcejon** [comment]
The SDRangel Map feature now supports 3D:

![image](https://user-images.githubusercontent.com/57259258/152678831-45bdb322-2c3b-4107-84be-ddb323f69449.png)

![image](https://user-images.githubusercontent.com/57259258/152678855-dc463694-b764-4210-9faa-75e61d284038.png)

Do you really want .kml as well, or will this do?

**Comment by choupette-change** [comment]
Hello, I haven't tested the 3D maps yet where can we find them and the
V6.19? If possible i want .kml output.
Greetings

**Comment by f4exb** [comment]
v 6.19 is yet to be released but the 3D map feature is already in the master branch

**Comment by choupette-change** [comment]
error when installing the latest master:

make[2]: ***
[pluginssrv/channelrx/demodapt/CMakeFiles/demodaptsrv.dir/build.make:147 :
pluginssrv/channelrx/demodapt/CMakeFiles/demodaptsrv.dir/aptdemodimageworker.cpp.o]
Erreur 1
make[2]: *** Attente des tâches non terminées....
[ 41%] Building CXX object
pluginssrv/channelrx/noisefigure/CMakeFiles/noisefiguresrv.dir/noisefiguresettings.cpp.o
[ 42%] Building CXX object
pluginssrv/channelrx/noisefigure/CMakeFiles/noisefiguresrv.dir/noisefigurebaseband.cpp.o
make[1]: *** [CMakeFiles/Makefile2:12640 :
pluginssrv/channelrx/demodapt/CMakeFiles/demodaptsrv.dir/all] Erreur 2
make[1]: *** Attente des tâches non terminées....
[ 42%] Building CXX object
pluginssrv/channelrx/noisefigure/CMakeFiles/noisefiguresrv.dir/noisefiguresink.cpp.o
[ 42%] Building CXX object
pluginssrv/channelrx/sigmffilesink/CMakeFiles/sigmffilesinksrv.dir/sigmffilesinkbaseband.cpp.o
[ 42%] Building CXX object
pluginssrv/channelrx/noisefigure/CMakeFiles/noisefiguresrv.dir/noisefigureplugin.cpp.o
[ 42%] Building CXX object
pluginssrv/channelrx/noisefigure/CMakeFiles/noisefiguresrv.dir/noisefigurewebapiadapter.cpp.o
[ 42%] Building CXX object
pluginssrv/channelrx/sigmffilesink/CMakeFiles/sigmffilesinksrv.dir/sigmffilesinksink.cpp.o
[ 42%] Building CXX object
pluginssrv/channelrx/sigmffilesink/CMakeFiles/sigmffilesinksrv.dir/sigmffilesinksettings.cpp.o
[ 42%] Building CXX object
pluginssrv/channelrx/sigmffilesink/CMakeFiles/sigmffilesinksrv.dir/sigmffilesinkmessages.cpp.o
[ 42%] Building CXX object
pluginssrv/channelrx/sigmffilesink/CMakeFiles/sigmffilesinksrv.dir/sigmffilesinkwebapiadapter.cpp.o
[ 42%] Building CXX object
pluginssrv/channelrx/sigmffilesink/CMakeFiles/sigmffilesinksrv.dir/sigmffilesinkplugin.cpp.o
[ 42%] Linking CXX shared library
../../../lib/pluginssrv/libnoisefiguresrv.so
[ 42%] Linking CXX shared library
../../../lib/pluginssrv/libsigmffilesinksrv.so
[ 42%] Built target noisefiguresrv
[ 42%] Built target sigmffilesinksrv
make: *** [Makefile:171 : all] Erreur 2
***@***.***:~/SDRangel/sdrangel/build$

**Comment by srcejon** [comment]
You don't appear to have pasted the actual error.

However, please make sure that you've git pulled and rebuilt / installed aptdec.

**Comment by choupette-change** [comment]
thanks for the tip, i reloaded aptdec and it works. I will test the 3d cards :)

**Comment by srcejon** [comment]
Implemented in 7.20
