### ISSUE TITLE
An error ... may be?

### ISSUE THREAD

**Issue by hiperiondev** [f4exb/sdrangel#1070]
This is not absolutely critical, but when close Sdrangel return this error:

/usr/include/c++/11/bits/stl_vector.h:1045: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = FeatureUISet*; _Alloc = std::allocator<FeatureUISet*>; std::vector<_Tp, _Alloc>::reference = FeatureUISet*&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__n < this->size()' failed.

**Comment by f4exb** [comment]
Such a small excerpt does not help. Is it part of a larger stack trace? Do you have the log right before it crashes?

**Comment by hiperiondev** [comment]
If I start from console this is the only "strange" output when push close window button on sdrangel or exit with File->Exit. If I kill the process with ctrl+c nothing return.

**Comment by hiperiondev** [comment]
I said not absolutely critical because it only happens when the program is voluntarily closed. But it could be a symptom of another type of error.

**Comment by srcejon** [comment]
I don't see this error message, with the latest release on Ubuntu 20.04 or 21.10.

It might be useful if you tell us what version of SDRangel you are using, what O/S and what plugins, if any, you have open.

**Comment by f4exb** [comment]
I see `/usr/include/c++/11/bits/stl_vector.h` so you are basically on a Linux system. The message is just the output of the assert to the console but usually this goes with a core dump and it would be useful if you could inspect it with gdb and get the stack trace. Of course to be really useful the code should be compiled with debug symbols (release with debug info). The rest of the message seems to relate to the array of `FeatureUISet` and possibly trying to access a non existent index (beyond the size limit). We are at exit time so one possibility is that it is trying to access an element already deleted although I do not see any obvious flaw in the code.
