### ISSUE TITLE
SDR-Angel does not safe the whole configuration if a source- and sink device is defined

### ISSUE THREAD

**Issue by RaspCla** [f4exb/sdrangel#1072]
I am using SDR-Angel v. 6.17.4, Build info:  QT5.15.2 64 bits
on a Windows 10 64 Bit machine, Version 10.0.19044 Build 19044
Prozessor	Intel(R) Core(TM) i7-2700K CPU @ 3.50GHz, 3501 MHz, 4 Kern(e), 8 logische(r) Prozessor(en)

I've configured a HackRF sink and source device, not using SoapySDR (delete SoapySDR.dll)
It seems that I'm not able to store Sink devices at all
Best Regards

**Comment by f4exb** [comment]
This is already discussed in #1050 In any case only the first device set R0 settings will be saved and restored upon program close and reopen. To save and restore complex configurations you will have to resort to a new framework to be implemented in #1050
