### ISSUE TITLE
Decode TETRA

### ISSUE THREAD

**Issue by jonas18z** [f4exb/sdrangel#108]
Is it possible to decode unencrypted tetra?
http://www.rtl-sdr.com/tetra-decoding-on-windows-with-telive/
http://tetra.osmocom.org/trac/

**Comment by f4exb** [comment]
There is presently not such plugin although it would be nice (contributors welcome). However you can use SDRangel as a radio front end to the decoding part in GNUradio by piping I/Q samples into GNUradio via UDP. 

  - On SDRangel side use the "UDP Channel Source" channel plugin in I/Q mode (source for external programs)
  - On GNUradio use a UDP source block (source in a graph)

**Comment by DG9BFC** [comment]
what about adding a "normal" support via virtual audio cable?!? then any use can setup any decoding software with sdrangel (like done in nearly all other sdrsoftware)

**Comment by f4exb** [comment]
Virtual audio cable is usually not a very smart way to connect applications. Wisely enough GNUradio uses UDP to transfer samples and this could be used with SDRangel.

Anyway and on Linux only portaudio is used which should make some audio plumbing possible.

**Comment by E3V3A** [comment]
@jonas18z You also found [this](https://github.com/sq5bpf/telive), right?

**Comment by jonas18z** [comment]
Yes but I wanted it in de sdrangle

**Comment by opabert** [comment]
> 
> 
> There is presently not such plugin although it would be nice (contributors welcome). However you can use SDRangel as a radio front end to the decoding part in GNUradio by piping I/Q samples into GNUradio via UDP.
> 
>     * On SDRangel side use the "UDP Channel Source" channel plugin in I/Q mode (source for external programs)
> 
>     * On GNUradio use a UDP source block (source in a graph)

Try contact

**Comment by opabert** [comment]
Like test new tetra plugin any contact with author possible?

**Comment by gaspar1987** [comment]
hello  sur le  4.11.5  la crypto voice DMR TERMINALE sur dsd demodeur .

**Comment by f4exb** [comment]
Someone pointed out this to me that can be interesting: https://gitlab.com/larryth/tetra-kit
It was also metioned in this RTl-SDR.com post: https://www.rtl-sdr.com/tetra-kit-a-new-open-source-tetra-decoder/

**Comment by f4exb** [comment]
dropped
