### ISSUE TITLE
Pouvez-vous faire un décodeur de TNT

### ISSUE THREAD

**Issue by gaspar1987** [f4exb/sdrangel#1090]
Pouvez-vous créer un décodeur de TNT grâce à vos logiciel que vous créez s'il vous plaît si vous pouvez en créer un ça serait bien pour regarder la télé.

**Comment by f4exb** [comment]
Not sure general purpose SDR is the most efficient way to watch telly. Anyway this request has been done before and is still active in the log: https://github.com/f4exb/sdrangel/issues/182.

So I am closing this one in favor of the older.
