### ISSUE TITLE
ABS 1090 MHZ  

### ISSUE THREAD

**Issue by gaspar1987** [f4exb/sdrangel#1096]
METTERE LA RADIO DANS LE LOGICIE POUR   ECOUTE LES COMVERSATION  PILOTE DE LA TOUR CONTROLE ET  PILOTE AVIONS !

**Comment by srcejon** [comment]
You can do this by adding an AM Demodulator and then clicking on the frequency you want to listen to on the map.

You will need multiple SDRs if you want to do both at the same time, as the frequencies are so far apart.

**Comment by gaspar1987** [comment]
Merci pour le renseignement. 👍

**Comment by f4exb** [comment]
Question answered thanks.
