### ISSUE TITLE
ADS-B broken flight tracks

### ISSUE THREAD

**Issue by MightyPork** [f4exb/sdrangel#1103]
My ADS-B decoder often adds a fixed horizontal offset to plane position, resulting in broken zigzag paths.
Good chance I set something wrong, but I can't figure out what.

SDRangel 6.17.7, receiving with NooElec NeSDR on Arch Linux with a ground-plane antenna.

Logfile: 
[sdrangel.txt](https://github.com/f4exb/sdrangel/files/7868475/sdrangel.txt)

Setup and the bug:
![Screenshot_20220114_075116](https://user-images.githubusercontent.com/2041118/149466053-6f85f659-2954-4511-929f-474efe5c052b.png)
![Screenshot_20220114_075129](https://user-images.githubusercontent.com/2041118/149466054-1ecde2f2-9e5f-41d0-bec5-cf5d5b30026d.png)
![Screenshot_20220114_075142](https://user-images.githubusercontent.com/2041118/149466056-9580704b-a5ef-4428-ba68-8c4edd14cb2a.png)
![Screenshot_20220114_075150](https://user-images.githubusercontent.com/2041118/149466060-46fe973c-30b9-412c-8e20-aa58c4dff8c4.png)

My antenna:
![IMG20220114075838s](https://user-images.githubusercontent.com/2041118/149466027-a0525bb1-463e-4268-83ac-0d5269a5171e.jpg)

I'm quite sure the reception itself is good, dump1090 does not have this problem:
![Screenshot_20220114_081039](https://user-images.githubusercontent.com/2041118/149466343-0973ec6c-1f3f-4196-850b-642be5d63e28.png)

**Comment by srcejon** [comment]
Have you set your position correctly  under Preferences > My position

**Comment by MightyPork** [comment]
You're right, I did not. I didn't even know that option exists! It works better with the setting.

Out of curiosity, what do you think was causing the glitch? Do ADS-B frames send the position with ambiguity that must be resolved this way?

**Comment by srcejon** [comment]
Yep, they don't always broadcast full coordinates - see: https://mode-s.org/decode/content/ads-b/3-airborne-position.html

There may be other ways to handle it - but best to set your position, as it's used for various things in SDRangel.

**Comment by MightyPork** [comment]
Okay, I'm closing this then. Perhaps the readme could be more explicit about the necessity to set the position.

From friefly reading the source, it looks like dump1090 waits for two messages and uses the following algorithm for disambiguation http://www.lll.lu/~edward/edward/adsb/DecodingADSBposition.html

**Comment by srcejon** [comment]
I'll update the readme. I'll also see if I can display a message if My Position is set to the default values.

The plugin does use the global decoding that requires two messages, but it also does a local decode that can work on just one position message + position of the receiver.
