### ISSUE TITLE
Minor typo in rgetz page

### ISSUE THREAD

**Issue by AlanM1** [f4exb/sdrangel#1109]
Not sure where/how the page is generated, but at the top of https://rgetz.github.io/sdrangel/ there is a typo of a backslash instead of a slash in the closing tag of:

> `Developer docs for <a href="https://github.com/f4exb/sdrangel">SDRangel<\a>`

causing the HTML code to appear instead of just the linked <a href="https://github.com/f4exb/sdrangel">SDRangel</a>.

**Comment by f4exb** [comment]
Please post issue in rgetz repository
