### ISSUE TITLE
SDRPLAY RSP1 and Win7 64 bit

### ISSUE THREAD

**Issue by StephaneG73** [f4exb/sdrangel#111]
Hello
Can anyone tell me if the SDRPlay RSP1 is compatible with SDRAngel under windows ?.
I am under Windows 7 64 bit and after having launched SDRAngel, when I go under select sampling device I see only ” file source ” or ” SDRdaemonsource ” I do not see my SDRPlay is it normal ?.
 I do not understand What to do .
Can you help me ?
I apologize for my english, I’m french 🙂
Thank you

**Comment by f4exb** [comment]
SDRplay is not supported in Windows so it is normal that you don't see it. It is based on libmirisdr and is too unstable in Windows so the plugin is not built there.
