### ISSUE TITLE
STRangel and DAB 

### ISSUE THREAD

**Issue by clivekay** [f4exb/sdrangel#1112]
Can’t get it to work at all , what settings do I need ? I upped the SR to over 2048 megs but nothing happens …also no DAB in the MAC version installed under macports and on fm does RDS work ?

**Comment by srcejon** [comment]
A screenshot might help.

**Comment by clivekay** [comment]
Enclosed nothing seems to work , I do get fm radio but no stereo …

**Comment by clivekay** [comment]
Got it to work but not very good ! Crashes the computer and Audio seems speeded up !

**Comment by srcejon** [comment]
I can't see a screenshot. Try adding via webpage, rather than email.

**Comment by clivekay** [comment]
Got it running the RF gain was hidden !! How do you stop the audio and waterfall being choppy ! Is it poss to do the broadcast fm in stereo ?

**Comment by clivekay** [comment]
Sorted it by using an  sdrplay instead of an RTL-SDR. That worked fine !

**Comment by f4exb** [comment]
This can be closed
