### ISSUE TITLE
Sat Tracker does not always stop APT demod automatically at LOS

### ISSUE THREAD

**Issue by choupette-change** [f4exb/sdrangel#1129]
Hello, are you sure it is working correctly? I see problems again. https://github.com/f4exb/sdrangel/issues/893
Thank you for your help

**Comment by srcejon** [comment]
I made some additional changes for this yesterday. Were you using the build with the 3D map when you saw this, or an older version?

**Comment by choupette-change** [comment]
![image](https://user-images.githubusercontent.com/68333247/152678023-5a801326-9400-448f-b583-7499553e513d.png)
I used this version (see screenshot), should I load the latest version?

**Comment by srcejon** [comment]
Ok, thanks. A "better" fix should be in the next release of SDRangel. So let us know if you still have problems after 6.19 is released.

**Comment by choupette-change** [comment]
Thanks for your quick return. Another improvement, if possible, add "My position" on the map produced by the satellite. In cloudy weather, it is difficult to identify geographically.

**Comment by srcejon** [comment]
You get that with the new 3D Map - one of the Red dots in this image is "my position" and you can customise what is drawn for it and the transparency of the clouds etc.

![image](https://user-images.githubusercontent.com/57259258/152678622-3efc1899-ebc2-441c-8480-8cae8579d9cd.png)

**Comment by srcejon** [comment]
Have you seen this problem with the most recent version?

**Comment by choupette-change** [comment]
Now it's ok with new versions Thanks
