### ISSUE TITLE
SSBDemodSink::feed: 0/512 tail samples written

### ISSUE THREAD

**Issue by Valstee** [f4exb/sdrangel#1132]
I'm playing with Raspberry PI 4 and sdrangel server to do some really simple receiving station for nanosatellite/metrological satellite 
but I also use sdrangel gui on a desktop PC to test and improve things.

### Subject or type of issue
After several days of use, i have very often this error message when i use a demodulator and satellite tracker which drives the channel:
(D) SSBDemodSink::feed: 0/512 tail samples written
So I have some freeze of the waterfall and of the audio signal that cuts out very briefly on a regular basis (about every second = this is also the refresh rate I put on satelitte tracker).  I also use File sink to record the passage, it is triggered by sat tracker but the doppler is not driven by the feature (while the demodulator has the doppler driven by sat tracker)

### SDR
I use SDRangel 6.16.2-5-g991d25bcb with Ubuntu 20.04.3 LTS ,x86_64 and qt 5.12.8

### Steps to reproduce
I've got this only with the GUI version but it appears after 3 or 4 days of use...

### Log Files
(D) SSBDemodSink::feed: 0/512 tail samples written 
(D) SSBDemodSink::feed: 0/512 tail samples written 
(D) SSBDemodSink::feed: 0/512 tail samples written 
.....
The error line appears several times in a row (between 4 and 10 times and about every second).

I found something here: https://groups.io/g/sdrangel/message/933
But I don't use docker to run the GUI version

**Comment by srcejon** [comment]
I see this fairly frequently on Windows without the Satellite Tracker.

**Comment by f4exb** [comment]
I also noticed this on Linux more often when the system is stressed. In fact the message is sent from here: https://github.com/f4exb/sdrangel/blob/master/plugins/channelrx/demodssb/ssbdemodsink.cpp#L247 So it should rather start with `SSBDemodSink::processOneSample` but the code was probably split off the `feed` method at some point without updating the message. Apparently it has to do with the audio buffer being full and not accepting any more input (the write returns 0 bytes just above). Possibly 512 bytes is too small for the buffer damping to work in all situations. With 16 bit stereo this is only 128 samples thus only 2.67ms at 48 kHz. I have to check how the other plugins with audio are written I think I observed these messages only or mostly on the SSB demod.

**Comment by f4exb** [comment]
Indeed it does not seem necessary to write the residual audio samples at this point. The same logic exists for the AM demod, BFM demod, FreeDV demod, NFM demod, VOR demods and WFM demods. Although in all other cases but SSB it is less problematic since it happens on the `feed` call and not for every sample. However some optimization could be done there also.

**Comment by Valstee** [comment]
ok, thanks a lot for the explanation. 
I didn't have the skills to identify the problem but your explanations allow me to understand better how sdrangel works.
