### ISSUE TITLE
E: Unable to locate package qtwebengine5-dev

### ISSUE THREAD

**Issue by Valstee** [f4exb/sdrangel#1133]
Hi, I can't install this package on my Debian Bullsesye Raspberry. Is this problematic for the good functioning of sdrangel_server ?
Thanks a lot, 
Best regards,
Valentin

**Comment by f4exb** [comment]
Anyway I do recommend Ubuntu server 64 bits for RPi4 or 3B+

**Comment by alphafox02** [comment]
If it’s Ubuntu server it’s likely 20.04 based, which I’m finding the 3d map doesn’t work on x64 20.04. I suspect that same result on the pi which I’ll check later.
