### ISSUE TITLE
DATV plugin without 9,999 MHz BW filter

### ISSUE THREAD

**Issue by fxzzze** [f4exb/sdrangel#1136]
Some signals are now increasingly bigger and faster, I have the problem with one at a 12+MBPS so bigger than the filter. I know this is a DVB-S with 2/3 FEC, just can't get it to work for a probable simple limitation.

Would that be easy to increase the max BW ?

**Comment by fxzzze** [comment]
If I'm reading this correctly this is the modulator not the demodDATV unfortunately

**Comment by f4exb** [comment]
Implemented in v6.19.1
