### ISSUE TITLE
Spectrum marker cur/max doesn't appear at correct level when zoomed in

### ISSUE THREAD

**Issue by srcejon** [f4exb/sdrangel#1140]
Hi,

I'm trying to use the Spectrum Markers with the Cur/Max setting. It's doesn't appear to work properly when zoomed in.

When zoomed out, the marker is at -9.5dB as expected:

![image](https://user-images.githubusercontent.com/57259258/153382534-7827be61-fda7-4e9f-95d6-32ffa006073a.png)

When zooming in it drops to -72db:

![image](https://user-images.githubusercontent.com/57259258/153382685-0a2ef188-677b-4fb2-9b6b-dec2364cc16a.png)

**Comment by f4exb** [comment]
Possibly the correspondence between screen position and FFT bin does not follow the zooming for the current/max being watched.

**Comment by f4exb** [comment]
The problem is that the fft bin index remains based on the full spectrum while the spectrum used is only a part of it.
