### ISSUE TITLE
Display problem with Windows version

### ISSUE THREAD

**Issue by choupette-change** [f4exb/sdrangel#1146]
--Normal running of sdrangel
![image](https://user-images.githubusercontent.com/68333247/153458868-add9bd5f-7b96-42a9-86c6-cec6c4658350.png)

--Press F11, screens disappear
Horizontal menus no longer work, screens go black
![image](https://user-images.githubusercontent.com/68333247/153458111-7db7fc58-61ad-4e1e-883d-6077386bb7f2.png)
--press F11 again ok

**Comment by srcejon** [comment]
Seems to only be a problem when the Map feature has been opened. Possibly something to do with the Map's full screen mode.
