### ISSUE TITLE
3D map does not appears (unbuntu 20.04)

### ISSUE THREAD

**Issue by parlotto** [f4exb/sdrangel#1148]
Thank you for this amazing software.

### The 3D map zone is white
* I use the ads-b module to display planes on the map. 2D map is fine but 3D map zone is white.
* I have tried my own API key from maptiler but the result is the same.
![image](https://user-images.githubusercontent.com/14200538/153712341-74b0b9cf-9554-4f0c-bcd5-31012b1ae98e.png)

### Log Files
Here is my log file, if it could help
[sdrangel.log](https://github.com/f4exb/sdrangel/files/8053423/sdrangel.log)

**Comment by srcejon** [comment]
This should have been fixed with PR #1135 but isn't in the latest linux release yet.

**Comment by parlotto** [comment]
Thank you for the answer. I will wait for the next release.

**Comment by srcejon** [comment]
This should be fixed. Can you let us know if you still have a problem? Thanks.

**Comment by parlotto** [comment]
Yes !!! 3D view is awesome. Thanks for this great software.
