### ISSUE TITLE
Channels dock always doesn't display all channels after restoring preset

### ISSUE THREAD

**Issue by srcejon** [f4exb/sdrangel#1151]
It seems that after loading a preset, not all of the channels may be displayed properly:

To recreate:

- Create a preset containing two Channel Analyzers
- Load the preset
- Only one of the Channel Analyzers will be visible (if both are - load the preset again)
- Resize the window, and the other should appear

Observed on both Linux and Windows.

**Comment by f4exb** [comment]
Deferred to the new UI project

**Comment by f4exb** [comment]
The issue does not appear anymore in v7

**Comment by f4exb** [comment]
Fixed in v7.0.0-alpha2
