### ISSUE TITLE
Option to resize buttons.

### ISSUE THREAD

**Issue by Jcwscience** [f4exb/sdrangel#1156]
I’m using a touchscreen (a pretty pathetic one) and it is really difficult to hit the close button on the modules, and a few other items that are close together. Perhaps a config option could increase the ui scale? Or maybe just make the close button larger at least? Thanks!

**Comment by f4exb** [comment]
This is not possible really.

**Comment by Jcwscience** [comment]
@f4exb ehh worth a shot. It’s fine. By the way I have to say this program is probably the coolest thing I’ve seen in 2 years!
