### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by choupette-change** [f4exb/sdrangel#1157]
Hello, in the Windows version: in which file are the preset features saved? if I delete some, they reappear the next time Sdrangel is loaded.
In the Ubuntu version, I have problems displaying certain points or tracks colors in 3d maps...

**Comment by srcejon** [comment]
They're in the registry under HKEY_CURRENT_USER\SOFTWARE\f4exb\SDRangel

For the 3D maps issue, please post a screenshot and a description. We can't guess what the problem is!
