### ISSUE TITLE
when addinhg a receive channel the soft stops working

### ISSUE THREAD

**Issue by DG9BFC** [f4exb/sdrangel#116]
i have managed to get the lime board working with my (a bit old) laptop
replacing the limesuite dll and all is well
i can see signals in vfh uhf ... or when using the nco also in shortwave BUT
i can not RECEIVE
when i add a receiving channel (be it am, ssb, whatever) then the soft stops working
i can use wide bw or narrow bw ... when i click on the plus sign (to add a filter somewhere in passband) the soft hangs ...
it is the first time that i have the lime here in working condition with sdrangel (works fine in hdsdr or sdrc v3) so maybe i am just still making some faults in the setup?!?
would be nice if someone would give me a step by step instruction how to get also receive audio from the lime
cpu load is low (around 20% or so) and memory used is only around 1 gig so i am thinking that it is not a machine issue
need help .. greetz sigi dg9bfc

**Comment by f4exb** [comment]
This question would be better answered at: https://groups.io/g/sdrangel
