### ISSUE TITLE
AM Demodulator RF bandwidth setting in presets not being applied

### ISSUE THREAD

**Issue by brendanthebig** [f4exb/sdrangel#117]
Re Version 3.9.1... When loading presets with AM Demodulator, I have noticed that the RF bandwidth setting is not being applied. It works ok when making manual adjustments. I have tried to re-save the preset after making bandwidth changes but problem still persists.

**Comment by f4exb** [comment]
I also noticed the same with the SSB demod. It  may be due to changes in sample rate handling in which case it was introduced in 3.9.0

**Comment by brendanthebig** [comment]
I haven't noticed the problem with SSB demod myself. AM demod had no issues in 3.9.0 for me.

**Comment by f4exb** [comment]
There is definitely a problem with the sample rate used in the interpolator:
https://github.com/f4exb/sdrangel/blob/master/plugins/channelrx/demodam/amdemod.cpp#L200

It was already there in 3.9.0:
https://github.com/f4exb/sdrangel/commit/d4767364874785c69e3e67100694fa4a4a13bf26

It also affects SSB demod and SSB mod in a similar way.

Fix is easy and will be part of next release.

**Comment by brendanthebig** [comment]
Hi Edouard, V3.10.0 has fixed the issue with RF bandwidth on AM demod but there is still an issue with SSB demod. It seems that the cut-off frequency being applied is about half of what is selected.

**Comment by f4exb** [comment]
The frequency shift has an influence on how many halfband decimators are used each stage halving the baseband sample rate before feeding the samples to the demod (this is the "channelizer" step).

**Comment by f4exb** [comment]
There is an additional problem with the SSB demod filtering that I think has been there for ages. The demod decimator filter is set at half the required RF bandwidth. This is fine for double sideband signals when what is meant by RF bandwidth is the total double sideband bandwidth which is the case for all other demods. I suppose the decimator settings for the SSB were just copied and pasted and that was a long time ago...

**Comment by brendanthebig** [comment]
Working well in V3.10.1...Good job Edouard...
