### ISSUE TITLE
How do you get 3D with Radiosonde ?

### ISSUE THREAD

**Issue by m1ctk** [f4exb/sdrangel#1175]
I am currently tracking 405.8 frames are being received but how do you see anything on the map ?

**Comment by srcejon** [comment]
Hi,There are new models, so you need to press the "download 3d models" button again.Cheers,Jon
-------- Original message --------From: m1ctk ***@***.***> Date: 06/03/2022  00:33  (GMT+00:00) To: f4exb/sdrangel ***@***.***> Cc: Subscribed ***@***.***> Subject: [f4exb/sdrangel] How do you get 3D with Radiosonde ? (Issue #1175) 
I am currently tracking 405.8 frames are being received but how do you see anything on the map ?
