### ISSUE TITLE
SDRPLAY RSP1A is no longer recognized with the lastest version

### ISSUE THREAD

**Issue by choupette-change** [f4exb/sdrangel#1176]
Since the latest version of SDRangel 6.20.0 my SDRPLAY RSP1A is no longer recognized, it is ok with Ubuntu 21.10?? Installed with sdrangel-6.20.0-win64.exe 
![image](https://user-images.githubusercontent.com/68333247/157035886-6673bb5e-dcfe-488c-95a3-20926829c7e9.png)

**Comment by srcejon** [comment]
I don't think anything should have changed.

Is the device recognizable by other s/w on Windows?

**Comment by choupette-change** [comment]
it's ok after testing on other apps, sorry ):
