### ISSUE TITLE
release 6.20.1 freeze during loading process

### ISSUE THREAD

**Issue by IU4FIR** [f4exb/sdrangel#1177]
### Subject or type of issue
* the program during the loading phase stops at the point "LOAD PLUGINS" and remains freezed...
* sdrangel-6.20.0-win64.exe and 6.20.1-win64.exe have the same issue.
* Install and/or run like USER or ADMIN have the same issue

### SDR
* Nooelec NESDR SMArTee XTR SDR - Premium RTL-SDR w/ Extended Tuning Range, Aluminum Enclosure, Bias Tee, 0.5PPM TCXO, SMA Input

### HW
* CPU 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
* RAM 16,0 GB
* SW Windows 11 Pro (V 22H2)

![Immagine 2022-03-10 113151](https://user-images.githubusercontent.com/96939950/157650913-bc984a63-7b92-49d8-8347-66cb4db3ceb5.png)

**Comment by srcejon** [comment]
Works OK for me.  Does 6.19 or earlier work for you? Does it help if you unplug any SDRs?

Did you happen to enable logging previously? If you can run an older version - enable the log file - then try the new version and send the log file it creates before hanging.

**Comment by IU4FIR** [comment]
Even the older version does not work, I suspect that the issue it's generate from "Cumulative Update for Windows 11, version 22H2 (10.0.22567.200) (KB5012432)" installed two days ago. 
The same behaviour using AIRSPY HF+.
Any suggestion or idea ???

**Comment by f4exb** [comment]
How do you connect the devices to the USB port on the machine? Do you use an extension cable? Cables are not born equal and  I have encountered issues sometimes particularly when the cable is long (> 3m).

**Comment by IU4FIR** [comment]
after a WIN11 update, now the sw remain idle (same point LOAD PLUGIN) for 3/4 minutes and start!

**Comment by srcejon** [comment]
If it is now starting, enable the log file (Preferences > logging menu) and then we can see why it is taking so long to start.

Another user recently had a long startup time due to SoapySDR scanning lots of audio devices.

**Comment by IU4FIR** [comment]
now after several startup the idle time decrease...

[IU4FIR.txt](https://github.com/f4exb/sdrangel/files/8253070/IU4FIR.txt)

**Comment by srcejon** [comment]
15 seconds seems about normal.

**Comment by IU4FIR** [comment]
After another win11 update, seems ok!

**Comment by PD5DJ** [comment]
I suddenly have the same with the latest download of SDRAngle.. worked for days.. and suddenly freezes upon start.. with load plugins and thats it.. I have to restart the PC, I can not kill the process in W10

**Comment by srcejon** [comment]
Does other SDR s/w run OK?
