### ISSUE TITLE
add support to ATSC and ISDB  DATV modes

### ISSUE THREAD

**Issue by patomoi** [f4exb/sdrangel#1187]
Hello, first of all, I would like to thank you for the work that has been achieved in developing this excellent software.

My request is about implementing the possibility of demodulating digital television transmissions in ATSC and ISDB, ISDB-T.

hoping that you are very well and that there are no setbacks in the development of this software.

Patrick.

**Comment by f4exb** [comment]
DATV demodulator is based on Lean DVB that does not support these srandards/
