### ISSUE TITLE
Satellite tracks do not line up with the satellite icons

### ISSUE THREAD

**Issue by srs4511351** [f4exb/sdrangel#1188]
I have a SDRplay RSP1A with API 3.07 running on a Raspberry Pi 4 B. I installed SDRangel on Debian Bullseye and Bookworm.

I have been enjoying receiving satellites recently.

I tried versions 6.19.1-18, 6.19.1-34 and 6.20.1-29. Satellite tracks do not line up with the satellite icons on the map. They are shifted somewhat.

The icon positions are correct as observed by acquisitions in the tracker list and signals received.
Updating the satellite data did not help.

Older versions before 3D maps were added, work correctly.
Using a .conf file from a working system did not help, but the configuration worked otherwise.

When using the replay feature in Satellite Tracker, with send time to map checked, the icons are correctly positioned on the ground tracks.

Is there a setting that I need to change to correct this?

----Steve

**Comment by choupette-change** [comment]
Hello, same observation, the satellite tracks are no longer displayed (since the switch to summer time in Europe???)

**Comment by srcejon** [comment]
Can you post a picture?

I see:

![image](https://user-images.githubusercontent.com/57259258/160404448-acfc4a46-6167-44fc-a22c-8201274afd0f.png)

Which looks ok.

**Comment by choupette-change** [comment]
ok in 2 D map but nothing in 3D map since the switch to summer time in Europe???
![image](https://user-images.githubusercontent.com/68333247/160414620-dc5137db-93ae-4a50-9294-7a278cb80c75.png)

**Comment by choupette-change** [comment]
It is ok for me

**Comment by srs4511351** [comment]
What changed to make it OK you you? Did you change to UTC?
Your screen shot was not OK.

-----Steve

**Comment by srcejon** [comment]
It should be fixed if you git update and rebuild.

**Comment by choupette-change** [comment]
![image](https://user-images.githubusercontent.com/68333247/160701988-29d4c94d-9727-45ef-b85c-308d589bec8d.png)

**Comment by srs4511351** [comment]
I uninstalled, recompiled with the new version 6.20.1-37, and the satellite tracks do line up with the icons.
Thanks! Good work!

----Steve

**Comment by f4exb** [comment]
Fix released in v6.20.2 hence can be closed
