### ISSUE TITLE
Can't go below 30 Mhz with LimeSDR / SoapySDR driver

### ISSUE THREAD

**Issue by rmivdc** [f4exb/sdrangel#1189]
Hi, 

I have a  Runtime issue,

LimeSDR hardware being used (not LimeSDR mini)
I've tried the Soapy/LimeSDR combo driver with other SDRs software and i can reach **below** 30 mhz.

### Development environment :
Fedora 35 with last lu3vea sdrangel build (6.20.1) - Qt 5.15.2 : 
https://copr.fedorainfracloud.org/coprs/lu3vea/sdrangel/

### Actual behavior : 
-Choosing LimeSDR with soapy Driver from device list
-Trying to scroll the frequency under 30mhz - it's locking at 30mhz.

### Expected behavior
-Scrolling under 30 Mhz should be possible. (?)

**Comment by srcejon** [comment]
Why not use the native Lime driver?

https://github.com/f4exb/sdrangel/blob/master/plugins/samplesource/limesdrinput/readme.md
