### ISSUE TITLE
dot in a file

### ISSUE THREAD

**Issue by choupette-change** [f4exb/sdrangel#1192]
Why is a dot added at the beginning of the file name? This file is no longer recognized unless you modify the name of this file by hand (remove the dot). Is-it a bug ??
![image](https://user-images.githubusercontent.com/68333247/160826221-80890895-e4b7-4587-832f-b9abfe37de5c.png)
![image](https://user-images.githubusercontent.com/68333247/160827122-9f71cfcb-2ed9-4a4c-a7b1-1808e2e8aa72.png)
![image](https://user-images.githubusercontent.com/68333247/160827232-3528d85c-99c6-451a-844a-b65fae9ffc3a.png)

**Comment by f4exb** [comment]
Give he file a root name. Please read the documentation before posting an issue: https://github.com/f4exb/sdrangel/tree/master/plugins/channelrx/filesink

**Comment by choupette-change** [comment]
Oups I read the documentation before posting this bug but my English is light I did not see or understand the information Sorry
