### ISSUE TITLE
No audio in DSD Demodulator

### ISSUE THREAD

**Issue by kallix** [f4exb/sdrangel#120]
Hi, 

I can't seem to obtain any audio out of the DSD Demodulator, even though the speaker icons are green (see screenshot)

I do have correct audio from NFM / WFM / Broadcast FM Demodulators. 

Am I missing something or doing something wrong ? 
Is there something special about how the DSD Demodulator handles sound ?

I'm running the current git head on Debian.

![dsd](https://user-images.githubusercontent.com/5512987/34650819-56d73e12-f3c7-11e7-9558-364531bfd649.png)

**Comment by f4exb** [comment]
I guess you compile the software in which case you need to have mbelib installed in your system. If you have mbelib installed in a custom location, say /opt/install/mbelib you will need to add these defines to the cmake command: -DLIBMBE_INCLUDE_DIR=/opt/install/mbelib/include -DLIBMBE_LIBRARY=/opt/install/mbelib/lib/libmbe.so

**Comment by f4exb** [comment]
This question would be better aswered at: https://groups.io/g/sdrangel

**Comment by ivanenev** [comment]
Hi,
Any solution to this problem? 
I have the same issue although I compiled with mbelib support.

Thanks

**Comment by sh123** [comment]
Same issue on debian, no audio output, while log indicates that VOX frames are received.

**Comment by nukedclx** [comment]
same here, vox and speaker icon green and no audio..

**Comment by vetrivelmnv13** [comment]
hi guys, i am trying to receive walkie-talkie signal by using my limesdrmini. the walkie- talkie doing 4FSK modulation. i am using sdr angel for reception. but sdrangel seems like, does not have any FSK demodulation. so i how can i receive the walkie talkie signal ? can anyone give me some suggestion

**Comment by f4exb** [comment]
Question would be better answered here: https://groups.io/g/sdrangel

**Comment by vetrivelmnv13** [comment]
> Question would be better answered here: https://groups.io/g/sdrangel

hi @f4exb ,
i am not able to post a question in sdrangel forum, can you guide me?
