### ISSUE TITLE
V7: Menus

### ISSUE THREAD

**Issue by srcejon** [f4exb/sdrangel#1208]
Apologies if these are things you already know about, but just haven't had time to do, but I'd thought I'd log it anyway:

In V6, menus have keyboard shortcuts:

![image](https://user-images.githubusercontent.com/57259258/164220073-52d2cd23-b947-49cb-9b80-d8dabd57b0c9.png)

These are missing in V7:

![image](https://user-images.githubusercontent.com/57259258/164220137-4b3bc815-7736-4840-8612-aee6c732a76c.png)

As are the ... for Menus that open dialogs.

(Also B is accidentally capitalised in ABout SDRangel)

**Comment by f4exb** [comment]
Implemented in v7.0.0-alpha2
