### ISSUE TITLE
V7: Cascade of Spectrum/Waterfall

### ISSUE THREAD

**Issue by srcejon** [f4exb/sdrangel#1210]
When Cascading the Spectrum/Waterfall window, the toolbar overlaps the waterfall:

![image](https://user-images.githubusercontent.com/57259258/164233230-f9e595f3-6653-4c73-b395-91fc1730715b.png)

(It fixes itself when you resize the window and you can't seem to be able to do this by resizing the window manually).

**Comment by f4exb** [comment]
Fixed in v7.0.0-alpha2
