### ISSUE TITLE
V7: Crash when removing device

### ISSUE THREAD

**Issue by srcejon** [f4exb/sdrangel#1211]
To recreate:

- Workspaces > New
- Add Rx device > File Input
- Add Rx device > File Input
- Close first device
- Close second device

And it should crash

![image](https://user-images.githubusercontent.com/57259258/164433674-15a4922f-b221-49ac-9fd1-b445bbf1b074.png)

**Comment by f4exb** [comment]
Fixed in v7.0.0-alpha2
