### ISSUE TITLE
How can I reset SDRangel?

### ISSUE THREAD

**Issue by sefirot43** [f4exb/sdrangel#1218]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by srcejon** [comment]
Do you mean you want to delete all settings?

On Windows, you can delete the registry entries under: HKEY_CURRENT_USER\SOFTWARE\f4exb\SDRangel

**Comment by sefirot43** [comment]
Yes, I mean to delete all settings to start all over again.
