### ISSUE TITLE
Decommission SDRplay (v1) in favor of SDRPlayV3

### ISSUE THREAD

**Issue by f4exb** [f4exb/sdrangel#1222]
Thus removing dependency on libmirisdr4 that wants to live its own life.

**Comment by f4exb** [comment]
The legacy SDRplay v1 and its Chinese clones are well supported by V3.

**Comment by f4exb** [comment]
After thorough checking it appears that with V3 and SDRplay RSP1 there are short discontinuities in the IQ flow so we should keep the libmirisdr4 v1.1.2 (v2.0.0 does not work) based version.

**Comment by srcejon** [comment]
Is this something that needs fixing in the sdrangel v3 code or that might affect other radios?

(I don't have an RSP1 to test)

**Comment by f4exb** [comment]
It is only with a Chinese clone of RSP1 (the blue "MSi.SDR"with a dolphin logo). The RSP2 works fine.

**Comment by f4exb** [comment]
This one (not all of them have the logo):
![image](https://user-images.githubusercontent.com/6192319/167245012-a266876a-6bda-4209-9b30-9b4e34888052.png)
