### ISSUE TITLE
v7: workspaces question

### ISSUE THREAD

**Issue by sefirot43** [f4exb/sdrangel#1229]
Can I place different demodulators (AM, FM, ADS-B, etc) in the same workplace? Or do I have to create a workspace for each one of them?

**Comment by f4exb** [comment]
The very purpose of the new UI design is to be able to place any component UI anywhere in any workspace. At creation time the components are placed in the workspace that has focus. You create channels from the device UI therefore they are also placed in the same workspace. Then you can move items to another workspace. This is the button with the square and an exit arrow on the right of the top bar. The details are documented in the readme of sdrgui folder in the v7 branch: https://github.com/f4exb/sdrangel/tree/v7/sdrgui

**Comment by sefirot43** [comment]
Thank you.
