### ISSUE TITLE
libopencv-core4.2 dependency not satsifiable with Ubuntu 22.04

### ISSUE THREAD

**Issue by elmatou** [f4exb/sdrangel#1235]
Hi,
libopencv-core4.2 has been ditched for libopencv-core4.5 with Ubuntu 22.04 (and maybe since 21.10)
I just upgraded to Ubuntu 22.04 and cannot install sdrangel from deb package anymore. I didn't tried from source, but it should be the same.

Would be great if the docker images could be uploaded to Dockerhub in order to avoid these kind of issue.

thx for the good work.

**Comment by f4exb** [comment]
.deb package is for 20.04 as specified. As soon as a 22.04 image will be available in Appveyor I will try to upgrade and change documentation accordingly
