### ISSUE TITLE
Problem in  ADS-B demodulator 

### ISSUE THREAD

**Issue by mosta7il** [f4exb/sdrangel#1237]
1. sampling rate problem:
        error message : Sample rate must be >= 2000000. Currently 64000.
       though I chose SR = 12 M
2. No airplanes appear
3. Is there any document which I can follow to make ADS-B works,
   Is there any restrictions on antenna connected to SDR
   
   Thanks in advance

**Comment by srcejon** [comment]
> 1. sampling rate problem:
>    error message : Sample rate must be >= 2000000. Currently 64000.
>    though I chose SR = 12 M

This is referring to the baseband sample rate, which is set by the device sample rate and the decimation (Dec) setting. Which SDR are you using? If RTL SDR, set it's sample rate at 2,400,000 and Dec to 1. Perhaps attach a screenshot.

The SR setting in the ADS-B window is the channel sample rate - I'd recommend having that as 4.

> No airplanes appear

They wont until baseband sample rate is >= 2MSa/s 

> Is there any restrictions on antenna connected to SDR

Not really - just one that works well at 1090MHz. I use one of these LNAs as well which helps: https://store.uputronics.com/index.php?route=product/product&product_id=50

**Comment by mosta7il** [comment]
> Which SDR are you using? If RTL SDR, set it's sample rate at 2,400,000 and Dec to 1.
Yes, I use RTL SDR
>  set it's sample rate at 2,400,000 and Dec to 1.
i set it as you say is say something i missed ?
![rd_angel](https://user-images.githubusercontent.com/17255813/167293043-81d6ad14-709b-4bd9-bc7b-8ffe04724244.JPG)
this my used antenna 
![image](https://user-images.githubusercontent.com/17255813/167294117-f793e4e5-7f50-437c-81b3-005e2d382c5e.png)

**Comment by srcejon** [comment]
Try turning device gain up to maximum. 

Set ADSB threshold to 5.

Under Preferences > My location set yor correct latitude and longitude. 

Try with antenna outside withonly a short amount of cable to SDR.

**Comment by mistergitj** [comment]
I have found that even though I am in USA, I need to set my Longitude to a minus number to have home on the correct ADS-B Map.
Thanks and enjoy, John.

**Comment by srcejon** [comment]
Yes, East and North are positive.

**Comment by mistergitj** [comment]
Thanks, srcejon. I always thought that West was positive. Enjoy, John.
