### ISSUE TITLE
Impossible to load maps with Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by choupette-change** [f4exb/sdrangel#1241]
hello, impossible to load maps with Ubuntu 22.04 LTS, the latest version of Ubuntu with v7.0.0-alpha.3 and v6.20.3, ok with Windows
![image](https://user-images.githubusercontent.com/68333247/167407822-09c54ead-f518-4737-adef-9da858dc160f.png)

**Comment by choupette-change** [comment]
Hello, am I the only one who has this problem ? Can you confirm that it works with Ubuntu 22 04 LTS. Best regards

**Comment by loewal** [comment]
Tried to load the MAP feature under Linux.
System hangs!
Other 'features' are okay

**Comment by loewal** [comment]
Tried the same on iMac and Macbook Pro. Maps are loaded fine.

**Comment by srcejon** [comment]
This is probably the same problem as #1169 - in that 22.04 appears be using Qt 5.15.3

**Comment by srcejon** [comment]
Workaround implemented in 7.3.2.
