### ISSUE TITLE
Noise reduction

### ISSUE THREAD

**Issue by sefirot43** [f4exb/sdrangel#1252]
Is there a way to reduce the background and interference noise?

**Comment by srcejon** [comment]
What demodulator are you trying to use?

A screenshot might help.

**Comment by sefirot43** [comment]
![image](https://user-images.githubusercontent.com/86562774/169661318-cf8fb1b3-0d9f-4589-aaf2-9a105bbf4960.png)

**Comment by srcejon** [comment]
AM Demod docs are here: https://github.com/f4exb/sdrangel/blob/master/plugins/channelrx/demodam/readme.md

Try the bandpass filter or reducing RF bandwidth.

**Comment by sefirot43** [comment]
Will do.
Thank you.
