### ISSUE TITLE
Compiler error on v7.2.1 with latest codec2

### ISSUE THREAD

**Issue by loewal** [f4exb/sdrangel#1256]
Hi,
This happened on the latest version; v7.1 went well.
[ 40%] Linking CXX shared library ../../../lib/pluginssrv/libremotesinksrv.dylib
/Users/Loewal/Downloads/sdrangel/plugins/channelrx/demodfreedv/freedvdemodsink.cpp:436:13: error: no member named 'interleave_frames' in 'freedv_advanced'
        adv.interleave_frames = 1;
        ~~~ ^
[ 40%] Built target remotesinksrv
[ 40%] Building CXX object pluginssrv/channelrx/demodfreedv/CMakeFiles/demodfreedvsrv.dir/freedvdemodsettings.cpp.o
1 error generated.
make[2]: *** [pluginssrv/channelrx/demodfreedv/CMakeFiles/demodfreedvsrv.dir/freedvdemodsink.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 40%] Building CXX object pluginssrv/channelrx/noisefigure/CMakeFiles/noisefiguresrv.dir/noisefiguresrv_autogen/mocs_compilation.cpp.o
make[1]: *** [pluginssrv/channelrx/demodfreedv/CMakeFiles/demodfreedvsrv.dir/all] Error 2

**Comment by loewal** [comment]
B.t.w. will there be a .dmg again?

**Comment by f4exb** [comment]
Nothing was changed in FreeDV plugins not codec2 required version since 7.1 so the problem is entirely on your side.

**Comment by srcejon** [comment]
> B.t.w. will there be a .dmg again?

It's available now - and should only use SSE this time.

**Comment by srcejon** [comment]
As to the compiler error, it's most likely because you are using a more recent version of of the codec2 library than SDRangel supports. sdrangel/external/CMakeLists.txt assumes v0.9.2 - the latest tag looks to be v1.03 - and the field referred to no longer exists.

codec2 github not obviously clear on what the changes are - but could be worth trying to pull in the latest version - as v0.9.2 is a couple of years old.

**Comment by loewal** [comment]
Can confirm that it runs fine on a 13 year old iMac 24" with Catalina-patcher installed.

Thanks Jon

**Comment by loewal** [comment]
> Nothing was changed in FreeDV plugins not codec2 required version since 7.1 so the problem is entirely on your side.

Happily enough there is a DMG which runs fine.
The iMac that compiles fine  has its dependencies installed with Homebrew.
The other one has Macports. Which refuses.....

**Comment by ra1nb0w** [comment]
`freedv_advanced.interleave_frames` was removed 5 months ago from codec2 ([see](https://github.com/drowe67/codec2/commit/840e5a7797fa06d94bfdbdcf284fa86a64ca31ab)) and macports tracks the latest commit to support "freedv activity days" and experimenter (this is not an habit in macports).
I fixed the issue; update macports with `sudo port selfupdate` and then you can compile sdrangel (also available from macports and from tomorrow as binary).

Please, confirm the fix.

**Comment by loewal** [comment]
So #ra1nb0w,
Are these my steps:
- sudo port selfupdate
- sudo port install codec2
And then git pull the angel7 source and compile?

I just tried to compile codec2 according the manual installation of SDRangel, but got a linker-error: unknown option: -Map=ofdm_stack.dir/all Error 2

I am not sure what to do and when....sorry.

**Comment by loewal** [comment]
sorry Map=ofdm_stack.map

**Comment by ra1nb0w** [comment]
if you want to build sdrangel from source and install only default dependencies:
```
sudo port selfupdate
sudo port install rdepof:sdrangel
```
otherwise
```
sudo port install sdrangel
```

**Comment by loewal** [comment]
But this way I compile the 'old' v6.20.3?
I would like the v7.2.1 the manual way as in Linux.
This worked with v7.0

**Comment by ra1nb0w** [comment]
macports has already 7.2.1

**Comment by loewal** [comment]
Thank you!

**Comment by loewal** [comment]
> `freedv_advanced.interleave_frames` was removed 5 months ago from codec2 ([see](https://github.com/drowe67/codec2/commit/840e5a7797fa06d94bfdbdcf284fa86a64ca31ab)) and macports tracks the latest commit to support "freedv activity days" and experimenter (this is not an habit in macports). I fixed the issue; update macports with `sudo port selfupdate` and then you can compile sdrangel (also available from macports and from tomorrow as binary).
> 
> Please, confirm the fix.

Confirmed!! Thank you.
