### ISSUE TITLE
Funcube

### ISSUE THREAD

**Issue by loewal** [f4exb/sdrangel#1266]
Neither latest Macos-version, selfcompiled, nor latest Windows version, supplied by Jon, works.
Even compiled on Linux Jellyfish.
I started fcdhid to check presence of the dongle. It was recognized.

It works nowhere....I think it never worked.
Why does SDRuno with extio.dll work? Also SDR# (not fluently..)?

**Comment by f4exb** [comment]
> It works nowhere....I think it never worked.

Really?
![image](https://user-images.githubusercontent.com/6192319/171067487-4ed18ee1-240f-4313-856a-c70fb59610b5.png)

**Comment by f4exb** [comment]
I tried the Windows version. I think that the problem is that it does not recognize the audio device of the FunCube. The IQ data of the FunCube is sampled via an audio device. As a consequence the device runs but yields no data. The controls (hence hidapi) seem to work (no errors).

**Comment by loewal** [comment]
Strange Edouard,
I noticed several things:
- mix is not enabled
- RF filt differs from frequency: mine is 192k
- I see nog signal at all

Are there many others with these problems?
Otherwise, remove Funcube form SDRA.


![Schermafbeelding 2022-05-31 om 11 56 36](https://user-images.githubusercontent.com/7289719/171147477-1f266070-f1f5-4476-bbe5-0faebe1b1af2.jpg)

**Comment by loewal** [comment]
Must correct myself:
- above settings are in MacOs
- in Win11 the samplerate is 96K; shouldn't it be the fixed 192K?
- rest: no signal

**Comment by f4exb** [comment]
> Otherwise, remove Funcube form SDRA.

Works perfectly in Linux there is no reason to remove it.

**Comment by loewal** [comment]
Installed also in Linux (Jellyfish).
My udev-rules:
# Udev rules for the Funcube Dongle Pro+ (0xfb31) 

# HIDAPI/libusb: 

SUBSYSTEMS=="usb", ATTRS{idVendor}=="04d8", ATTRS{idProduct}=="fb31", GROUP:="users", MODE:="0660", SYMLINK+="FCDPP" 

# HIDAPI/hidraw: 

#KERNEL=="hidraw*", ATTRS{busnum}=="1", ATTRS{idVendor}=="04d8", ATTRS{idProduct}=="fb31", MODE="0666" 

Still no signal.
Device works in Windows: SDRuno and SDR#.

Is there perhaps something I could have overlooked?
When started from the commandprompt I see, that the Halincrest Funcube v2.0-analog-stereo is the input....

Is that alright?

**Comment by srcejon** [comment]
> I tried the Windows version. I think that the problem is that it does not recognize the audio device of the FunCube. The IQ data of the FunCube is sampled via an audio device. 

In FCDProInput::openFCDAudio it looks for an audio device with a specific name, which comes from fcdlib/fcdtraits.cpp, which can be either:

    const char *fcd_traits<Pro>::qtDeviceName = "FUNcube_Dongle_V1.0";
    const char *fcd_traits<ProPlus>::qtDeviceName = "FUNcube_Dongle_V2.0";

Do you have an audio device with that name?

Do you get   qCritical("FCDProInput::openFCDAudio: device with name %s not found", cardname); printed in your log? That should be printed if it fails to find the device.

**Comment by f4exb** [comment]
I can see it in the sound devices in the Devices manager:
![image](https://user-images.githubusercontent.com/6192319/171284208-e7425e02-1e11-4b0a-9865-17d8edb0ebdb.png)
but I cannot see it in the audio devices in SDRangel:
![image](https://user-images.githubusercontent.com/6192319/171284318-5af2abca-8bdb-4fb0-9268-180b6a7af3e5.png)

**Comment by f4exb** [comment]
OK for me now on Windows with b5ad1b27f5ef0356d002c695e294cdccda8fa412
![image](https://user-images.githubusercontent.com/6192319/171307630-00795be5-e79a-4b3b-89a5-da5cfd14526e.png)

**Comment by loewal** [comment]
Awaiting this version on Github!

**Comment by f4exb** [comment]
It is there already (unofficial): https://github.com/f4exb/sdrangel/actions/runs/2418252820

**Comment by loewal** [comment]
Hi Edouard,

Beautiful!!
At last it’s working here too!

Thank you very much.

Grtz.

**Comment by srcejon** [comment]
> Hi Edouard, Beautiful!! At last it’s working here too! Thank you very much. Grtz.

It might help if you can post a screenshot of Audio Devices > Audio Inputs from MacOS, so we can see if it's the same problem.

**Comment by loewal** [comment]
I managed to get things working on an old Dell laptop on Linux 20.04.
The problems I found were on an 10 year old iMac 27" running Jammy Jellyfish.
Perhaps the namingconventions are therefore different...?

**Comment by loewal** [comment]
![Schermafbeelding 2022-06-01 om 10 06 59](https://user-images.githubusercontent.com/7289719/171360636-c2d536ae-9226-4b27-8ba6-2f3b0308884b.jpg)
![Schermafbeelding 2022-06-01 om 10 06 30](https://user-images.githubusercontent.com/7289719/171360644-17168420-c6bf-4618-856d-9708a302be90.jpg)

**Comment by loewal** [comment]
This on my iMac 27" with Jammy Jellyfish:
![Schermafbeelding 2022-06-01 om 10 45 02](https://user-images.githubusercontent.com/7289719/171365318-895dbe54-71ec-4949-ba09-795176554e63.jpg)

**Comment by f4exb** [comment]
It looks similar on Mac and Windows so Linux being the odd guy there by reversing the condition it should work for all 3 systems.

**Comment by f4exb** [comment]
Implemented in v7.3.1
