### ISSUE TITLE
dependencies broken/un-obtainable  on ubuntu 22.04 "jammy"

### ISSUE THREAD

**Issue by Scorpia10x** [f4exb/sdrangel#1267]
attempting to install sdrangel on ubuntu 22.04 from the .deb in the archive yields the following error...
```
roy@host:~/sdrangel-1477-master$ sudo apt install ./sdrangel_7.3.0-1_amd64.deb
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'sdrangel' instead of "./sdrangel_7.3.0-1_amd64.deb"
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation

The following packages have unmet dependencies:
 sdrangel : Depends: libuhd3.15.0 (>= 3.15.0.0) but it is not installable
            Depends: qtbase-abi-5-12-8 but it is not installable
E: Unable to correct problems, you have held broken packages.
```
it appears sdrangel relies on "older" versions, as I cannot find those specific version in the current repo but only newer.
I apologies if this is a simple fix but would be appreciative of any help 
:)

**Comment by f4exb** [comment]
I thought that was clear enough but apparently not: THE .deb IN THE RELEASES SECTION IS FOR UBUNTU 20.04

**Comment by Scorpia10x** [comment]
I apologies for asking for help, I wont bother you to waste time with helping to get it work on any newer distro.

**Comment by beta-tester** [comment]
> I thought that was clear enough but apparently not: **THE .deb IN THE RELEASES SECTION IS FOR UBUNTU 20.04**

i thought ubuntu 20.04 was choosen, because it was the LTS version of ubuntu back in that time.
now ubuntu 22.04 is the current LTS version, so i thought the deb build would follow the current LTS version as well...

is there a plan to update the build-chain ?

**Comment by f4exb** [comment]
It depends on how fast Appveyor is in upgrading their images to 22.04

**Comment by beta-tester** [comment]
oh, Appveyor is the reason.
that i didn't know. thank you for the information.

**Comment by f4exb** [comment]
Found a workaround with #1416 and since v7.7.0 the .deb package is for Ubuntu 22.04
