### ISSUE TITLE
Cannot add IP:PORT to AMBE Controller on Windows using hardware AMBE3000R DVStick30

### ISSUE THREAD

**Issue by Hermite123456** [f4exb/sdrangel#1272]
Hello,
I'm on a NXDN-4800 frequency and I can hear good audio decoding without the AMBE controller.
When the AMBE Controller is enabled (connected via BlueDV AMBE Server), I only get failed frames when decoding.

I noticed that if I start the BlueDV Server, I cannot add the IP:PORT to the AMBE Controller (probably locked by BlueDV Server?).
And vice versa, if the BlueDV Server is stopped, I can then succesfully add the IP:PORT to the AMBE Controller but when I try to start the BlueDV Server, the hardware (AMBE3000R) is not recognized anymore (IP:PORT locked by AMBE Controller?)

Am I doing something wrong ? 

Thank you.

[
![ambe_controller](https://user-images.githubusercontent.com/54645050/171504729-8052f839-4797-4c7b-9f2d-cee49916f17d.JPG)
]

**Comment by f4exb** [comment]
Check your network setup. For me it works:
![image](https://user-images.githubusercontent.com/6192319/171624327-8c856961-0016-46df-a29d-23379a3e6c15.png)

Note: using AMBE server from https://github.com/marrold/AMBEServer on a RPi4.

**Comment by Hermite123456** [comment]
Ok, but do you (or anybody else) have a proven working connectivity example of an AMBE Server on Windows 10 ?
 
I'm using BlueDV and BlueDV AMBE Server and they work just fine on Windows 10. No IP:PORT conflicts.

Checking my Network setup is a broad statement... what could possibly be the culprit if BlueDV connectivity to AMBE Server works fine?
