### ISSUE TITLE
Transmit a 2,45GHz continuosly wave

### ISSUE THREAD

**Issue by MiguelStattmiller** [f4exb/sdrangel#1285]
Hey, I need to transmit a 2,45GHz wave continuosly. I m using 802.14 modultaion, but this transmits in bursts.

How can I transmit this 2,45GHz continuosly ,with digital modulation. Thanks to all

**Comment by srcejon** [comment]
Right click on the repeat button (next to TX) and set delay between frames to 0.

**Comment by MiguelStattmiller** [comment]
Sorry where can I changethe delay between frames?

thanks a lot
