### ISSUE TITLE
Button does not work with the "radio clock" channel

### ISSUE THREAD

**Issue by choupette-change** [f4exb/sdrangel#1286]
Hello, "common settings" button does not work with the "radio clock" channel (perhaps with other untested channels). OK with "AM demodulator"
![image](https://user-images.githubusercontent.com/68333247/173110693-86db1d89-bbbd-462d-bb19-37ef7bd470b7.png)

**Comment by f4exb** [comment]
Probably the signal connection is missing

**Comment by f4exb** [comment]
Also on a different note the menu does not appear at the right position for features because the signal emission is  coded like this:

```c++
void FeatureGUI::activateSettingsDialog()
{
    QPoint p = mapFromGlobal(QCursor::pos());
    m_contextMenuType = ContextMenuChannelSettings;
    emit customContextMenuRequested(p);
}
```
While it should be like this:

```c++
void DeviceGUI::activateSettingsDialog()
{
    QPoint p = QCursor::pos();
    m_contextMenuType = ContextMenuDeviceSettings;
    emit customContextMenuRequested(p);
}
```
Notice the difference with `QPoint`
