### ISSUE TITLE
Gnuradio support

### ISSUE THREAD

**Issue by zeke800** [f4exb/sdrangel#1289]
How can I pipe my QPSK modulator output from GNURadio 3.7 to SdrAngel?

**Comment by f4exb** [comment]
I think GNU radio has a UDP output block so you can get in via the UDP source if your intention is to transmit via SDRangel: https://github.com/f4exb/sdrangel/tree/master/plugins/channeltx/udpsource#readme. You would use the "SnLE I/Q" format and the size of samples depends on the way SDRangel was compiled. Most probably this is 24 bit wide over 32 bits for the I or Q sample.
