### ISSUE TITLE
Compiler error 

### ISSUE THREAD

**Issue by SA7BNT** [f4exb/sdrangel#1290]
Hi,

running into this compiler error 
<img width="1440" alt="Bildschirmfoto 2022-06-13 um 23 15 31" src="https://user-images.githubusercontent.com/35367117/173446792-8d631898-b49c-4572-9a55-13d4bf011240.png">
I already tried to reinstall SDL2 but it didn't make the thing. 
How can i fix this error?

OSx is Big Sur (11.6.6)

**Comment by srcejon** [comment]
I compile it on a Mac that doesn't have SDL2 installed. 

You could try changing the compilation options listed so implicit function defs aren't treated as errors.

**Comment by loewal** [comment]
Compiling went OK.

But I also always install the DMG when it is available.
That last one didn’t startup…until this morning:

I ran my own compiled version and after that the DMG (not at the same time).

Now it’s ok.

Sometimes………………………….??

**Comment by loewal** [comment]
By the way….SDL2?

Never installed it and until v7.3.1 all went fine…until yesterday.
A good nights sleep…trying v7.3.2 again….yes!!

So….puzzles….
