### ISSUE TITLE
APTdec plugin compile error (RPi4)

### ISSUE THREAD

**Issue by joecupano** [f4exb/sdrangel#1307]
Per subject

[ 45%] Building CXX object pluginssrv/channelrx/demodapt/CMakeFiles/demodaptsrv.dir/aptdemodplugin.cpp.o
[ 45%] Linking CXX shared library ../../../lib/pluginssrv/libdemoddabsrv.so
/home/pi/SIG/source/sdrangel/plugins/channelrx/demodapt/aptdemodimageworker.cpp: In member function ‘QImage APTDemodImageWorker::processImage(QStringList&, APTDemodSettings::ChannelSelection)’:
/home/pi/SIG/source/sdrangel/plugins/channelrx/demodapt/aptdemodimageworker.cpp:850:9: error: ‘apt_temperature’ was not declared in this scope
  850 |         apt_temperature(satnum, &m_tempImage, APT_CHB_OFFSET, APT_CH_WIDTH);
      |         ^~~~~~~~~~~~~~~
[ 45%] Building CXX object pluginssrv/channelrx/demoddsd/CMakeFiles/demoddsdsrv.dir/dsddemodbaudrates.cpp.o
[ 45%] Building CXX object pluginssrv/channelrx/demoddsd/CMakeFiles/demoddsdsrv.dir/dsddemodsettings.cpp.o
make[2]: *** [pluginssrv/channelrx/demodapt/CMakeFiles/demodaptsrv.dir/build.make:147: pluginssrv/channelrx/demodapt/CMakeFiles/demodaptsrv.dir/aptdemodimageworker.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....

**Comment by srcejon** [comment]
Make sure you have updated to the latest aptdec

**Comment by joecupano** [comment]
I am - compiling from current on github repo

**Comment by srcejon** [comment]
You're missing:

 git checkout libaptdec

From: https://github.com/f4exb/sdrangel/wiki/Compile-from-source-in-Linux

(Although I've just updated the master branch - so maybe that will now work too if you git pull on it)

**Comment by joecupano** [comment]
Cheers and Thank you for all your efforts and contribution.
