### ISSUE TITLE
Plotting radiosondes on map causes crash

### ISSUE THREAD

**Issue by kord1e** [f4exb/sdrangel#1318]
If you have radiosonde demodulator and the radiosonde "feature" window open, and then try to use the map feature to plot the sondes on map, SDRangel crashes.

Only this is printed to SDRangel console output:

`Segmentation fault (core dumped)`

This can be seen in dmesg:

`[ 1676.273605] sdrangel[2836]: segfault at 10 ip 000079c97f5b212c sp 00007ffd229354c0 error 4 in libQt5Core.so.5.15.3[79c97f36b000+2cb000]`

Receiving radiosondes works, plotting them on the map doesn't.  I tried to disable the 3D map feature but that didn't help.

Plotting aircraft on the map using the ADS-B demodulator works without problems (both separate map, and the built in map in the demod).

Operating system is Fedora 36 running as a QubesOS VM. 

SDRangel version is 7.3.2, installed from repositories.

Receiver is RTL-SDR.

**Comment by srcejon** [comment]
Should be fixed in this build: https://github.com/f4exb/sdrangel/suites/7157837753/artifacts/284976988
