### ISSUE TITLE
double free or corruption (!prev)

### ISSUE THREAD

**Issue by eu2aa** [f4exb/sdrangel#1321]
Hello Edouard,

Thanks for the great program.
I have been using it every day for over 3 years.
Thanks to your program, I achieved high results when working through the QO-100 satellite in the CW mode
https://qo100dx.club/rankings-dxcc
https://qo100dx.club/rankings-grids
using an earlier version.

I also work in SSB and FT-8 (I keep PTT manually).

A week ago I switched to your latest version of SDRangel 7.3.0, and see many new features.

Unfortunately, getting frequent crashes. Literally every 2-4 minutes or so.
In SSB, CW and FT-8 modes.
Sometimes I can finish QSO, and sometimes I can't.

My setup: OpenSUSE + PLUTO + SDRangel 7.3.0

I am getting this error:

```
double free or corruption (!prev)
sdrangel exited with code: null
```
or this error
```
malloc(): invalid next size (unsorted)
sdrangel exited with code: null
```

I would be very grateful for any advice,

--
Yours sincerely,
Vladimir Chepyzhenko,
EU2AA
2019 - https://observablehq.com/@eu2aa
2017  - http://eu2aa.com
1992 - https://eu2aa-qrz-ru.translate.goog/orbita.html?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=en&_x_tr_sch=http

**Comment by srcejon** [comment]
Which was the earlier version that was working for you?

A screenshot showing the channels / features you have open might help.

**Comment by eu2aa** [comment]
I don't remember exact version, but it was v6.x.x

![EU2AA_2022-07-02 13-49-09](https://user-images.githubusercontent.com/13078619/176998082-d1a6ef59-f177-4c1c-a065-9e329bbca63b.png)

Sometimes it gives this splash screen.

![EU2AA_2022-07-02 13-49-50](https://user-images.githubusercontent.com/13078619/176998119-012542d6-d2dd-4c9d-bdbd-7b1b42da821b.png)

**Comment by eu2aa** [comment]
free(): invalid pointer
node:internal/errors:692
  const ex = new Error(msg);
             ^

Error: socket hang up
    at connResetException (node:internal/errors:692:14)
    at Socket.socketOnEnd (node:_http_client:478:23)
    at Socket.emit (node:events:539:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'ECONNRESET'
}

**Comment by eu2aa** [comment]
double free or corruption (!prev)
sdrangel exited with code: null

**Comment by eu2aa** [comment]
Took action:
1 Connected PLUTO through a separate USB-C HUB.
2 MIDI, which I use for the RIT function, remained on the same HUB.
A USB microphone is also connected there.
3 I noticed that when TX1 was turned on, the SDRangel screen began to twitch much less.

**Comment by eu2aa** [comment]
Noticed one feature.
First of all, the panorama freezes, the reception continues, but blindly.
There is no transmission either.

**Comment by eu2aa** [comment]
On August 1, the CW worked with the F6HCC.
The program crashed 6 times.
Jean was perplexed, had to apologize every time.

**Comment by eu2aa** [comment]
**Solving the problem**

After starting Strangel in the window
https://github.com/eu2aa/eu2aa.github.io/blob/master/photo/T1_.png 
you need to press the start/stop generation button THREE TIMES: ON — OFF — ON

Then in the window
https://github.com/eu2aa/eu2aa.github.io/blob/master/photo/T1.0.png 
you need to press the Audio input button TWICE: OFF — ON

There are no failures after these procedures.

**The problem is solved.**
