### ISSUE TITLE
PlutoSDR RX Max Freq. 5,749,987

### ISSUE THREAD

**Issue by eu2aa** [f4exb/sdrangel#1324]
While working with PlutoSDR I was able to tune TX up to 6,000,000 KHz while RX is limited to 5,749,987 KHz
Is it limitation of SDRangel or PlutoSDR?

![Снимок экрана от 2022-07-02 16-38-38](https://user-images.githubusercontent.com/13078619/177003314-a5701960-849f-4677-a014-47d979dce318.png)

**Comment by drom** [comment]
I have the same issue. PlutoSDR customized as ad9361 https://wiki.analog.com/university/tools/pluto/users/customizing
Suppose to support up to 6GHz. But somehow is limited to 5,749,987 in SDRangel.

**Comment by f4exb** [comment]
Look at that "X" button that is engaged. This is the transverter mode. This recalculates the dial frequency depending on the transverter shift value. You have to switch it off for a direct access to the device frequency.

**Comment by drom** [comment]
Yep. Thank you. That works

**Comment by eu2aa** [comment]
В письме от воскресенье, 3 июля 2022 г. 10:40:58 MSK 
пользователь Edouard Griffiths написал:
> Look at that "X" button that is engaged. This is the 
transverter mode. This recalculates the dial frequency 
depending on the transverter shift value. You have to switch it 
off for a direct access to the device frequency.


Yes, I disabled the X button, the frequency was adjusted higher! 
Thanks for the helpful advice Edouard!

**Comment by eu2aa** [comment]
В письме от воскресенье, 3 июля 2022 г. 10:40:58 MSK 
пользователь Edouard Griffiths написал:
> Look at that "X" button that is engaged. This is the transverter 
mode. This recalculates the dial frequency depending on the 
transverter shift value. You have to switch it off for a direct access 
to the device frequency.

Yes, I disabled the X button, the frequency was adjusted higher!
Thanks for the helpful advice Edouard!

**Comment by f4exb** [comment]
hence closed.
