### ISSUE TITLE
DATV LDPC decoding question

### ISSUE THREAD

**Issue by DL9UFB** [f4exb/sdrangel#1341]
It is possibele to implement LDPC in the Windows Version for receiving DATV on QO-100?

**Comment by f4exb** [comment]
`ldpctool` is a Linux-centric external program. So... no.

**Comment by srcejon** [comment]
> `ldpctool` is a Linux-centric external program. So... no.

Could it not be modified to build as a library? I've only had a quick glance, but it seems fairly OS independent apart from ldpc_tool.cpp, which doesn't seem that big, so could potentially be adapted.

**Comment by srcejon** [comment]
With a just few changes ldpc_tool can build on Windows - the process management in leansdr/dvbs2 looks a little trickier though - but pipes to subprocesses can be made to work.

**Comment by f4exb** [comment]
Or use QThread...

**Comment by srcejon** [comment]
To clarify, I meant I can build ldpctool as a .exe on Windows - and in that case, pipes are needed for I/O to the child processes stdin/stdout. I've just written the code for this, but not working yet.

If it were to be rewritten as a library - then yes, QThread makes sense.

**Comment by f4exb** [comment]
I see but aren't pipes used already? Cf https://github.com/f4exb/sdrangel/blob/master/plugins/channelrx/demoddatv/leansdr/dvbs2.h#L3451

**Comment by f4exb** [comment]
Implemented in v7.6.0
