### ISSUE TITLE
Where to find download for old builds?

### ISSUE THREAD

**Issue by cjflnyc** [f4exb/sdrangel#1348]
Hello, I have an original HackRf one. I have to use an old version on Windows. I believe it was something around version 3 but it can even be version two. I had a backup of this windows build install but I lost the hard drive and its files. And for the life of me I can't find a link to the old builds. All the new versions I try with hackRF I can only set the frequency to max of 7.5 mhz. With the old version I was able to set the hackRF all the way into the UHF bands if I wanted.

I'm just looking for the last windows build where the original HackRF was able to transmit on all the supported frequency range of the device. I am so sorry if this request seems unusual but I don't know what else to do. This program worked great on my little hackRF and I tried to downgrade to version 4 and its still the same thing.  I'm sorry if I don't remember the exact build. This is why It would be nice to have a download link for a few of those older builds.
Thanks!
Regards.

**Comment by f4exb** [comment]
Some day you have to move forward...

**Comment by cjflnyc** [comment]
My apologies for wasting your time. I didn't realize the HackRF was obsolete.  I guess I'm going to have to find someone who can build from source. Shame it worked just fine on my Windows10 system. Thanks

**Comment by f4exb** [comment]
> the HackRF was obsolete

Not really. HackRF should run fine with the latest release.
