### ISSUE TITLE
Flathub build

### ISSUE THREAD

**Issue by AsciiWolf** [f4exb/sdrangel#1355]
I am working on a SDRangel Flatpak and want to publish it on [Flathub](https://flathub.org/). Please, let me know whether you are interested in co-maintaining the Flatpak. Thanks! :-)

**Comment by f4exb** [comment]
>  Please, let me know whether you are interested in co-maintaining the Flatpak. Thanks! :-)

Clearly, no sorry.

**Comment by AsciiWolf** [comment]
That's fine, I just had to ask (it's in the Flathub rules). :-)
