### ISSUE TITLE
Channel Analyzer: changing "Trace offset" switches trace memory back to #1

### ISSUE THREAD

**Issue by Forlorn18** [f4exb/sdrangel#1375]
Hi and thank you for this great tool!

I'm facing an issue in Channel Analyzer plugin while being on a memorized trace older than the first saved one (let's say "M: 04"):
- the first step change of "Trace offset" correctly applies the offset to the trace view, but it also changes to "M: 01" indication
- the second step change of "Trace offset" displays the first memorized trace (and applies the offset on it)

The issue is visible even with no acquired signal, simply by opening a fresh new Channel Analyzer window and moving to any memorized trace other than "M: 01".

Debian unstable, SDRangel 7.6.1 from github released .deb package (with package tweaking due to #1373)

**Comment by f4exb** [comment]
Originally this was done to solve this issue: https://github.com/f4exb/sdrangel/issues/892
