### ISSUE TITLE
PlutoSDR Output Plugin missing in 32bit windows release

### ISSUE THREAD

**Issue by RipperFox** [f4exb/sdrangel#138]
- Works in sdrangel64_v3.11.0
- Missing in sdrangel_v3.12.0 & sdrangel_v3.11.0

**Comment by f4exb** [comment]
It looks like it is missing from the deployment script: windows.install.bat and therefore was not included in the bundle.

**Comment by f4exb** [comment]
Redeployed sdrangel_v3.12.0.7z now including the missing plugin. Also fixed the deployment script for the next releases.
