### ISSUE TITLE
M17 plugin does not load because of an undefined symbol

### ISSUE THREAD

**Issue by AsciiWolf** [f4exb/sdrangel#1380]
Latest SDRangel 7.6.1 (Flatpak build from [Flathub](https://flathub.org)). This is in the SDRangel log:

`PluginManager::loadPluginsDir: Cannot load library /app/lib/sdrangel/plugins/libmodm17.so: (/app/lib/sdrangel/plugins/libmodm17.so: undefined symbol: _ZN9M17ModGUI30on_channelSpacingApply_clickedEv)`

**Comment by f4exb** [comment]
This is `M17ModGUI::on_channelSpacingApply_clicked` but it should not be implemented. I guess this is a leftover from NFMDemod from which the GUI was copied.
