### ISSUE TITLE
Missing mimo channels for Bladerf 

### ISSUE THREAD

**Issue by alphafox02** [f4exb/sdrangel#1388]
Setup: 20.04 source builds and deb packages. 

Expected Result: Using bladerf, selected Mimo source and then fine doa channel.

Actual Result: Using both the latest source and deb package installs, mimo channels are no longer listed. 

Temp Fix: Reverting to the deb package that specifically mentioned the doa mimo channel does in fact present the option.

Not sure what gas changed recently or why the beam steer and other channels are missing.

**Comment by f4exb** [comment]
There is a stray comma here: https://github.com/f4exb/sdrangel/blob/master/CMakeLists.txt#L103 this was missed when fixing #1310 

It should be:
```cmake
option(ENABLE_CHANNELMIMO "Enable channelmimo plugins" ON)
```
