### ISSUE TITLE
Impossible to compile on windows... 

### ISSUE THREAD

**Issue by Paulo-D2000** [f4exb/sdrangel#1396]
Windows 10
VS 2022
QT 5.15.2
CMake 3.24.1
Ninja 1.10.2

[61/2933] Linking CXX shared library bin\httpserver.dll
FAILED: bin/httpserver.dll lib/httpserver.lib
...
bin\httpserver.dll : fatal error LNK1120: 303 unresolved externs

**Comment by Paulo-D2000** [comment]
[error.txt](https://github.com/f4exb/sdrangel/files/9440015/error.txt)

**Comment by gvanem** [comment]
Simple, you are mixing `x86` .obj-files with `x64` libraries:

* Link command `/machine:X86`
* and using 64-bit libraries: `C:\Qt\5.15.2\msvc2019_64\lib\Qt5Network.lib`

You need to fix your Qt setup for `QTDIR=C:\Qt\5.15.2\msvc2019` instead.

**Comment by Paulo-D2000** [comment]
Thanks! I've used the x64 tools from msvc
