### ISSUE TITLE
Adalm Pluto

### ISSUE THREAD

**Issue by loewal** [f4exb/sdrangel#1398]
Could you please incorporate support for Adalm Pluto in the macOS DMG file?

Thnx of course!

**Comment by srcejon** [comment]
Does it work if you compile it with mac ports?

**Comment by loewal** [comment]
I have it working with Homebrew, but this has the disadvantage, that I have to start SDRangel from the prompt.
Not a big deal of course, but I would like to start it from the taskbar. Using a Hackrf or RTLSDR is possible then, but not Pluto.

**Comment by srcejon** [comment]
Done
