### ISSUE TITLE
aptdec removed `apt_image_t.zenith`

### ISSUE THREAD

**Issue by ra1nb0w** [f4exb/sdrangel#1422]
https://github.com/Xerbo/aptdec/commit/18ac507d32f088b038f5abcb04e77417af2eaced

**Comment by srcejon** [comment]
Ok, I'll take a look.

Note the instructions suggest this version:

git clone https://github.com/srcejon/aptdec.git

**Comment by srcejon** [comment]
The current aptdec code can't compile with MSVC, so this can't be updated at the moment.

**Comment by ra1nb0w** [comment]
Do you want that I will open an issue to aptdec about MSVC?

**Comment by srcejon** [comment]
https://github.com/Xerbo/aptdec/issues/20

**Comment by ra1nb0w** [comment]
gut. thank you

**Comment by ra1nb0w** [comment]
https://github.com/Xerbo/aptdec/commit/8be50e7844ccc8a9fce263127978fb3017f0f60d fixes the `zenith` issue
