### ISSUE TITLE
LO ppm correction not working with HackRF SDR

### ISSUE THREAD

**Issue by MihaiRF** [f4exb/sdrangel#1443]
The ppm correction slider does not seem to work with my HackRF card. The applied correction is corresponding to the default value (0ppm) no mater the slider position.
However, it does work with my AirSPY mini.

Thank you,
Regards,
YO5OMT

**Comment by f4exb** [comment]
Hardware correction does not seem to work

**Comment by MihaiRF** [comment]
Hi,
I'm using an older version (the latest from repository - 6.17.4) and probably missing this fix. Or maybe I got it wrong, is there another way to compensate for the reference error in the app? I'm using a very stable oven controlled 10Mhz reference and it would be nice to have the exact numbers...
Thank you, 73!
