### ISSUE TITLE
Request: In Satellite Tracker, allow AOS/LOS commands to use Satellite Tracker variables

### ISSUE THREAD

**Issue by gvimlag** [f4exb/sdrangel#1452]
Request:
According to https://github.com/f4exb/sdrangel/blob/master/plugins/feature/satellitetracker/readme.md
the "AOS speech warning" and "LOS speech warning" allow the user to use the following variables:
```
  ${name}
  ${duration}
  ${elevation}
```

Please allow the "AOS command" and "LOS command" (under both "Show settings dialog" and "SDRangel control") to also use these variables.
In addition, please add more variables.  For example:
```
  ${name}
  ${duration}
  ${elevation}
  ${LOS}
  ${AOS}
  ${Range}
```

Use examples (under both "Show settings dialog" and "SDRangel control"):
```
  AOS command: /tmp/test.bash "${name} started at ${AOS} at ${Range} kilometers"
  LOS command: /tmp/test.bash "${name} stopped at ${LOS} at ${Range} kilometers"
```

**Comment by srcejon** [comment]
Implemented in above patch.
