### ISSUE TITLE
RTLSDR Direct mode

### ISSUE THREAD

**Issue by letonton** [f4exb/sdrangel#146]
Bonjour
le build pour Win marche très bien... cependant la gamme pour le Rtl sdr en direct mode
s'arrete à 1Mhz, pas possible d'arriver au moins à 200Khz ?

**Comment by f4exb** [comment]
Sure. I think that direct mode should actually start at DC as it is supposed to connect to the ADC directly.

**Comment by f4exb** [comment]
Implemented in v3.13.1
