### ISSUE TITLE
BUG: Option and window settings forgotten

### ISSUE THREAD

**Issue by gvimlag** [f4exb/sdrangel#1474]
PROBLEM:
When SDRangel is closed and re-opened, some window sizes are altered, plus some device settings are forgotten.
(These issues also occur with saved "Configurations...".)

EXAMPLE ("Satellite Tracker" configuration):
```
rm -rf ~/.config/f4exb                        #clean initial conditions
SoapySDRUtil --probe                          #detect Soapy devices
/opt/install/sdrangel/bin/sdrangel --soapy    #start sdrangel
  Maximize SDRangel window
  Preferences->Devices->User arguments...
    <select>SoapySDR 1 SoapySDR[1:0] remote: Generic TRL2832U OEM :: 00000001
    <down arrow: Add the selected hardware to the list below>
    <select>SoapySDR 1 
    Args: soapy=0,driver=remote,remote:driver=rtlsdr
    OK
  Add Rx device:
      SoapySDR[1:0] remote: Generic RTL2832U OEM :: 00000001
    OK
  Add channels:
      AM Demodulator
    Apply
      APT Demodulator
    Apply
    Close
  Add features:
      Map
    Apply
      Satellite Tracker feature
    Apply
    Close
  Configure settings for:
    SoapySDR[1:0] device
      enlarge window to show all options
      Frequency: 0,137,500 kHz
      enable AGC
      max Global gain
      max TUNER gain
    AM Demodulator channel
      adjust window to minimum size
      move window below SoapySDR[1:0] device window
      max RF BW
      max Vol
      min Sq
    APT Demodulator channel
      adjust window to minimum size
      move window to right side of SoapySDR[1:0] device window
    Spectrum R:0 SoapySDR[1:0] Window
      adjust window to minimum size
      move window to below APT Demodulator window
      expand frequency spectrum and reduce waterfall
      Averaging type: Fix
      Number of averaging samples (avg time: 20.00ms): 20
    Satellite Tracker feature
      adjust window to minimum size
      move window to right side of APT Demodulator window
      Select satellites
        Add satellite to selected list:
          NOAA 15
          NOAA 18
          NOAA 19
        OK
      Update satellite data
      Target: NOAA 18
  start/stop tracking    #start
  start/stop tracking    #stop
      <select>"Next" in Satellite Data Window (sort by "Next")    <- must be done after start/stop to avoid crash
    Map feature
      adjust window to minimum size
      move window to below Satellite Tracker window
  Preferences->Save all
    OK
  Preferences->Configurations...
    Save current workspaces configuration as new configuration
      Group:       Test
      Description: Test1
      OK
    Close
>> <SNAPSHOT-1>
  close SDRangel
SoapySDRUtil --probe                          #detect Soapy devices
/opt/install/sdrangel/bin/sdrangel --soapy    #restart sdrangel
>> <SNAPSHOT-2>
  Preferences->Configurations...
    <select>Test1
    Load selected configuration
    Close
>> <SNAPSHOT-3>
```

**SNAPSHOT-1: before close/reopen**
![Screenshot_20221012_020522](https://user-images.githubusercontent.com/90478595/195290432-327dd3f3-1244-4d2c-8adf-29889f44c89b.png)

**SNAPSHOT-2: after  close/reopen**
![Screenshot_20221012_020701](https://user-images.githubusercontent.com/90478595/195290584-ddb5baed-9651-43fb-a7fa-edfc2765be76.png)

**SNAPSHOT-3: after  "Preferences->Configurations...->Load selected configuration->Test1"**
![Screenshot_20221012_020933](https://user-images.githubusercontent.com/90478595/195290609-0d1c089d-e29d-4e4c-93bc-ca88598e216a.png)

**SoapySDR[1:0] device window changes**:
  AGC, Global gain, TUNER gain settings are all reset to OFF or ZERO.

**Satellite Tracker window changes**:
  The window length has extended down and partially covered the Map.
    <To see the window size change, click "adjust window to minimum size" to restore original size>
  Target: NOAA18 is reset to ISS
  Under "Satellite Data", "Next" sorting selection is lost

**APT Demodulator R0:1 window changes**:
  The window length is extended down covering the top part of the Spectrum window.
    <To see the window size change, click "adjust window to minimum size" to restore original size>

**Map window changes**:
  The window length is extended down.
    <To see the window size change, click "adjust window to minimum size" to restore original size>

**Spectrum window changes**:
  Waterfall scale (left side) has changed

**AM Demodulator window changes**:
  Window size preserved.
  All settings preserved.

SYSTEM:
```
  Hardware: x86 64-bit
  OS:       Debian 11 (bullseye) 64-bit
  Hardware: Raspberry Pi 4B
  OS:       Raspberry Pi OS Lite (bullseye) 64-bit
  Dongle:   RTL-SDR + antenna
  SDRangel: (compiled from source following "https://github.com/f4exb/sdrangel/wiki/Compile-from-source-in-Linux")
    Version 7.8.0-10-gc6496b11f
    Build info: Qt 5.15.2 64 bits
    DSP Rx 16 bits    Tx 16 bits
      Included plugins for "Hardware dependencies":
        RTL-SDR
      Included plugins for "Soapy SDR":
        RTL-SDR
        Soapy Remote
```

**Comment by CRD716** [comment]
sounds a little like #1432 but the config settings not saving is different
