### ISSUE TITLE
Feature Request: HD Radio Demodulator

### ISSUE THREAD

**Issue by CRD716** [f4exb/sdrangel#1475]
https://www.sigidwiki.com/wiki/HD_Radio_(FM)
https://en.wikipedia.org/wiki/HD_Radio
More importantly (and usefully)
https://github.com/theori-io/nrsc5

This is a very popular standard in my area, and it would be nice to have the option of high quality FM (and AM) stations with an SDR dongle. From my basic investigation it seems like it is mostly proprietary, however the github linked and sididwiki seem to point to there being at least some information out there.

Side note: Sorry for opening all these feature requests, just putting some ideas out there.

**Comment by srcejon** [comment]
Ideas welcome - but only seems to be in North America, so not something I can look at. Maybe someone else though.

**Comment by CRD716** [comment]
I'll attempt to grab some iq samples when I have the time, hopefully they'll help.

**Comment by CRD716** [comment]
[I think this should be good enough, was messing with some things though.](https://drive.google.com/file/d/16STXA8evVZt50Pg_yu6fWm-78y1Cq3BK/view?usp=sharing)
