### ISSUE TITLE
RTL SDR input max frequency is 1900MHz

### ISSUE THREAD

**Issue by srcejon** [f4exb/sdrangel#1497]
In rtlsdrinput.cpp, we have:

const quint64 RTLSDRInput::frequencyHighRangeMax = 1900000UL;

However, with the e4000 tuner, max frequency is supposedly 2.3GHz. E.g: https://www.nooelec.com/store/nesdr-xtr-rtl2832u-e4000.html

rtlsdr_tuner rtlsdr_get_tuner_type() should indicate if RTLSDR_TUNER_E4000 or RTLSDR_TUNER_R820, it we want to limit to 1900 for 820 tuners.

**Comment by f4exb** [comment]
Since dialing a frequency out of range does not seem to hurt anything maybe I would just set the limiit to 2.4 GHz so it can fit all possible tuners and possibly the 2.3 GHz Ham band for the E4000 units that may work at these frequencies since it is also very much dependent on the units.
