### ISSUE TITLE
Audio setup problems on Apple Silicon

### ISSUE THREAD

**Issue by betzburger** [f4exb/sdrangel#1498]
Hi Edouard,

I did some FT8 tests with SDRangel in combination with a RSPduo for reception and a HackRF One for transmission.
Windows version works perfectly. I was able to get some QSOs just with the output power of the HackRF at around 0,01 watts which is incredible.

But the Mac version - at least on my M1 Apple Silicon - does not work very well.
As soon as I try to set up the audio with virtual audio cables (I tried VB cable and Blackhole) by right clicking on the microphone on the SSB modulator unit or any other loudspeaker icon, I am unable to use SDRangel anymore.
When I then try to click again on - let’s say the microphone icon - I can’t switch it on or off anymore. Infact the whole SDRangel software does not respond correctly to buttons anymore.

You may think that I fucked up something on my system but other software like WSJT-X can set audio without problems. 

Any idea?

73,
Peter (DD2ZG)

**Comment by f4exb** [comment]
I do not have a Mac
