### ISSUE TITLE
For specturm component instead of binding to + bind to = and do this for any similar thing

### ISSUE THREAD

**Issue by Wolf2482-1639** [f4exb/sdrangel#1499]
This will remove unnecessary shift presses

**Comment by f4exb** [comment]
Can you be more precise?

**Comment by srcejon** [comment]
+ and - for zooming in and out of 3D view? If so, then yes, we make = the same function as +, so you don't have to press shift.

**Comment by Wolf2482-1639** [comment]
srcejon that is what I mean. I got a bit confused when I saw your thing thinking it was already implemented but saw that it was merged an hour or two ago. Now I just need to wait for the nix package to update. I think i can close this.
