### ISSUE TITLE
Aborted termination

### ISSUE THREAD

**Issue by wwoofbum** [f4exb/sdrangel#1506]
Raspberry Pi 4B 8Gb, Bullseye, following install as per SDRplayHamGuides, Raspberry Pi4 2gb with the RSPdx, with ./build_sdrangel_rpi.sh -all -cores, and ./build_sdrangel_rpi.sh -wisdom, executed with sdrangel --fftwf-wisdom ~/.config/f4exb/fftw-wisdom, on termination, the following:
...
SDRangel quit.
FFTFactory::~FFFactory: deleting FFTs
AMBEEngine::~AMBEEngine: 0 controllers
DataPipes::stopGC
MessagePipes::stopGC
munmap: Invalid argument
munmap: Invalid argument
munmap: Invalid argument
close: Bad file descriptor
double free or corruption (!prev)
Aborted

Does this represent a problem?

**Comment by srcejon** [comment]
Yes, that looks like a problem. Next step would be to track down where it's coming from. You could try using the debugger:

    gdb /path/to/sdrangel
    run

Debugger should stop when it aborts, and you can type:

    info stack

And then copy and paste the output here.

Or, you could try removing plugins one-by-one, to see which plugin is causing the problem.
