### ISSUE TITLE
Build error on Mac M1 (Apple Silicon) 

### ISSUE THREAD

**Issue by betzburger** [f4exb/sdrangel#1515]
OK, since no one seems to have an idea on how to fix the audio input issue I already posted a few days ago, I thought it may be worth a try to build an Apple Silicon version by myself because the only available pre-built version of SDRangel is for Intel and that means all newer Macs can't run the software natively on the Apple silicon (arm64) and need to use The "Rosetta" Intel emulator. I thought maybe then audio input issues are gone.

So far so good. Has anyone been able to compile? I get an error at 77% with undefined symbols and I am stuck at that point. Any suggestions? Anyone?

-- GIT_EXECUTABLE /opt/local/bin/git
-- GIT LIVE REPO VERSION RETRIEVED
-- X265 RELEASE VERSION 3.5+68-40e37bce9
-- Detected CXX compiler using -O3 optimization level
-- Configuring done
-- Generating done
-- Build files have been written to: /opt/build/sdrangel/build/external/x265/src/x265-build
[ 27%] Performing build step for 'x265'
Consolidate compiler generated dependencies of target common
[ 45%] Built target common
Consolidate compiler generated dependencies of target encoder
[ 65%] Built target encoder
[ 76%] Built target x265-static
[ 77%] Linking CXX shared library libx265.dylib
Undefined symbols for architecture arm64:
  "x265_entropyStateBits", referenced from:
      _x265_costCoeffNxN_neon in pixel-util.S.o
     (maybe you meant: _x265_entropyStateBits)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[5]: *** [libx265.206.dylib] Error 1
make[4]: *** [CMakeFiles/x265-shared.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [external/x265/src/x265-stamp/x265-build] Error 2
make[1]: *** [external/CMakeFiles/x265.dir/all] Error 2
make: *** [all] Error 2

**Comment by srcejon** [comment]
That's a problem building the x265 video codec, so you'd probably need to ask here

https://www.videolan.org/developers/x265.html

Or, try building using macports instead.
