### ISSUE TITLE
Bug APT demodulator channel

### ISSUE THREAD

**Issue by choupette-change** [f4exb/sdrangel#1516]
Hello, APT demodulator channel no longer appears in the list of demodulators  in Ubuntu version ?
![image](https://user-images.githubusercontent.com/68333247/202175925-15da74b0-559c-4e1f-b64a-6dbdd88ed122.png)
![image](https://user-images.githubusercontent.com/68333247/202175996-7dec4b64-5306-4868-8d92-c11d60efdbd4.png)

**Comment by Valstee** [comment]
I think it's due to this durint compilation :
  ```
In file included from /opt/build/sdrangel/plugins/channelrx/demodapt/aptdemod.h:35,
                from /opt/build/sdrangel/plugins/channelrx/demodapt/aptdemod.cpp:19:
/opt/build/sdrangel/plugins/channelrx/demodapt/aptdemodimageworker.h:40:17: error: ‘libsgp4’ is not a namespace-name
40 | using namespace libsgp4;
      |                 ^~~~~~~
```

**Comment by srcejon** [comment]
> I think it's due to that during the compilation :
> 
> ```
> In file included from /opt/build/sdrangel/plugins/channelrx/demodapt/aptdemod.h:35,
>               from /opt/build/sdrangel/plugins/channelrx/demodapt/aptdemod.cpp:19:
> /opt/build/sdrangel/plugins/channelrx/demodapt/aptdemodimageworker.h:40:17: error: ‘libsgp4’ is not a namespace-name
> 40 | using namespace libsgp4;
>     |                 ^~~~~~~
> ```

This error means you need to update and rebuild sgp4 - and also delete CMakeCache.txt in your sdrangel build directory and re-run cmake.

**Comment by choupette-change** [comment]
OK for me :) :)
