### ISSUE TITLE
Bug in Radiosonde Module - Speed/Heading Mixup

### ISSUE THREAD

**Issue by df6dbf** [f4exb/sdrangel#1527]
Hello!
i had tried to Monitoring Radiosondes with SDRangel. Thanks for your excellent work Edouard!
But it seems there is a mixup by displaying Speed and Heading. See the two Screenshots.

73s Holger, DF6DBF
![Speed_Screenshot 2022-12-04 131122](https://user-images.githubusercontent.com/19621920/205489860-605438c8-36bc-4970-9bf4-93f598e1fae5.jpg)
![Heading_Screenshot 2022-12-04 131122](https://user-images.githubusercontent.com/19621920/205489862-b313d229-9fbc-4e85-819f-e1cfcb2fed2d.jpg)

**Comment by f4exb** [comment]
Deployed in v7.8.5
