### ISSUE TITLE
DSD

### ISSUE THREAD

**Issue by wb2vwi** [f4exb/sdrangel#153]
NEW WIN VERSION WORKING GOOD.   PLEASE CHANGE POLARITY ON DMR MODE TO NEGATIVE
WHICH IS THE STANDARD ON DMR NETWORKS

**Comment by f4exb** [comment]
This is auto detected by DSDcc. If you find anything weird on this point please open an issue to DSDcc: https://github.com/f4exb/dsdcc/issues
