### ISSUE TITLE
SDRAngel Windows

### ISSUE THREAD

**Issue by dhagert** [f4exb/sdrangel#1534]
I am not able to find the link for the windows.exe file. Can someone help. Tanks Dale

**Comment by srcejon** [comment]
There is no windows build for 7.8.4. The last is 7.8.3: https://github.com/f4exb/sdrangel/releases/download/v7.8.3/sdrangel-7.8.3-win64.exe

**Comment by mistergitj** [comment]
There is a a Windows build for 7.8.5 just released today.  You will need to signed in to GitHub. Enjoy, John.

**Comment by f4exb** [comment]
Did you mean 7.8.6? https://github.com/f4exb/sdrangel/releases/tag/v7.8.6 Normally the upload of artifacts to releases has been fixed and it should not be necessary to be signed in anymore.
