### ISSUE TITLE
FM Broadcast plug-in and RDS

### ISSUE THREAD

**Issue by clivekay** [f4exb/sdrangel#1545]
Does anyone know in simple terms how to get RDS data to work . I switch it on on the toggle ,but nothing in the RDS pain works..What am I doing wrong ..Clues would be a help .

**Comment by srcejon** [comment]
Do you have stereo on too?

https://github.com/f4exb/sdrangel/blob/master/plugins/channelrx/demodbfm/readme.md

RDS data. Note that decoding RDS data requires the locking to the stereo pilot carrier therefore you should switch to stereo (A.3) to be able to decode RDS data

**Comment by clivekay** [comment]
Many thanks .. Didn’t see that .. Switched on and now all working !! Thanks fro the speedy reply . !!


Clive Kay G4TIH
