### ISSUE TITLE
Radio clock TDF demodulation is not working?

### ISSUE THREAD

**Issue by kord1e** [f4exb/sdrangel#1562]
I think the TDF radio clock demodulator may not be working. Can someone confirm? 

Or is there something wrong with the actual signal on 162 kHz? 

MSF and DCF77 demodulation work well.

SDRangel version is 7.8.4 and it was compiled from github source some weeks ago.

**Comment by f4exb** [comment]
it does work if you have good reception. You have to be a little bit patient so that it acquires the minute mark and starts decoding:
![image](https://user-images.githubusercontent.com/6192319/211173199-3d7198e5-df0f-4b67-bf4b-a6e6439cafbc.png)

**Comment by kord1e** [comment]
@f4exb
Ok, thanks for confirming, maybe signal level is the problem then. But TDF 162 kHz signal seems quite strong here and I think I can even see the minute marker coming, it should be visible in this picture I think... But decoding doesn't start. I've tried different bandwidth and threshold options too.

![TDF_clock](https://user-images.githubusercontent.com/79941375/213887427-66bae8f3-e626-46be-8476-48f75ea0850b.png)

**Comment by srcejon** [comment]
It's working OK for me too

![image](https://user-images.githubusercontent.com/57259258/217830063-00141abd-5884-4bf4-a680-3c39aa5f8b8d.png)

In the scope, set the trace to FM (in red box) and also include the centre frequency (other red box) in the screenshot please.

**Comment by kord1e** [comment]
I tuned the clock a bit lower than the top peak of the signal, set the scope to FM. Then I fine adjusted the frequency until the scope signal was centered. Now it finds the minute marker but loses it usually after 20 seconds or so.

I tried changing the bandwidth and threshold values but it didn't help, it still finds the minute marker but loses it before another marker comes.

Does this mean that the signal is too weak? The peak is almost 40 dB above noise floor.

![tdf2](https://user-images.githubusercontent.com/79941375/218850395-7fdd2370-2b22-4b2a-8a7e-f78e40a9db39.png)

**Comment by srcejon** [comment]
What sdr are you using and what are your settings? Seems a bit odd the frequency is that far off (but i'd have to go double check)

**Comment by f4exb** [comment]
From the device UI behind I can guess it is a RTL-SDR and that the "No-mod DS" (for direct sampling) is not checked. So I guess that at this very low frequency for RTL-SDR some converter sits on the front and its LO may not be very accurate.

**Comment by Ronda-00** [comment]
please
FYI receiving antenna is a MLA-30+ with a double loop

What diameter is the double loop and separation?

Thanks
