### ISSUE TITLE
Android "nightly" builds

### ISSUE THREAD

**Issue by fagci** [f4exb/sdrangel#1568]
Thanks for Android version.

Will be good to have Github action with Android target to build master and dev branches.

Or you can share just workflow of build, will adopt it for action.

**Comment by srcejon** [comment]
It's not straight forward to build. Currently:

It uses a patched version of Qt.
Some libraries are built on Linux, some on Windows.
Different bits are built with different versions of the Android cross-compilers.
It's not fully scripted yet, as cmake's support for Android has a couple of problems.

It should be possible to get it working, but it's not there yet.
