### ISSUE TITLE
V7.8.6 The program did not respond and crashed when trying to open "AudioOutput".

### ISSUE THREAD

**Issue by minexixi** [f4exb/sdrangel#1574]
V7.8.6 The program did not respond and crashed when trying to open "AudioOutput".
There is no ATV modulator in the mode list of the TX device.
There is no IEEE 802.15.4 demodulator in the mode list of RX devices.
The IEEE 802.15.4 modulator of TX device cannot open the window, and the main program does not respond.

**Comment by srcejon** [comment]
What OS are you on.

There isn't an 802.15.4 demodulator. The modulator opens ok for me.

ATV missing is in https://github.com/f4exb/sdrangel/issues/1525

**Comment by srcejon** [comment]
Crash in Audio output is due to m_worker being a nullpointer:

     AudioOutput::applySettings

        if (m_running) {
            m_worker->setIQMapping(settings.m_iqMapping);
        }

Looks like m_running isn't initialised.

**Comment by srcejon** [comment]
There's also a crash when closing Audio Output, looks like the mutex has been deleted, when AudioFifo::write is called.

![image](https://user-images.githubusercontent.com/57259258/215044392-bdcd9b0b-642a-4b8b-9ff5-65451f5c025c.png)

Looks like a deleted FIFO in the audioFifos list:

![image](https://user-images.githubusercontent.com/57259258/215045034-40406915-0072-42fe-aef2-3f5baeadceb1.png)

**Comment by srcejon** [comment]
Reopened, as there's a second bug, when trying to close the Audio Output, as shown in the post above.

**Comment by minexixi** [comment]
> What OS are you on?
> 
> There isn't an 802.15.4 demodulator. The modulator opens ok for me.
> 
> ATV mod missing is in #1525

Windows 11

**Comment by minexixi** [comment]
> 你是什​​么操作系统？
> 
> 没有 802.15.4 解调器。调制器对我来说打开正常。
> 
> 缺少 ATV 模组在#1525

![image](https://user-images.githubusercontent.com/24314717/215091254-97c79b01-5c7b-4939-81e2-92ce22c23456.png)
IEEE 802.15.4 modulator is available most of the time and occasionally results in no response
