### ISSUE TITLE
SDRPlay: increase the range of LO ppm

### ISSUE THREAD

**Issue by minexixi** [f4exb/sdrangel#1576]
It is recommended to increase the range of LO ppm. My device has a frequency error of - 52ppm. The frequency cannot be configured correctly in SDRAngel

**Comment by f4exb** [comment]
Don't you think something is missing in your request?

**Comment by minexixi** [comment]
> Don't you think something is missing in your request?

ummmm
V7.8.6 now only ±20ppm

**Comment by srcejon** [comment]
What SDR...?

**Comment by minexixi** [comment]
SDRPlay RSP1.LO frequency calibration.
![image](https://user-images.githubusercontent.com/24314717/215260764-c6f9f1e7-012c-4a8c-b8e8-f84eaf5ab013.png)

**Comment by f4exb** [comment]
Maybe check SDRPlay v.1 as well
