### ISSUE TITLE
sdrangel Android size of letters

### ISSUE THREAD

**Issue by cvafiadis** [f4exb/sdrangel#1579]
Hi to everybody 
thank you for the excellent app
please if possible a sollution for bigger letters otherwise is not workable..

thanks

**Comment by bubnikv** [comment]
I have the same issue on Chromebook running the Android build. It works nicely demodulating my KiwiSDR, however the font is extremely tiny, unreadable.

**Comment by srcejon** [comment]
> I have the same issue on Chromebook running the Android build. It works nicely demodulating my KiwiSDR, however the font is extremely tiny, unreadable.

Can you send a screenshot please.

**Comment by bubnikv** [comment]
[image: image.png]

**Comment by srcejon** [comment]
That didn't quite work unfortunately. Can you try attaching the image via the github site rather than email?

**Comment by bubnikv** [comment]
![image](https://user-images.githubusercontent.com/5830947/216927541-7812991d-9d96-4edf-b765-7eca1c098de0.png)
