### ISSUE TITLE
Compilation problem

### ISSUE THREAD

**Issue by pinozgit** [f4exb/sdrangel#1580]
On Mint 20.1 

/opt/build/sdrangel/build$ make -j $(nproc) install

[ 82%] Building CXX object plugins/channeltx/modchirpchat/CMakeFiles/modchirpchat.dir/chirpchatmodencoderlora.cpp.o
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libavcodec.a(lpc.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: failed to set dynamic section sizes: bad value
collect2: error: ld returned 1 exit status

**Comment by srcejon** [comment]
See: https://github.com/f4exb/sdrangel/issues/1339
