### ISSUE TITLE
Cannot find prebuilt *.dmg for MacOS

### ISSUE THREAD

**Issue by wolfch** [f4exb/sdrangel#1582]
This page: [https://github.com/f4exb/sdrangel/wiki/Quick-start](https://github.com/f4exb/sdrangel/wiki/Quick-start) says:
```
Mac O/S
For most releases you will find a .dmg file.
```
...without any links to such `*.dmg` file(s).  I've been clicking on different links and seem to be going in circles without finding a binary release for MacOS

**Comment by srcejon** [comment]
Releases page is: https://github.com/f4exb/sdrangel/releases

Expand the assets section:

![image](https://user-images.githubusercontent.com/57259258/216006321-932a4b39-10a0-4b96-8d53-85127a20d22e.png)

Latest is: https://github.com/f4exb/sdrangel/releases/download/v7.8.6/sdrangel-7.8.6-macx64.dmg

7.9.0 is still building!

**Comment by wolfch** [comment]
@srcejon - thanks for the link!  That worked. (I missed your initial response, sorry)
