### ISSUE TITLE
Compilation problem CMake Error 

### ISSUE THREAD

**Issue by EvgenRo** [f4exb/sdrangel#1598]
When compiling on MacOS, Terminal gives an error:  

CMake Error at /Users/evgen/Qt/Tools/CMake/CMake.app/Contents/share/cmake-3.24/Modules/ExternalProject.cmake:2741 (message):
  error: could not find svn for checkout of lame
Call Stack (most recent call first):
  /Users/evgen/Qt/Tools/CMake/CMake.app/Contents/share/cmake-3.24/Modules/ExternalProject.cmake:4170 (_ep_add_download_command)
  external/CMakeLists.txt:487 (ExternalProject_Add)
  
  How to fix it?
  Thanx.
  
  MacOs Ventura 13.1

<img width="1039" alt="Снимок экрана 2023-02-14 в 16 28 47" src="https://user-images.githubusercontent.com/93591577/218768581-8d55754f-7f74-4f59-9216-f5dd0a91cd1f.png">

**Comment by srcejon** [comment]
Looks like you need to install subversion (svn)

**Comment by srcejon** [comment]
I don't think svn is part of Qt. It was included with XCode at some point, but I think they removed it.

https://subversion.apache.org/packages.html

**Comment by EvgenRo** [comment]
> I don't think svn is part of Qt. It was included with XCode at some point, but I think they removed it.
> 
> https://subversion.apache.org/packages.html

Install SVN from MacPorts - fixed!
Thanx!
