### ISSUE TITLE
Compilation problem CMake Error

### ISSUE THREAD

**Issue by EvgenRo** [f4exb/sdrangel#1599]
After more than an hour of compiling, the Terminal gave such an error:

CMake Error at cmake/Modules/UHDComponent.cmake:59 (message):
  Dependencies for required component LibUHD not met.
Call Stack (most recent call first):
  CMakeLists.txt:432 (LIBUHD_REGISTER_COMPONENT)
  
After fixing this error, a new error appeared.

-- Generating done
-- Build files have been written to: /opt/build/sdrangel/build/external/uhd/src/uhd-build
[ 33%] Performing build step for 'uhd'
Consolidate compiler generated dependencies of target uhd_rpclib
[  2%] Built target uhd_rpclib
Consolidate compiler generated dependencies of target uhd-resources
[  5%] Built target uhd-resources
[  5%] Generating /opt/build/sdrangel/build/external/uhd/src/uhd-build/lib/transport/vrt_if_packet.cpp
/bin/sh: -B: command not found
make[5]: *** [lib/transport/vrt_if_packet.cpp] Error 127
make[4]: *** [lib/CMakeFiles/uhd.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [external/uhd/src/uhd-stamp/uhd-build] Error 2
make[1]: *** [external/CMakeFiles/uhd.dir/all] Error 2
make: *** [all] Error 2

  How to fix it?
  
  MacOs Ventura 13.1

  <img width="819" alt="Снимок экрана 2023-02-15 в 17 21 15" src="https://user-images.githubusercontent.com/93591577/219070908-e705185e-e5f4-4564-90f2-6f1940a35686.png">

**Comment by EvgenRo** [comment]
Fix in CMakeLists.txt  string 432

LIBUHD_REGISTER_COMPONENT("LibUHD" ENABLE_LIBUHD ON "Boost_FOUND;HAVE_PYTHON_MODULE_MAKO" OFF ON)

on

LIBUHD_REGISTER_COMPONENT("LibUHD" ENABLE_LIBUHD ON "Boost_FOUND;HAVE_PYTHON_MODULE_MAKO" ON ON)

**Comment by f4exb** [comment]
This is in libuhd code not SDRangel.
