### ISSUE TITLE
Bug in the decoding of the DAB TII?

### ISSUE THREAD

**Issue by choupette-change** [f4exb/sdrangel#1608]
Hello, SDRangel does not give the correct decoding of the TII of my radio. SDRAngel gives Main TII: FF and Sub TII: OA, another application gives Main TII: 20 and sub TII:10. The official documentation gives 20 and 10. Sincerely
![image](https://user-images.githubusercontent.com/68333247/221408654-9667e46e-0829-4146-9002-a0ab9b68b142.png)
![image](https://user-images.githubusercontent.com/68333247/221408668-4281ef60-98f3-4362-804e-934f5ca605e8.png)

**Comment by srcejon** [comment]
The sub ID is the same, it's just 0a is in hex and 10 is decimal. Not sure why you are getting FF for the main though.

Can you record a few minutes of IQ data as a .wav file (not .sdriq as that will be double the size), so I can give it a try?

**Comment by srcejon** [comment]
Actually, I've found a similar problem here with a Main TII of 20, that is being decoded as ff. The problem appears to be in the DAB library, rather than SDRangel though.

**Comment by srcejon** [comment]
> Ok, do you still need a sample of this radio ?

No, it's ok for now, as I've found a transmitter with TII of 20 as well.

> Can you remind me how to record in .wav ? 

Use the file sink, but set filename to file.wav rather than file.sdriq.

**Comment by choupette-change** [comment]
OK, I found this site to have the informations on the French DAB transmitters, if it can help you..
https://extranet.arcom.fr/radio/

**Comment by srcejon** [comment]
Thanks for the link. 

Does this look right?

![image](https://user-images.githubusercontent.com/57259258/221716117-6c52cd3c-c75c-4cc6-ae52-a58549bb152c.png)

**Comment by choupette-change** [comment]
hello, it's ok for me for these 2 examples Thank you
