### ISSUE TITLE
No Map in ASDB Plug-In .. Is it me ??

### ISSUE THREAD

**Issue by clivekay** [f4exb/sdrangel#1616]

**Comment by clivekay** [comment]
I open ADSB plug-in on the latest version and My map has gone .. What am I doing wrong ??

**Comment by clivekay** [comment]
Many thanks 🙏. Worked a treat ! On 6 Mar 2023, at 15:24, srcejon ***@***.***> wrote:﻿
Try Preferences > Graphics and set 2D Map MSAA to Off.

**Comment by clivekay** [comment]
Can the readout show the origin and destination of the aircraft ??

**Comment by srcejon** [comment]
Only in some cases, and if you have setup an avaiation stack API key.

See https://github.com/f4exb/sdrangel/blob/master/plugins/channelrx/demodadsb/readme.md
