### ISSUE TITLE
Spectrum initialisation

### ISSUE THREAD

**Issue by srcejon** [f4exb/sdrangel#1624]
It seems the Spectrum GUI does not completely reflect the spectrum settings when a spectrum is first displayed. To see this:

- Open any device (As an example use the Test Source and enable FM Modulation)
- Press start
- The spectrum will have the phosphor effect, but the phosphor effect button (histogram) will be unchecked.
- If you then press the button, the waterfall share will be adjusted.

This is probably because m_displayHistogram is initialsed to true in GlSpectrumView, but false in SpectrumSettings
Similarly, m_waterfallShare is 0.5 and 0.66. Also, m_displayCurrent is different between the two.

Easily fixed, but which setting would you prefer?

Secondly, how should a channel initialise the SpectrumSettings if it has an embedded spectrum? I see several channels use calls such as (From ft8demodgui):

	ui->glSpectrum->setDisplayMaxHold(true);

However, this only effects GLSpectrum, not GLSpectrumGUI, so the the GUI and SpectrumSettings will not be in sync (E.g. open FT8Demod and max hold is enabled in the spectrum, but the button is not checked).

I see some channels send a SpectrumVis::MsgConfigureSpectrumVis message to SpectrumVis, but SpectrumVis doesn't appear to forward this to GLSpectrumGUI, so doing it like that can also result in inconsistencies.

GLSpectrumGUI has the public functions updateFrom() and updateSettings(), that can result in settings being propagated to both GLSpectrum and SpectrumVis - but these are for the WebAPI, so not as convenient as something like a getSettings()/setSettings() call. However, I guess it's possible to have a GLSpectrum without GLSpectrumGUI - so perhaps the settings should just be sent to SpectrumVis, which should then propagate them on to any buddies.

**Comment by f4exb** [comment]
Re point #1: the constructor of `GLSpectrumGUI` is supposed to apply its settings to the `GLSpectrum` at constructor time however at this time the `GLSpectrum` is not referenced yet (it is nullptr) so this does not work. Probably this has to take place later.

**Comment by f4exb** [comment]
>  so perhaps the settings should just be sent to SpectrumVis, which should then propagate them on to any buddies.

Yes it should work like this

Also the direct calls to `ui->glSpectrum` set commands should simply not be there at least in the case of the FT8 and SSB demods. FT8 demod was copied from SSB demod originally and for some reason this was present in SSB demod but should not be there really.
