### ISSUE TITLE
Crash on Android when audio comes from DSD

### ISSUE THREAD

**Issue by fagci** [f4exb/sdrangel#1627]
If i switch off output from DSD, app will not crash.
Log created with crash.
[2023-03-11-13-01-06.txt](https://github.com/f4exb/sdrangel/files/10947814/2023-03-11-13-01-06.txt)

![IMG_20230311_134130](https://user-images.githubusercontent.com/8795970/224469612-6ce71556-c152-4c50-ad34-48ac6ec2ccec.jpg)

**Comment by Egghead67** [comment]
Was this issue ever resolved? All other channels work perfectly on my android tablet- looks fantastic too, but the moment I get a signal while using the DSD Demodulator the app will immediately crash. I've tried several configurations but always have the same issue.

**Comment by Auxilus** [comment]
I am still facing this issue, is there any work around for this?
