### ISSUE TITLE
hackRF unconfigured

### ISSUE THREAD

**Issue by EA3IGB** [f4exb/sdrangel#1628]
Hello
When installing drivers with Zadig for an RTL having the HackRF connected, it has been deconfigured. Now when it starts up, only the 3V3 and 1V8 leds go, I put the DFU mode but it is not recognized by the PC either. I have tried something with Hampi (linux) and Pentoo but I still can't find the key that solves the problem. Has anyone had this problem or could help me?  Thanks
![image](https://user-images.githubusercontent.com/94387371/224476251-2ecec2ef-63aa-4fb2-9a72-2a7292be37d7.png)
![image](https://user-images.githubusercontent.com/94387371/224476262-8180aa49-30ab-4db9-bbf7-f3ff3bd44d06.png)
![image](https://user-images.githubusercontent.com/94387371/224476281-cc9c6b87-87e1-41b9-a60f-4ddf05d6bc3c.png)
![image](https://user-images.githubusercontent.com/94387371/224476301-fac13bc6-d6c3-41bd-96ca-0deee5bde29c.png)

**Comment by f4exb** [comment]
Anything related to SDRangel? Maybe you posted this issue in the wrong place...

**Comment by EA3IGB** [comment]
NO, I'm just explaining how I got to this, the problem is the Hack, not the SDRAngel

**Comment by f4exb** [comment]
OK so I close the issue. The best place to post your question would be in a forum about HackRF. You can still possibly ask for help in the SDRangel forum: http://sdrangel.org/forum/index.php
