### ISSUE TITLE
How do I transmit?

### ISSUE THREAD

**Issue by radio-satellites** [f4exb/sdrangel#1630]
Hi,

Great software! I used to be able to transmit with my HackRF before, however now I can't seem to find the "add plugin" button. Where is it? And I searched the docs as well :)

73!

VE3SVF

**Comment by f4exb** [comment]
Hello, this is here: https://github.com/f4exb/sdrangel/tree/master/sdrgui#13-create-new-transmitter

**Comment by radio-satellites** [comment]
@f4exb yes agreed, I got that far. But how do I add a modulating device?

**Comment by srcejon** [comment]
Press the add channel button

![image](https://user-images.githubusercontent.com/57259258/228323968-f4c6122a-6ab0-492b-a326-e226ebdef6f9.png)

**Comment by radio-satellites** [comment]
Thank you so much!!

**Comment by radio-satellites** [comment]
close
