### ISSUE TITLE
Timestamp in Radio Astronomy plugin radiometer CSV export has no timezone.

### ISSUE THREAD

**Issue by lrowen** [f4exb/sdrangel#1640]
The Time column in the CSV radiometer data is timezone-naive.  There should be the option for a numeric UTC offset after the seconds so that timezone-aware analysis pipelines can properly correlate the times between different observations from different instruments.

Example:
current Time format: 13:35:00
desired Time format: 13:35:00+0000 or 13:35:00-0400 or similar.

**Comment by srcejon** [comment]
Sounds reasonable. Perhaps I could just add a UTC column to the table, so either could be viewed depending on what is most relevant for whatever it is you are doing.

**Comment by lrowen** [comment]
Either way is fine with me.

**Comment by srcejon** [comment]
In 7.12.0
