### ISSUE TITLE
Satellite Tracker not pulling in TLE from new Celestrak format

### ISSUE THREAD

**Issue by lrowen** [f4exb/sdrangel#1647]
Subject says it all.  The Celestrak website changed the URL format.  The page at [https://celestrak.org/NORAD/elements/](url) now points to a more dynamic query type URL.  Using the GPS operational satellites as an example, the URL is:

`https://celestrak.org/NORAD/elements/gp.php?GROUP=gps-ops&FORMAT=tle`

**Comment by srcejon** [comment]
Seems to work for me using the commit tag you e-mailed.

In the log I see:

2023-03-31 08:40:34.034 (D) HttpDownloadManager: Downloading from  QUrl("https://celestrak.org/NORAD/elements/gp.php?GROUP=gps-ops&FORMAT=tle")  to  "/home/jon/.local/share/f4exb/SDRangel/tle_gp.php"
2023-03-31 08:40:34.226 (D) HttpDownloadManager: Download from  "https://celestrak.org/NORAD/elements/gp.php?GROUP=gps-ops&FORMAT=tle"  to  "/home/jon/.local/share/f4exb/SDRangel/tle_gp.php"  finshed.

![image](https://user-images.githubusercontent.com/57259258/229056464-56b0f3c7-6423-4b0e-8c6c-39df124bd65b.png)

What does it say in your log?

**Comment by lrowen** [comment]
Hmm.... Not at the computer to check the log, unfortunately, but I do
remember seeing a tle_gp.php file.  If you have two of them (say
https://celestrak.org/NORAD/elements/gp.php?GROUP=gps-ops&FORMAT=tle and
https://celestrak.org/NORAD/elements/gp.php?GROUP=active&FORMAT=tle ) does
the download code overwrite tle_gp.php or merge it?  I was wondering why on
the production ops PC I had the 'active' the first, then the gps-ops list
second; the only satellites in the list are GPS.  On my laptop I had the
gps-ops first then the active, and it seems Celestrak has them named
differently in the two downloads.....  So perhaps a bug but not the bug I
thought..... I'll check when I have time, today's a full schedule and it
won't likely be today.

--
Lamar Owen

**Comment by srcejon** [comment]
> If you have two of them (say https://celestrak.org/NORAD/elements/gp.php?GROUP=gps-ops&FORMAT=tle and https://celestrak.org/NORAD/elements/gp.php?GROUP=active&FORMAT=tle ) does the download code overwrite tle_gp.php or merge it? 

It's overwriting it, so I'll have to fix that.
