### ISSUE TITLE
HackRF decimation issue

### ISSUE THREAD

**Issue by bdn76** [f4exb/sdrangel#165]
I'm need monitor 2MHz spectrum and listen around 8 channel but i'm hear audio distortion with sample rate more than ~600ks/s but i need more for listen spectrum distnce channel (with SQ of course). Why i can not use high sample rate for NBFM without decimation?

**Comment by f4exb** [comment]
I cannot understand this dribble can someone translate please?

**Comment by f4exb** [comment]
Try to be more specific and describe exactly what you are trying to do with detailed steps to be able to reproduce.

**Comment by bdn76** [comment]
I'm sorry for my english. In first example i use low decimation but nfm demodulator not work:

![wide-spectrum-not-work](https://user-images.githubusercontent.com/17513453/39230430-20fcc0f8-486f-11e8-847f-aefeb9599782.jpg)

In second example i use high decimation and nfm demod work fine:

![narrow-spectrum-work](https://user-images.githubusercontent.com/17513453/39230431-211d43dc-486f-11e8-95be-04b8791e2e65.jpg)

How i can listent to channel with ~1MHz distance?

**Comment by f4exb** [comment]
Thanks for the screenshots this helps a lot. Well it looks like you are running a RTL-SDR not a HackRF. So I see a first issue with the settings of RTL-SDR: your gain is zero so you are not going to get much RF into the system anyway. The stripes you see on the waterfall are probably internal birdies. You should push this slider at least into the ~40 dB range and if you get overloaded by strong signals you can check the AGC checkbox next.

**Comment by bdn76** [comment]
I'm provide with screenshot for explanation only because i have not HackRF at hand now but problem exactly the same - nbfm rx channel work fine with low I/Q sample rate (up to ~300k) and not work with high I/Q sample rate (above ~300k). I can listen one channel with low sample rate perfectly but i can not listen two channel simultaneously with big frequency distance (1MHz as on second screenshot). Are you understand my explanation?

**Comment by f4exb** [comment]
Does it make any difference if at "high" I/Q sample rate (say 2.4 MS/s) you reduce the distance between channels to the same distance you are using for ~300k (with decimation)? This is to sort out if pb is due to sample rate or channel separation. Also can you provide a screenshot with the settings of the NFM demodulator?

**Comment by bdn76** [comment]
I'm check now - no. With "high" I/Q sample rate i can not start even one channel but i can start two or more with "low" I/Q sample rate. Are you need screentshot?

**Comment by f4exb** [comment]
A few more questions first:
- On which hardware are you running
- I see you run on a Debian buster (testing) distribution. Did you compile from source or did you install the Debian release package?

**Comment by bdn76** [comment]
i5 M520 2.4G, 8GB.
Compile from source.
With "high" I/Q sample rate i can not use nfm demod at all - noise and rattle instead of voice but with "low" I/Q nbfm work fine.

**Comment by f4exb** [comment]
No problem here... (this is dev version but there are no differences with 3.14.4 for that matter).
![2018-04-26-235519_1920x1080_scrot](https://user-images.githubusercontent.com/6192319/39334050-71b6001a-49ad-11e8-8817-40c96afb65b6.png)

**Comment by bdn76** [comment]
I'm think this is phosphor issue. If i'm enable phosphor then CPU usage drop to 200% insead of 400% without phosphor.

Work fine (~400% CPU usage, all 4 core work):
![20180427084435](https://user-images.githubusercontent.com/17513453/39346588-a0563454-49f7-11e8-9982-d644d1a0204c.jpg)
![20180427084221](https://user-images.githubusercontent.com/17513453/39346600-aeaf0922-49f7-11e8-8dbf-4da20c4bdc4f.jpg)

Not work (~200% CPU usage, only 2 core work):
![20180427084120](https://user-images.githubusercontent.com/17513453/39346648-e2811b0a-49f7-11e8-8e97-602b06fa36fd.jpg)
![20180427084158](https://user-images.githubusercontent.com/17513453/39346657-e70dd578-49f7-11e8-86ec-c9d4cf16c1c5.jpg)

And thus if i use only 2 core i have I/Q processing limitation.

**Comment by f4exb** [comment]
OK I see... you have to set parameters sensibly. It does not make sense to run at 20 MS/s and have a RF filter at 1.75 MHz. 20 MS/s is very fast and needs powerful hardware (at least i7 8 core CPU) to be run properly. It is interesting to notice however that the phosphor thing changes the way the CPU cores are used. For sure 209.6% for 2 CPU is too much while 379% for 4 CPU is still (barely) acceptable.

This is very high CPU usage though. Did you compile with the 24 bit sample option on? You should turn it off for such high speed operation and of course compile for release and not debug.

**Comment by f4exb** [comment]
Not an issue.
