### ISSUE TITLE
[Feature Request] Be able to output audio from packet modulator

### ISSUE THREAD

**Issue by radio-satellites** [f4exb/sdrangel#1651]
Is it please possible to do so?

Thanks!!!

73!

Sasha VE3SVF

**Comment by srcejon** [comment]
Sorry, misread that as the demodulator.

What are you trying to do?

**Comment by radio-satellites** [comment]
@srcejon so I have a python app which sends APRS messages. I couldn't get it to connect to direwolf to modulate the signal, so SDRAngel was the only option. It worked well via UDP, so I used it. However, it only allows the transmission into a HackRF; I need it to go into an HT.

**Comment by srcejon** [comment]
Have you tried the audio output device?

**Comment by srcejon** [comment]
Actually,  that probably won't work if you just need the afsk modulation.

**Comment by radio-satellites** [comment]
Yeah, I tried that. Unfortunately, it just outputs FM IQ to the soundcard.

**Comment by f4exb** [comment]
The best possible way to implement this use case would be to add an audio output to the demod analyzer. However this use case is not in the scope of a SDR application that processes in and out I/Q data not real audio.

**Comment by srcejon** [comment]
As a possible workaround:

- add a Remote Output device with the Packet Modulator
- add a Remote Input device with a NFM Demodulator (i.e. so you have a TX -> RX loopback within SDRangel)

You should then get the demodulated audio from the NFM Demodulator. It sounds about right - not sure how well it will work though,
