### ISSUE TITLE
Heat Map plugin: Save to image or csv doesn't work

### ISSUE THREAD

**Issue by kermit112** [f4exb/sdrangel#1652]
Using v7.12.0 on Windows 10, I couldn't save any image or csv from the heatmap plugin. If I'm trying to do so, there's window that's telling me, it couldn't open the file I defined before. 
Any hint how to solve this? Am I holding it wrong?

**Comment by srcejon** [comment]
Where are you try to save it to? You wont be able to write to the sdrangel directory. Try c:\users\you or post a screenshot.

**Comment by kermit112** [comment]
I thought I've tested another location, but it seems I was wrong. Saving in another folder works, so thank you for the hint!
