### ISSUE TITLE
Support Adalm Pluto on Mac

### ISSUE THREAD

**Issue by loewal** [f4exb/sdrangel#1657]
Sorry if this is not the right place:

I would like support fot the Adalm Pluto in the MacOs DMG-version.

Thanks

**Comment by srcejon** [comment]
Currently ENABLE_IIO=OFF for the DMG build, because current build of libxml2 requires autoconf which is a dependency I didn't want on Mac.

However, it looks like it may be able to be built with cmake instead - so I'll give that a try.

**Comment by loewal** [comment]
Thanks in advance Jon


Regards

**Comment by srcejon** [comment]
Give this a try - No idea if it works, as I don't have a pluto.

https://sdrangel.org/downloads/sdrangel-7.13.0_10.14.6_x86_64.dmg

**Comment by loewal** [comment]
Yes Jon. It works!
Ever so grateful. Will support be permanent now?

Kind regards

**Comment by srcejon** [comment]
Implemented.
