### ISSUE TITLE
Apt demodulator is no longer avaliable in flatpak and nix build.

### ISSUE THREAD

**Issue by Tungsten842** [f4exb/sdrangel#1659]
With sdrangel 7.13 from flatpak and from nix this can be seen:
![image](https://user-images.githubusercontent.com/24614168/232204937-833aa37d-1d44-4699-9ea3-f87774aac777.png)

**Comment by srcejon** [comment]
I think you need to report that to whoever builds it, as it isn't done by us.

The problem will probably be that the aptdec library is missing, when cmake is run.
