### ISSUE TITLE
Frequency Manager

### ISSUE THREAD

**Issue by jwmarcinek** [f4exb/sdrangel#1666]
Please forgive me if this has been already asked, or if this is the wrong subforum to ask it, but does SDRAngel have any sort of Frequency Manager?

Something where I can bookmark/make a list of the frequencies I use along with a description, like "162.550 KWO-39 Chicago". I'm not looking for anything fancier, like labels on the spectrum or anything.

Thanks in advance, I am LOVING the program....using the Android version.

**Comment by srcejon** [comment]
Yes, see the Spectrum Annotation markers: https://github.com/f4exb/sdrangel/blob/master/sdrgui/gui/spectrummarkers.md#annotation-markers-tab

When Annotations are added, a Goto button will appear in the Spectrum GUI controls.

**Comment by jwmarcinek** [comment]
Thank you!

**Comment by arfy8820** [comment]
This seems related, and maybe a bit fancier, but does SDRangel have anything like a band manager, and related stepping on that band? For example. The AM broadcast band could be defined as being between 522 and 1620KHZ, with a step size of 9KHZ, using an AM demodulator. If you then switched to say, 93.5MHZ, it would be within the FM band, where the step size is 100KHZ and switched to a Broadcast FM demodulator. The FM band would be between 88 and 108MHZ. This seems like the perfect use of the web API, or perhaps this is already a plugin?
