### ISSUE TITLE
sdrangelspectrum (angular/core and angular/cli version updated)

### ISSUE THREAD

**Issue by Valstee** [f4exb/sdrangel#1669]
Hi F4EXB, 
I know it's not the right directory but it's been several nights that I've been trying to install sdrangelspectrum on ubuntu 22.04 whether it's in a docker or not without succeeding because of angular/core, angular/cli updates, etc... can you look at how to fix this? it was really great to be able to do this remotely...
Thanks a lot,
F4JIZ

**Comment by f4exb** [comment]
sdrangelspectrum is too way in the past. It cannot be updated anymore.

**Comment by f4exb** [comment]
Closed in favor of https://github.com/f4exb/sdrangelspectrum/issues/36
