### ISSUE TITLE
c++: fatal error: when compiling SDRangel

### ISSUE THREAD

**Issue by thomstas** [f4exb/sdrangel#1680]
Hello
Need help
Raspberry PI4B Raspbian Buster get error:

[ 14%] Building CXX object sdrbase/CMakeFiles/sdrbase.dir/sdrbase_autogen/3YJK5W5UP7/qrc_webapi.cpp.o
c++: fatal error: signal terminated program cc1plus
compilation terminated.
make[2]: *** [sdrbase/CMakeFiles/sdrbase.dir/build.make:2226: sdrbase/CMakeFiles/sdrbase.dir/sdrbase_autogen/3YJK5W5UP7/qrc_webapi.cpp.o] Błąd 1
make[1]: *** [CMakeFiles/Makefile2:4835: sdrbase/CMakeFiles/sdrbase.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
pi@raspberrypi:/opt/build/sdrangel/build$

**Comment by srcejon** [comment]
Probably out of memory. 

Try make without -j option
