### ISSUE TITLE
7.14.1: SR and BB inverted on ADS-B window?

### ISSUE THREAD

**Issue by Antonov-2** [f4exb/sdrangel#1698]
Salut Ed,

Used to be able to decode ADS-B quite easily using 7.14.0. Now, it seems that SR is calling a value to be more than 3,200,000 (as usual) but displaying the current value as 143,850, the exact value of ... the BB, therefore rendering its decoding un-doable. Have a look on  the screenshot.

Cheers.

Phil
<img width="453" alt="Screenshot 2023-05-25 at 13 39 03" src="https://github.com/f4exb/sdrangel/assets/95187570/07ed0a05-f45f-4c46-b874-476cae488300">

**Comment by srcejon** [comment]
You have DEC (decimation) set to 16. Set it to 1.

**Comment by Antonov-2** [comment]
My fault. Woks now!

Cheers.

Phil
