### ISSUE TITLE
add timestamp to filename of .sdriq file

### ISSUE THREAD

**Issue by beta-tester** [f4exb/sdrangel#170]
it would be great, when each recording to file would get a unique file name each time you press record.
it happend to me very often that i override an existing recorded sdrif file by accident, because each time sdrangel is using the same file name.

maybe  there is a reason for that current behavior, but there is also a reason to do not override files or better create unique files each time you make a recording.
so maybe make it optionional to add a timestamp to the filename.

**Comment by beta-tester** [comment]
thank you for the changed file name.
but guess the ':' (collon) in the filename (HH:mm:ss) will be an issue for windows file systems. a collon is not allowed - only for drive letter separation (**C:**\...)

**Comment by f4exb** [comment]
This is why I like Windows so much :) The format `yyyy-MM-ddTHH:mm:ss` is the ISO format for a date/time stamp. OK to remove the colons ...

**Comment by beta-tester** [comment]
oops...
i thought i could help a little bit with doing some easy stuff instead of wasting your time...
by doing [pullrequest ](https://github.com/f4exb/sdrangel/pull/177)...
but i was too slow.

**Comment by f4exb** [comment]
kept!
