### ISSUE TITLE
SDRplay build error

### ISSUE THREAD

**Issue by FabC** [f4exb/sdrangel#1703]
When [building from sources](https://github.com/f4exb/sdrangel/wiki/Compile-from-source-in-Linux) , "SDRplay (Using SDRplay's V3 API)" chapter, the command `sudo install_lib.sh` cannot be executed on Linux Mint 21: should it be changed in `sudo .\install_lib.sh` ?

**Comment by f4exb** [comment]
Probably `sudo ./install_lib.sh` yes.

**Comment by f4exb** [comment]
Wiki updated
