### ISSUE TITLE
Aaronia RTSA RX connection issue

### ISSUE THREAD

**Issue by maxPUNKT** [f4exb/sdrangel#1708]
Hello,

i tried to connect with my Spectran V6/RTSA Suite and both sites show an established connection. SDRAngel is able to read the frequency of the IQ demodulator and also write it.
But I get no output and the sample rate is 0. If I try to change the sample rate, it jumpes back to 0.

I used sdrangel newest build 7.14.2 and RTSA Suite Build 12821 and 12598.
Tried on two different Computers Win10 and Win11.

Thanks in advance
Max

**Comment by f4exb** [comment]
Make sure you follow instructions closely: https://github.com/f4exb/sdrangel/tree/master/plugins/samplesource/aaroniartsainput#readme

In particular: "Of course the IQ Demodulator span should fit in the bandwidth set in the Spectran V6 block else it will yield no output."
