### ISSUE TITLE
Build for Qt6

### ISSUE THREAD

**Issue by choupette-change** [f4exb/sdrangel#1712]
hello, I can't find libqt6charts6-dev in my distribution: Ubuntu 22.10 ??

**Comment by srcejon** [comment]
https://packages.ubuntu.com/search?keywords=qt+charts+&searchon=names&suite=kinetic&section=all

Try qt6-charts-dev maybe.

**Comment by choupette-change** [comment]
it's good but I don't have the "MAP" feature ?
![image](https://github.com/f4exb/sdrangel/assets/68333247/8d0df1c0-977d-4f93-8ada-5fb542e7fce8)

**Comment by srcejon** [comment]
There isn't any.
