### ISSUE TITLE
fatal error C1083: : “hidapi.h”: No such file or directory

### ISSUE THREAD

**Issue by dream100200** [f4exb/sdrangel#1714]
hi,My project's compilation environment is VS2015 or Qt 5.15 on Windows 10 . When I compile the project, it shows that a file(hidapi.h) is missing. Please explain why this is happening. Thank you.

**Comment by srcejon** [comment]
Please show the full error message.

Compile instructions are here: https://github.com/f4exb/sdrangel/wiki/Compile-in-Windows - VS2015 isn't recommended.

**Comment by dream100200** [comment]
the only error just point out the file of hidapi.h is missed when complied the project with vs2015.
the only err msg: it can not find a file of hidapi.h.

**Comment by srcejon** [comment]
If you don't show the full context of the error you are seeing, I can't help you.

**Comment by dream100200** [comment]
ok,tks, i check out slowly by Compile instructions are here: https://github.com/f4exb/sdrangel/wiki/Compile-in-Windows - VS2015 isn't recommended.

**Comment by f4exb** [comment]
hidapi.h is provided via an external library in the external/windows submodule: https://github.com/f4exb/sdrangel-windows-libraries/tree/a3f4cd7f7e1250a7fa79fce9d5edc573747ca819/hidapi/include 

When cloning the repository did you do a "git submodule init" and "git submodule update" ?
