### ISSUE TITLE
PlutoSDR issue with soft decimation and Fc

### ISSUE THREAD

**Issue by beta-tester** [f4exb/sdrangel#172]
hello,
i have an issue with PlutoSDR and "Software Decimation" in combination with "Relative position of device center frequency".
it is not an issue with RTLSDR source, when using the equivalent switches.

if **Software Decimation** is =1, it does not matter that **Relative position of device center frequency** mode i use, all frequencies are where they should be.

if i turn **Software Decimation** >1 and **Relative position of device center frequency** mode to "Cen" then still everything is ok.

but if i turn **Software Decimation** to >1 and **Relative position of device center frequency** mode to "Sup" or "Inf", then the all frequencies are shifted or swapped  (don't know how to explain).

see picture compilation:
![sdrangel-plutosdr-1-cen](https://user-images.githubusercontent.com/4750719/39764190-5c0cf3be-52df-11e8-8293-d7eb4841c75a.jpg)
![sdrangel-plutosdr-1-sup](https://user-images.githubusercontent.com/4750719/39764208-65dd6d7e-52df-11e8-9d31-5b4d80e41598.jpg)
![sdrangel-plutosdr-1-inf](https://user-images.githubusercontent.com/4750719/39764198-619ce050-52df-11e8-9a18-44558d5ea2c7.jpg)
![sdrangel-plutosdr-2-cen](https://user-images.githubusercontent.com/4750719/39764215-69380240-52df-11e8-9f4c-5415c9af4a2e.jpg)
![sdrangel-plutosdr-2-sup](https://user-images.githubusercontent.com/4750719/39764553-28b05172-52e0-11e8-8dba-2be88710e8a2.jpg)
![sdrangel-plutosdr-2-inf](https://user-images.githubusercontent.com/4750719/39764559-2c03b60c-52e0-11e8-87b7-9804ff068e1b.jpg)

and in case **Software Decimation** =1, and **Relative position of device center frequency** mode "Inf" or "Sup", when you just switch from **Software Decimation** =1 to **Software Decimation** >1, then there it appears as when the **Relative position of device center frequency** is switched to "Cen" in reallity, because there is not that issue describes for "Inf"/"Sup", but it does not show "Cen" - until you touch the **Relative position of device center frequency** mode switch and switch it to something else and back to the "Inf" or Sup" mode, then you again will see issue in the frequency band.

OS: Windows 10 Pro 64bit and Ubuntu 18.04 LTS 64 bit
SDRAngel: current official release ((SDRangel 3.14.5) and dev (SDRangel 3.14.6 Qt 5.9.5 64b x86_64 Ubuntu 18.04 LTS DSP Rx:16b Tx:16b )
devices: PlutoSDR rev B

**Comment by f4exb** [comment]
By comparing `plutosdrinput.cpp` and `rtlsdrinput.cpp` it seems the logic implementing the frequency shift is not implemented for Pluto.

I would like to take this opportunity to challenge the way the shifted decimation is made. There is a possible optimization by using the rotating halfband decimators only or mostly. The purpose of this kind of operation was to move the DC out of the band. It is enough in fact to move it on one side in which case a successive combination of rotating halfband decimators could work. This makes the frequency shift calculation different but only determined by the decimation factor and the decimation chain implemented for this decimation factor.

**Comment by f4exb** [comment]
These decimators have poor rejection and normally they should be used for monitoring a transmitter rather than for reception.

**Comment by f4exb** [comment]
This was not mentioned but v3.14.6 fixes the filtering also so inf/sup decimation can now be used normally. Moreover the frequency shift scheme has been changed to be closer to the device center frequency thus avoiding excessively large RF filters.

**Comment by beta-tester** [comment]
i saw it... thanks.
