### ISSUE TITLE
Question: Is it possible to publish the Android application on "alternative" app stores too?

### ISSUE THREAD

**Issue by cygeus** [f4exb/sdrangel#1723]
Currently the Android binary is only available trough the [Official Google Play Store](https://play.google.com/store/apps/details?id=org.sdrangel&pli=1). 
As I prefer to limit the presence of closed-source software on my phone, I currently download the binary from [APKPure](https://apkpure.com/sdrangel/org.sdrangel) and install it manually (after unzipping the xapk file) on my device using
`adb install-multiple config.xxhdpi.apk config.arm64_v8a.apk org.sdrangel.apk`

I was wondering if there is a possibility to publish the Android application on an alternative App Store like [F-Droid](https://f-droid.org/) or make the Android application available for download through GitHub or your [website](https://www.sdrangel.org/)?

**Comment by srcejon** [comment]
Yes, eventually the apk should appear on the releases page.
