### ISSUE TITLE
ADS-B Demodulator "blind"

### ISSUE THREAD

**Issue by Makvils** [f4exb/sdrangel#1728]
Windows 10
RTL-SDR USB
ADS-B Demodulator
Radiora SkyScan MK II
After a few days after installation,  stopped seeing planes.
Signal strength OK.
Reinstalling didn't help.
Is Windows update a problem? How to fix it?

**Comment by srcejon** [comment]
Please post a screenshot

**Comment by srcejon** [comment]
Your RFBW setting is too low. Try 2,500kHz.

You might also want to enable DC offset correction (The DC button).

(Also, the reason why you have some graphical problems is your graphics card/driver doesn't support OpenGL 3 - make sure you have the latest driver).

**Comment by Makvils** [comment]
Thank You, now works fine.

wt., 4 lip 2023, 17:38 użytkownik srcejon ***@***.***>
napisał:
