### ISSUE TITLE
TX Audio source fails after 1 TX cycle

### ISSUE THREAD

**Issue by artscotty** [f4exb/sdrangel#1731]
Using the latest release (compiled and binary versions) on MAC OS Ventura and Ubuntu 22.04, my Hack RF looses audio after one perfect transmission. The first time  I transmit the Mic audio is excellent and all works, then after the PTT is released, a second TX has no audio or a low noise but no audio. The TONE AUDIO still works and does CW so I assume it's related to audio devices. Has anyone found this or a solution? Thanks Scot

**Comment by f4exb** [comment]
Issue #1717 has revealed an outstanding design flaw with audio output. Audio input is affected by a similar flaw. The thread handling the audio is the one first starting the audio interface but it should be independent and tied to the audio device. However to implement a similar solution FCD audio handling should be amended to use the Audio Manager. 

When you stop/start the Tx device the attached channels are also stopped and started and in this process the "baseband" thread is also stopped and started.

**Comment by artscotty** [comment]
Edouard, thank you for your reply. I think you are suggesting I compile the 1717 buffer size() patch ? Also I must install some audio manager like PulseAudio on Mac and use this for audio?

**Comment by f4exb** [comment]
No this will not change anything, The problem is with the threading model. This has been fixed for audio output but the same flaw is present for audio input (what interests you here). In order to fix this the handling of Funcube Dongles (FCD plugins) has to be fixed to use the Audio Manager instead of accessing the audio input directly.

**Comment by f4exb** [comment]
Tried only with the TestSink plugin but it did fix the issue.

**Comment by artscotty** [comment]
Worth recompiling the current code then you think Eduardo?

**Comment by artscotty** [comment]
I have compiled and tested this with NFM Modulator and confirm it works as expected. I see no reason other modulators won't work correctly but have not tested those yet. Great job Eduardo!
