### ISSUE TITLE
OpenGL graphics corrupted on Ubuntu 23 04

### ISSUE THREAD

**Issue by choupette-change** [f4exb/sdrangel#1735]
Question: Have you tested Sdrangel vs Ubuntu 23 04?

**Comment by robbietee** [comment]
Yes. Compiled from source on Ubuntu 23.04. Spectrum windows show the window or desktop behind as if the window is transparent then it gets progressively weirder and not usable.
![Screenshot from 2023-07-15 00-47-14](https://github.com/f4exb/sdrangel/assets/71612217/1d906029-d62c-40e1-97d7-00f98815e338)
![Screenshot from 2023-07-15 00-48-06](https://github.com/f4exb/sdrangel/assets/71612217/cffd7117-226a-4cc3-95f5-aa0bd29ccb4d)

**Comment by robbietee** [comment]
Screenshots didn't catch the issue correctly. The actual screen looks more like this:
![5a006be9-410b-4af6-a810-7bd2ba2ced11](https://github.com/f4exb/sdrangel/assets/71612217/e5c1a31c-6210-48a5-84b9-974d59056671)
![5a006be9-410b-4af6-a810-7bd2ba2ced11](https://github.com/f4exb/sdrangel/assets/71612217/65a60395-75c2-4673-aae5-6ee9eacb9ced)

**Comment by robbietee** [comment]
Graphics issues aside, functionality is good. I found no issues with:
Rtl-Sdr 

Channels:
ADS-B
AIS
AM
Broadcast FM
DAB
NFM
Packet
Pager
Radiosonde
Packet
Pager

Features:
AIS
APRS
Map
Radiosonde

I've never had much luck with digital modes on any version. A "Configurations Download" Page would be useful.

Thanks, Rob M6RXT

**Comment by f4exb** [comment]
Not an issue with Ubuntu 23.04 nor the code. It compiles and wirks:
![image](https://github.com/f4exb/sdrangel/assets/6192319/b193054e-c22a-4479-ac00-bad401c0253d)

**Comment by srcejon** [comment]
I see the same problem,  so presumably something graphics driver / opengl related.

**Comment by f4exb** [comment]
Make sure you start compiling from scratch. The drivers have probably been upgraded this is to make sure the current version is used.

**Comment by robbietee** [comment]
I compiled from scratch on a fresh install and still have the issue. I will start researching.....

 *-display
             description: VGA compatible controller
             product: 3rd Gen Core processor Graphics Controller
             vendor: Intel Corporation
             physical id: 2
             bus info: pci@0000:00:02.0
             logical name: /dev/fb0
             version: 09
             width: 64 bits
             clock: 33MHz
             capabilities: msi pm vga_controller bus_master cap_list rom fb
             configuration: depth=32 driver=i915 latency=0 resolution=1366,768
             resources: irq:31 memory:f6400000-f67fffff memory:e0000000-efffffff ioport:f000(size=64) memory:c0000-dffff

**Comment by srcejon** [comment]
I just compiled the Qt openglwindow example (from Qt Creator) and this shows a similar corruption. So I suspect it's a Qt/Graphics driver issue.

**Comment by robbietee** [comment]
It's so annoying. I don't know why I bothered with the 23.04 "upgrade". Having said that, I haven't found any other issues with it....yet.

**Comment by srcejon** [comment]
If you can build from source, give that patch a try - it fixes it for me.
