### ISSUE TITLE
Porting to the sBitx v2

### ISSUE THREAD

**Issue by rafael2k** [f4exb/sdrangel#1736]
Any guide on how to port to another radio (1 channel alsa for tx/rx, 1 channel alsa for mic and speaker, and some gpio commands for frequency), called sBitx.
Can I individually select left and right alsa channels in sdrangel?

**Comment by f4exb** [comment]
If it can be controlled via CAT you can use the Audio CAT SISO plugin: https://github.com/f4exb/sdrangel/tree/master/plugins/samplemimo/audiocatsiso#audio-cat-siso-plugin

**Comment by rafael2k** [comment]
Perfect. Will give a try and report my results. I'm running Linux on the Pi 4. I was not really planning to use hamlib (but call directly the radio functions using a shared memory interface I created [1]).

[1] https://github.com/Rhizomatica/hermes-net/tree/main/trx_v2-userland

**Comment by rafael2k** [comment]
Hi Edouard, would it be ok if I reopen this one. I think the way to go is a specific plugin for supporting the sbitx, for example, to deal with using left and right for different purposes (mic and rx, tx and speaker), the passband is aroud 6 kHz up to around 30 kHz, and talk with the I/O daemon over shared memory as I'm writing in here:
https://github.com/Rhizomatica/hermes-net/tree/main/trx_v2-userland
