### ISSUE TITLE
DMG Please

### ISSUE THREAD

**Issue by loewal** [f4exb/sdrangel#1737]
DMG Please....

ThnX

**Comment by srcejon** [comment]
Not for a couple of weeks, I'm afraid,  as dont currently have access to a mac.

**Comment by artscotty** [comment]
> Not for a couple of weeks, I'm afraid, as dont currently have access to a mac.

Thanks Jon , I managed to compile 7.15.1 from src on ubuntu but im not able to compile on Mac as I cant get it to recognise my libusb and it errors out too much. I look forward you you getting a DMG out there for the TX audio fix version! Thanks again

**Comment by K7IU** [comment]
Is a .dmg for 7.15.1 available yet?  Is there a 7.14 .dmg someplace that I can try out until 7.15 is available?

**Comment by srcejon** [comment]
No 7.15.1, but 7.15.0 is available on the releases page if you click the "Assests" under 7.15.0 button a list of files will be displayed.

**Comment by K7IU** [comment]
Thanks, got it.Sent from my iPadAnd YES it's cool!On Jul 29, 2023, at 10:00 AM, srcejon ***@***.***> wrote:﻿
No 7.15.1, but 7.15.0 is available on the releases page if you click the "Assests" under 7.15.0 button a list of files will be displayed.

**Comment by srcejon** [comment]
DMG built for 7.15.2.
