### ISSUE TITLE
RSP1A missing under "Hardware/Native support for:" in "www.sdrangel.org" home-page

### ISSUE THREAD

**Issue by gvimlag** [f4exb/sdrangel#1743]
The web-page "https://github.com/f4exb/sdrangel/wiki/Sample-source-plugins-(Rx-devices)" shows that the "SDRplay RSP1A" is supported within plugin "SDRplay v3".

Unfortunately, the home-page "https://www.sdrangel.org/" is missing "SDRplay RSP1A" under "Hardware/Native support for:".
Please update the "www.sdrangel.org" home page.
Thank you.

**Comment by srcejon** [comment]
Done
