### ISSUE TITLE
GUI: Channels docker does not keep it size

### ISSUE THREAD

**Issue by antoine-roux** [f4exb/sdrangel#176]
### Description
Hello, since some time (sorry, I can't say when), the Channels docker doesn't keep the size I give it.

![buggy_docker](https://user-images.githubusercontent.com/2011328/39899622-512da210-54bd-11e8-8f3c-7cbbd8f8d8a4.gif)

If I move the docker elsewhere the problem disappear.
![docker_ok](https://user-images.githubusercontent.com/2011328/39899855-6dcf6ee8-54be-11e8-9613-8a06c34d3a51.gif)

### Version
sdrangel 3.14.5 Qt 5.10.1
ArchLinux up-to-date today

### Steps to Reproduce
- open sdrangel
- start the acquisition
- add a demodulator
- try to resize the Channels docker

Have a nice day,
Antoine

**Comment by f4exb** [comment]
First point: this is not normal. I don't have it with Qt 5.9.5 maybe this was introduced with 5.10

Second point: this is normal when changing the shape of the containing docker from a tall horizontal shape to a large vertical one. I think this is done by Qt and there is not much to do about it.

**Comment by antoine-roux** [comment]
Yes, I'm agree with you: the second screencast is the normal behaviour.
What I was explaining is when I open sdrangel and before I change the docker's layout, they can't be resized. If I change the layout of the docker, the first problem disappears...

Unfortunately, I would have many difficulties to try with Qt 5.9 as many of my distribution packages are dependent upon Qt 5.10

**Comment by antoine-roux** [comment]
As you said, this is a Qt bug: https://bugreports.qt.io/browse/QTBUG-65592
As it's known up-stream fell free to close the issue :)

Have a nice day!

**Comment by antoine-roux** [comment]
In case you want to add a workaround in the code... :innocent: https://stackoverflow.com/a/48871010
