### ISSUE TITLE
Application has issues running on macOS ARM

### ISSUE THREAD

**Issue by 555krhariharan555** [f4exb/sdrangel#1767]
The Waterfall is not getting generated. Instead of the waterfall, I am able to see an inverted view of dashboard.

Older versions of SDRAngel (The version before 3D waterfall) was working well.

Also wanted to know where to find the Presets TAB.

**Comment by srcejon** [comment]
What version of OpenGL is reported in the status bar?

Is there anything in the log? Perhaps a shader compilation error? 

Are you using 7.15.2, because I fixed a couple of shader issues recently.

Press the Star button for presets.

**Comment by 555krhariharan555** [comment]
<img width="1512" alt="Screenshot 2023-08-09 at 1 48 50 PM" src="https://github.com/f4exb/sdrangel/assets/61796721/dc298100-9a2a-4b18-9c43-5f1d2f40215f">

Please find the below OpenGL version and the mirror image in waterfall area. I currently using macOS 13.5 M1pro

**Comment by srcejon** [comment]
Ok, thanks. What's in the log file? (Preferences > logging)

**Comment by gutaker** [comment]
Same here Macbook Pro M1, macOS Sonoma, log below.
Requesting to reopen the issue.
[sdrangel.log](https://github.com/f4exb/sdrangel/files/13257493/sdrangel.log)
