### ISSUE TITLE
Version 7.15.2 has no SDRplay-support

### ISSUE THREAD

**Issue by loewal** [f4exb/sdrangel#1769]
SDRplay support missing in 7.15.2 DMG
Went back to 7.15.0 and there is was again.

Could you check please?

**Comment by srcejon** [comment]
Hmm - I didn't change anything in relation to that.

**Comment by ChristianFFB** [comment]
I can confirm this, my fake RSP1 is not visible after 7.14.1

**Comment by srcejon** [comment]
Yeah, I can see the plugin is missing - not sure why yet.

**Comment by srcejon** [comment]
Should be fixed in 7.15.3
