### ISSUE TITLE
Rotator Controller manual entry box up-down buttons for azimuth and elevation offsets are not precision-aware

### ISSUE THREAD

**Issue by lrowen** [f4exb/sdrangel#1771]
The manual up-down controls for the azimuth and elevation offsets change the value by integer degrees.  The change should probably track the precision of the offsets.  I've tried selecting portions of the number to change, but the up-down only changes the integer degrees.

**Comment by srcejon** [comment]
In GS232ControllerGUI::on_precision_valueChanged() you could try:

    double step = pow(10.0, -3.0);
    ui->coord1->setSingleStep(step);
    ui->coord2->setSingleStep(step);
    ui->azimuthOffset->setSingleStep(step);
    ui->elevationOffset->setSingleStep(step);

**Comment by lrowen** [comment]
That works.

**Comment by srcejon** [comment]
Implemented in 7.15.3
