### ISSUE TITLE
PlutoSDR not showing up in Sampling device list

### ISSUE THREAD

**Issue by w1wra** [f4exb/sdrangel#1780]
Windows 11 
SDRAngel 7.15.2

PlutoSDR is not showing up in the Sampling Device list. Works fine and is detected in various other apps.

It does show up as a TX device. When I select it as a TX device, it adds a sampling device that I can use.  However even once that device is created and is being used, it still does not appear in the Add Sampling Device list.

 The device does show up if I look in Preferences -> User -> Devices -> User Arguments 

The PlutoSDR is running v0.37 firmware (which is it's latest).

**Comment by srcejon** [comment]
Please attach your log file.
