### ISSUE TITLE
I hope RX888 support is being considered.

### ISSUE THREAD

**Issue by mistergitj** [f4exb/sdrangel#1782]
Is supporting SDR RX888 being considered? Here are some links - good and not so good.
https://youtu.be/WmaB4dIh99Y
https://docs.google.com/document/d/1hG634yVkBBIMykmmnosUxw7gumAoc3z1SmWDrH1TucM/edit
Thanks, John.

**Comment by f4exb** [comment]
Considering the document in the last link you mention sorry probably not.

**Comment by mistergitj** [comment]
Thanks for your response, Edouard. I suspected that article might deter you but hoped you would look past it. There are lots of positive comments on the RX888. I have one on order to see what Direct Sampling is about. A request came right after mine (Add support for RTL-SDR Blog V4) that looks like a similar device without direct sampling. I hope you will reconsider supporting the RX888.
Thanks much, John.

**Comment by nmaster2042** [comment]
@mistergitj you can watch this: https://github.com/cozycactus/SoapyRX888

It's an attempt to develop a soapySDR driver for this device.

I don't know if it will go to final stage.

The author is working on a lib rx888 https://github.com/cozycactus/librx888 for his SoapySDR Driver.

**Comment by mistergitj** [comment]
Thanks, nmaster2042. I am a Windows user and know almost nothing about Linux. I have used GQRX many years ago but prefer to  use W10 and SDRangel for my radios. Thanks, John.

**Comment by f4exb** [comment]
There is also this one: https://github.com/modrzywolski/rx666m
