### ISSUE TITLE
Pointer to help file for USB Demodulation Plugin.

### ISSUE THREAD

**Issue by mistergitj** [f4exb/sdrangel#1784]
I cannot find a help file (? icon) for the SSB demodulator. I hope someone will help me. Thanks, John.

**Comment by srcejon** [comment]
https://github.com/f4exb/sdrangel/blob/master/plugins/channelrx/demodssb/readme.md

**Comment by mistergitj** [comment]
Sorry, srcejon. I was premature. Here is an image of my SSB demodulator. It is not the same as the one you posted. Enjoy, John.

<img width="1920" alt="SSB" src="https://github.com/f4exb/sdrangel/assets/45215756/0b66f4a6-f95e-4bf0-b4af-736e36b948c1">

**Comment by srcejon** [comment]
It's the same, just the picture in the docs is slightly out of date.

What specific question do you have/

**Comment by mistergitj** [comment]
Thanks, srcejon. I will try to come up with some specific questions.  Enjoy, John.
    On Wednesday, August 23, 2023 at 11:51:16 AM CDT, srcejon ***@***.***> wrote:  
 
 


It's the same, just the picture in the docs is slightly out of date.

What specific question do you have/
