### ISSUE TITLE
vkFFt and macOS

### ISSUE THREAD

**Issue by loewal** [f4exb/sdrangel#1785]
I miss the explanations of vkFFT for Mac-users; also miss the DMG.

Will it be updated?

**Comment by loewal** [comment]
Thanks forthe DMG and by the way....SDRPlay is back again 👍

**Comment by srcejon** [comment]
The instructions should basically be the same - install the Vulkan SDK and run cmake with -DVKFFT_BACKEND=0, but I haven't tried, as for desktop Windows/Linux, it's probably pointless right now anyway.
