### ISSUE TITLE
Multiple Airspy devices not working

### ISSUE THREAD

**Issue by autodiag** [f4exb/sdrangel#1787]
no detect airspy mini

**Comment by srcejon** [comment]
Please include a log file (Preferences > Logging) and give us as much information as possible. What OS are you using? Does your mini work with other SDR s/w?

**Comment by autodiag** [comment]
[sdrangel.log](https://github.com/f4exb/sdrangel/files/12427650/sdrangel.log)

system is W10x64
have Airspy mini 3pcs and one R2
R2 is detected
airspy nothing
all another work (linux &win x64)

**Comment by autodiag** [comment]
now check same problem to sdrplay2

Airspy r2,Pluto,RTL-SDR  work

**Comment by srcejon** [comment]
What happens if you just have a single mini connected (no r2).

For SDRplay, you need the SDRplay API installed - https://www.sdrplay.com/api/

**Comment by autodiag** [comment]
my mistake, the log was without RSP2 connected, I will give you the log with it connected

yes of course I know what is yours, same situation as with airspy, everywhere else only SDR Angel works :/

and no other applications nor Airspy mini any RSP2

all tested after reboot

**Comment by autodiag** [comment]
up

if there is only one Aispy it finds it, if there are more it ignores them and it doesn't matter what version of airspy it is

if RSP2 is connected together with Pluto sdrangel will remain on the splashscreen

if RSP2 is connected separately it is not detected anyway

info log include
[sdrangel.log](https://github.com/f4exb/sdrangel/files/12428965/sdrangel.log)

**Comment by srcejon** [comment]
> if there is only one Aispy it finds it, if there are more it ignores them and it doesn't matter what version of airspy it is

Ok, have updated the issue title.
 
> if RSP2 is connected separately it is not detected anyway

In your log, you have:

2023-08-24 13:26:06.973 (C) SDRPlayV3Plugin::enumOriginDevices: Failed to get SDRPlay devices:  sdrplay_api_ServiceNotResponding

What version of SDRplay API do you have installed?
Is the SDRplay API windows service running? (Run Services program to check)
Does SDRplay's Uno work if you try it after getting this error in SDRangel?

**Comment by srcejon** [comment]
Unfortunately I don't have several Airspy devices to test with. 

Do you have the same problem with SDRangel on Linux?

**Comment by f4exb** [comment]
What are the serial numbers of your Airspy devices? You can have this issue if they all have the same serial number this is what would happen with RTL-SDR for example.

**Comment by autodiag** [comment]
no, SN is diferent,its original no chnesse shit ;) ..
