### ISSUE TITLE
BUG: Crash when using Soapy to access remote RTL-SDR

### ISSUE THREAD

**Issue by beppelpo** [f4exb/sdrangel#1788]
From version 7.8.6 SDRangle crashes when starting acquisition of REMOTE soapy rtl-sdr

**Comment by gvimlag** [comment]
I have the same problem (see: https://github.com/f4exb/sdrangel/issues/1772).

**Comment by gvimlag** [comment]
Hello beppelpo,
I believe this link might fix your problem:
https://github.com/f4exb/sdrangel/issues/1441

Good luck.
