### ISSUE TITLE
missing and blurry sdrangel application icon

### ISSUE THREAD

**Issue by beta-tester** [f4exb/sdrangel#179]
hi,
sdrangle has no application icon in the file browser on **Windows**.
(it looks ugly in the file browser and is painfull if you create a shortcut to the desktop and have no proper application icon available)
![no-app-icon](https://user-images.githubusercontent.com/4750719/39939346-50112eda-5556-11e8-9a0e-578c87e4dbd7.PNG)

and a blurry icon on **Ubuntu** and **Windows**, in the "_Task_" bar when the sdrangel application is running.
![screenshot from 2018-05-11 20-05-21](https://user-images.githubusercontent.com/4750719/39939489-bec0fce8-5556-11e8-9a73-ace906b119d0.png)

i guess it is because of the **sdrangel_icon.ico** is not a multi-resolution icon (i only 32x32) that makes it blurry when it is scaled up.

i have no experience with linux application icons at all.
i have no experience with windows application icons in Qt...
i have no idea where to put the icons to and how to link them to the project to get compiled/linked to the final executable application in a way, that it is used as application icon in the task bar at run-time and is visible in the file browser on Windows.
i only have experience with Windows application icons in VisualStudio, but that experience doesn't help me here.

so all my tries to provide useful code changes for a pull-request failed.
but i provide a zip file with files for a "_hires_" icon (at least for Windows).

- **sdrangel_icon_template (needs font OpenSans Bold).svg** is the base template for all following icon files. it requires "**Open Sans** (Bold)" font you can download [here](https://fonts.google.com/specimen/Open+Sans)
- **sdrangel_icon_scalable.svg** is for linux (ubuntu **/usr/share/icons/hicolor/scalable/**). it does not need any font.
- **sdrangel_icon.xcf** is the template for multi-resolution **sdrangel_icon.ico**
- **sdrangel_icon.ico** is the multi-resolution icon for at least Windows application.
- **sdrangel_icon_256x256.png** ... **sdrangel_icon_16x16.png** are the icons in the most common resolution (ubuntu **/usr/share/icons/hicolor/256x256/** ... **/usr/share/icons/hicolor/16x16/**).

[sdrangel_icons.zip](https://github.com/f4exb/sdrangel/files/1996428/sdrangel_icons.zip)

maybe you can use those icons...

**Comment by Vort** [comment]
Strange thing is that project contains `sdrangel_icon.ico`, `sdrangel.rc` and corresponding line in `CMakeLists.txt`.
In my custom build icon also appears. So problem with missing icon is somewhere in build process.

**Comment by f4exb** [comment]
The build process is being revisited thanks to the contribution of ra1nb0w. Currently build on windows is hand crafted without cmake.

**Comment by Vort** [comment]
You mean `.pro` files?
[Adding of](https://doc.qt.io/qt-5/appicon.html) `RC_ICONS = ../sdrgui/resources/sdrangel_icon.ico` line into `app.pro` should be enough.

**Comment by f4exb** [comment]
Thanks! It's working

**Comment by beta-tester** [comment]
thank you for fixing the icon.
