### ISSUE TITLE
Random Crashes, Trigger not Working in Channel Analyzer

### ISSUE THREAD

**Issue by S0ulan** [f4exb/sdrangel#1801]
Under Windows and Ubuntu:

SDRAngle crashes completley randomly. It freezes and then its over. Need to restart the Application. Frustrating.
Also for the Channelanalyzer: The Oneshot Trigger is not beeing activated despite correct settings.

**Comment by srcejon** [comment]
> SDRAngle crashes completley randomly. It freezes and then its over. Need to restart the Application. Frustrating. 

What SDR are you using and what channels / features?
