### ISSUE TITLE
I Need Help Searching for Open Source Software Stack for 3G

### ISSUE THREAD

**Issue by serttasbugrahan** [f4exb/sdrangel#1813]
I am looking for open source software stack for 3G, like OpenAirInterface for 5G or Osmocom for 2G. (Osmocom has partial support for 3G)

Kindly asking you to forward me to the right source who may know.

Thank you for your time and kind attention.

Best Regards,

**Comment by f4exb** [comment]
Can you please ask your question in the forum: http://sdrangel.org/forum/index.php?sid=e1c648c7fe286f2a2cf7c53210eded33
