### ISSUE TITLE
DVB-T(2) demodulator

### ISSUE THREAD

**Issue by Yume303** [f4exb/sdrangel#182]
It would be possible to add DVB-T(2) demodulator ?

**Comment by veso266** [comment]
well DVB-S is added, maybe DVB-T could be next then DVB-T2, then DVB-S2 and maybe maybe DVB-C

**Comment by KC7NOA** [comment]
Wonderful news

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by zanco** [comment]
Hi, with the Es'Hail satellite activated and DVB-S2 choosen as standard, is there a change that DVB-S2 is added to the software as reception mode ?
Thanks,
Ben

**Comment by KC7NOA** [comment]
I dont see DVB-S2 as standard ... listed as experimental .... from AMSAT-UK

Es’hail-2 carries two “Phase 4” amateur radio transponders<https://ukamsat.files.wordpress.com/2018/11/amsat-uk_eshail-2_transponder_info.pdf> operating in the 2400 MHz and 10450 MHz bands. A 250 kHz bandwidth linear transponder intended for conventional analogue operations and an 8 MHz bandwidth transponder for experimental digital modulation schemes and DVB amateur television.

KC7NOA

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by f4exb** [comment]
dropped
