### ISSUE TITLE
DSD Demodulator scope display freezes

### ISSUE THREAD

**Issue by nostar** [f4exb/sdrangel#1836]
The DSD scope freezes after doing things like stopping and starting the device or changing device frequency.  It stays frozen untill sdrangel is restarted.  This is git source build on Fedora using either rtl-sdr or HackRF.

**Comment by srcejon** [comment]
Yep - can see this happening on Windows too.

**Comment by simonmarty** [comment]
Was able to reproduce on macOS and release v7.16.0.

**Comment by srcejon** [comment]
One thing to check is the squelch setting. 

But it seems it can stop even when that is at the minimum setting

**Comment by c3kkos** [comment]
I have an issue with DSD demodulator. 

I can open another issue here but i think its more polite just to add content.

so here i am, i setup a basic usb rtl sdr and trying to decode something from the air.

the samples are recieved but dsd is dead. what am i doing wrong?

https://github.com/f4exb/sdrangel/assets/30070329/5bf173e9-1cf2-4798-9176-c7e627d15480
