### ISSUE TITLE
Question : Sdrangel upgrade to Ubuntu 23.04 version

### ISSUE THREAD

**Issue by choupette-change** [f4exb/sdrangel#1838]
Is there a plan to upgrade Sdrangel to Ubuntu 23.04 ?
![Capture d’écran du 2023-09-22 13-34-17](https://github.com/f4exb/sdrangel/assets/68333247/93e8b95c-5dec-4cf3-87e0-af5999b7f8df)

**Comment by f4exb** [comment]
SDRangel .deb package is for Ubuntu 22.04
