### ISSUE TITLE
Ubuntu 22.10 SDRangel install via Apps store.

### ISSUE THREAD

**Issue by agentpatience** [f4exb/sdrangel#1847]
Hello, I'm new to this but I get an error when I try to install SDR Angel on Ubuntu 22.10 saying:

/usr/bin$ sdrangel
2023-10-14 18:31:03.771 (F) This application failed to start because it could not find or load the Qt platform plugin "wayland-egl"
in "".

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.

Reinstalling the application may fix this problem.
Aborted (core dumped)

![image](https://github.com/f4exb/sdrangel/assets/36264810/dc210cff-be49-40ce-aba5-7f89ee11f1d2)

What command fixes this?

**Comment by f4exb** [comment]
Try to install the .deb file you will find in the releases section here. It is for 22.04 but may work for 22.10. The best option would still be to compile from source.

**Comment by agentpatience** [comment]
I cant find the deb file? Also, would you give me instructions to build from source. I dont know the process? Thanks!

**Comment by srcejon** [comment]
https://github.com/f4exb/sdrangel/releases

https://github.com/f4exb/sdrangel/wiki/Compile-from-source-in-Linux

**Comment by neural-loop** [comment]
Is there supposed to be a .deb version here? 
![image](https://github.com/f4exb/sdrangel/assets/654993/81d7aea2-1b89-4021-a8d4-8e54584935e5)

**Comment by srcejon** [comment]
> Is there supposed to be a .deb version here? ![image](https://user-images.githubusercontent.com/654993/280848857-81d7aea2-1b89-4021-a8d4-8e54584935e5.png)

In master.tar.gz.
