### ISSUE TITLE
RTTY Demodulator Plugin

### ISSUE THREAD

**Issue by choupette-change** [f4exb/sdrangel#1848]
RTTY Demodulator Plugin is not working correctly
![image](https://github.com/f4exb/sdrangel/assets/68333247/2c77b604-2ee2-422e-a42d-07003a5a82dc)

**Comment by srcejon** [comment]
The docs say the S-M button should be checked for DWD broadcasts, so give that a try.

**Comment by choupette-change** [comment]
it's ok with this new setting thanks
