### ISSUE TITLE
DSD Demodulator not decoding 

### ISSUE THREAD

**Issue by c3kkos** [f4exb/sdrangel#1850]
Tried both windows and linux latest versions

I tried to decode some DMR from a sdrangel server with no luck.

That made me download a .wav file from various site, convert them in WAVs 16bit PCM STEREO as sdrangel's docs saying, and feeding them into sdrangel via the "FileInput" source.

everything seems to be good to go but.....

DSD Demodulator is doing NOTHING. I see from the power bar that its recieving data (sound) but nothing happens.

No logs, no constellation... what i'm doing wrong?

I will attach a screenshot of the version, and the file used as sample (i've used plenty.... DMR, D-STAR.... no luck with any at all!)

![Clipboard01](https://github.com/f4exb/sdrangel/assets/30070329/857aa8b9-ea4f-4170-94dd-c8ea1f81d9ca)
![Clipboard02](https://github.com/f4exb/sdrangel/assets/30070329/fe315bed-d8a4-40ef-a362-3c47563d7b45)

**Comment by srcejon** [comment]
If I recall correctly, the DSD Demod doesn't work well if sample rate is below 48kHz, which appears to be the case with your .wav file.

Also, are you sure those .wav files are IQ baseband recordings?

**Comment by srcejon** [comment]
That doesn't appear to be an IQ file. The left and right channels appear identical.

**Comment by c3kkos** [comment]
Done another test with linux version. In linux i can use pipewire to pipe inside sdrangel the audio from firefox browser. Then, go to DMR SAMPLES pages and inject the sound. SOMETHING happens. So: windows build do not allow any audio input devices, when we would need at least the local stereo loopback.

PCM is not i/q data (of course....) i thought, since we got a fileinput, dsd would work with sound, rather then raw i/q samples.. and indeed it (kinda) work...

**Comment by srcejon** [comment]
What web site are you referring to?

In Windows, you can see the constellation for the file you uploaded, if you adjust the input frequency offset a little (E.g. delta f to 50 Hz)The problem appears to be it isn't an IQ recording.

**Comment by f4exb** [comment]
I confirm you need an input sample rate of at least 48 kS/s. The DSD demod uses several samples per symbol to be able to decode correctly.

**Comment by c3kkos** [comment]
Ok, done 1 more test with proper .wav file provided by:

https://sdrplay.com/resources/IQ/dmr.zip

Now the plugin "reads" but cannot render realtime voice, just a few "glitches"


![Clipboard01](https://github.com/f4exb/sdrangel/assets/30070329/46294e61-f7e1-42b4-9d50-971853c72e3a)

**Comment by c3kkos** [comment]
OK Done proper test with proper .wav file provided by:

https://sdrplay.com/resources/IQ/dmr.zip

and i get proper voice, so dsd plugin is working.

I still cant see constellation but maybe this is due to 4k monitor. (too thin points)

Next step is decoding something from real antenna and not a recording. more tests feedbacks asap

**Comment by srcejon** [comment]
I can see the constellation on a 4k monitor.

**Comment by c3kkos** [comment]
OK done some tests.

First of all, sdrangel quits always with a segmentation fault. This is not a problem, but sometimes it goes segfault even only loading the dsd demodulator.

Sometimes, at random, dsd demod simply do not work. You can set squelch -100 and still icon not goin green

In "normal" usage, dsd mod gives you weird sound only using thermal noise (example...)

I found a workaround to make it work 100% times:

start with audio source. load dsd onto that device

then load the RTL (usb connected) only after that switch device on dsd mod, from audio to rtl sdr.

Weird enough!

Ah! also have some issue with pipewire. I switched back to pulse output, it seems more stable.

I'm running arch linux full updated

**Comment by f4exb** [comment]
> Ah! also have some issue with pipewire. I switched back to pulse output, it seems more stable.

No wonder... I remember someone willing to push usage of pipewire as the next World's marvel. Well it is probably not...

**Comment by c3kkos** [comment]
This will go off topic, but let me say i've been using Pipewire and Wireplumber as session manager and IMHO is a VERY good piece of software! Piping audio made easy and reliable. Of course it need knowledge to work with it

**Comment by aminichangeez** [comment]
> OK Done proper test with proper .wav file provided by:
> 
> https://sdrplay.com/resources/IQ/dmr.zip
> 
> and i get proper voice, so dsd plugin is working.
> 
> I still cant see constellation but maybe this is due to 4k monitor. (too thin points)
> 
> Next step is decoding something from real antenna and not a recording. more tests feedbacks asap

Hello

First of all, I have to admit that it's an honor for me to make contact with you

Regarding the DMR sample in https://github.com/f4exb/dsdcc/tree/master/samples:

Therefore, if you please upload the related files, including data &
voice similar to [dmr_it_8.dis](https://github.com/f4exb/dsdcc/blob/master/samples/dmr_it_8.dis) with a determined frequency & sample rate.

Any other help would be appreciated, including the explanation of the process to decode https://sdrplay.com/resources/IQ/dmr.zip.

I hope it's not too much to ask. 

Best Regards
Changeez Amini
