### ISSUE TITLE
Error in compiling Soapy SDR

### ISSUE THREAD

**Issue by auskimus** [f4exb/sdrangel#1860]
Hi, having difficulty locating what went wrong compiling SoapySDR
 $ make -j $(nproc) install
on Ubuntu22.04
![Screenshot from 2023-10-27 00-30-46](https://github.com/f4exb/sdrangel/assets/45010047/2dc674cd-2dc4-4cd1-ac5a-53478db73117)

**Comment by srcejon** [comment]
Problem appears to be python related. Make sure you have python3 installed as per the instructions.

Then have a look at what cmake outputs - I get:

-- Could NOT find Python3InterpDbg (missing: PYTHON3_DBG_EXECUTABLE) 
-- PYTHON3INTERP_FOUND: TRUE
-- PYTHON3_EXECUTABLE: /usr/bin/python3
/opt/build/SoapySDR/python3/../python/get_python_lib.py:4: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.sysconfig import get_python_lib
/opt/build/SoapySDR/python3/../python/get_python_lib.py:4: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
  from distutils.sysconfig import get_python_lib
-- PYTHON3_INSTALL_DIR: ${prefix}/lib/python3.10/site-packages
-- Found Python3Libs: -L/usr/lib/python3.10/config-3.10-x86_64-linux-gnu -L/usr/lib/x86_64-linux-gnu  -lcrypt -ldl  -lm -lm  
-- PYTHON3LIBS_FOUND: TRUE
-- PYTHON3_INCLUDE_DIRS: /usr/include/python3.10;/usr/include/python3.10
-- PYTHON3_LIBRARIES: -L/usr/lib/python3.10/config-3.10-x86_64-linux-gnu -L/usr/lib/x86_64-linux-gnu  -lcrypt -ldl  -lm -lm

**Comment by auskimus** [comment]
Hi

The guy seems to not answering questions about some issues already mentioned in the Read me
I just installed a snaped Version.

Regards
Sent from my iPhone

On 26 Feb 2024, at 6:31 pm, Fangrf ***@***.***> wrote:

﻿

@auskimus<https://github.com/auskimus> HI,I met the same problem. Have you solved the problem
