### ISSUE TITLE
3 D map disappears

### ISSUE THREAD

**Issue by choupette-change** [f4exb/sdrangel#1868]
After several minutes of operation, the 3 D map disappears ???

[sdrangel.log](https://github.com/f4exb/sdrangel/files/13198838/sdrangel.log)
![Capture d’écran du 2023-10-29 19-01-54](https://github.com/f4exb/sdrangel/assets/68333247/a2454fa5-9e17-4665-ba86-945554a6ed7c)

**Comment by srcejon** [comment]
The log doesn't show anything.

What graphics card do you have? How much memory does it have? Some of the AIS models are quite large.

Do you have the same problem when not running the AIS demods?

**Comment by choupette-change** [comment]
During my first problem, I was in a virtual machine under Windows 11. Now, I installed Ubuntu 22.04 directly on my PC and there no problem of disappearance but the display of the 3 D map is much slower than the 2D...
My current situation (see screenshot below)

![Capture d’écran du 2023-10-30 14-06-43](https://github.com/f4exb/sdrangel/assets/68333247/bc18a8fa-7fae-4af2-b3c7-be555437fa37)
