### ISSUE TITLE
display

### ISSUE THREAD

**Issue by KC7NOA** [f4exb/sdrangel#187]
MESA-LOADER: failed to retrieve device information
libGL error: unable to load driver: mali_drm_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: mali_drm

is that an issue?

**Comment by KC7NOA** [comment]
is it hard to support GLESv1 GLESv2 and EGL?

**Comment by KC7NOA** [comment]
Odroid-c2   quad core mali-450 

SdrAngel runs well with LimeSDR with a sample rate of 5Ms/ps ... software decimation at 2 and hardware decimation at 1 ....

Just see this when starting and was wondering if there was any way to improve performance on my C2

**Comment by f4exb** [comment]
To improve the performance of the whole configuration you should increase the hardware decimation and reduce the host sample rate accordingly. Hardware decimation capability is one of the big advantages of LimeSDR.

**Comment by KC7NOA** [comment]
Works best other way around ... i can get 15M/s with hardware at 1 and software at 4 ... sample around 7M on usb2.0

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
