### ISSUE TITLE
Change 

### ISSUE THREAD

**Issue by Rizboy11** [f4exb/sdrangel#1872]
if I change the coding in mainwindow.cpp, will it change the appearance for the application/software sdrangel ?

**Comment by srcejon** [comment]
Yes, but depends what you want to change.

If you want to change the palette/theme, see app/main.cpp runQtApplication()

**Comment by Rizboy11** [comment]
That is, when I want to change the display color, is it possible?

If yes, what steps should I do? 

please guide me sir, thank you

**Comment by srcejon** [comment]
Well, in that function, you'll see code such as:

	palette.setColor(QPalette::Window, QColor(64,64,64));
	palette.setColor(QPalette::WindowText, Qt::white);
	palette.setColor(QPalette::Base, QColor(25,25,25));
	palette.setColor(QPalette::AlternateBase, QColor(53,53,53));

You'll need to change that to what you want and recompile. Compile instructions are on the Wiki.

**Comment by Rizboy11** [comment]
okay i understand about the code programs. 

but i don't know how to recompile the programs so that it works into software sir, please guide me or you gift me the link to learn how to recompile this code programs

**Comment by srcejon** [comment]
https://github.com/f4exb/sdrangel/wiki/Compile-from-source-in-Linux

https://github.com/f4exb/sdrangel/wiki/Compile-in-Windows

**Comment by Rizboy11** [comment]
okay thankyou sir, i'll try it.

**Comment by Rizboy11** [comment]
Hello sir, i'll ask to you, how step to compile my new programs ?

**Comment by Rizboy11** [comment]
i was download all the software material from your suggestion at Wiki
