### ISSUE TITLE
Question : FT8 demodulator

### ISSUE THREAD

**Issue by choupette-change** [f4exb/sdrangel#1879]
I can't display the points on the map. Thanks for your help
![Capture d’écran du 2023-11-05 16-39-56](https://github.com/f4exb/sdrangel/assets/68333247/03e8e77c-f4ac-4716-adc3-709e4dde1ca9)
like on the forum
![Capture d’écran du 2023-11-05 16-37-45](https://github.com/f4exb/sdrangel/assets/68333247/5216e0c8-83f4-4afb-baa5-41ac9551572a)

**Comment by srcejon** [comment]
With a 2D Min Zoom setting of 8, they will only be visible if you zoom in further.

If you want to see them when you are zoomed out a long way, as in your picture, then set 2D Min Zoom setting to 2 or 3.

**Comment by choupette-change** [comment]
It's OK Thanks
