### ISSUE TITLE
Radiosonde Demodulator CSV log all fields

### ISSUE THREAD

**Issue by ArtemKiyashko** [f4exb/sdrangel#1880]
@srcejon

Hey! I am tracking RS41 and want to have full flight log in CSV file, but cant find a way to get altitude to be written into csv log file.
Could you explain how i can make it work? Or, if its not implemented yet, could you add such feature? If you can write all flight data to the csv that would be perfect.

Thanks!

**Comment by srcejon** [comment]
Also add range and freq columns.
