### ISSUE TITLE
Map not showing Radiosonde demod results

### ISSUE THREAD

**Issue by BarryH1962** [f4exb/sdrangel#1884]
I'm new to sdrangel and running version 7.17.0 on win 64 and map feature will not show radiosonde demod tracks. The data from the demod plugin looks normal. I've tried the adsb demod and map shows aircraft normally. Is there something else I need to do?

**Comment by srcejon** [comment]
Have you added the RadioSonde feature? You need that, as well as the Demod.

**Comment by BarryH1962** [comment]
Thanks. That resolved it.
