### ISSUE TITLE
LimeSDR Mini Sink Definition

### ISSUE THREAD

**Issue by MZachmann** [f4exb/sdrangel#189]
Hi,

I'm fairly sure the LimeSDR Mini Transmit (sink) antenna choice is defined backwards - that is, Lo is actually the Hi antenna. This can be repaired trivially in the .ui file by swapping Hi and Lo, but I have no idea about LimeSDR non-mini implications. It's quite confusing as is if I'm correct. Thanks.

---

Also... When I start the output sink my transmit level shows -60dB. When I add a modulator it goes up to about -35dB and even if I delete the modulator the level stays up. When I delete the sink and re-add it the cycle repeats.

**Comment by f4exb** [comment]
It may be possible to swap controls if the Lime detected is a mini (I think there is an indication in the device name somewhere) but I think this is a little bit awkward. After all you should know what's hanging at the other end of the wire.
