### ISSUE TITLE
SDRAngel, Andriod applcation, ADSB decode, options page is exceeding beyond the screen size

### ISSUE THREAD

**Issue by telehawk911** [f4exb/sdrangel#1896]
Hi,

Thank you for providing such an excellent software, i love this,
Everything is working great however I noticed a problem in the ADSB decode section options (three small horizontal lines) screen is not adjusting according to the screen size due to this reason I can't see the bottom where I can choose "OK".

Would someone be kind enough to explain how to use the Noise figure?

Appreciate your support in solving the above-mentioned problem.

Thank you and regards,

**Comment by srcejon** [comment]
> Thank you for providing such an excellent software, i love this, Everything is working great however I noticed a problem in the ADSB decode section options (three small horizontal lines) screen is not adjusting according to the screen size due to this reason I can't see the bottom where I can choose "OK".

Dialogs don't automatically resize - so this would need to be redesigned.

> Would someone be kind enough to explain how to use the Noise figure?

https://github.com/f4exb/sdrangel/blob/master/plugins/channelrx/noisefigure/readme.md

Probably not usable on Android.
