### ISSUE TITLE
NFM Mod Freq Deviation

### ISSUE THREAD

**Issue by srcejon** [f4exb/sdrangel#1899]
I think the NFM Mod has the same problem with Frequency Deviation as the M17 Mod - i.e. a missing factor of PI.

    m_modPhasor += (m_settings.m_fmDeviation / (float) m_audioSampleRate) * t1;

Should be:

    m_modPhasor += (M_PI * m_settings.m_fmDeviation / (float) m_audioSampleRate) * t1;

With that change, I would expect with a full-scale audio signal (i.e. setting t0=1), to get peak deviation. However, there's an extra factor of 1.2:

    if (m_settings.m_ctcssOn) {
        t1 = (0.85f * m_bandpass.filter(t) + 0.15f * 0.625f * m_ctcssNco.next()) * 1.2f;
    } else if (m_settings.m_dcsOn) {
        t1 = (0.9f * m_bandpass.filter(t) + 0.1f * 0.625f * m_dcsMod.next()) * 1.2f;
    } else if (m_settings.m_bpfOn) {
        t1 = m_bandpass.filter(t) * 1.2f;
    } else {
        t1 = m_lowpass.filter(t) * 1.2f;
    }

Any idea what that's for?

I suspect the last case should just be:

        t1 = m_lowpass.filter(t);

**Comment by f4exb** [comment]
I think this was some empirical adjustment maybe to compensate filter attenuation. There is also a 0.625 factor applied to the CTCSS and DCS modulations supposedly also empirical.

**Comment by srcejon** [comment]
> I think this was some empirical adjustment maybe to compensate filter attenuation. 

Here's freq response of the current low pass filter, which doesn't look like it needs it, as 0dB:

![image](https://github.com/f4exb/sdrangel/assets/57259258/aa15d0a5-f395-4d2d-839c-61fcc932e860)

And the bandpass filter looks to be 0dB in passpand too:

![image](https://github.com/f4exb/sdrangel/assets/57259258/065bbe91-4fed-4b62-82f5-e4f916f8db19)

**Comment by f4exb** [comment]
Verified how it is for WFM modulator and indeed there is a multiplication by &pi; 
https://github.com/f4exb/sdrangel/blob/master/plugins/channeltx/modwfm/wfmmodsource.cpp#L122
