### ISSUE TITLE
SDRplay

### ISSUE THREAD

**Issue by loewal** [f4exb/sdrangel#1904]
I read this:
Add instant replay for RTL SDR, _**SDR Play V3**_, USRP and Airspy HF RXes. PR https://github.com/f4exb/sdrangel/pull/1900 from @srcejon.

But the latest 17.1 macarm64 still doesn't contain a plugin for SDRplay.
Am I right or do I miss something?

Regards,

**Comment by loewal** [comment]
Could we have the updateted macintel64 as well please?

**Comment by srcejon** [comment]
I've just done an updated macarm64 build that includes SDR Play support. You need to make sure 3.12 API is installed and the service is running,
