### ISSUE TITLE
Latest Download for Android seems not the actual release.

### ISSUE THREAD

**Issue by p-f-w** [f4exb/sdrangel#1910]
Download link under latest release

https://github.com/f4exb/sdrangel/releases/download/v7.17.1/sdrangel-7.17.1-android.apk

is 7.17.0.1 and seems like the same as last month and PlayStore will still offer me 7.17.1.1 after installation

i see also no difference in ADS-B widget

**Comment by srcejon** [comment]
Have just re-uploaded it.

Please send a screenshot of ADS-B if you still think there's a problem.

**Comment by p-f-w** [comment]
Re-upload has fixed the issue, now it will shown the version 1.17.1.1 and no more offer update bei play store.
![Screenshot_20231205-042418](https://github.com/f4exb/sdrangel/assets/81571337/e0d69fc9-9fe5-40de-88a1-2d47e0084c94)
