### ISSUE TITLE
Support for DVStick30 on MacOS

### ISSUE THREAD

**Issue by Gissmo2023** [f4exb/sdrangel#1913]
Hello,

I have a DVStick30, which is in the system as /dev/tty.usbserial-D200G2GM & cu.usbserial-D200G2GM.
However, it cannot be selected from serial devices via the AmbeController.
Is there a way to use the stick directly?

MacOS 13.5.1
SDRAngel 7.17.2

**Comment by f4exb** [comment]
If it does not work directly from USB  you may try to use it through an AMBE server: https://github.com/f4exb/sdrangel/tree/master/plugins/feature/ambe#1-ambe-server-address-and-port-or-direct-input

**Comment by Gissmo2023** [comment]
"Cannot open..." 
but there are no outgoing connection attempts at port 2460.
Buster works great
