### ISSUE TITLE
Radiosonde CSV header fix

### ISSUE THREAD

**Issue by ArtemKiyashko** [f4exb/sdrangel#1915]
Hey guys, could you remove space before 'U (%)'?
It is now:
```c++
m_logStream << "Date,Time,Data,Serial,Frame,Lat,Lon,Alt (m),Speed (m/s),V/R (m/s),Heading,P (hPa),T (C), U (%)\n";
``` 
And should be:
```c++
m_logStream << "Date,Time,Data,Serial,Frame,Lat,Lon,Alt (m),Speed (m/s),V/R (m/s),Heading,P (hPa),T (C),U (%)\n";
``` 

https://github.com/f4exb/sdrangel/blob/cb97263129653b47d40cf3b02c1e4c15a6701900/plugins/channelrx/demodradiosonde/radiosondedemod.cpp#L386

@srcejon 

Thanks a lot!

**Comment by srcejon** [comment]
Done
