### ISSUE TITLE
AIS Tx - message encoding for API or UDP stream

### ISSUE THREAD

**Issue by Cubster1990** [f4exb/sdrangel#1927]
Hi guys
All around great tool for learning about SDR. I have a small boat and thought AIS rx/tx would be a good way to learn about SDR.

Trying to get the AIS message encoded to correct hex data string- either to the API or the UDP stream, from the human readable format or AIVDM. 

Could not find much documentation of the API encode function

"AISModActions": { 
"tx": 1, 
**("encode": 1 (or 0))**
"data": "000000000000000000000000000000000000000000" }}'

Alternatively using the UDP stream but haven't been able to get the data to match AIVDM ->UDP->AIS demod (readable)

Perhaps I missed something in the documentation. 

Any ideas?

(Working with a loopback (127.0.0.1) to avoid any legal issues, while learning)

**Comment by srcejon** [comment]
If encode is 1, then the message data to transmit is encoded from the values in the AISModSettings fields. E.g. you can set AISModSettings.speed = 2, AISModSettings.heading=4, then call encode without a AISModActions.data field.

If encode is 0, and you include the data field, then the message data will be what you pass in the AISModActions.data field. For that, you need to encode according to AIS specification yourself: https://www.itu.int/dms_pubrec/itu-r/rec/m/R-REC-M.1371-5-201402-I!!PDF-E.pdf

**Comment by Cubster1990** [comment]
Perfect - that explained exactly what I was looking for. 
Thanks for the quick response

**Comment by Cubster1990** [comment]
Follow up question:

What input does the UDP stream take? When the encoded data from the "encoder function" is passed through: 
`nc -u 127.0.0.1 9998` 
The decoded data in AIS demodulator is not correct/corresponding the initial input into the encoder

**Comment by srcejon** [comment]
> What input does the UDP stream take? 

Raw bytes to transmit.

> When the encoded data from the "encoder function" is passed through: `nc -u 127.0.0.1 9998` The decoded data in AIS demodulator is not correct/corresponding the initial input into the encoder

You'll have to give an example.

**Comment by Cubster1990** [comment]
![sdrangel](https://github.com/f4exb/sdrangel/assets/153741311/265593e7-82dd-4fae-9786-929308799e6b)
Here is a screenshot of the setup

Transmitting encoded message copied from encoder in AIS modulator via UDP w/ nc 
`041d6f34542003c09ba3c006ddd0003203d6000000`
Recieving in AIS demodulator: 
`3034316436663334353432303033633039626133633030366464643030303332303365323030303030300a`

**Comment by srcejon** [comment]
0x30 is is ASCII '0' and 0x34 is ASCII '4' 

Is netcat sending ASCII rather than converting the hex to binary?

**Comment by Cubster1990** [comment]
That would make sense - based on your interpretation of the data together with this post on stackoverflow 

https://stackoverflow.com/questions/43919867/sending-a-hex-string-to-a-remote-via-netcat

I will give it a shot and let you know how it goes 

Thanks for your expertise (would have taken forever to figure out alone)

**Comment by Cubster1990** [comment]
It worked with the description from the stackoverflow solution.

`echo -n -e "\x02\x45\x31\x38\x03\x34\x43\x0d\x0a" | nc -u 127.0.0.1 9998`
