### ISSUE TITLE
windows builds/downloads are behind linux ones

### ISSUE THREAD

**Issue by beta-tester** [f4exb/sdrangel#193]
hi,
on [f4exb/sdrangel - Latest release](https://github.com/f4exb/sdrangel/releases),
there is no windows release available for sdrangel build 4.0.1 and 4.0.2.
does it mean, that windows support is stopped or broken or do those builds contains only fixes for linux?

**Comment by beta-tester** [comment]
oh, forgett it - just saw that your dev environment smoked.
sorry to hear.

**Comment by f4exb** [comment]
Still facing issues with the hard disk where the Windows VM used to live. Waiting for parts.

**Comment by beta-tester** [comment]
oh man... you have all the work and now all the pain...
and i have nothing better to do as to cry.

thank you for your work.

PS.: maybe i should better do a backup of my hard disk... before it will smoke as well.

**Comment by beta-tester** [comment]
it brings tears to my eyes...
but i respect your decision.

**Comment by beta-tester** [comment]
now you can change it from "maybe" to "is"
![is](https://user-images.githubusercontent.com/4750719/42418348-957e77f0-829e-11e8-8ef4-00109b3ae321.PNG)

**Comment by f4exb** [comment]
I eventually managed to have a working environment for the build so as you may notice you now have an archive for v4.0.3:
https://github.com/f4exb/sdrangel/releases/tag/v4.0.3
