### ISSUE TITLE
Increase in transmit power on WFM Demodulator with a HackRF

### ISSUE THREAD

**Issue by EmilEmilchen** [f4exb/sdrangel#1930]
I'm not 100% sure if I'm just doing something wrong but while transmitting some WFM modulated audio using SDRangel and my HackRF the I guess amplitude off the lower signals just randomly increases. When listening to the signal using an RTL SDR there is suddenly a lot off noise in the audio signal. Moving the AFBW slider of the modulator fixes the problem but then it just appears again. I attached a screenshot of when this happened. I dont think this is intended behavior and I would also be surprised if it was a hardware problem but I dont really know seing as I'm kind of a noob when it comes to RF.
![Screenshot 2023-12-14 224137](https://github.com/f4exb/sdrangel/assets/70268797/a8863246-47d8-4ffe-9e58-2ec1a1cb2ed0)

**Comment by wickersoft** [comment]
Are you sure your audio file is correct? Does it happen randomly or always at the same point in the file?

**Comment by EmilEmilchen** [comment]
It happens on completely random occasions.
