### ISSUE TITLE
SOAPYremote not in device list (v7.17.2 OSX)

### ISSUE THREAD

**Issue by kobold81** [f4exb/sdrangel#1934]
Hello,

as far as I understand, sdrangel should be able to conect to a soapyremote instance.
"Select samplin device" does not show an entry for soapy in v7.17.2 for OSX Version. Do I have to compile sdrangel or will future builds include sopy?

**Comment by srcejon** [comment]
Soapy isn't included in the Mac build currently, so you'd need to compile it.

Note also, you need to use command line option --soapy to enable it and to connect to remote devices, see: https://github.com/f4exb/sdrangel/wiki/Soapy-Remote

**Comment by kobold81** [comment]
thanks, is it included in the other OS builds?

**Comment by f4exb** [comment]
Sorry Soapy will remain optional

**Comment by srcejon** [comment]
The latest macarm64 dmg should contain Soapy Remote (but no other Soapy drivers). Untested, so let me know how you get on.

**Comment by kobold81** [comment]
Hi, 
I own a intel mac, so if I have time in the near future, I will tr an build sdrangel with soapy addons :-)
