### ISSUE TITLE
Pager decoder plug-in UDP output

### ISSUE THREAD

**Issue by UncleBuck62** [f4exb/sdrangel#1936]
I am not sure if this will be resolved as part of #1928 or not, however, I thought I would raise this as an issue and it can always be merged if needed.

1. The date output does not follow a regular structure in the packet - 
the date comes in as Sat Dec 23 14:12:29 2023 so the year is preceded by the time. 
It is shown in the correct format in the SDRangel plug-in as two fields (date and time).
2. The CapCode is inconsistent - 
The CapCodes with a value of less than 7 digits are not padded with leading zeros.
It is shown in the correct format in the SDRangel plug-in as 0123456 but the UDP has it as 123456

A real example of this is show here:
This is what is coming from the UDP packet....
```
Sat Dec 23 15:07:44 202318721300HbPLEASE ADVISE ....
Sat Dec 23 15:07:46 20231622020HbPLEASE ADVISE ....

```
and this is what is shown in the plug-in (pipe char indicates the seperate columns)....
```
Sat Dec 23 2023 | 15:07:44 | 1872130 | HbPLEASE ADVISE ....
Sat Dec 23 2023 | 15:07:46 | 0162202 | HbPLEASE ADVISE ....

```
Hope that all makes sense.

Have a Merry Christmas.
Cheers and keep up the great work.
Colin

**Comment by srcejon** [comment]
Implemented in 7.17.3
