### ISSUE TITLE
Tx antenna switch locks

### ISSUE THREAD

**Issue by KC7NOA** [f4exb/sdrangel#194]
when i switch to antenna no to lo i lock up ....

have not tried Hi yet ....

Ok ... so select the antenna port before starting ... i show no output on display ... and cant modulate yet ...

is antenna selection functional yet?

**Comment by f4exb** [comment]
What is the source plugin concerned? LimeSDR?

**Comment by KC7NOA** [comment]
Im sorry ....

Yes LimeSdr and Ubuntu 18

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by f4exb** [comment]
It works perfectly fine. You need to add a modulator to see something happening.

**Comment by f4exb** [comment]
Is this a Lime-Mini or Lime-USB?
Is it connected to a USB-2 or USB-3 port?
What sample rate do you use?

**Comment by KC7NOA** [comment]
Its a LimeSDR usb ,,, i keep sample rate as low as i can ,,, i set Rx to lowest it will go ....

Tx @1Msps .... iv tried lower with same effect ....

Hardware decimation to 1 and software at anywhere from 1 to 16.
Low antenna on Lime (0,0)  ....

Would it be better to use Tx on Lime(0,1) ?

Usb2 port ... i can Rx arounf 13M per sec with hardware at 1 and Software at 8 or 16 easy ... that's 7Ms/s ...but when trying tx i keep it low (also have left it alone)

There is a Tx blip when i have a NFM active when starting the radio 
There is a carrier when starting the radio with out a modulator, then adding a modulator will still be active -- but nothing is captured from the microphne goes out as modulation -- flat carrier. if i change anything -- even trying to stop the Tx radio/thread it seems to lock up and needs a ctrl-c ...

is there an option for building to show more debug information ?

System monitor is always low .... especially on an Intel i5 dual core (laptop)

I get same things on Odroid-C2 as my Laptop Dell E5500

**Comment by KC7NOA** [comment]
I am also now using a Quad core Q8400 and i still get NO Tx .. and usually no GUI activity after the stop (reverse of play/start) antenna change ...

I don't see any warnings or anything when the freeze up occurs ...
