### ISSUE TITLE
AIS message type 5  in AIS modulator

### ISSUE THREAD

**Issue by Cubster1990** [f4exb/sdrangel#1943]
Hi 
Got the modulator working with UDP and the API to TX type 1 messages "Scheduled position report" but as I understand AIS RX stations also need a type 5 message "Static and voyage related data". 
The type 5 message includes static info such as: IMO, Vessel name, Call sign, Ship type, ETA, Draught and Destination. 

How would I transmit a type 5 message in SDRangel?

**Comment by srcejon** [comment]
You'd need to encode it yourself as hex in the Msg field.

**Comment by Cubster1990** [comment]
> You'd need to encode it yourself as hex in the Msg field.

Been reading up on the encoding from [this PDF](https://www.itu.int/dms_pubrec/itu-r/rec/m/R-REC-M.1371-5-201402-I!!PDF-E.pdf) from this earlier  [post](https://github.com/f4exb/sdrangel/issues/1927) .
Haven't been able to "crack" the encoding from NMEA to HEX in order to generate my own type 5 message.
Any suggestions?

**Comment by srcejon** [comment]
You shouldn't need NMEA. Create the message a sequence of bits according to the table, then convert to hex.
