### ISSUE TITLE
SDRangel crashes when trying to load/click on ADS-B map

### ISSUE THREAD

**Issue by ituri** [f4exb/sdrangel#1949]
Hi,

I installed SDRangel in order to receive some ADS-B signals. Receiving the signals works fine but no map is shown. Once I doubleclick on an aircraft or once I click on "Find ADS-B map" the application crashes. I have attached the crash report.

Best 
ituri
[crashreport.txt](https://github.com/f4exb/sdrangel/files/13875916/crashreport.txt)

**Comment by srcejon** [comment]
The ADS-B map isn't supported in the Mac ARM build (as it uses Qt 6), as per #1870 - you'd need to use the x64 build.
