### ISSUE TITLE
OSX: ADS-B Map not showing

### ISSUE THREAD

**Issue by adecarolis** [f4exb/sdrangel#1950]
Hello,

No map is being shown on OSX (see below).

OSX Sonoma 14.2 (M1 Processor)
SDRAngel 7.17.3 installed via the macarm64 release

<img width="911" alt="Screenshot 2024-01-12 at 6 43 38 PM" src="https://github.com/f4exb/sdrangel/assets/6162075/4ef47efc-3f96-4a35-8794-56379120dbcb">

Same happens within the Satellite Tracker (no maps).

Thanks

**Comment by srcejon** [comment]
Yes, this is expected as the Map doesn't work with Qt6 as per #1870
