### ISSUE TITLE
Support for SDRplay RSPdx

### ISSUE THREAD

**Issue by bi3mw** [f4exb/sdrangel#1958]
Hello,
Does SDRangel also support the SDRplay RSPdx device ?

**Comment by srcejon** [comment]
It should do.

**Comment by bi3mw** [comment]
Well, the SDRplay cannot be found in the list under Devices.

**Comment by srcejon** [comment]
> The problem is solved. I changed the version number from 3.07 to 3.12 in /usr/lib/sdrangel/plugins/libinputsdrplayv3.so with a HEX editor. Now the device is recognized without errors

That doesn't mean it will work properly, as some data structures may differ.

I'd suggest you either install v3.07 of the API or recompile SDRangel with the 3.12 API.
