### ISSUE TITLE
Support for FlexRadio products.

### ISSUE THREAD

**Issue by D-Michel-E** [f4exb/sdrangel#1960]
Hi! I am a student at the University of Louisiana at Lafayette and we are looking to acquire a FlexRadio System with transverters for V and U. Unfortunately, SDRAngel does not state support for these devices, even with a seemingly open API and other projects on github related to interfacing with it. I would love to continue using SDRAngel to interface with our potentially new radio.
Thanks,
Michel

**Comment by srcejon** [comment]
Well, you can add your own sample source plugin to support it. See: https://github.com/f4exb/sdrangel/tree/master/plugins/samplesource for the existing drivers.

Or ask the manufacturer or uni to send us one so we can add support for it ;p
