### ISSUE TITLE
F-Droid Support

### ISSUE THREAD

**Issue by aadityabhatia** [f4exb/sdrangel#1972]
Please consider publishing this app to F-Droid, one of the most popular app stores for FOSS apps built from source. It will increase the reach and popularity of the app by making it available to users / devices not on Google ecosystem. See [F-Droid Quick Start Guide](https://f-droid.org/docs/Submitting_to_F-Droid_Quick_Start_Guide/) for details.

**Comment by Davem734** [comment]
I second this request. I have a de-googled tablet running LineageOS and would prefer to install SDRAngel from F-Droid to have notifications and easy access to updates. 

And thank you all for the hard work that has gone into this amazing project...

**Comment by aadityabhatia** [comment]
What inactivity?

**Comment by Davem734** [comment]
A bump to keep the dream alive (for the bot's sake)
