### ISSUE TITLE
Unable to see USRP sampling device

### ISSUE THREAD

**Issue by keukenrol** [f4exb/sdrangel#1974]
Hello

I have followed the guide describing how to get samples from an USRP device.
uhd_find_devices lists the following (serial not shown):
addr: 192.168.10.2
fpga: HG
name:
product: X310
type: x300
Under device user arguments I then set the device: 
![afbeelding](https://github.com/f4exb/sdrangel/assets/56192644/e65c09bb-862a-4b06-b534-6a3f6b4e7e25)
However, once restarted the device is not listed in the sampling devices (from add RX device).
Any idea?

I am able to connect using GNU Radio.

Thanks!

**Comment by srcejon** [comment]
Possibly no one has tried an X300 before. Have a look in the log file and see if it says anything relevant.

**Comment by keukenrol** [comment]
(D) DeviceUSRP::enumOriginDevices: Could not find any USRP device

**Comment by srcejon** [comment]
Can you post anything it says before that as well please?

**Comment by keukenrol** [comment]
[sdrangel.log](https://github.com/f4exb/sdrangel/files/14177219/sdrangel.log)

**Comment by srcejon** [comment]
Try ip_addr instead of addr=

**Comment by keukenrol** [comment]
No difference, both with and without brackets.

**Comment by keukenrol** [comment]
Edit: the log file told me that the FPGA firmware is incompatible.
2024-02-06 15:42:10.737 (D) DeviceEnumerator::enumerateDevices: sdrangel.samplesource.testsource
2024-02-06 15:42:10.737 (D) DeviceEnumerator::enumerateDevices: sdrangel.samplesource.usrp
2024-02-06 15:42:12.958 (D) DeviceUSRP::enumOriginDevices: found USRP device "[0:$1] CENSORED"
2024-02-06 15:42:12.958 (D) DeviceUSRPParams::open: type=x300,addr=192.168.10.2,fpga=HG,name=,serial=CENSORED,product=X310
2024-02-06 15:42:14.069 (D) DeviceUSRPParams::open: exception: RuntimeError: Expected FPGA compatibility number 38, but got 39:

The FPGA image on your device is not compatible with this host code build.
Download the appropriate FPGA images for this version of UHD.
As an Administrator, please run:

"C:/Program Files\SDRangel\uhd\utils\uhd_images_downloader.py"

Thanks!

**Comment by srcejon** [comment]
UHD now being used in 7.18.1

**Comment by Ali6114** [comment]
Currently, I have set the below settings. Fortunately, SDRangel doesn't crash but the spectrum & Waterfall updating/processing becomes slow.
![image](https://github.com/f4exb/sdrangel/assets/53070719/261579c1-0656-4c0f-9695-d15c7bff92f0)
