### ISSUE TITLE
Auto DC Culling dip in frequency

### ISSUE THREAD

**Issue by LingKuja** [f4exb/sdrangel#1982]
![sdrangel_2024-02-12_01-29-39](https://github.com/f4exb/sdrangel/assets/35222780/57a757a0-5598-4946-a824-6c261cc7b1d9)
SSB (DSB) added in for clarity.
In short, my issue is that for some reason if I enable the Auto DC culling there's a dip around the center, where the antenna should be located. This is an issue, because if for example I punch the correct frequency for the clock or a CW frequency I know, I can't see it for nothing

Any fix? This didn't happened with other programs like SDRConsole (but it doesn't have all the demodulators like SDRAngel lol)

SDR: RTL-SDR V4;
Tuner: Rafael Micro R828D;
OS: Windows 10 21H2, this also happened on Linux Mint 21.3

**Comment by srcejon** [comment]
> my issue is that for some reason if I enable the Auto DC culling there's a dip around the center,

That's exactly what that option is supposed to do.

> Any fix? 

You don't set the device centre frequency to the frequency you are trying to receive, you set it lower / higher, then use the delta f option in the SSB settings (that is hidden in your picture) to tune to the frequency you are interested in.

> This didn't happened with other programs like SDRConsole 

Haven't used it for a while, but any DC removal feature is going to do the same. Perhaps SDRconsole is automatically applying a frequency offset or something.

**Comment by LingKuja** [comment]
> You don't set the device centre frequency to the frequency you are trying to receive, you set it lower / higher, then use the delta f option in the SSB settings (that is hidden in your picture) to tune to the frequency you are interested in.

That is what I've been doing, I've just noticed this dip, and used the SSB demodulator to highlight it. Good to know that it's the intended behavior.

**Comment by f4exb** [comment]
Welcome to SDR Zero IF technology...
