### ISSUE TITLE
iMac Ubunto 18.04 LTS some strange issue related with sound 

### ISSUE THREAD

**Issue by siralexbox** [f4exb/sdrangel#199]
Sorry for my late reply on the other post.
Ubunto 18.04 LTS
When using SDRangel with HackRF to transmit in NFM if audio is not muted crashes SDRangel.
If I have anything already running that used the capture audio source SDRangel freezes.

Made a small video trying to show the issue.
[video](https://www.youtube.com/watch?v=X3LeyElzJQk)
Wile making the video, I notice that if I enable sound recording the freeze happens.

**Comment by f4exb** [comment]
Are you running Ubuntu in a virtual machine on iMac?
In any case you should set the interpolation factor to better match the required bandwidth for NFM modulator (48k) that is if HackRF sample rate is 2400 kS/s either:
  - 16 for a 150k baseband
  - 32 for a 75k baseband

**Comment by siralexbox** [comment]
No virtual machine, its running on the hardware, and its the only OS
Tried playing around with parameters but always freezes is any audio is already playing in the computer.

**Comment by f4exb** [comment]
If you have issues with audio another thing to check is that pulseaudio is properly set up. Maybe you can check this: https://github.com/f4exb/sdrangel#notes-on-pulseaudio-setup It is about audio output but input should be similar.
