### ISSUE TITLE
Rsp1b seems detected but crashes when selected., plus error message on open.

### ISSUE THREAD

**Issue by mistergitj** [f4exb/sdrangel#1990]
My RSP1b seems to be detected but crashes when selected. I also get this error message on start:
<img width="512" alt="AngleError" src="https://github.com/f4exb/sdrangel/assets/45215756/abbcc498-9538-4ec4-99c6-564c6af3d73a">

Running 7.18.0 on W10 x64. Thanks and enjoy, John.

**Comment by srcejon** [comment]
RSP1B support isn't in the latest Windows release. It will be in the next version.

The error message is from the Satellite Tracker. That TLE file is obsolete. Remove it by pressing "Show settings Dialog" button in Satellite Tracker window. Select TLEs tab. Delete the goes.txt file mentioned in the error, by selecting it, then pressing the - button.
