### ISSUE TITLE
High CPU usage in sdrangel (over 100%) - ADS-B - how to fix ?

### ISSUE THREAD

**Issue by ds2k5** [f4exb/sdrangel#1993]
Hi,
have Debian 12 x86_64

Compiled the sdrangel
when running inactive the CPU Load is around 

But when running ADS-B
CPU Load is over 100% by one CPU

![grafik](https://github.com/f4exb/sdrangel/assets/11292286/b32445e7-c33e-47f9-9c7f-06f6cfaf6a6d)

![grafik](https://github.com/f4exb/sdrangel/assets/11292286/c8e894e8-61fe-4d93-93dc-a132fef78e9b)

![grafik](https://github.com/f4exb/sdrangel/assets/11292286/29c6a2d6-e33b-45cf-ab24-66e32eaf0e0d)

Any hint for Compiling options that not have so high CPU load?

When using  Boradcast FM Demodulator CPU load is around  42 %  for sdrangel process

**Comment by srcejon** [comment]
ADS-B demod requires significantly more CPU than FM. ADS-B demod runs at 4MSa/s, whereas FM is running at 48kHz. It's like comparing broadband to dial-up.

You can possibly reducing the load by adjusting sample rates and threshold, but this will affect packet error rate.

**Comment by ds2k5** [comment]
@srcejon 

>You can possibly reducing the load by adjusting sample rates and threshold, but this will affect packet error rate.

thank you
