### ISSUE TITLE
Pluto+ SDR MIMO not working after updating to 0.38 via DFU

### ISSUE THREAD

**Issue by Argonghost** [f4exb/sdrangel#1994]
Hi,  

When i upgraded the Pluto+ firmware to 0.38, and i run a quick experiment using pyADI, i keep getting this error:

```
  File "/home/argonghost/.local/lib/python3.10/site-packages/adi/rx_tx.py", line 184, in _rx_init_channels
    raise Exception(f"Channel {m} not found")
Exception: Channel voltage2 not found
```

im using the dual loop code from here [https://github.com/jonkraft/PlutoSDR_Labs/blob/master/Pluto_revC_rev2.py](url)
the DFU mode upgrade seems to be successful since in the uboot env, it shows me that version 0.38.  and even after setting 
``` fw_setenv attr_name compatible ,,,,,,,, ad9361, 2r2t ``` etc, the dual transmit and receive still doesnt work.

Any help would highly be appreciated.
Thanks

**Comment by srcejon** [comment]
I don't think this is an SDRangel issue
