### ISSUE TITLE
latest release file sdrangel_v4.0.3

### ISSUE THREAD

**Issue by Tonyprosdr** [f4exb/sdrangel#200]
Trying to unzip through .rar utility - its showing 103 errors and the unzipping process has been terminated. Could you please let me know which utility i should use or if yo
[sdrangel_v4.0.3.zip](https://github.com/f4exb/sdrangel/files/2200281/sdrangel_v4.0.3.zip)
u can rezipp and upload once again

**Comment by f4exb** [comment]
7Zip pretty obvious...

**Comment by Tonyprosdr** [comment]
Thank you very much – I was unzipping through .rar utility
