### ISSUE TITLE
Map feature ADSB on arm Mac

### ISSUE THREAD

**Issue by loewal** [f4exb/sdrangel#2010]
Hi Jon,
Since there is support for Qt6, does that mean that SDRangel Arm version supports the map with ADSB?

Regards

**Comment by loewal** [comment]
> Hi Jon, Since there is support for Qt6, does that mean that SDRangel Arm version supports the map with ADSB?
> 
> Regards

Sorry...add: I tried it, but still white surface.

**Comment by srcejon** [comment]
It should have fixed it, but I see an error:

    Qt5Compat.GraphicalEffects is not installed.

So I'll have to see why this isn't installed on the mac.

**Comment by srcejon** [comment]
New build uploaded

**Comment by loewal** [comment]
Yes! That did it Jon.
Thanks very much for the superquick solution.
Regards

**Comment by loewal** [comment]
Sorry Jon, I was to quick:
- x64 version: selec mapboxgl --> crash;  osm-map okay with centering on "My position"
- Arm version: select mapboxgl --> white surface; nocrash; no centering screen on "My Position" using osm-map, but visible map

Regards

**Comment by srcejon** [comment]
Qt 6 on Mac doesn't support mapboxgl, so I'd expect that.

**Comment by srcejon** [comment]
I'll update the list, so only available plugins are listed.

**Comment by loewal** [comment]
Hi Jon,
I installed version 7.20.0 Arm (no Intel yet?)
Using ADSB, the map is centered near London and not my position.
As I mentioned before, using the Intel version, the map is okay.
Could you please look into this?
Tanks!
