### ISSUE TITLE
udev-rules

### ISSUE THREAD

**Issue by srcejon** [f4exb/sdrangel#2015]
Should the udev-rules from sdrangel-docker also be included in sdrangel? 

Might make the initial install a little bit easier, as everything would be available in one package.

**Comment by f4exb** [comment]
If I remember right they were moved out of sdrangel in favor of sdrangel-docker. I don't remember the exact details but I vaguely remember that somebody claimed it was better practice not to have it in sdrangel source tree and was so insistent that I eventually gave up...

**Comment by srcejon** [comment]
Ok
