### ISSUE TITLE
adding pluto sdr on SDR angel

### ISSUE THREAD

**Issue by CyC-Innovation** [f4exb/sdrangel#202]
Hello,

I don't reach to add the source plutosdr on sdrangel,
I have install the librarry libiio.
May you can help me?

Thank you in advance
F4GDW

**Comment by unixpunk** [comment]
You may need to specify the location of the libiio libs and include on the cmake command line for sdrangel.  Check the main page for this project for the syntax and example.  Please also consider this is not the proper forum for future questions such as this: https://groups.io/g/sdrangel  Hope that helps!

**Comment by f4exb** [comment]
As stated please use the discussion group to seek help from users.
