### ISSUE TITLE
MacOS: no spectrum 

### ISSUE THREAD

**Issue by Czukuru** [f4exb/sdrangel#2022]
MacOs Sonoma. The is no spectrum, i got some kind of screen mirroring. If i move windows in program, in spectrum they will  move too. I tried different releases and same issue. 
Any help would be greatly appreciated!
![IMG_20240316_094517_139](https://github.com/f4exb/sdrangel/assets/110229624/f68d4615-177f-4778-b117-dafcb8b71e60)
![IMG_20240316_094517_627](https://github.com/f4exb/sdrangel/assets/110229624/b972fb3e-4e5f-4ef1-8ca8-96ab6c8bf116)

**Comment by srcejon** [comment]
Look in log file (preferences > logging menu) to see if that tells you anything.

**Comment by Czukuru** [comment]
> Look in log file (preferences > logging menu) to see if that tells you anything.

**Comment by Czukuru** [comment]
> Look in log file (preferences > logging menu) to see if that tells you anything.

[log — копия.txt](https://github.com/f4exb/sdrangel/files/14622756/log.txt)

**Comment by Czukuru** [comment]
> > Look in log file (preferences > logging menu) to see if that tells you anything.
> 
> [log — копия.txt](https://github.com/f4exb/sdrangel/files/14622756/log.txt)
> 
> is it right file?

<img width="467" alt="Снимок экрана 2024-03-16 в 10 16 26" src="https://github.com/f4exb/sdrangel/assets/110229624/d05b4820-88bc-4fd5-a16c-6b2822ab9940">

**Comment by Czukuru** [comment]
if i move cursor around this window, i can change frequency by dragging something that should be in spectrum. so computer thinks that he is spectrum there but wrong visual output

**Comment by srcejon** [comment]
It's an opengl problem of some sort.

Try running from a terminal to see if anything is output there.

**Comment by Czukuru** [comment]
> It's an opengl problem of some sort.
> 
> Try running from a terminal to see if anything is output there.

can you explain a little please. im not really sure what to do. i run this app from terminal, but no difference

**Comment by srcejon** [comment]
I was just hoping some error message might be output - but apparently not.

**Comment by Czukuru** [comment]
So the is no possible chance to fix this it in my case?

**Comment by Czukuru** [comment]
> Я просто надеялся, что появится какое-нибудь сообщение об ошибке, но, видимо, нет.

I saw some people who got the same problem, but no solution. Can i do something to fix this?

**Comment by Czukuru** [comment]
Installing from macports or from dmg, or different versions won't help

**Comment by Czukuru** [comment]
![IMG_20240316_193646_812](https://github.com/f4exb/sdrangel/assets/110229624/a9e728a6-40b7-48cc-9065-cebce6d44f30)

**Comment by srcejon** [comment]
If you're able to compile the source yourself, you could try changing sdrgui/gui/glspectrumview.cpp. On line 900, change:

    // Enable OpenGL debugging
    // Disable for release, as some OpenGL drivers are quite verbose and output
    // info on every frame
    if (false)

To 

    // Enable OpenGL debugging
    // Disable for release, as some OpenGL drivers are quite verbose and output
    // info on every frame
    if (true)

And it might give us some information about the problem.

**Comment by srcejon** [comment]
> I saw some people who got the same problem, but no solution. Can i do something to fix this?

Might be useful if you can link to those some how, so we can see what you have in common. E.g. h/w, s/w etc.
