### ISSUE TITLE
APRS igate only forwards packets it can decode

### ISSUE THREAD

**Issue by hessu** [f4exb/sdrangel#2029]
Hi,

The APRS igate does not forward packets it can not decode itself. There may be packets out there that are not yet implemented in the decoder of sdrangel, or new/experimental packets. The igate does not need to care whether it can understand the APRS packet contents - the decision whether to forward the packet can be left to the APRS-IS servers, and other decoders on the other side of APRS-IS may well be able to decode them. It's good to obey the "NOGATE", "RFONLY" rules, of course.

https://github.com/f4exb/sdrangel/blob/cb89392c86e4a218c53cbec6b1afeff93cd75f23/plugins/feature/aprs/aprsworker.cpp#L108

Just make sure the igate is binary clean, and send bytes up to the first CR or LF character seen in the AX.25 data field.

**Comment by srcejon** [comment]
Should be fixed in 7.20
