### ISSUE TITLE
entry point error

### ISSUE THREAD

**Issue by TonyHagen** [f4exb/sdrangel#203]
When i start the transmitter a pop up window appears " Entry point error, not able to locate some .dll files"

What could be the reason ?
-Tony

**Comment by f4exb** [comment]
Without any more information I conclude at a bad installation.

**Comment by TonyHagen** [comment]
check here too the first post – the same has been reported https://www.rtl-sdr.com/a-tutorial-on-using-sdrangel-for-dmr-d-star-and-fusion-reception-with-an-rtl-sdr/

Fuurther what I understand you should have 64bit os and system and the sdrangel software folder needs to be placed in the program folder and run the sdrangel application – SO WHERE THE INSTALLATION IS INVOLVED

OTHERWISE my hackrf is working perfect

73
Tony

**Comment by TonyHagen** [comment]
IS it compatible with hackrf

73
Tony

**Comment by f4exb** [comment]
If you have such questions particularly regarding running on Windows please post a message to https://groups.io/g/sdrangel to seek help from other users.
