### ISSUE TITLE
Win 7 problems can't start

### ISSUE THREAD

**Issue by Hackrfan** [f4exb/sdrangel#2032]
Unfortunately, I can no longer start SDRANGEL with WIN7 Prof. There is always an error message. dll missing.
What can I do?
![fehler](https://github.com/f4exb/sdrangel/assets/161310720/593af600-1ab7-49cf-a435-da71f6f281ba)

**Comment by srcejon** [comment]
- Upgrade to a supported version of Windows.
- See if you can get a copy of that dll from somewhere - although no guarantees it will work
- Try compiling SDRangel yourself

**Comment by mxi-box** [comment]
SDRangel should works on Win7.
You can See [https://www.sevenforums.com/gaming/424879-epic-games-api-ms-win-downlevel-kernel32-l1-1-0-dll-missing-error-2.html](url) for something may help you
