### ISSUE TITLE
 DATV Modulator on Ubuntu

### ISSUE THREAD

**Issue by hb9dug** [f4exb/sdrangel#2033]
On the Windows version, the DATV demodulator has, next to the "UDP bitrate" parameter, a parameter indicating how full is the UDP buffer.

In the Ubuntu version, I can't find this parameter, which is very useful for correctly adjusting the TS bitrate.

It would be great to add it in a future update.

Best regards,
Michel

**Comment by srcejon** [comment]
Unfortunately the Linux SIOCINQ ioctl doesn't report how much data is in the UDP buffer, as is the case on other OSes, so it can't be supported, unless someone knows another method.
