### ISSUE TITLE
flatpak not working on arm64

### ISSUE THREAD

**Issue by ksbjr** [f4exb/sdrangel#2044]
the flatpack img you have does not work on arm64 currently

**Comment by srcejon** [comment]
I don't know who builds the Flatpak. Maybe @AsciiWolf here: https://github.com/flathub/org.sdrangel.SDRangel

**Comment by AsciiWolf** [comment]
Yes, it should be reported [here](https://github.com/flathub/org.sdrangel.SDRangel/issues) instead. But please, provide some logs and additional details. Thanks!
