### ISSUE TITLE
linux build out of date 

### ISSUE THREAD

**Issue by RichNeese** [f4exb/sdrangel#2046]
https://github.com/f4exb/sdrangel/wiki/Compile-from-source-in-Linux
for one we have moved to soapysdr0.8 and most of it installed as modules only a few itels are not supported.
next is /opt on linux is for the mostpart not used.
need to work on a real install using the /usr/local for the extra parts.
I will work on a script to fix alot but man we need to get this to use pkgs where it can
I like sdrangle I use it on the mac . but on linux the flatpack is not working on arm64 
and alot of us dont like docker for building when we can have more native installs
.

This is the what most hams on debian and archlinux like

**Comment by f4exb** [comment]
https://github.com/f4exb/sdrangel/wiki/Compile-from-source-in-Linux are working it its context. Installing in /usr/local requires root privileges which should be avoided if not strictly necessary.

If you don't like this approach you can adapt it to your own but these instructions based on /opt will not change.
