### ISSUE TITLE
Enter centerfreq don't work on android

### ISSUE THREAD

**Issue by DickVos** [f4exb/sdrangel#2047]
Hello,

Does anybody have the same issue that you can not enter the centre freq or BW? 

This is on an android device. The keyboard appears when you press a digit but whatever you type I don't change the digit?

Dick

**Comment by srcejon** [comment]
Similar issue reported here: https://github.com/f4exb/sdrangel/issues/1732

What version of Android and device?

Unfortunately, I can't reproduce it, so don't know how to fix it.

**Comment by DickVos** [comment]
Thanks for respond,

I have the Galaxy Tab II with Android 9

**Comment by abelouso** [comment]
I have the same problem, Galaxy Tab A 8.0, Android 9

**Comment by DickVos** [comment]
Looks like an Android 9 I.c.w. SDR Angel issue

**Comment by DickVos** [comment]
I have installed GBoard, Google keyboard from the playstore and set it as default. Now it's working. Problem solved.
