### ISSUE TITLE
playing recording broken

### ISSUE THREAD

**Issue by beta-tester** [f4exb/sdrangel#205]
in version 4.0.6 seems the recording is broken.
i just recorded a huge file with sdrangel 4.0.6 and tried to play it back,
but the shown frequency "1,000,000kHz",
the shown bandwidth "0.058k",
the shown time "1970-03-15"
and the shown length are totally wrong
and nothing is shown on the waterfall nor the spectrum view.

i tried an older similar huge recoding made with 4.0.4 and there i can playback the recording correctly on 4.0.6.

damn stupid me, i updated sdrangel without testing if the recording will succeed, just before i recorrded an importand one-time-ever-event... (installing and setting up the wireless consumption meter of my  radiator)
now i guess i lost everything i wanted to record/playback/analyse... :((

i used the windows version 4.0.6 of sdrangel.
with my PlutoSDR.

![recording broken](https://user-images.githubusercontent.com/4750719/44255735-491e6680-a207-11e8-8684-95df8675cc45.PNG)

**Comment by beta-tester** [comment]
maybe it is depending only on the file-size.
the faulty recording is 17GB big, the file with 12GB is working.

**Comment by f4exb** [comment]
Well I have not encountered this issue just by changing the record name with a 'ö' in the name. So it must be something else that corrupted the header of the file. The first few bytes contain time and sample rate information that was obviously damaged.

**Comment by beta-tester** [comment]
the file name that wasn't read correctly was moved and renamed fust after recording and before i tried to load in FileSource: 
from `E:\SDR\sdrangel\rec0_2018-08-17T05_51_40_895.sdriq`
to `E:\SDR\rec0_2018-08-17T05_51_40_895-Heizkörper08-13.sdriq`

the working dir and path of sdrangel is:
`E:\SDR\sdrangel\`
`E:\SDR\sdrangel\sdrangel.exe`

filesystem is: `ntfs`

every think went good with renaming the file to:
`E:\SDR\rec0_2018-08-17T05_51_40_895-Heizkoerper08-13.sdriq`

so the file header/content is not damaged.

i think the FileSource wasn't reading the file header at all, because i get similar values shown in the screenshot, when i try to read a file with 0Byte into the FileSource.

e.g.
`E:\SDR\null.sdriq` with 0byte shows 00:00:00 [Total record time]
![null](https://user-images.githubusercontent.com/4750719/44305778-d802be80-a380-11e8-8100-bbdd1a06dbf7.PNG)

`E:\SDR\null-ö.sdriq` with 0byte shows 01:17:38 [Total record time]
![o](https://user-images.githubusercontent.com/4750719/44305822-23699c80-a382-11e8-88a3-6c418a42b064.PNG)

`E:\SDR\null-ö-2.sdriq` with 0byte shows 10:08:57 [Total record time]
![o2](https://user-images.githubusercontent.com/4750719/44305828-39775d00-a382-11e8-8691-557a6ce11bf5.PNG)

different values just by changing the name of the file only.

**Comment by f4exb** [comment]
To be sure the file header needs a CRC to protect it in case of corruption.
Closed in favor of #206

**Comment by gaspar1987** [comment]
bonsoir  le record  qui marche pas  parque que il enregistrent pas .
