### ISSUE TITLE
Hermes Lite 2 [openHPSDR] Full Support

### ISSUE THREAD

**Issue by CRD716** [f4exb/sdrangel#2050]
The [Hermes Lite 2](http://www.hermeslite.com/) is a pretty common open source SDR, and I think many would enjoy it being fully supported in sdrangel. I know it works somewhat as a MIMO device, but last I saw it was missing some features like N2ADR filter board control. I could also be completely blind/making this up, but this is what I've read/found in the documentation so far.

https://github.com/softerhardware/Hermes-Lite2/wiki/Software has a list of other programs that currently support it, along with some other info, like the openHPSDR protocol used.

**Comment by CRD716** [comment]
_Cough_

**Comment by CRD716** [comment]
cough cough cough

**Comment by CRD716** [comment]
but what if

**Comment by Cisien** [comment]
This would be amazing. I just picked up a Hermes Lite 2, and find the current supported linux SDR options a bit clunky to use.

**Comment by SJRDorset** [comment]
I completely agree. It would be really good to have complete support for the Hermes Lite 2. I also have an Anan 10 and it would be nice if this was supported as well.
