### ISSUE TITLE
Fix wiki page Compile-from-source-in-Linux.md

### ISSUE THREAD

**Issue by dforsi** [f4exb/sdrangel#2064]
The attached patch fixes two small issues in the documentation.

If you did copy and paste the command suggested in the terminal you would get errors and fail to install all needed packages because some lines containing the names of the packages to be installed would be interpreted by the shell as commands:
```
E: Unable to locate package  
-bash: qml6-module-qtquick-dialogs: command not found
-bash: qt6-webengine-dev-tools: command not found
```
[0001-Fix-continuation-lines.patch.txt](https://github.com/f4exb/sdrangel/files/14966933/0001-Fix-continuation-lines.patch.txt)

**Comment by dforsi** [comment]
The following packages are missing from the list of dependencies for Qt6 in `Compile-from-source-in-Linux.md`:
- qt6-svg-dev
- qt6-location

**Comment by f4exb** [comment]
Thanks, done.
