### ISSUE TITLE
Device settings changes are not communicated via Reverse API

### ISSUE THREAD

**Issue by godsic** [f4exb/sdrangel#2065]
When Reverse API is activated for a device, the corresponding server receives all device settings via PATCH method as expected. Any subsequent device settings changes, notably center frequency, are not communicated to the server neither through PATCH or PUT requests.

Can help to fix the problem if you can point me in the right direction.

![image](https://github.com/f4exb/sdrangel/assets/2339291/1de37ebf-096a-4bd0-ab4f-11fbba7db9ec)

**Comment by srcejon** [comment]
Which device?

**Comment by godsic** [comment]
@srcejon rtlsdr

**Comment by godsic** [comment]
@srcejon According to this logic:

```cpp
 if (settingsKeys.contains("useReverseAPI"))
    {
        bool fullUpdate = (settingsKeys.contains("useReverseAPI") && settings.m_useReverseAPI) ||
            settingsKeys.contains("reverseAPIAddress") ||
            settingsKeys.contains("reverseAPIPort") ||
            settingsKeys.contains("reverseAPIDeviceIndex");
        webapiReverseSendSettings(settingsKeys, settings, fullUpdate || force);
    }
```

The communication would only happen if `settingsKeys.contains("useReverseAPI")`, i.e., if `useReverseAPI` is changed. Shouldn't this be something like ` if (settingsKeys.contains("useReverseAPI") || settings.m_useReverseAPI)`?
