### ISSUE TITLE
LimeSuite 18.10.0

### ISSUE THREAD

**Issue by lryindra** [f4exb/sdrangel#209]
it appears that the latest LimeSuite (gitrev: 2b4e91fd8ecb059f4b8256d63ca1d125cac9f818) works with sdrAngel.  This is only a change to the README.

**Comment by f4exb** [comment]
I usually do not upgrade on commits but on releases tags. I saw that there has been new releases so I can upgrade in one of the next  versions

**Comment by f4exb** [comment]
18.10.0 is out: https://github.com/myriadrf/LimeSuite/releases/tag/v18.10.0

**Comment by f4exb** [comment]
Implemented in v4.2.4
