### ISSUE TITLE
GL Scope problem with the latest versions of Ubuntu.

### ISSUE THREAD

**Issue by choupette-change** [f4exb/sdrangel#2090]
For your information, with the latest versions of Ubuntu 23 10 and 24 04 LTS, it works except for the "Waveform" item. The screenshot does not represent the real problem, it would be a problem updating this part, all the curves accumulate and end up making a big spot of color..
![Capture d’écran du 2024-04-26 16-32-37](https://github.com/f4exb/sdrangel/assets/68333247/9d12f4f9-4a15-4c9e-9372-b1a9e8c2959b)

**Comment by srcejon** [comment]
In 24.04 under VM Workstation, I get:

![image](https://github.com/f4exb/sdrangel/assets/57259258/0a3dd472-759c-4b10-8abd-7f0ae6a5e6c3)

**Comment by choupette-change** [comment]
I have the same problem as you in virtual machine VM 24 04 and installation Ubuntu 24 04 dual boot with Windows.

**Comment by f4exb** [comment]
it appears that 24.04 is not available yet using the do release upgrade method. They say that there are some issues and they wait for 24.04.1 to be released in August

**Comment by f4exb** [comment]
I have compiled SDRangel on my brand new RasPi 5 on Ubuntu 24.04 and did not notice anything wrong with the display.
