### ISSUE TITLE
Wrong images for UDP Sink plugin

### ISSUE THREAD

**Issue by dforsi** [f4exb/sdrangel#2092]
The .png and .xcf images for the UDP *Sink* plugin are identical to the one for the *Source* plugin.

It seems they were overwritten in commit https://github.com/f4exb/sdrangel/commit/bdb0e50c5fcd588f9d50242b92f0fffe0e965dbf

**Comment by f4exb** [comment]
This is an old image but the controls are right

**Comment by dforsi** [comment]
You are right, I must have compared the xcf with the png of the same window!
We can fix the title with some copy and paste.
