### ISSUE TITLE
Add AIS Feed Support

### ISSUE THREAD

**Issue by ZanderBrumbaugh** [f4exb/sdrangel#2100]
The ADS-B feed is very useful, especially when setting up localhost as the client and SDRangel as the server. It would be great if similar functionality was available for AIS or some alternative method for streaming live data. Even an API to save and export data repeatedly would be helpful. It doesn't appear there's any way to get AIS data out of the application currently without manually saving it to a .kml.

**Comment by srcejon** [comment]
Check the UDP option in the demod, it can export NMEA. Or you can use the log file. 
https://github.com/f4exb/sdrangel/blob/master/plugins/channelrx/demodais/readme.md
