### ISSUE TITLE
Reverse API for Frequency Scanner?

### ISSUE THREAD

**Issue by sandric** [f4exb/sdrangel#2108]
Hi, I'm playing with frequency scanner reverse api, the idea is to scan list of freq's and send reverse api request to check if it became "active" - e.g. power level got bigger than some theshold. I see that it does not send any change on any of channel changes I make, so I wonder if its my setup is wrong (its working for other channels I test though), feature is not implemented, or its not even planned to be implemented since this channel would generate a ton of requests each scan?
Thx

**Comment by srcejon** [comment]
Currently it only reports via the GUI.

I could probably add the results to the channel report.

**Comment by CharlieDeltaOskar** [comment]
Also, it would be great to have start/stop scanning controls.
