### ISSUE TITLE
This file is not loading : airportFrequenciesDatabase.csv

### ISSUE THREAD

**Issue by choupette-change** [f4exb/sdrangel#2113]
This file is not loading
![Capture d’écran du 2024-05-15 12-05-01](https://github.com/f4exb/sdrangel/assets/68333247/87d46b20-213d-405b-a7dc-7448b2aac2a2)

**Comment by srcejon** [comment]
That file doesn't contain spectrum markers. (It's for use by the ADS-B plugin).
