### ISSUE TITLE
how to use Map in offline computer

### ISSUE THREAD

**Issue by adityadeva9** [f4exb/sdrangel#2117]
HIi, 

I was trying to use the map data downloaded in a online computer (ubuntu 20.04) and copying it to a computer with same OS and same version of SDR angel (ver-7.15.3). 

I copied the following directories. 

/home/username /.cache/QtLocation  - 	map data

/home/username /.cache/f4exb 		-	cache

/home/username /.config/f4exb		-	configuration

/home/username /.local/share/f4exb	-	files

/home/username /.config/f4exb		-	config

however I am not able to see the maps in the offline system. also map data get reset if the online system is restarted with internet off. 

is there some way i can use the map in a offline system where there is no internet access.

**Comment by srcejon** [comment]
Map cache is  QStandardPaths::GenericCacheLocation  + /QtLocation/5.8/tiles

But it wouldn't surprise me if it doesn't work offline, I'm afraid.
