### ISSUE TITLE
Flatpack UI unusable on openSUSE with 4K monitor

### ISSUE THREAD

**Issue by shidel** [f4exb/sdrangel#2118]
I don't know if the program is working or not. I can't get it to seem to do anything. In part because I'm new to SDR. But, also in part to the UI being incomprehensible with multiple elements overwriting each other, text being cropped, etc.

![Screenshot_20240518_175535](https://github.com/f4exb/sdrangel/assets/10198034/25b8d0aa-6218-4a04-a3d2-7698879f590a)

**Comment by srcejon** [comment]
What do you have for UI scaling under Preferences > Graphics menu.

**Comment by shidel** [comment]
Originally, just 100%. It was just as bad at that setting and tiny. Turned it up to about 200%. A little on the big side. But everything still just messed up. Not better, not worse, just bigger.  I turned it back to 100% and restarted the program for theses screen shots...
![Screenshot_20240518_205515](https://github.com/f4exb/sdrangel/assets/10198034/45f86bfb-bb3d-435a-8e06-f3224226ff6d)
![Screenshot_20240518_205549](https://github.com/f4exb/sdrangel/assets/10198034/c0082071-d4af-4475-a30f-451fda3f53a8)

**Comment by shidel** [comment]
Using KDE, global scale settings, just 100%. 

![Screenshot_20240518_210223](https://github.com/f4exb/sdrangel/assets/10198034/ca0e71c8-806d-4165-9bb0-5a0fedab1e8c)

**Comment by shidel** [comment]
This issue has been resolved.
