### ISSUE TITLE
SDRDuo 

### ISSUE THREAD

**Issue by ThermoNuclear65** [f4exb/sdrangel#2129]
Hi all ,

SDRDuo doesn't work anymore in 7.21 , it does nor appear in the "select sampling device" drop down.

In 7.17 it is still working .

Any hints or tricks .

Regards 
Patrick

**Comment by ThermoNuclear65** [comment]
SDRduo issue is on a MAC M1.

**Comment by srcejon** [comment]
Latest version of SDRangel requires SDRplay API 3.14.

**Comment by ThermoNuclear65** [comment]
yes , running now , Thank you.

**Comment by alphafox02** [comment]
I know this is closed, but I assume you all are tracking the SDRplay API has been bumped to 3.15 for the new hardware?
