### ISSUE TITLE
SSB Demodulator

### ISSUE THREAD

**Issue by ThermoNuclear65** [f4exb/sdrangel#2130]
Hi All ,
when i open the settings of the noise reduction (Right click) in the SSB Demod window and close this pop-up , after this in the whole SSB window nothing responds anymore , after restart SDRAngel the effect is the same.

This is with V 7.21.1 on a MAC M1.

Any idea's ?

Kind Regards

**Comment by ThermoNuclear65** [comment]
Actualy , non of the windws respond any more ,only after restrart all is ok unyill you push thr NR button again.

**Comment by ThermoNuclear65** [comment]
In the windows version everything works perfect.

**Comment by srcejon** [comment]
Probably the same as: https://github.com/f4exb/sdrangel/issues/1979
