### ISSUE TITLE
Morse Demodulator not visible in ver 7.20.1 macOS M2 chip

### ISSUE THREAD

**Issue by Axpelle** [f4exb/sdrangel#2135]
Please see screenshot of features list as seen on my computer (Sonoma M2 chip). Morse demod. absent.
[Features List.pdf](https://github.com/f4exb/sdrangel/files/15483641/Features.List.pdf)

**Comment by srcejon** [comment]
Works for me. 

Can you send the log file (Preferences > Logging)

**Comment by Axpelle** [comment]
Hi there

The problem has been solved in Ver. 7.21.1 so please disregard the post.

Thank you for your prompt reply.

Regards

Axel


——— Original message received from "srcejon" ***@***.***> 
on 04/06/2024 15:12:02 ———
