### ISSUE TITLE
Windows: SSB audio compressor: default settings generate feedback

### ISSUE THREAD

**Issue by RipperFox** [f4exb/sdrangel#214]
Tested v4.0.7 on Windows with Pluto sink - CMP seems almost unusable for me.

![grafik](https://user-images.githubusercontent.com/14198311/45139905-9613ae00-b1b1-11e8-8994-e5576fbb1789.png)

See video here: https://youtu.be/xxj7Rzq0h2I (Audio was recorded from RF via another SDR.)

**Comment by f4exb** [comment]
Not sure it is entirely related but you have a very very large sample rate in the baseband for just SSB judging by the number at the top left corner of the screenshot and confirmed by the frequency scale. 2500 kS/s is a lot when you just need 48 kS/s. This puts a lot of strain on the channel interpolator that is not designed to match such a large gap. You should try to increase software decimation on the Pluto device interface.

**Comment by RipperFox** [comment]
Just tried with these settings - same distortion:

Same signal 
![grafik](https://user-images.githubusercontent.com/14198311/45160432-b8c1b900-b1e9-11e8-9946-bfed9c8bd2d0.png)

**Comment by RipperFox** [comment]
I tested a but further: Problem exists with FileSync & Source, too.
It seems there is some gain routine going wild? Even when there's no input from the mic (I tested muting the device in Windows and by selecting a unconnected virtual audio cable) there's a build up of noise..

**Comment by g0hww** [comment]
I'm not entirely certain how the compressor should be set up, but i have had similar issues with instability. I could do with a bit more oomph in my HackRF-based uplink for Es'hail-2, which has netted me a QSO using sdrangel for SSB tx, with a 13dB "4W" wifi amp and a 21dBi 50cm dish :)

**Comment by f4exb** [comment]
Cannot reproduce.
