### ISSUE TITLE
Unable to add a second audio input source

### ISSUE THREAD

**Issue by dforsi** [f4exb/sdrangel#2143]
I have two sound cards (one is builtin on the motherboard of my PC and the other is embedded in my radio), I can add an audio source and select either one. I would like to add both as separate sources for differente demodulators, but the sampling device dialog allows only to add one audio source.

**Comment by f4exb** [comment]
You have to right click on the "mute" button. This is generally the same with all demods with sound. Example with the SSB demod:
![image](https://github.com/f4exb/sdrangel/assets/6192319/4b882bb0-a042-4da8-9cd4-d3f249c18a62)

**Comment by f4exb** [comment]
Probably due to the way the Audio plugin is handled as if it was an actual hardware device. This does not happen with KiwiSDR for example.

**Comment by f4exb** [comment]
Issue is here: https://github.com/f4exb/sdrangel/blob/master/plugins/samplesource/audioinput/audioinputplugin.cpp#L96 it should be listed as a "BuiltInDevice"
