### ISSUE TITLE
Why does sdrangel depend on out of date libraries?

### ISSUE THREAD

**Issue by tomcass240** [f4exb/sdrangel#2150]
I want to install sdrangel on Debian Bookworm but it isn't installable because it requires packages that aren't available on this version of Debian because they're outdated.

Is there any chance someone is going to release a version that can be installed on an operating system that isn't out of date?

**Comment by srcejon** [comment]
There are flatpak and snap builds available, or you can compile from source.

**Comment by f4exb** [comment]
> I want to install sdrangel on Debian Bookworm but it isn't installable because it requires packages that aren't available on this version of Debian because they're outdated.

The Docker image builds perfectly based on a Bookworm image: https://github.com/f4exb/sdrangel-docker/blob/master/sdrangel/Dockerfile

**Comment by tomcass240** [comment]
> > I want to install sdrangel on Debian Bookworm but it isn't installable because it requires packages that aren't available on this version of Debian because they're outdated.
> 
> The Docker image builds perfectly based on a Bookworm image: https://github.com/f4exb/sdrangel-docker/blob/master/sdrangel/Dockerfile

How do I use the docker image?

**Comment by f4exb** [comment]
The answer should be here: https://github.com/f4exb/sdrangel-docker/blob/master/sdrangel/readme.md
