### ISSUE TITLE
Radiosonde feature - SondeHub Feed

### ISSUE THREAD

**Issue by ArtemKiyashko** [f4exb/sdrangel#2162]
@srcejon 

Hi. Why This button is not visible on tablet (Android) even on your screens in docs:
![telegram-cloud-photo-size-2-5422793199778388636-y](https://github.com/f4exb/sdrangel/assets/32637427/c3dd5c13-db6f-4302-87e7-6f28e82973e3)

But visible on desktop (macos):
![telegram-cloud-photo-size-2-5422793199778388637-y](https://github.com/f4exb/sdrangel/assets/32637427/50f51a9e-77d6-4315-a3bd-f6b9b7198fc0)

Cannot find an answer in docs. Thanks in advance.

**Comment by srcejon** [comment]
Android build hasn't been updated to include it yet.

**Comment by ArtemKiyashko** [comment]
Gotcha! Waiting then :)
