### ISSUE TITLE
Antanna Diversity support.

### ISSUE THREAD

**Issue by ThermoNuclear65** [f4exb/sdrangel#2163]
Hi ,
I've tested the interferometer with the Red Pitaya 122-16 bit Metis protocol and with the Pavel software running on the Red Pitaya, works perfect on the Mac M1 , but on WIN 11 ,when I want to "Insert" the Interferometer , SDRangel become unresponsive and crashes after 20 seconds.
Any Hints or Tips.

Kind Regards. 73

Patrick

**Comment by CocolinoFan** [comment]
Can you post the debug info before SDRangel crashes? 
You can enable debugging in Preferences -> Logging -> tick "Log to file" -> select destination for file -> OK
