### ISSUE TITLE
ALE MIL-STD 188-141 Decoder

### ISSUE THREAD

**Issue by DE3JGA** [f4exb/sdrangel#2188]
Hello,

Sorry, I have to ask again. There are countless ALE 2G (MIL-STD 188-141) shortwave networks worldwide. Is work being done to get a decoder for SDRANGEL?

I'm sure that many DXers would be happy about it.

Thank you very much for your effort and work!

Good luck in the future!!!

73, Josef

**Comment by srcejon** [comment]
> Is work being done to get a decoder for SDRANGEL?

Not currently.
