### ISSUE TITLE
SDRAngel Android: Error saving files

### ISSUE THREAD

**Issue by rkarikari** [f4exb/sdrangel#2189]
Hello,

I'm unable to save any files in sdrangel android. 
Any attempt results in a zero-byte file and an error message as shown in the attached screenshots.

Any help / suggestions would be greatly appreciated.

Thanks.

PS: I have enabled all permissions for the app.

![sdrAngel-android2](https://github.com/f4exb/sdrangel/assets/115777368/7eeb1d7a-0d93-4a3b-9e9b-32acdc0b1af0)
![sdrAngel-android](https://github.com/f4exb/sdrangel/assets/115777368/d64ed852-7d98-415a-944a-8e65fb6f6169)

**Comment by srcejon** [comment]
Android needs special file handling, and that has yet been implemented yet for exporting configuration files.

**Comment by rkarikari** [comment]
Thanks for the prompt response.

I guess the same issue applies to saving anything in sdrangel for android (downloaded/decoded APT images) as I got the same error when trying to save.

**Comment by srcejon** [comment]
Saving images from APT demod works for me.

**Comment by srcejon** [comment]
Actually, saving the configuration should work as well, but you need to make sure you enter a filename with the .cfgx extension.

Likewise, when saving APT image, make sure you enter a .jpg or .png extension in the file dialog.

(Android wont let SDRangel add the extension itself).

**Comment by rkarikari** [comment]
> Actually, saving the configuration should work as well, but you need to make sure you enter a filename with the .cfgx extension.
> 
> Likewise, when saving APT image, make sure you enter a .jpg or .png extension in the file dialog.
> 
> (Android wont let SDRangel add the extension itself).

I tried  the .jpg extention and got the following error...
![Noaa18](https://github.com/f4exb/sdrangel/assets/115777368/f7bfdc9c-d52e-4286-bfdc-c1d31cf6d610)

However, using .png works !
I've also  confirmed that saving works for the configuration files once the .cfgx extension is appended to the file name.

Thanks so much.
