### ISSUE TITLE
Hey It NOT ISSUES But i need colormap Add cubehelix

### ISSUE THREAD

**Issue by KristapsSDRSharp** [f4exb/sdrangel#2191]
![Colormap](https://github.com/f4exb/sdrangel/assets/162813515/576fdff4-e830-4e4e-8b68-d2b450e479e7)

**Comment by f4exb** [comment]
It is pretty difficult to retrieve values from a picture. In SDRangel color maps are stored as 256 (R,G,B) floating point values (0.0 to 1.0) from lower to higher. If you can provide these values it will be no big deal to add this color map.

**Comment by f4exb** [comment]
This can be done in Python...
Firstly install pillow:
```
pip install pillow
```
Then this snippet should print out the colormap structure to be inserted in `sdrgui\gui\colormap.cpp`:
```python
from PIL import Image

im = Image.open('cubehelix.png') 
pix = im.load()
xsize = im.size[0]

print("const float ColorMap::m_cubehelix[m_size] =")
print("{")

for xi in range(256):
    x = int((xsize/256)*xi)
    colortuple = pix[x, 0][:-1]
    rf = colortuple[0] / 256
    gf = colortuple[1] / 256
    bf = colortuple[2] / 256
    print(f"    {rf:.4f},   {gf:.4f},   {bf:.4f},")

print("};")
```

**Comment by f4exb** [comment]
The explanation that goes with this palette seems to be here: https://people.phy.cam.ac.uk/dag9/CUBEHELIX/ Could be nice indeed.

**Comment by f4exb** [comment]
Two new colormaps:

- cubehelix: derived from the attached image which has linear grayscale progression
- cubegamma: calculated with the javascript app applying a gamma factor of 0.4 to accentuate weak signals
