### ISSUE TITLE
qtgamepad not exist in QT6

### ISSUE THREAD

**Issue by hiperiondev** [f4exb/sdrangel#2192]
I am the maintainer of the Sdrangel build for fedora.
qtgamepad does not exist for QT6 and it is very possible that it will not be ported for quite some time (the developer wants to make many changes before making the port)
Is there any alternative to its use? Is it still necessary?

**Comment by f4exb** [comment]
As far as I can see this is used only in the Rotor controller feature (gs232controller) so you can always skip this plugin from your build. However maybe you do want this feature.

**Comment by hiperiondev** [comment]
Thank you very much for the reply. It does not seem to generate conflicts in operation using the qt5 library

**Comment by hiperiondev** [comment]
But when it starts I find the following error:

2024-06-30 19:14:06.248 (W) AudioOutputDevice::start: using system default device Default ALSA Output (currently PipeWire Media Server)
2024-06-30 19:14:06.248 (I) AudioOutputDevice::start: audio format OK
ALSA lib pcm.c:8750:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:8750:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:8750:(snd_pcm_recover) underrun occurred

**Comment by srcejon** [comment]
> But when it starts I find the following error:
> 
> 2024-06-30 19:14:06.248 (W) AudioOutputDevice::start: using system default device Default ALSA Output (currently PipeWire Media Server) 2024-06-30 19:14:06.248 (I) AudioOutputDevice::start: audio format OK ALSA lib pcm.c:8750:(snd_pcm_recover) underrun occurred ALSA lib pcm.c:8750:(snd_pcm_recover) underrun occurred ALSA lib pcm.c:8750:(snd_pcm_recover) underrun occurred

This is unrelated to qtgamepad.

**Comment by srcejon** [comment]
> As far as I can see this is used only in the Rotor controller feature (gs232controller) so you can always skip this plugin from your build. However maybe you do want this feature.

The plugin should still compile and work even without qtgamepad - the code that uses it should all be conditional on if it is available. If it doesn't compile, please let me know.

**Comment by hiperiondev** [comment]
Yes, compile and work.
Txs
