### ISSUE TITLE
Ability to pre-cache map data (so that you can see the ADB-S map while offline)

### ISSUE THREAD

**Issue by petruut** [f4exb/sdrangel#2193]
Currently, the solutions to see planes on a map while offline/ in the field are clunky.

It'd be great to allow SDRangel to function truly stand-alone, and enable the user to pre-cache/ download map data to render while offline.

Thanks for considering this and thanks for a fantastic piece of software

**Comment by dforsi** [comment]
You can display pre-downloaded maps in the OpenStreetMap format. When using a local directory you need to prefix with file://
I'm going to open a pull request to add this and  other details to the readme.

For cached maps did you try what was suggested in https://github.com/f4exb/sdrangel/issues/2117#issuecomment-2116937128 ?
