### ISSUE TITLE
Windows 11

### ISSUE THREAD

**Issue by HB9RYZ** [f4exb/sdrangel#2207]
Hi All
SDRangel version "sdrangel-7.21.4-win64.exe" works only on **one** of three Windows 11 PCs/Notebook.

I start SDRangel, but nothing will happen - no error message - just nothing.

Hard to analyze and to find out the issue?

Any idea?

73 de HB9RYZ
Wolfgang

**Comment by srcejon** [comment]
Try installing the latest Visual C libraries from: https://aka.ms/vs/17/release/vc_redist.x64.exe

**Comment by HB9RYZ** [comment]
Thanks "srcejon", you are the best. Now SDRangel works :-)
73 de HB9RYZ
Wolfgang

**Comment by OP25Rookie** [comment]
I also had the same issue and this resolved it.  SDRAngel would not open.  Running it only showed the opening splash screen for a couple seconds. Then the splash screen disappears and the program never opened.  Running that .exe installer got it working now.  Thanks all.
