### ISSUE TITLE
Converting special characters in pocsag logger

### ISSUE THREAD

**Issue by johanios** [f4exb/sdrangel#2211]
Hi!

I'm using the pocsag modulator to log messages to a csv file. Sometimes the alpha message contains characters like ' " ' which messes upp the structure of the csv file. Same thing with commas ','.

Is it possible to somehow convert those characters to some other before writing to the log file?

Thanks!

**Comment by srcejon** [comment]
It seems , should be in "" and " should be in "" escaped with " (i.e. "he said ""hi""")

**Comment by srcejon** [comment]
Have added a patch that should escape double quotes.

The message field is also output with surrounding quotes, so , in message shouldn't cause a problem.
