### ISSUE TITLE
ADS-B Open Notification Dialog

### ISSUE THREAD

**Issue by Comm-on-call** [f4exb/sdrangel#2223]
What is the syntax used to make use of the audio notifications? I am having trouble finding anything more than what is on the wiki. I would like to to use the language and command strings accurately.

**Comment by srcejon** [comment]
All it does it that simple substitutions. What are you hoping for?

**Comment by srcejon** [comment]
That isn't supported currently I'm afriad

**Comment by Comm-on-call** [comment]
That's fine. What "syntax" is used under the "Reg Exp" column? I'm looking for "broad information" not trying to have my hand held necessarily. The wiki image give the impression there is the ability to filter to a certain extent.

**Comment by srcejon** [comment]
Sorry, I misunderstood. I thought you were just referring to the substitutions. Reg Exps are Regular Expressions and should be broadly compatible with Perl syntax.

See: 

https://en.wikipedia.org/wiki/Regular_expression
https://regexr.com/
https://pcre.org/original/doc/html/pcrepattern.html

**Comment by Comm-on-call** [comment]
Fantastic. This was what I looking for. I appreciate it.
