### ISSUE TITLE
Could not found RTLSDR device On linux

### ISSUE THREAD

**Issue by Ledruyde** [f4exb/sdrangel#2236]
Hello 

I running Linux mint 21.3 and Sdrangel on his latest version.

RTLSDR  is missing from the device list. But the dongle has been correctly detected with lsusb command. 

just for clarify

Linux mint 21.3 just updated
SDRAngel version 7.22.0
ran as superuser
tested with gqrx no detected too
tested on other machine runnig windows with no problems

This config run wstjtx with CAT control with no problems.

Hope you have ideas 
Thanks reading and answering

**Comment by srcejon** [comment]
Would recommend not running as superuser.

Make sure you have the rtl-sdr.rules udev rules installed: https://github.com/f4exb/sdrangel-docker/blob/master/udev-rules/rtl-sdr.rules

Check what driver is loaded with 'usb-devices'

Post SDRangel's debug log (Preferences > Logging) when it starts up.
