### ISSUE TITLE
second connection to a kiwisdr not possible - bug or feature?

### ISSUE THREAD

**Issue by df6dbf** [f4exb/sdrangel#2240]
Hello Edouard, I found out that with SDR Angel in the current version I cannot establish two connections to my local kiwisdr. However, due to the limited bandwidth of the kiwisdr in SDR Angel, this would be interesting for monitoring DSC transmissions on different Bands. Is this limitation a bug or intentional by the author?

73s Holger, DF6DBF

**Comment by f4exb** [comment]
There is one instance of the KiwiSDR device plugin per IP and port.
