### ISSUE TITLE
Soapy-version 

### ISSUE THREAD

**Issue by loewal** [f4exb/sdrangel#2241]
Hi, 
Is it possible to also compile a Soapy-ready version that can be run on a Mac Mini M2?

Thank you.

**Comment by Axpelle** [comment]
I would back that totally. It would give us a chance to try the new WDSP plugin.

**Comment by srcejon** [comment]
Unfortunately, I smashed the screen on my M2 Mac.

**Comment by Axpelle** [comment]
😱


——— Original message received from "srcejon" ***@***.***> 
on 28/08/2024 14:32:06 ———
