### ISSUE TITLE
Mac arm64 package?

### ISSUE THREAD

**Issue by bazineta** [f4exb/sdrangel#2247]
The binary asset releases have typically contained a Mac arm64 package, but the current release does not. Am curious if there's something that prevents it.

**Comment by srcejon** [comment]
https://github.com/f4exb/sdrangel/issues/2241#issuecomment-2314941963

**Comment by bazineta** [comment]
Something you're getting fixed, or do you need a volunteer to produce the binary assets?

**Comment by srcejon** [comment]
Well, it really should be set to build as a github action.
