### ISSUE TITLE
ATV modulator no longer available in Windows build

### ISSUE THREAD

**Issue by pa3byv** [f4exb/sdrangel#2248]
Hi, we are still using v6.16 in Windows 10 because it has an ATV modulator. It seems to have disappeared from Windows builds in V7, probably from V6.20 onwards. But I see it is still maintained and available in the Linux builds. Is there a special reason for this and if not could you please include it in the V7 Windows build again? 

Many thanks,
Poll

**Comment by srcejon** [comment]
From the github action log, I see:

 Not building modatv (ENABLE_CHANNELTX_MODATV=ON OpenCV_FOUND=0)

I think this is probably due to the version of OpenCV in sdrangelwindowslibraries not working with the latest version of Visual C. Updating to 4.10 seems to work.

**Comment by pa3byv** [comment]
Thanks for looking into it. Hopefully the ATV module will reappear in the next build then.

**Comment by 0x0V3RF10W** [comment]
Hello! Any plans to return modatv to windows builds?

**Comment by srcejon** [comment]
@f4exb - unfortunately need a small patch to the opencv cmakefiles: https://github.com/f4exb/sdrangel-windows-libraries/pull/26

**Comment by srcejon** [comment]
> Hello! Any plans to return modatv to windows builds?

Hopefully should be in the next release.

**Comment by srcejon** [comment]
Back in 7.22.1

**Comment by pa3byv** [comment]
Thanks very much!On 11 Oct 2024, at 14:38, srcejon ***@***.***> wrote:﻿
Back in 7.22.1
