### ISSUE TITLE
Average Power transmitted increases randomly (HackRF One)

### ISSUE THREAD

**Issue by EmilEmilchen** [f4exb/sdrangel#2251]
The screenshot is pretty self explanatory, I didn't change anything and I couldn't find anything in the logs. This doesn't just show up in the FFT but also when double checking with an other SDR. I tried reinstalling the software, using the flatpak package, using older versions, using the latest realease and using the microphone input as well as using the file input with a prerecorded test file using audacity. The audio doesn't seem to be the problem here. My pulseaudio setup (I'm using KUbuntu 24.04) works just fine and the feedback audio isn't messed up at all either. In other software I don't experience this problem and it shows up in the FFT and the actual outgoing signal which makes me think its not a hardware issue either. I'm really out of ideas here.
![image](https://github.com/user-attachments/assets/9396e0e2-7c39-481e-b5d6-7aad79647489)
This is worse then it looks and completely breaks the signal. Also I think the intensity varies, I could be wrong about that one though.

**Comment by duckyondiscord** [comment]
Same thing happens here on nobara using the flatpak ver
