### ISSUE TITLE
RTLSDR not found on Win10x64, other SDR apps find it no problem

### ISSUE THREAD

**Issue by veronica-g** [f4exb/sdrangel#2255]
Happy to share logs etc. 
Troubleshooting steps: I tried running as admin, and obviously rebooting. 
SDR++ and SDRSharp both see the dongle and work fine. 
SDRAngel does not even list it as an option. 
Dongle is NESDR Smart, also tried NESDR SMartee with the same result.
Machine is an i7 7k w/16GB RAM

Thank you!

**Comment by srcejon** [comment]
Please attach logs (Preferences > Logging menu) and also attach a screenshot
