### ISSUE TITLE
Momentary Tx when changing Tx

### ISSUE THREAD

**Issue by KC7NOA** [f4exb/sdrangel#226]
Momentary Tx when changing frequency on freq panel.

I don’t know if this is a problem with SoapySdr or the SDR program i’m using … or Lime’s drivers for Linux …

I use LimeSDR-usb on Ubuntu 18.04 with SdrAngel and when ever i change frequencies with the Tx playing and mute on (the icon with the -120DB) showing … i get a momentary Tx of signal … i have not
used FM and no other mode …

Just wondering if any other FM SSB AM sdr programs show the same issue …

**Comment by KC7NOA** [comment]
Lime people gave this as a posibility

https://discourse.myriadrf.org/t/momentary-tx-when-changing-frequencies/3488

**Comment by f4exb** [comment]
Can you please describe in detail what you are trying to do? I cannot reproduce the issue with a simple scenario.

**Comment by f4exb** [comment]
This is my FM modulator setup on Tx side with the Lime Mini:
![image](https://user-images.githubusercontent.com/6192319/47612303-5d3cda80-da78-11e8-839a-375010dbe6a6.png)
And the settings for the Lime mini itself:
![image](https://user-images.githubusercontent.com/6192319/47612331-cd4b6080-da78-11e8-9e92-8c1adbac0b8d.png)
I have a RTL-SDR listening on the Rx side:
![image](https://user-images.githubusercontent.com/6192319/47612345-0b488480-da79-11e8-9e47-bbebeaf0c6bb.png)
And when I move center frequency from 435000 kHz to 435010 and back this is what I see in the Rx waterfall:
![image](https://user-images.githubusercontent.com/6192319/47612368-8ad65380-da79-11e8-9a1a-15cc454dd996.png)
Wideband is OK too:
![image](https://user-images.githubusercontent.com/6192319/47612430-9d04c180-da7a-11e8-8524-1a002834868a.png)

So... no issues.
