### ISSUE TITLE
Is it possible to record squelched audio

### ISSUE THREAD

**Issue by gervaila** [f4exb/sdrangel#2260]
What I'm doing is using the frequency scanner to scan some air bands.
After that I use AM demodulator to listen to it.
I found the way to record the output in settings audio.
Is there a way to record the audio but with the squelch feature.
So by the end of my session I can listen to a "recap" of what happenend but without the blanks ?
Like the file sink actually.

**Comment by srcejon** [comment]
Preferences > Audio and use the dial to the right, I think:

![image](https://github.com/user-attachments/assets/83ada989-c28b-47d5-a642-b80d00cb3fed)
