### ISSUE TITLE
SDRAngel for Windows missing hackrfoutput.dll

### ISSUE THREAD

**Issue by DerrickLau** [f4exb/sdrangel#2265]
I am looking for the hackrfoutput.dll, the plugin for transmitting using the HackRF One on Windows, but cannot find it.  How do I build it?  Is there a way I can just grab the dll off of github?

![image](https://github.com/user-attachments/assets/643b058d-9b67-4b4c-85ce-840bb581a235)

**Comment by gvanem** [comment]
I think you mean `<ROOT>/plugins/outputhackrf.dll`. It's part of the official install.
Built via `<ROOT>/plugins/samplesink/hackrfoutput/CMakeLists.txt`.

**Comment by DerrickLau** [comment]
TNX.  Sorry found the dll now.  Do something else is not getting my voice to the HackRF One...
