### ISSUE TITLE
7.22.1 issue -modssb

### ISSUE THREAD

**Issue by DB-Billy** [f4exb/sdrangel#2273]
modssb not working w64

**Comment by srcejon** [comment]
Can you be more specific please (including screenshots)? Very quick check here and it looks ok.

**Comment by DB-Billy** [comment]
![Στιγμιότυπο οθόνης (93)](https://github.com/user-attachments/assets/a55da826-81b5-45fd-8450-dcdb8196444c)
this 2 bars not working at all remain left

**Comment by srcejon** [comment]
Ok, I can reproduce that.

**Comment by f4exb** [comment]
`SSBModGUI::on_spanLog2_valueChanged` is missing from `SSBModGUI::makeUIConnections` therefore the allowed span remains at 0 and other buttons cannot be moved.

**Comment by DB-Billy** [comment]
thank u for all 73
