### ISSUE TITLE
DAB Demodulator Samplerate Error?

### ISSUE THREAD

**Issue by Highspeedy** [f4exb/sdrangel#2275]
Hello, 

the DAB Demodulator module didn´t work with my RTL-SDR Stick V3 and shows a sample alert.
It needs samplerates of minimum 2.048 MSample/s.
I think programsettings will be o.k. (see the added picture).

Is it a bug or a wrong setting by myself?

Thanks.

![Screenshot 2024-10-11 084157](https://github.com/user-attachments/assets/49fcb673-6c78-48ea-8ed7-8af1d2526470)

**Comment by srcejon** [comment]
You have DEC (Decimation) set to 64. So the baseband sample rate will be 2048000/64= 32000 S/s.

Try with DEC set to 1.
