### ISSUE TITLE
Latest Android APK Availability?

### ISSUE THREAD

**Issue by WB0OCV** [f4exb/sdrangel#2280]
I have a Samsung Galaxy S22+ running Android 14.  The latest version of SDRangel in the Google Play Store is v7.21.3.1 dated 20-Jun-2024.  I checked the releases page, and the last Android APK shown is v7.21.4 dated 29-Jun-2024.  The descriptions of changes and fixes for v7.22.0 and v7.22.1 both mention Android fixes, but there are no APKs listed for either of these newer releases.
As an aside, I downloaded v7.21.4 and attempted a forced install over v7.21.3, but received an error.  I uninstalled v7.21.3 and was able to reinstall v7.21.4, and it functions properly, but when I check the version in the Apps info page, it indicates a version number of 7.21.3.1 even though I had installed v7.21.4.
How do I obtain Android APK for the latest v7.22.1?  Thank you.
Ken -- WBØOCV

**Comment by srcejon** [comment]
> How do I obtain Android APK for the latest v7.22.1

It doesn't exist at the moment.
