### ISSUE TITLE
ChripChat Demodulator für LORA

### ISSUE THREAD

**Issue by Hackrfan** [f4exb/sdrangel#2284]
Hello to all,
is it possible to increase the “Pre” in the ChripChat Demodulator Plugin for LORA from currently 20 to max 32 ?
I would need this for MESHCOM 4 decoding.
Please give me some info
Thanks to all 
Georg DC8GY

**Comment by f4exb** [comment]
Yes... Note that with the REST API there is no control on the limit so it is always possible to go this way.
