### ISSUE TITLE
Frequency (and other settings) are not set correctly with Pluto SDR on Mac

### ISSUE THREAD

**Issue by RolfNoot** [f4exb/sdrangel#2286]
Hi!

When starting SDRangel on MacOS, I am not able to change frequency (and possibly other settings) of the SDR radio. When starting another SDR program along (for example Gqrx) and I use this to change frequency, it will update the radio correctly.

Any ideas how I can see the settings data to update from mac to Pluto?

Version: 7.22.0
MacOS: Sonoma and Monterey (both same issue)
Pluto SDR fw: v0.39

**Comment by srcejon** [comment]
Please can you let us know if this is still a problem with the latest version, as a few fixes have been made, that may help.

**Comment by RolfNoot** [comment]
Just tested it, it seems okay now 🥳

**Comment by srcejon** [comment]
Great
