### ISSUE TITLE
PlutoSDR plugin and FIR decimation

### ISSUE THREAD

**Issue by dm6tt** [f4exb/sdrangel#2308]
Hi Edouard,
I'm playing around with the PlutoSDR plugin on 7.22.0 an have a question about the FIR decimation.
When enabling the FIR and setting the decimation to 4 I do not encounter a reduction of the ethernet bandwidth on that interface. It stays constant.

Referring to the RX Signal Path section in [https://wiki.analog.com/resources/tools-software/linux-drivers/iio-transceiver/ad9361](url) the FIR decimation factor can be querried on cli with:
`pluto:/sys/bus/iio/devices/iio:device0]# cat rx_path_rates`

Example:
Wit disabled FIR:
![grafik](https://github.com/user-attachments/assets/7853c9da-abc0-40bd-bc91-42479eea10d4)

Leads to: 
`[pluto:/sys/bus/iio/devices/iio:device0]# cat rx_path_rates`
`BBPLL:953601026 ADC:29800032 R2:9933344 R1:4966672 RF:2483336 RXSAMP:2483336`

With enabled FIR:
![grafik](https://github.com/user-attachments/assets/7ecb6746-2895-4c96-8df9-5018c31d45fc)

Leads to:[pluto:/sys/bus/iio/devices/iio:device0]# cat in_voltage_sampling_frequency
2483336

`[pluto:/sys/bus/iio/devices/iio:device0]# cat rx_path_rates`
`BBPLL:1271468041 ADC:79466752 R2:39733376 R1:19866688 RF:9933344 RXSAMP:2483336`

In both cases the sampling frequency shows the same value:
`[pluto:/sys/bus/iio/devices/iio:device0]# cat in_voltage_sampling_frequency`
`2483336`

I would have expected that the Baseband sampling rate would be decreased with the FIR decimation.

Thanks
Marcus, DM6TT

**Comment by f4exb** [comment]
That's the AD chip business not SDRangel's. In fact the baseband rate stays constant but the actual sampling frequency of the ADC is 4 times higher with a decimation of 4. It shows in the top left corner number below the start/stop button. This displays the actual ADC rate. See: https://github.com/f4exb/sdrangel/tree/master/plugins/samplesource/plutosdrinput#14-adc-sample-rate

**Comment by f4exb** [comment]
This is actually explained in the link to the AD documentation you gave. In this table:
![image](https://github.com/user-attachments/assets/0fbacc51-9af1-4234-8b21-ce64239a08d1)
The HW decimation control only controls the decimation of the FIR filter so RF/ RXSAMP and effectively they are the same with a factor of 1: `RF:2483336 RXSAMP:2483336` and RF is 4 times RXSAMP when HW decimation is 4: `RF:9933344 RXSAMP:2483336` The rest of the chain is not controlled by the user.

**Comment by f4exb** [comment]
Note that if the ethernet bandwidth is your concern you may use software decimation.
