### ISSUE TITLE
Unable to play .wav file generated from Demod Analyzer

### ISSUE THREAD

**Issue by mjanicki** [f4exb/sdrangel#2309]
Recorded .wav file from NFMDemod and saved as a ...wav file.
Unfortunately, unable to play back the file.
Using macOS Ventura 13.7.1, SDRangel 7.22.2
Tried playback using iMusic and Elmedia player. 
Looking to record the audio, not the IQ information.

**Comment by srcejon** [comment]
Looks like the sample rate is sometimes written as 0.
