### ISSUE TITLE
7.22.3 crashes in Mac OS Sequoia 15.1

### ISSUE THREAD

**Issue by Axpelle** [f4exb/sdrangel#2317]
Using Airspy Mini in frequency scanner mode, when the start/stop scanner button is pressed and then the Start/Stop Acquisition is pressed SDRAngel crashes. I'm using a Mac mini M2. Receiver is WDSP.

**Comment by srcejon** [comment]
Can you post a picture of your settings please

**Comment by Axpelle** [comment]
> Can you post a picture of your settings please

Screenshots of settings as requested. In fact SDRa crashes as soon as I hit the "start acquisition" button.
[Settings 1.pdf](https://github.com/user-attachments/files/17694333/Settings.1.pdf)
[Settings 2.pdf](https://github.com/user-attachments/files/17694335/Settings.2.pdf)
[Settings 3.pdf](https://github.com/user-attachments/files/17694336/Settings.3.pdf)

**Comment by Axpelle** [comment]
And I add that SDRa 7.22.2 for Intel (running on Rosetta) does not crash when I hit the "start acquisition" button.

**Comment by srcejon** [comment]
Closing in favour of the other issue
