### ISSUE TITLE
Pager Demodulator new features match on message instead of alpha

### ISSUE THREAD

**Issue by doftheworld** [f4exb/sdrangel#2319]
The new features which add the ability to add notifications and filtering match using the "message" column instead of "alpha". The message column displays the raw data received before it is decoded and the actual decoded message is visible in the "alpha" column.

**Comment by doftheworld** [comment]
Closed and reposted under feature thread

**Comment by srcejon** [comment]
Done. 

Note: not sure what you meant by "feature thread", but it's easier to track if a separate issue like this.
