### ISSUE TITLE
Consistent crash when loading a different device set preset

### ISSUE THREAD

**Issue by murrayn** [f4exb/sdrangel#2332]
The crash happens reliably when loading a new device set preset while the SDR is running. If the SDR is stopped before loading a device set preset the crash does not occur.

sdrangel_7.22.4_ubuntu-22.04

Here is an example trace: [sdrangel-log.txt](https://github.com/user-attachments/files/17772017/sdrangel-log.txt)

**Comment by srcejon** [comment]
Can you attach the preset as well please?

**Comment by murrayn** [comment]
It's not dependent on any particular preset. It's also been an issue for me for a long time, just never got around to reporting it. I just work around it by stopping the SDR before switching presets. It could be my hardware, an old V3 rtl-sdr. I just thought the trace might give some clue, although I didn't see anything that stood out to me.

**Comment by f4exb** [comment]
Is this an issue to stop the device before loading a new preset?

**Comment by srcejon** [comment]
Crash appears to be in DSPDeviceSourceEngine::handleMessage for a DSPSignalNotification - the list of m_basebandSampleSinks is no longer valid. 

> Is this an issue to stop the device before loading a new preset?

For this and #2315, it might be simpler if we just stop the device first.
