### ISSUE TITLE
Excessive decimal places reported to SondeHub

### ISSUE THREAD

**Issue by smithse** [f4exb/sdrangel#2337]
Hi @f4exb, 

I am not using SDRAngel, but noticed that the radiosonde plugin is reporting an excessive number of decimal places to the SondeHub API. Attached a screenshot for your reference.

![Screenshot 2024-11-18 at 08 39 00](https://github.com/user-attachments/assets/471013f0-dd4b-4080-8253-f0852b7ee0fd)

**Comment by darksidelemm** [comment]
Just as some comparisons:

sdrangel:
{"alt":21406.02734375,"batt":2.5,"datetime":"2024-11-18T00:47:08.001000Z","frame":8448,"frequency":401.5,"heading":314.79605799491327,"humidity":1.7817134857177734,"lat":-32.28943926347931,"lon":116.28312367601,"manufacturer":"Vaisala","sats":10,"serial":"W1310116","software_name":"SDRangel","software_version":"7.21.4","subtype":"RS41-SG","temp":-60.89262771606445,"time_received":"2024-11-18T00:46:51.842000Z","type":"RS41","uploader_callsign":"C0","uploader_position":"-32.130001068115234,116","vel_h":2.940194761105341,"vel_v":4.5699731691519485,"user-agent":"Amazon CloudFront","position":"-32.28943926347931,116.28312367601","uploader_alt":30}

auto_rx:
{"software_name":"radiosonde_auto_rx","software_version":"1.7.4","uploader_callsign":"I1OAB","uploader_position":"-31.829007403523928,115.87914026136872","uploader_antenna":"Home Made 1/4 Wave Ground Plane","time_received":"2024-11-18T00:46:52.187614Z","datetime":"2024-11-18T00:47:08.001000Z","manufacturer":"Vaisala","type":"RS41","serial":"W1310116","subtype":"RS41-SG","frame":8448,"lat":-32.28944,"lon":116.28313,"alt":21405.98112,"temp":-60.9,"humidity":1.6,"vel_v":4.56997,"vel_h":2.9402,"heading":314.79605,"sats":10,"batt":2.5,"frequency":401.502,"burst_timer":65535,"ref_position":"GPS","ref_datetime":"GPS","rs41_mainboard":"RSM412","rs41_mainboard_fw":"20215","snr":21.6,"tx_frequency":401.5,"user-agent":"Amazon CloudFront","position":"-32.28944,116.28313","upload_time_delta":-1.321,"uploader_alt":50}

I'd probably suggest the following number of decimal places when uploading telemetry (happy to take comment on this - I need to modify auto_rx as well):

- Latitude / Longitude: 5
- Altitude: 1 (auto_rx also needs to be modified here)
- vel_h, vel_v: 2 (auto_rx also needs to be modified here)
- Heading: 1 (auto_rx also needs to be modified here)
- Temperature: 1
- Humidity: 1
- Pressure: 2
- Battery voltage: 1
