### ISSUE TITLE
The microphone has no sound (with sound feedback turned on) when using SSB modulation

### ISSUE THREAD

**Issue by RealCommonCat** [f4exb/sdrangel#2348]
The microphone works fine when WFM is used, but there is no sound when SSB is used (with sound feedback turned on).
At the same time the sound signal is not transmitted but the" tone modulation "is normal

![image](https://github.com/user-attachments/assets/03b1e9c6-09be-4c00-815d-bc1a47531796)
![image](https://github.com/user-attachments/assets/244a06cb-d06b-4b43-834a-578468d2210a)
![image](https://github.com/user-attachments/assets/1e2db13f-65ee-4c1a-be4a-24673599f99b)

I also found that the older version (7.15.4) does not have this problem

**Comment by srcejon** [comment]
Duplicate of https://github.com/f4exb/sdrangel/issues/2336

**Comment by RealCommonCat** [comment]
OK
