### ISSUE TITLE
LimeSDR gpio 

### ISSUE THREAD

**Issue by KC7NOA** [f4exb/sdrangel#235]
This is a support request for LimeSDR support for gpio through the fpga for transmit and possible band pass selection on J19 ( i think )

**Comment by f4exb** [comment]
Alternatively you can use the command feature: https://github.com/f4exb/sdrangel/blob/master/sdrgui/readme.md#5b-commands

This way you can do whatever you like in a Python script for example to command the LimeSDR GPIO or any device that can be controlled programmatically. This makes the GPIO control from the plugin interface within SDRangel not so interesting. Moreover the script invocation can be linked to any key or key combination which makes PTT easy to implement. There is such PTT script example here: https://github.com/f4exb/sdrangel/blob/master/swagger/sdrangel/examples/ptt.py

**Comment by KC7NOA** [comment]
Ok ... im glad that your looking into this ...

The Rf detection circuit of my PA that i use with my LimeSDR takes half the power generated to trip the relays ...

**Comment by f4exb** [comment]
Implemented in v4.3.1
