### ISSUE TITLE
suggestion: Channels dock to window

### ISSUE THREAD

**Issue by sgoudelis** [f4exb/sdrangel#240]
I think for people that use more than on monitors (like me) it would be fantastic if the channel window/view would actually pop out and became an independent window that would be fit in another monitor, and not disappear when the SDRAngel app looses focus as it is now.

**Comment by f4exb** [comment]
This all depends on Qt. I am not sure this is feasible.

**Comment by sgoudelis** [comment]
Yes that is the main issue. Also it would be nice if it was an actual window that is managed by the window manager.

**Comment by f4exb** [comment]
I don't think this is possible. All docking widgets belong to the main window. Nothing prevents you from working on another application on the top of the main window though.
