### ISSUE TITLE
Slow down the waterfall.

### ISSUE THREAD

**Issue by bdn76** [f4exb/sdrangel#244]
How i can slow down the waterfall? Most SDR software have nice feature for slowing down waterfall without decimation. This is useful for monitoring rare signals.

**Comment by f4exb** [comment]
Please read documentation. Most SDR software do not have the "max" option that truly allows seeing bursts:
https://github.com/f4exb/sdrangel/blob/master/sdrgui/readme.md#45-averaging-mode

**Comment by bdn76** [comment]
Thank you.
