### ISSUE TITLE
Problems with audio

### ISSUE THREAD

**Issue by sh123** [f4exb/sdrangel#247]
Debian, pulse audio, alsa_output*analog-stereo is selected in sdrangel Audio Output. DSD RX - no audio, NFM/WFM - audio works, SSB - audio works but after toggling AGC stops working.

**Comment by sh123** [comment]
> See my comments in #231 this is probably something similar

Tried various suggestions from this thread, but could not get SSB work reliably, DSD plugin works, but no audio. Note, that all works fine on windows builds.

**Comment by f4exb** [comment]
No idea

**Comment by nukedclx** [comment]
i have idea, maybe its because RAS in use

**Comment by sh123** [comment]
It started working after some time, not sure what was the problem. Either pulse was buggy and started working after distro upgrade or got fixed in sdrangel.
