### ISSUE TITLE
Groups arrangement

### ISSUE THREAD

**Issue by i-am-tof** [f4exb/sdrangel#250]
Hello

Each time a preset is created or modified, all groups become developed.
It would be great to keep groups state as it was set.
I noticed that sdrangel takes a little time to refresh that list when doing so. Perhaps modifying that could cut this tiny delay.

**Comment by f4exb** [comment]
If the list is long then it takes some time to re-arrange everything. Not sure it is possible to optimize this as it depends very much on the underlying structures managed by Qt. 

There is a sorting order by group then frequency that helps finding things out. I am not planning to change that nor to spend time in the collapse/expand thing.

**Comment by f4exb** [comment]
No changes planned,
