### ISSUE TITLE
Pluto support for MSVC 2017 build

### ISSUE THREAD

**Issue by lucapgt** [f4exb/sdrangel#254]
Hi, when you release a new version with pluto support? old version works with pluto, why is not supported in new release? thanks

**Comment by f4exb** [comment]
I thought this was clear in the release notes. I supposed you're talking about the MSVC 2017 version.

**Comment by lucapgt** [comment]
Hi, i try minGW version but pluto is not listes. With the previous version works fine. I use windows 10 pro 64bit.

**Comment by f4exb** [comment]
Implemented in v4.3.1
