### ISSUE TITLE
Replace the XPM by a PNG or SVG icon

### ISSUE THREAD

**Issue by probonopd** [f4exb/sdrangel#259]
https://github.com/f4exb/sdrangel/blob/95f39109f757a2640f949305ecb33c82d3cfa0c3/desktop/sdrangel.desktop#L6

Please replace the XPM by a PNG or SVG, since XPM is really considered outdated by now.

**Comment by probonopd** [comment]
https://standards.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html states:

> XPM is supported due to backwards compability reasons, and it is not recommended that new themes use XPM files. Support for SVGs is optional.

**Comment by f4exb** [comment]
PR please. I will now not only encourage but demand collaboration on this project.

**Comment by f4exb** [comment]
Done in v4.3.2
