### ISSUE TITLE
Channel Analyzer: fix rational downsampler

### ISSUE THREAD

**Issue by f4exb** [f4exb/sdrangel#262]
1. When the downsampler is engaged the signal is altered. A sign is that the triggering is altered
2. The sample rate sent to the scope widget is not correct when the input (baseband) rate is altered. This is described in #251

**Comment by GkvJeep** [comment]
The problem disappears, at the first event from change "lowpass filter cut-off frequency".

**Comment by f4exb** [comment]
That's for number 2. True that 1 and 2 are not exactly related. After some trial and error it seems that the interpolator problem (1) lies in the use of SSE2 based code. With modern compilers it might not be needed anyway.

**Comment by GkvJeep** [comment]
I do not see anything suspicious, given that the sampling rate is changed 10 times.

Sample 1.28 M/S 
![128](https://user-images.githubusercontent.com/34664260/49702136-2b399f00-fc06-11e8-815d-dbd81853f592.png)

Sample 10.24 M/S 
![1024](https://user-images.githubusercontent.com/34664260/49702151-4dcbb800-fc06-11e8-969f-3ec031b06606.png)

**Comment by f4exb** [comment]
for point no 2 it seems the down channelizer rate change is forwarded from the input object to scope and spectrum GUIs while it is also done from the GUI. Both messages conflict and only the one sent from the GUI should be considered as it handles possible rational resampling.

**Comment by GkvJeep** [comment]
I do not observe such an effect.
Baseband is at 2.56 MS/s without rational downsampling:
![resoff](https://user-images.githubusercontent.com/34664260/49705849-9f8a3780-fc32-11e8-83ff-2d9abc30ce24.png)

Rational downsampling at 1.194 MS/s (factor 2.143):
![reson](https://user-images.githubusercontent.com/34664260/49705850-a44eeb80-fc32-11e8-9b60-f66bb70ab07c.png)

**Comment by GkvJeep** [comment]
I do not understand, why limit to 1.996 (1.0/0.501)
Example. 
Joseph D. Gaeddert
http://liquidsdr.org/doc/msresamp/
Rational downsampling at 8.547 or (1.0/0.117f)
![filter_msresamp_crcf_freq](https://user-images.githubusercontent.com/34664260/49748284-511e7c80-fcb6-11e8-8547-8f6ed8bd4a0d.png)

**Comment by GkvJeep** [comment]
I do not understand why limit to 1.996 (1.0/0.501)
Example
Joseph D. Gaeddert
http://liquidsdr.org/doc/msresamp2/
decimate by 2^4=16
![msresamp2_crcf_freq](https://user-images.githubusercontent.com/34664260/49749174-aa87ab00-fcb8-11e8-81db-208c4687755c.png)

**Comment by f4exb** [comment]
The present code for the rational resampler in SDRangel that I have not written myself works like that. Take it as a given. Of course it can be replaced by the Liquid SDR one bit this is not something to be taken lightly. For the moment you should be able to obtain any sampling rate using half band decimators and rational resampler for the last half.

**Comment by GkvJeep** [comment]
I agree, read the documentation!  ;-))
Russians have an expression ... 
"Who pays for a girl in a restaurant, he uses it."
Distracted. ((-;
What prevents in the plugin to immediately make a complete decimation, without any additional switching.

**Comment by f4exb** [comment]
The channelizer should be configured from the GUI to do just that. Maybe this does not work as expected.

**Comment by f4exb** [comment]
Fixed in v4.3.2
