### ISSUE TITLE
Randomise colour of duplicate demodulators

### ISSUE THREAD

**Issue by troffasky** [f4exb/sdrangel#275]
When adding an additional demodulator of the same type, the colour [or maybe just saturation] should be randomised to make it clearer which one is which.

**Comment by f4exb** [comment]
You can change the colour yourself. Right clicking on the little grey square on the top left corner of the demodulator window will open a dialog to let you do so.

So no point in changing anything here.

**Comment by troffasky** [comment]
Yes, I am aware that I can change the colour manually. The reason for this feature request is that I believe usability would be improved [faster workflow] if the colours of demodulators could be automatically disambiguated.

**Comment by f4exb** [comment]
It is a matter of taste and I don't think so. The color is related to the type of demodulator.

**Comment by f4exb** [comment]
Note that this could be scripted externally using the REST API.
