### ISSUE TITLE
v4.3.2 windows 10 - sample device list visualization problem

### ISSUE THREAD

**Issue by lucapgt** [f4exb/sdrangel#276]
Hi, sdrangel v4.3.2 on windows 10 on some PC have a visualization problem.  On "select sampling device" box, you can see text "select from list" but dropdown menu is missing.

**Comment by f4exb** [comment]
Isn't it related to very large displays as it has been mentioned before? Can you please detail the "some PC"?

**Comment by lucapgt** [comment]
high resolution display for sure. I can't find the issue related to very large displays

**Comment by f4exb** [comment]
This one: #103

**Comment by lucapgt** [comment]
ok. Now I confirm, solved with "override high DPI scaling behaviour" option. Thanks
