### ISSUE TITLE
SoapySDR -windows10- sdrangel 4.4.1

### ISSUE THREAD

**Issue by lucapgt** [f4exb/sdrangel#280]
Hi, how i can select soapySDR source frome list? Is not present. The plugin on sdrandel is listed.
I use soapySDR server directly loaded into the plutosdr. 
Thakns

**Comment by f4exb** [comment]
You have to install SoapySDR separately to get hardware support.

**Comment by lucapgt** [comment]
I've installed soapySDR on windows 10. SoapySDR is installed and running on PlutoSdr, connected on usb port. I can't see soapySDR source on Sdr Angel. What is the mistake?
