### ISSUE TITLE
Failure compiling target inputairspyhf

### ISSUE THREAD

**Issue by unixpunk** [f4exb/sdrangel#281]
Hi!  Been a while!  Ubuntu 16.04.5 LTS, cmake version 3.5.1.

I've started with fresh pull of sdrangel and a clean build directory.  I've also started fresh with your fork of airspyhf as noted in your wiki, which compiles just fine.  Any advice is appreciated!

Scanning dependencies of target inputairspyhf
[ 59%] Building CXX object plugins/samplesource/airspyhf/CMakeFiles/inputairspyhf.dir/airspyhfgui.cpp.o
[ 59%] Building CXX object plugins/samplesource/airspyhf/CMakeFiles/inputairspyhf.dir/airspyhfinput.cpp.o
/home/steve/Desktop/SDR/sdrangel/plugins/samplesource/airspyhf/airspyhfinput.cpp: In member function ‘bool AirspyHFInput::applySettings(const AirspyHFSettings&, bool)’:
/home/steve/Desktop/SDR/sdrangel/plugins/samplesource/airspyhf/airspyhfinput.cpp:523:87: error: ‘airspyhf_set_hf_agc’ was not declared in this scope
             rc = (airspyhf_error) airspyhf_set_hf_agc(m_dev, settings.m_useAGC ? 1 : 0);
                                                                                       ^
/home/steve/Desktop/SDR/sdrangel/plugins/samplesource/airspyhf/airspyhfinput.cpp:539:98: error: ‘airspyhf_set_hf_agc_threshold’ was not declared in this scope
         rc = (airspyhf_error) airspyhf_set_hf_agc_threshold(m_dev, settings.m_agcHigh ? 1 : 0);
                                                                                              ^
/home/steve/Desktop/SDR/sdrangel/plugins/samplesource/airspyhf/airspyhfinput.cpp:555:88: error: ‘airspyhf_set_lib_dsp’ was not declared in this scope
             rc = (airspyhf_error) airspyhf_set_lib_dsp(m_dev, settings.m_useDSP ? 1 : 0);
                                                                                        ^
/home/steve/Desktop/SDR/sdrangel/plugins/samplesource/airspyhf/airspyhfinput.cpp:571:87: error: ‘airspyhf_set_hf_lna’ was not declared in this scope
             rc = (airspyhf_error) airspyhf_set_hf_lna(m_dev, settings.m_useLNA ? 1 : 0);
                                                                                       ^
/home/steve/Desktop/SDR/sdrangel/plugins/samplesource/airspyhf/airspyhfinput.cpp:587:88: error: ‘airspyhf_set_hf_att’ was not declared in this scope
             rc = (airspyhf_error) airspyhf_set_hf_att(m_dev, settings.m_attenuatorSteps);
                                                                                        ^
plugins/samplesource/airspyhf/CMakeFiles/inputairspyhf.dir/build.make:90: recipe for target 'plugins/samplesource/airspyhf/CMakeFiles/inputairspyhf.dir/airspyhfinput.cpp.o' failed
make[2]: *** [plugins/samplesource/airspyhf/CMakeFiles/inputairspyhf.dir/airspyhfinput.cpp.o] Error 1
CMakeFiles/Makefile2:3454: recipe for target 'plugins/samplesource/airspyhf/CMakeFiles/inputairspyhf.dir/all' failed
make[1]: *** [plugins/samplesource/airspyhf/CMakeFiles/inputairspyhf.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by unixpunk** [comment]
When using the original airspyhf, I get the exact same as well, which is not what I'd expect.

**Comment by f4exb** [comment]
This should work with the latest version of the original airspyhf. BTW this is the one you should use so the Wiki may be wrong.

**Comment by f4exb** [comment]
Right. Corrected.
