### ISSUE TITLE
XTRX support in Windows

### ISSUE THREAD

**Issue by DG9BFC** [f4exb/sdrangel#282]
just installed the win drivers ... that was tricky but finally it worked
so ... xtrx found in device manager ...
but it is not found in sdrangel ...
need some help to get it working

**Comment by DG9BFC** [comment]
hnmm i do not know how to do that ... i am just a user ... not a programmer
i thought it would work similar to pluto or lime (install drivers and start soft)
if drivers installed and soft supports the hardware it should work that way
why is it not working?
i have no idea how to compile a windows soft ... even installing of the windows drivers was a bit tricky (but i finally found out how to do it) ...
maybe you can help me on that?? ...
sdrangel is the first and only workable sdrsoftware that has the xtrx ... otherwise i have a nice but expensive letterweight for 350 euros

**Comment by DG9BFC** [comment]
i found and xtrx/sdrangel fork .... but that stops at version 385 (no version 4 or higher) so that was also a dead end street :-(

**Comment by f4exb** [comment]
I am not responsible of this blame the XTRX guys

**Comment by DG9BFC** [comment]
that is what i found in xtrx-sdr/images:

Is Windows driver support planned?

We plan to add Windows PCIe drivers but we don't have specific schedule for this right now. If it's blocking factor please contact us xtrx@fairwaves.co. However, all other software layers are windows compatible and USB3380 adapter should work via WinUSB.

**Comment by f4exb** [comment]
It's been some time since the last time I visited XTRX Github repo. This was posted 18 days ago: https://github.com/xtrx-sdr/images/tree/master/binaries/Windows/x64

Maybe it can work. No guarantee but I can have a try

**Comment by f4exb** [comment]
OK let's keep it open maybe forever...

**Comment by DG9BFC** [comment]
hopefully not forever .... i did install the drivers fro here
https://github.com/xtrx-sdr/images/tree/master/binaries/Windows/driver_usb3380
..... i do not know if that were the correct ones but now the xtrx is found in the devices manager
... i also downloaded the drivers from the x64 folder (but have no idea how to intall them) ... would be nice if you could help me on that cause i guess the fairwaves guys can not help me with getting your software to work with the xtrx (or is it still a driver fault?!?)

**Comment by f4exb** [comment]
This may never happen. Dropped.
