### ISSUE TITLE
Help! I need a simple instructional

### ISSUE THREAD

**Issue by DRTAC7** [f4exb/sdrangel#286]
Can someone reply with a simple step-by-step instructional on how to install SDRAngel on Ubuntu 16.04 LTS? I have tried to cmake install and evrything but I cannot figure out how to do this correctly.

**Comment by DRTAC7** [comment]
I just need to know what commands to enter in what order.

**Comment by f4exb** [comment]
This would be better answered at:
https://groups.io/g/sdrangel

If you are into cmake it means you will want to build from source:
https://github.com/f4exb/sdrangel/wiki/Compile-from-source-in-Linux

Then to start up:
https://github.com/f4exb/sdrangel/wiki/Quick-start

**Comment by f4exb** [comment]
Posted in https://groups.io/g/sdrangel/topic/i_need_simple_instructions/29685375?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,29685375
