### ISSUE TITLE
remotesink.cpp not build debian9

### ISSUE THREAD

**Issue by Red-Owl** [f4exb/sdrangel#289]
Building CXX object plugins/channelrx/remotesink/CMakeFiles/remotesink.dir/remotesink.cpp.o
In file included from /usr/local/include/cm256cc/cm256.h:36,
                 from /home/gufo/Scrivania/sdrangel/plugins/channelrx/remotesink/../remotesink/remotesinkthread.h:31,
                 from /home/gufo/Scrivania/sdrangel/plugins/channelrx/remotesink/remotesink.cpp:42:
/usr/local/include/cm256cc/gf256.h:127:19: error: variable ‘CM256CC_API gf256_ctx’ has initializer but incomplete type
 class CM256CC_API gf256_ctx // 141,072 bytes
                   ^~~~~~~~~
/usr/local/include/cm256cc/gf256.h:129:1: error: expected primary-expression before ‘public’
 public:
 ^~~~~~
/usr/local/include/cm256cc/gf256.h:129:1: error: expected ‘}’ before ‘public’
/usr/local/include/cm256cc/gf256.h:128:1: note: to match this ‘{’
 {
 ^
/usr/local/include/cm256cc/gf256.h:129:1: error: expected ‘,’ or ‘;’ before ‘public’
 public:
 ^~~~~~
/usr/local/include/cm256cc/gf256.h:131:15: error: expected class-name before ‘(’ token
     ~gf256_ctx();
               ^
/usr/local/include/cm256cc/gf256.h:133:26: error: non-member function ‘bool isInitialized()’ cannot have cv-qualifier
     bool isInitialized() const { return initialized; }
                          ^~~~~
/usr/local/include/cm256cc/gf256.h: In function ‘bool isInitialized()’:
/usr/local/include/cm256cc/gf256.h:133:41: error: ‘initialized’ was not declared in this scope
     bool isInitialized() const { return initialized; }
                                         ^~~~~~~~~~~
/usr/local/include/cm256cc/gf256.h:133:41: note: suggested alternative: ‘isInitialized’
     bool isInitialized() const { return initialized; }
                                         ^~~~~~~~~~~
                                         isInitialized
In file included from /usr/local/include/cm256cc/cm256.h:36,
                 from /home/gufo/Scrivania/sdrangel/plugins/channelrx/remotesink/../remotesink/remotesinkthread.h:31,
                 from /home/gufo/Scrivania/sdrangel/plugins/channelrx/remotesink/remotesink.cpp:42:
/usr/local/include/cm256cc/gf256.h: In function ‘uint8_t gf256_mul(uint8_t, uint8_t)’:
/usr/local/include/cm256cc/gf256.h:154:16: error: ‘GF256_MUL_TABLE’ was not declared in this scope
         return GF256_MUL_TABLE[((unsigned)y << 8) + x];
                ^~~~~~~~~~~~~~~
/usr/local/include/cm256cc/gf256.h: In function ‘uint8_t gf256_div(uint8_t, uint8_t)’:
/usr/local/include/cm256cc/gf256.h:161:16: error: ‘GF256_DIV_TABLE’ was not declared in this scope
         return GF256_DIV_TABLE[((unsigned)y << 8) + x];
                ^~~~~~~~~~~~~~~
/usr/local/include/cm256cc/gf256.h: In function ‘uint8_t gf256_inv(uint8_t)’:
/usr/local/include/cm256cc/gf256.h:167:16: error: ‘GF256_INV_TABLE’ was not declared in this scope
         return GF256_INV_TABLE[x];
                ^~~~~~~~~~~~~~~
/usr/local/include/cm256cc/gf256.h:167:16: note: suggested alternative: ‘Q_INVOKABLE’
         return GF256_INV_TABLE[x];
                ^~~~~~~~~~~~~~~
                Q_INVOKABLE
compilation terminated due to -fmax-errors=10.
make[2]: *** [plugins/channelrx/remotesink/CMakeFiles/remotesink.dir/build.make:67: plugins/channelrx/remotesink/CMakeFiles/remotesink.dir/remotesink.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2542: plugins/channelrx/remotesink/CMakeFiles/remotesink.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by f4exb** [comment]
Something wrong with your Cm256cc dependency. Please try to follow instructions here: https://github.com/f4exb/sdrangel/wiki/Compile-from-source-in-Linux
