### ISSUE TITLE
Application displays incorrectly on Microsoft Surface Pro Gen5

### ISSUE THREAD

**Issue by St0ner1995** [f4exb/sdrangel#292]
Hello,

the application is displaying incorrectly on my Surface Pro

https://imgur.com/9QdvtZe

the screen resolution is 2736x1824 and i have display scaling set to 200x (Everything would be tiny otherwise)

i have run the software on my desktop with a 1920x1080 display and scaling set to 100% and it displayed everything correctly (same install)

EDIT: sometimes the menu on the left will be thinner than it should be causing elements to overlap each other in it, and the menu on the right will reset it's size when i change it

**Comment by f4exb** [comment]
This has already been reported here: https://github.com/f4exb/sdrangel/issues/103
Unfortunately there is no solution.
