### ISSUE TITLE
SoapySDR -windows10- sdrangel 4.4.5

### ISSUE THREAD

**Issue by lucapgt** [f4exb/sdrangel#298]
I've installed soapySDR on windows 10. SoapySDR is installed and running on PlutoSdr, connected on usb port. I can't see soapySDR source on Sdr Angel. What is the mistake?

**Comment by f4exb** [comment]
Just a question: why would you use Soapy for Pluto when you have native support|?

**Comment by lucapgt** [comment]
Because in this way i can use Pluto remotely. On Pluto only connect USB WiFi Key and Power cable, and Pluto is in my LAN :-)

**Comment by f4exb** [comment]
Can you describe the architecture in more detail? It seems to me this is an issue with SoapySDR remote. Make sure you follow SoapySDR instructions here https://github.com/pothosware/SoapyRemote/wiki and make sure you can connect to your remote by other means (SoapySDR utility). Then only if you cannot see it in the list of SoapySDR devices there could be a problem with SDRangel SoapySDR support.

**Comment by lucapgt** [comment]
Yes, i followed the instructions. If i try to connect with cubicsdr works fine, sdrangel not list pluto on soapy.
For example now, connected on usb port: 

![image](https://user-images.githubusercontent.com/15378725/53423228-46d06c80-39e1-11e9-9eb5-59c09828e2d5.png)
![image](https://user-images.githubusercontent.com/15378725/53423286-636ca480-39e1-11e9-8a19-1be17556f695.png)


on cubicsdr
![image](https://user-images.githubusercontent.com/15378725/53423324-72ebed80-39e1-11e9-8610-b81c83cd91d1.png)

![image](https://user-images.githubusercontent.com/15378725/53423339-78e1ce80-39e1-11e9-80d3-d192ce36a95b.png)

**Comment by lucapgt** [comment]
last info from pc:
![image](https://user-images.githubusercontent.com/15378725/53424963-78970280-39e4-11e9-81e9-3fe4528f11e0.png)

**Comment by lucapgt** [comment]
Hi, any idea?

**Comment by KC7NOA** [comment]
Probably a stupid question but did you compile SDR Angel after soapySDR remote was installed?

**Comment by lucapgt** [comment]
I'm using Windows and soapy plugin seems to be ok.

**Comment by synthead** [comment]
@lucapgt, how did you make this work?
