### ISSUE TITLE
Windows GUI interface

### ISSUE THREAD

**Issue by IW1EPY** [f4exb/sdrangel#302]

**Comment by IW1EPY** [comment]
Just beginning  with Pluto - sdrangel , there is a way to use the mouse wheel to fine  tune stations and to rotate all the small pot ? can the small pots stop at the limits?
Thanks in advance for the help

**Comment by IW1EPY** [comment]
Sorry i am a beginner on this site

**Comment by f4exb** [comment]
Yes to rotate the small pots you move the mouse pointer inside the pot and use the wheel. You an also move the thumbwheel dials this way.

**Comment by satfan52** [comment]
I would like to point a click on the SSB signal of interest in the waterfall display and then use the mouse wheel immediately thereafter to fine tune the reception. I am new to sdrangel and only started to use it very recently, but unless I am mistaken this is not possible. What I noticed is that it is possible instead is to use the mouse wheel in combination with the rotary encoders but this is less convenient as it requires to move the mouse away  from the signal of interest  to the rotary encoders, then  to the fine tune frequency and eventualy go back to the waterfall display to check the next signal of interest (not always convenient if it needs to be done very frequently).  I noticed that the arrows work too to change the rotary encoders so not only the mousewheel, but again it would be more convenient if I could use my mouse wheel after having clicked on the signal of interest in the waterfall frequency display. Thanks for clarifying if it can be done or not with sdrangel. Regards. Peter

**Comment by f4exb** [comment]
You can drag and drop the center line in the waterfall

**Comment by f4exb** [comment]
Yes it is definitely possible (and just coded) to move the center line with the mouse wheel. Will be in next version and in dev soon.

**Comment by satfan52** [comment]
Yes, thanks, I know. The point is that fine tuning the rx frequency is not
easy that way  that's is why the mouse wheel could come very handy to
tlfine tune on an SSB signal
