### ISSUE TITLE
LoRa demodulator revival as ChirpChat

### ISSUE THREAD

**Issue by f4exb** [f4exb/sdrangel#309]
This has been requested through direct mail and I also have been thinking of doing it some day. Let's make a proper ticket... 

The present LoRa demod plugin is a legacy from the old Sdrangelove base and was not really taken care of since (well it just compiles) so in fact it is not really functional.

This ticket is open to make a functional LoRa demodulator plugin and also a modulator.

**Comment by Zapero** [comment]
This would be great!

**Comment by f4exb** [comment]
LoRa modulator to be handled in a separate issue.

**Comment by f4exb** [comment]
https://www.link-labs.com/blog/what-is-lora
https://github.com/BastilleResearch/gr-lora

**Comment by f4exb** [comment]
More info here: https://www.ntu.edu.sg/home/limo/papers/TOSN-LoRa.pdf

**Comment by f4exb** [comment]
The demodulation part shows that +/-1 bit error are common on FFT argmax detection. This paper explains how this is mitigated by Gray coding: https://myriadrf.org/news/lora-modem-limesdr/

**Comment by f4exb** [comment]
Implemented in v5.2.0

**Comment by f4exb** [comment]
LoRa demodulator plugin is now ChirpChat demodulator plugin. It has a LoRa compatible mode.

**Comment by f4exb** [comment]
To be retrofitted to master as v6

**Comment by f4exb** [comment]
Deployed in v6.0.0
