### ISSUE TITLE
limesdr start 30mhz not 100khz

### ISSUE THREAD

**Issue by Red-Owl** [f4exb/sdrangel#315]
limesdr (not mini) start at 30mhz this SDR should start from 100khz.

**Comment by f4exb** [comment]
The LO does start at 30 MHz. Please read the documentation more carefully.

**Comment by Red-Owl** [comment]
[ERROR] SetFrequencySXR(29 MHz) - required VCO frequency is out of range [3800-7714] MHz

in wi lo hi in any input have idea to resove ?
