### ISSUE TITLE
Sdrangel on Windows 10 with rsp2pro and hackrfone

### ISSUE THREAD

**Issue by f6jig** [f4exb/sdrangel#316]
Hi ,

I try to install sdrangel on windows 10 usine rsp2duo and hackrf one.
But i don't find how to on Windows with this to hardware.
73 Raymond F6JIG

**Comment by f4exb** [comment]
This kind of question will be better answered in the discussion group

**Comment by f4exb** [comment]
Note: discussion group is here: https://groups.io/g/sdrangel
