### ISSUE TITLE
Missing COPYING/LICENSE file.

### ISSUE THREAD

**Issue by 9600** [f4exb/sdrangel#322]
It's not clear what license SDRangel is provided under.

**Comment by rgetz** [comment]
Most of the code that I looked at is under GPL3. For example:

https://github.com/f4exb/sdrangel/blob/master/sdrbase/mainparser.cpp
https://github.com/f4exb/sdrangel/blob/master/sdrgui/mainwindow.cpp

invoking the way back machine....

http://git.osmocom.org/sdrangelove/tree/main.cpp?id=d00f719934a26ba17b9c573c33f91be97cae12fd

still says GPL3.

but, yes - a COPYING or LICNESE file missing from the root folder.

**Comment by f4exb** [comment]
Done:
https://github.com/f4exb/sdrangel/commit/ae3e4fed457d8dd259d9113a383ff3d64ac2f1c6

**Comment by 9600** [comment]
Thanks!
