### ISSUE TITLE
Source Selector; High Resolution Displays doesn't display devices

### ISSUE THREAD

**Issue by rgetz** [f4exb/sdrangel#323]
SDRangel 4.5.3; Win 10; 4k display. by default, I don't see the drop down list in the source selector, and clicking everywhere doesn't display the drop down box.

![image](https://user-images.githubusercontent.com/1017869/55898720-33442400-5b91-11e9-855a-cc04dfc3cbbc.png)

If I change properties -> compatibility ->  Override high DPI scaling:
![image](https://user-images.githubusercontent.com/1017869/55898632-0728a300-5b91-11e9-852e-6683f2f2c4b7.png)

I get something that works:

![image](https://user-images.githubusercontent.com/1017869/55898563-dba5b880-5b90-11e9-91ab-414d524b91a2.png)

-Robin

**Comment by f4exb** [comment]
"If I change properties -> compatibility -> Override high DPI scaling:"
  - Any more details on how to do that?
  - Do you have any idea on making it programmatically?

This is an annoying recurring issue (not restricted to Windows) and I would like to fix it once for all.

**Comment by f4exb** [comment]
See #103

**Comment by rgetz** [comment]
For Windows - there are two options (that I can find):
- Create a new file GdiScaling.manifest in your project. See : https://stackoverflow.com/questions/46428510/enhanced-system-dpi-scaling-with-vs2017
 - call IsValidDpiAwarenessContext and SetProcessDpiAwarenessContex See : https://stackoverflow.com/questions/49333034/programmatically-override-the-high-dpi-awareness

I don't think either of those fixes the actual root cause (which is some Qt DPI issue for the widget that is being used).

**Comment by f4exb** [comment]
Suppsedly fixed with #522 (cannot test it)
