### ISSUE TITLE
Cannot enable audio input Windows

### ISSUE THREAD

**Issue by Retartist** [f4exb/sdrangel#324]
When attempting to set an audio input, nothing happens and no sound is transmitted 
![image](https://user-images.githubusercontent.com/49677613/56198685-b75d4680-607e-11e9-8231-75a28a033ae9.png)

**Comment by f4exb** [comment]
You have no input selected on your modulator. Please read documentation before opening issues.

**Comment by Retartist** [comment]
I will admit that the photo isn't the best, but even when enabling the input on the modulator, nothing comes out. After further tweaking, I found out that the systems default audio input will work, but i cannot change that in the program. E.g. if the default device is the microphone, the microphone will work, BUT if i wanted to change it to the Virtual cable, the program will ignore my selection.

**Comment by f4exb** [comment]
The source is selected by right clicking on the microphone: https://github.com/f4exb/sdrangel/blob/master/plugins/channeltx/modnfm/readme.md#104-audio-input-select-and-select-audio-input-device
