### ISSUE TITLE
Please we look for QO-100 DVBS2 decoder support on sdrangel any news ? 

### ISSUE THREAD

**Issue by khanfar** [f4exb/sdrangel#333]

**Comment by khanfar** [comment]
may be this software can help to catch something to add in sdrangel 
http://www.pabr.org/radio/leandvb/leandvb.en.html#

**Comment by khanfar** [comment]
and this too :
https://github.com/pabr/xdsopl-LDPC-pabr

**Comment by f4exb** [comment]
leandvb is already used in the DATV Demod plugin. I think it implements LDPC internally so there should not be a need for something specific for LDPC.

Closing this one as dupe of #299
