### ISSUE TITLE
Windows zip file for latest release for sdrangel-4.8.0

### ISSUE THREAD

**Issue by zendogpc** [f4exb/sdrangel#350]
The latest release of sdrangel-4.8.0 for Windows doesn't contain a windows executable file? Somebody please advise.

**Comment by f4exb** [comment]
How do you call `sdrangel.exe` ?

**Comment by Vort** [comment]
It just have no icon. Look at #179.

**Comment by f4exb** [comment]
Closed in favor od #179

**Comment by zendogpc** [comment]
I have done a search through the extracted zip file and found no sdrangel.exe with or without an icon. I don't understand why someone has to be so against a operations system that aren't open source? I thought this would be a community to help people not put them down....

**Comment by Vort** [comment]
@zendogpc looks like you have downloaded wrong file.
[This one](https://github.com/f4exb/sdrangel/archive/v4.8.0.zip) is source code and you need [this one](https://github.com/f4exb/sdrangel/releases/download/v4.8.0/sdrangel_v4.8.0.7z).
It can be extracted with 7-Zip or WinRAR.

**Comment by zendogpc** [comment]
I appreciate the clarification and I have downloaded the correct file.
Thanks for the consideration.

**Comment by Vort** [comment]
If file download location is correct, then it is probably some software on your PC is removing `sdrangel.exe` file.
Size of `sdrangel_v4.8.0.7z` should be `39137747` bytes, MD5 checksum `7a30f99d122f27f45355669a09ad6cf9`.
And here is the screenshot of executable file, as seen with 7-Zip 19.00 (x64):
![7zs](https://user-images.githubusercontent.com/1242858/58227249-be890b80-7d32-11e9-96c0-6867742d3977.png)
