### ISSUE TITLE
Interpolation in AM Demodulator is completely broken

### ISSUE THREAD

**Issue by Vort** [f4exb/sdrangel#354]
The goal is to demodulate 12 kHz BW file of AM transmission: [la_bamba.zip](https://github.com/f4exb/sdrangel/files/3227576/la_bamba.zip)
Right now result looks like this:
![la_bamba_sdrangel_demod](https://user-images.githubusercontent.com/1242858/58477748-ff32bb80-815c-11e9-8a8a-eddae032e0b4.png)
It is not needed even to hear that thing to know that it is broken (your ears will not like this).
I am not sure how it should be fixed (and how many times this code is duplicated), but such quick and dirty hackfix allowed me to hear what looks like correct demodulation:
```patch
diff --git a/plugins/channelrx/demodam/amdemod.cpp b/plugins/channelrx/demodam/amdemod.cpp
index 99eeb32..448e996 100644
--- a/plugins/channelrx/demodam/amdemod.cpp
+++ b/plugins/channelrx/demodam/amdemod.cpp
@@ -130,14 +130,11 @@ void AMDemod::feed(const SampleVector::const_iterator& begin, const SampleVector
 
 		if (m_interpolatorDistance < 1.0f) // interpolate
 		{
-            processOneSample(ci);
-
-		    while (m_interpolator.interpolate(&m_interpolatorDistanceRemain, c, &ci))
+		    while (!m_interpolator.interpolate(&m_interpolatorDistanceRemain, c, &ci))
             {
                 processOneSample(ci);
+				m_interpolatorDistanceRemain += m_interpolatorDistance;
             }
-
-            m_interpolatorDistanceRemain += m_interpolatorDistance;
 		}
 		else // decimate
 		{ 
```
![la_bamba_sdrangel_demod_fixed](https://user-images.githubusercontent.com/1242858/58478299-64d37780-815e-11e9-8a77-7b5e5a9bb2fe.png)
Please investigate this problem.

**Comment by f4exb** [comment]
Yes it works thanks! 

I didn't care too much about it because pulseaudio can do it possibly more efficiently. But I agree this can be convenient and if it is there then it should work. It could be extended to other audio demods at least SSB and FM which are the most likely to be used with sample rates below the common 48k audio.

**Comment by f4exb** [comment]
Done on SSB and NFB (dev branch) also.

**Comment by Vort** [comment]
Interpolated waveform looks smooth, so it counts as fixed.
