### ISSUE TITLE
Windows: missing RTL-SDR support

### ISSUE THREAD

**Issue by f4exb** [f4exb/sdrangel#366]

**Comment by gaspar1987** [comment]
hello j ai pas le device de rtl sdr comme faire le interniez sur sdrangel 4.10.2

**Comment by f4exb** [comment]
Unreadable and unrelated to the subject

**Comment by gaspar1987** [comment]
pas de rtl sdr sur vous logiciel  merci ?

**Comment by f4exb** [comment]
Which system? Windows, Ubuntu 18.04, Ubuntu 19.04, Debian Buster ?

**Comment by gaspar1987** [comment]
la cle rtl sdr marche pas sur la nouvelle version !

**Comment by gaspar1987** [comment]
c est window s 8.1

**Comment by f4exb** [comment]
Should be built as an external library but is missing here: https://github.com/f4exb/sdrangel/blob/master/external/CMakeLists.txt

**Comment by f4exb** [comment]
Fixed in v4.10.3

**Comment by gaspar1987** [comment]
slt de FRS 2606 qz merci F4exb .

**Comment by f4exb** [comment]
Thanks for reporting :smile:

**Comment by gaspar1987** [comment]
bonjour  je veux  le dsd  de crypto audio sur version nouvelle 4.10.4 sdrangel Windows 8.1 ?
