### ISSUE TITLE
No binary packages for Debian Stretch

### ISSUE THREAD

**Issue by maciek84krk** [f4exb/sdrangel#367]
Hello!

Is any chance to have old binary version of sdrangel which was working with Debian Stretch?
New version want new libc, new libraries etc, and for me its change a half of all system, and
 i have very restricted system based on stretch which can't have newest libraries.
Can somebody give me old version for stretch in binary .deb?

I will very happy if yes... My mail maciek.tumidajski@gmail.com

My suggestion for author: Program is very very super, but don't remove old versions so 
 fast, many peoples can't change system to new in some days :)

Maciej

**Comment by f4exb** [comment]
Stretch is too old and has dependency incompatibilities with the newest changes so it is definitely dropped.

**Comment by f4exb** [comment]
This is essentially your problem. However if you are able to install Docker and I think this should be possible even on Stretch then you can build a Docker image which is based on Ubuntu 18.04 and therefore get free from all compatibility issues. See: https://github.com/f4exb/sdrangel-docker

**Comment by maciek84krk** [comment]
Thank you f4exb, i think it's solving my problem :)
