### ISSUE TITLE
SDRangel freezing

### ISSUE THREAD

**Issue by sashatytko** [f4exb/sdrangel#368]
Hello! Sdrangel freeze on my laptop in windows 10 and Ubuntu 18/04.When i start transmitting voice i just see 
 
![Screenshot from 2019-06-19 16-17-38](https://user-images.githubusercontent.com/27360903/59768914-da3dee00-92ad-11e9-8a7a-7bf881cb89f9.png)
![Screenshot from 2019-06-19 16-17-42](https://user-images.githubusercontent.com/27360903/59768927-dd38de80-92ad-11e9-8b2a-47a2cb8fe3bd.png)

windows 10 tx no voice as ubuntu but ubuntu freeze

**Comment by f4exb** [comment]
I don't understand this mishmash. Please be clear and read documentation first. On the first picture it is obvious that you have no source selected

**Comment by sashatytko** [comment]
![Screenshot from 2019-06-20 10-39-02](https://user-images.githubusercontent.com/27360903/59830163-be872600-9347-11e9-86b7-4f0eaa206d16.png)
Nothing happen.
On windows 10 at the same settings you see picture 

![](https://user-images.githubusercontent.com/27360903/59771048-ad8bd580-92b1-11e9-8709-198dac62f4d5.jpg)

**Comment by f4exb** [comment]
![rtfm](https://user-images.githubusercontent.com/6192319/59981069-e2c05c80-95fe-11e9-9c2e-32a453d17e7e.png)
RTFM:
https://github.com/f4exb/sdrangel/wiki/Quick-start

**Comment by sashatytko** [comment]
I push this button!! I just make screenshot when stop everything.On photo where is windows 10 it is playing.On linux you can see on waterfall just whole signal without any voice!
