### ISSUE TITLE
19-06-2019, demodfreedv, build error

### ISSUE THREAD

**Issue by Red-Owl** [f4exb/sdrangel#369]
[ 52%] Building CXX object plugins/channelrx/demodfreedv/CMakeFiles/demodfreedv.dir/freedvdemod.cpp.o
/home/gufo/Scrivania/sdrangel/plugins/channelrx/demodfreedv/freedvdemod.cpp: In member function ‘void FreeDVDemod::applyFreeDVMode(FreeDVDemodSettings::FreeDVMode)’:
/home/gufo/Scrivania/sdrangel/plugins/channelrx/demodfreedv/freedvdemod.cpp:629:9: error: ‘freedv_set_ext_vco’ was not declared in this scope
         freedv_set_ext_vco(m_freeDV, 0);
         ^~~~~~~~~~~~~~~~~~
/home/gufo/Scrivania/sdrangel/plugins/channelrx/demodfreedv/freedvdemod.cpp:629:9: note: suggested alternative: ‘freedv_set_tx_bpf’
         freedv_set_ext_vco(m_freeDV, 0);
         ^~~~~~~~~~~~~~~~~~
         freedv_set_tx_bpf
/home/gufo/Scrivania/sdrangel/plugins/channelrx/demodfreedv/freedvdemod.cpp:639:18: error: ‘freedv_get_modem_symbol_rate’ was not declared in this scope
         int Rs = freedv_get_modem_symbol_rate(m_freeDV);
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/gufo/Scrivania/sdrangel/plugins/channelrx/demodfreedv/freedvdemod.cpp:639:18: note: suggested alternative: ‘freedv_get_modem_sample_rate’
         int Rs = freedv_get_modem_symbol_rate(m_freeDV);
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
                  freedv_get_modem_sample_rate
make[2]: *** [plugins/channelrx/demodfreedv/CMakeFiles/demodfreedv.dir/build.make:63: plugins/channelrx/demodfreedv/CMakeFiles/demodfreedv.dir/freedvdemod.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2320: plugins/channelrx/demodfreedv/CMakeFiles/demodfreedv.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
gufo@meo:~/Scrivania/sdrangel/bu$

**Comment by f4exb** [comment]
You need the latest version of codec2. Use commit 76a20416d715ee06f8b36a9953506876689a3bd2
