### ISSUE TITLE
Unwanted consle window in 4.10.4

### ISSUE THREAD

**Issue by gm8arv** [f4exb/sdrangel#374]
I see a console window in 4.10.4 which wasn't in 4.10.0.  How can I hide this window, please?  I tried setting the console logging level to Info, but the unwanted console still appears, and the level is back to debugging.

**Comment by f4exb** [comment]
"and the level is back to debugging." Sorry,,, no. Only until the logger is initialized then you have the requested level of messages.

**Comment by Vort** [comment]
Windows GUI programs traditionally have no console window visible.

**Comment by f4exb** [comment]
I understand you may want a toy app to get along with your toy O/S. For serious usage you do need console messages. 

I am not going to do anything about it personally but ready to receive a PR.

**Comment by Vort** [comment]
> I am not going to do anything about it personally but ready to receive a PR.

However you was doing something to remove console hiding option.

> For serious usage you do need console messages.

Messages - yes, console - no.
Look how it is done in VLC:
![vlc_messages](https://user-images.githubusercontent.com/1242858/60724786-ff825b80-9f3f-11e9-8008-731ff0475a93.png)

**Comment by f4exb** [comment]
> However you was doing something to remove console hiding option.
The build process for Windows is entirely new since 4.10.3 so maybe something got lost in the translation.

**Comment by gm8arv** [comment]
I can understand that the change was unintentional and unexpected.  I agree that console/debugging information can be helpful, but I would prefer that it was normally disabled, and perhaps a command-line switch -console be added to enable the window.  Alternatively, perhaps a "-noconsole" flag?  Let me know if I can help.

**Comment by Vort** [comment]
> The build process for Windows is entirely new since 4.10.3 so maybe something got lost in the translation.

I guess that [`/SUBSYSTEM:WINDOWS`](https://docs.microsoft.com/en-us/cpp/build/reference/subsystem-specify-subsystem?view=vs-2017) linker parameter was lost. Did not checked yet.

> but I would prefer that it was normally disabled, and perhaps a command-line switch -console be added to enable the window.

Console visibility is usually hardcoded inside exe file header.
Most likely, it is possible to control its appearing in runtime, but software do not do it usually.

**Comment by Vort** [comment]
This change should fix the problem:
(also imported improvement for Qt detection from decff91427db150ee7043f708afe7d4d694e664c)
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index d4dc402..5a93a84 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -480,6 +480,10 @@ if (BUILD_GUI)
     sdrgui
     logging
     )
+
+    if (MSVC)
+        set(CMAKE_EXE_LINKER_FLAGS_RELEASE "${CMAKE_EXE_LINKER_FLAGS} /SUBSYSTEM:WINDOWS /ENTRY:mainCRTStartup")
+    endif()
 endif()
 
 ############ build sdrangel server ################
diff --git a/cmake/Modules/QtLocator.cmake b/cmake/Modules/QtLocator.cmake
index 1403bbb..34d97aa 100644
--- a/cmake/Modules/QtLocator.cmake
+++ b/cmake/Modules/QtLocator.cmake
@@ -2,7 +2,7 @@ SET(QT_MISSING True)
 # msvc only; mingw will need different logic
 IF(MSVC)
     # look for user-registry pointing to qtcreator
-    GET_FILENAME_COMPONENT(QT_BIN [HKEY_CURRENT_USER\\Software\\Classes\\Applications\\QtProject.QtCreator.cpp\\shell\\Open\\Command] PATH)
+    GET_FILENAME_COMPONENT(QT_BIN [HKEY_CURRENT_USER\\Software\\Classes\\Applications\\QtProject.QtCreator.pro\\shell\\Open\\Command] PATH)
 
     # get root path so we can search for 5.3, 5.4, 5.5, etc
     STRING(REPLACE "/Tools" ";" QT_BIN "${QT_BIN}")
@@ -22,7 +22,15 @@ IF(MSVC)
     # - qt uses (e.g.) "msvc2012"
     # - cmake uses (e.g.) "1800"
     # - see also https://cmake.org/cmake/help/v3.0/variable/MSVC_VERSION.html
-    MATH(EXPR QT_MSVC "2000 + (${MSVC_VERSION} - 200) / 100")
+
+    # check compiler version
+    if(MSVC_VERSION GREATER 1910 AND MSVC_VERSION LESS 1919)
+      set(QT_MSVC 2017)
+    elseif(MSVC_VERSION GREATER 1899 AND MSVC_VERSION LESS 1910)
+      set(QT_MSVC 2015)
+    else()
+      MATH(EXPR QT_MSVC "2000 + (${MSVC_VERSION} - 600) / 100")
+    endif()
 
     # check for 64-bit os
     # may need to be removed for older compilers as it wasn't always offered 
```

**Comment by f4exb** [comment]
Tried it. Looks like it's doing the job 😄

**Comment by netdoggy** [comment]
As for me the console was useful.
Maybe you should add or parameter to display the console. Or, judging by the fact, it's all about the build paramters, then you can probably build a build with 2 exes :)

**Comment by Vort** [comment]
@netdoggy console window can be enabled with the help of the hex editor.
Just replace byte `02` with `03` at address `174`:
![sdra_console](https://user-images.githubusercontent.com/1242858/60764509-0b7f3200-a094-11e9-8f9f-ecdfc9f82351.png)

**Comment by f4exb** [comment]
I am not going to do zillions of versions (even just two) and there is not going to be an option to show the console. So there will be no console started period. You have three ways to get the console messages:

  - use the trick just above for a permanent change
  - start the program from the bash prompt of the "Git for Windows" application https://git-scm.com/download/win (as a bonus you will have git)
  - Write the log to file See https://github.com/f4exb/sdrangel/blob/master/sdrgui/readme.md#12-preferences---logging

So I am going to close the issue.

**Comment by gm8arv** [comment]
Perfect solution, thanks!  73, David

**Comment by netdoggy** [comment]
Great, Thank you!
