### ISSUE TITLE
SSB modulador version 10.    Hackrf   windows

### ISSUE THREAD

**Issue by Pedro9012** [f4exb/sdrangel#376]
Hola, a partir de esta version el modo ssb a hido a peor ,  o le pones con el volumen a 0,1 sin AGC ,
 o bien le pones con AGC y volumen a 9,9 ,  otros ajustes sale totalmente distorsionado.
Sdrangel v 4.10.02 , windows 10 pro , hackrf.
¿alguien mas tiene este problema?
Un SALUDO.

Hello, from this version the mode ssb to hido to worse, or you put it with the volume at 0.1 without AGC,
 or you put it with AGC and volume at 9.9, other settings comes out totally distorted.
Sdrangel v 4.10.02, windows 10 pro, hackrf.
Does anyone else have this problem?
A greeting.

**Comment by f4exb** [comment]
It all depends on how you set the numerous controls of the CMP which is indeed an AGC. Anyway in v4.11.1 I am going to implement a real compressor based on the code of the sndfilter library which is a far better implementation as the first tests tend to prove.

**Comment by f4exb** [comment]
As mentioned above v4.11.1 implements a new proper audio compressor with a single on/off button. This should fix issues related to compressor (not to your individual audio settings).

**Comment by Pedro9012** [comment]
Ok, thank you very much for the information
