### ISSUE TITLE
Broadcast FM demod: RDS is broken

### ISSUE THREAD

**Issue by f4exb** [f4exb/sdrangel#39]
Zero decodes when engaged although baseband spectrum shows good quality RDS carrier

**Comment by f4exb** [comment]
I have to check if the sample rate and/or RF bandwidth that should drive the channelizer downsampling have an influence

**Comment by f4exb** [comment]
Well at the moment there is no documentation at all for this plugin and it is not a small job due to the many fields of RDS.

**Comment by Dl4APT** [comment]
if I remember correctly RDS works fine but only in Stereo mode

**Comment by f4exb** [comment]
Hello, it needs the 19 kHz pilot to be locked so most probably this is indeed tied to the stereo mode.

**Comment by f4exb** [comment]
There's seem to be an issue with the sample rate. Some baseband sample rates cause it not to work. For example 384 kS/s. Maybe there's an assumption somewhere that depends on the sample rate.

**Comment by f4exb** [comment]
dropped
