### ISSUE TITLE
can't save settings

### ISSUE THREAD

**Issue by drom** [f4exb/sdrangel#391]
Setting SDRangle on the PlutoSDR box, with R0/T1, SSB demodulator/modulator, window sizes, locations, etc.
I can't find a way to store my settings and I have to set up it again after every restart.
Presets can store some R0 settings, but I am losing T1 settings for sure.

**Comment by f4exb** [comment]
This is no possible by design sorry.

**Comment by f4exb** [comment]
This can be worked around with the rest API. See:
https://github.com/f4exb/sdrangel/blob/master/swagger/sdrangel/examples/config.py
and
https://github.com/f4exb/sdrangel/blob/master/swagger/sdrangel/examples/test.json

**Comment by f4exb** [comment]
I suppose this workaround is OK hence closing the issue
