### ISSUE TITLE
issue starting sdrangel 4.11.6-win64.exe on windows 7

### ISSUE THREAD

**Issue by jcfpi** [f4exb/sdrangel#409]
App crash at startup, see the attached files. Fresh Installation yersteday with sdrangel-4.11.6-win64.exe. No issue with 4.3.0  build qt 5.11.1 32 bits on windows 7
 Thank you
![1](https://user-images.githubusercontent.com/33512703/63520408-fac83580-c4f4-11e9-91f8-7c86a850a6a8.jpg)
![2](https://user-images.githubusercontent.com/33512703/63520492-1df2e500-c4f5-11e9-8375-66e2720cc6ee.jpg)

**Comment by f4exb** [comment]
What is that you don't understand in sdrangel-4.11.6-**win64**.exe?

**Comment by f4exb** [comment]
Windows 32 bits unsupported

**Comment by Vort** [comment]
> What is that you don't understand in sdrangel-4.11.6-**win64**.exe?

It's you, who don't understand that 32-bit system can't have Exception Offset of 0000000000009ff4.

**Comment by f4exb** [comment]
True but it does not really matter as I am planning no action on this.
