### ISSUE TITLE
compressor

### ISSUE THREAD

**Issue by gowzel** [f4exb/sdrangel#412]
How do I adjust the compression, old version I was using the compressor could be adjusted with the knob next to the compressor button, but now after installing latest version there is no way to adjust the compression, or am I missing something
Thanks
John

**Comment by f4exb** [comment]
Yes the SSB compressor was changed at version 4.11.1. See: https://github.com/f4exb/sdrangel/releases/tag/v4.11.1

This algorithm is a standard compression algorithm simply applying a non linear curve on the audio power which works much better than the previous one and is also drastically more simple. After a few tests I did not think there is was need to make adjustments so this is just on/off.
