### ISSUE TITLE
Corrupt window version

### ISSUE THREAD

**Issue by virendera** [f4exb/sdrangel#413]
I downloaded this file "sdrangel-4.11.8-win64.exe" two times but it shows corrupt package manager. Can you solve this issue? 
System Windows 10 with 64bit.

**Comment by f4exb** [comment]
The 4.11.8 and 4.11.7 releases were removed anyway because they contained a serious bug. 4.11.9 is available now and I just downloaded it and installed on another machine so it is working.

**Comment by virendera** [comment]
Thanks 😊
