### ISSUE TITLE
Audio stuttering

### ISSUE THREAD

**Issue by dh1tw** [f4exb/sdrangel#414]
Hi,

I'm trying to get a PlutoSDR (via LAN) working with SDRAngel. I can connect to the PlutoSDR and I'm receiving IQ samples. However when trying to demodulate (I tried WFM, AM and SSB), the audio is stuttering. It seems that this caused by audio buffer underflows. On the console I get the following output: 

```
ALSA lib pcm.c:8306:(snd_pcm_recover) underrun occurred
```

From my experience, increasing the sample size and/or audio buffer will fix this problem. Is there a way in SDRAngel to modify the sample size / audio buffer size? 

I'm able to reproduce this on my two computers:
1. Beefy Macbook i7 / 16Gb with Ubuntu 18.04
2. Mini PC with Intel Gemini Lake / 6Gb with Windows 10

Both times running SDR Angel 4.11.9

Thanks & 73,
Tobias, DH1TW

**Comment by f4exb** [comment]
How do you get the Pluto working with LAN? Can you detail this please? Native support of Pluto is supposed to be USB only. If you use it through Soapy then this is not really supported. Soapy is supposed to be used as a last resort when a device is not natively supported.

Which sample size are you talking about? Audio or I/Q? Audio is normally 2x16 bits (you get the L+R channels always and possibly duplicated for mono). I/Q is either 2x24 bits (on 32 bit integers) or 2x16 bits (on 16 bit integers) there is no possibility to change this on the fly this is a compiler option. Packages are compiled with the 24 bit option.

How is your decimation chain set up? It is usually better to put the strain on the device decimation (the one that you can control) and not on the channel decimation (the one that you can't control). i.e. for a 48 kHz audio sample rate (most commonly) try to have baseband width not way much larger (i.e. not several MHz). You have the Local Sink plugin to split the band in several sections if necessary.

The decimation chain could possibly be improved by taking larger steps up front but this is not so obvious as half-band decimation filters have more zeros than "fourth" or "eighth" band decimation filters (today this is a chain of half-band decimators). You may also need to increase the length of the filter to keep a satisfactory OOB attenuation. On the other hand the larger the decimation factor the less computation you have to do at each cycle. This can be benchmarked but I have no plans to do this in the immediate future. I personally do not run in such issues in particular with the Pluto.

**Comment by dh1tw** [comment]
Hey Edouard,
thanks for the swift reply! While browsing through the issues and PRs, I stumbled over PR #304 . Since this PR got merged, my assumption was that LAN was supported for the Pluto. In the PR the FQDN ´pluto.local´ seems to be hardcoded. With an entry in `/etc/hosts` I point `pluto.local` to the correct IP address. After that, Pluto gets properly discovered within SDRAngel as `PlutoSDR[0] networked`

I've tried to setup decimation & baseband bandwidth to be relatively low. Find attached the screenshot of my setup. I presume 312.5kHz should be ok.

Does that look ok?

I'm personally talking about the audio sample size. The buffer underflow warning which portaudio throws, indicates that at the time of writing to the sound card, no audio frames were available. 

hw?

73 Tobias

**Comment by f4exb** [comment]
This looks like reasonable settings. I also monitor the QO-100 narrowband transponder (I guess this is what you attempt to do here!) but with a RTL-SDR for the Rx at 1120 kS/s then it is dowsampled by 4 to 280 kS/s which fits nicely the two beacons on the sides then I further downsample it by 2 into 2 sub bands (high, low) using Local Sinks then the high part (Local input in another tab) has a Frequency Tracker and a SSB demod  and the low part has 2 SSB demods. I split the bands more for convenience to have a more detailed view on the spectrum display rather than due to sample rate considerations. I use this setup routinely and this works fine. The device to host sample rate is about half of yours but this should not really make a difference. It is possible to lower this sample rate for the Pluto by decimating in hardware with the FIR filter. The really big difference I think is the network in the middle.

**Comment by satfan52** [comment]
I connect to my pluto both over USB or over the network with an external Ethernet Adaptor. The max sampling rate I can reliably use with a USB connection  is 3.0 - 3.2 MSA (depending if the FIR filter is set or not). With an Ethernet adaptor the performance degraded by 10% approximately.

**Comment by dh1tw** [comment]
@satfan52 do you experience any audio stuttering when connecting to the Pluto via LAN? If not, would you mind sharing a screenshot? 
I don't think that LAN or bandwidth is really an issue. With SDR-Console I can perfectly receive and transmit through my Pluto via LAN (500kS bandwidth).

**Comment by satfan52** [comment]
> @satfan52 do you experience any audio stuttering when connecting to the Pluto via LAN? If not, would you mind sharing a screenshot?
![Screenshot from 2019-10-08 21-25-53](https://user-images.githubusercontent.com/14941529/66426605-80a33000-ea12-11e9-9e96-4707eba89d52.png)
![Screenshot from 2019-10-08 21-25-35](https://user-images.githubusercontent.com/14941529/66426606-826cf380-ea12-11e9-9f43-7496e088f8e2.png)
![Screenshot from 2019-10-08 21-25-05](https://user-images.githubusercontent.com/14941529/66426610-8436b700-ea12-11e9-8aa9-ba5e1289dff1.png)
![Screenshot from 2019-10-08 21-22-55](https://user-images.githubusercontent.com/14941529/66426614-86007a80-ea12-11e9-890c-8afcf7c803e0.png)

Transmitted with  my FT-847 into a dummy load and checked the quality of the modulation in FM and SSB. Works for me up to 3 MSA, **no suttering EXCEPT in full duplex.** When operating in full duplex,  audio is indeed suttering (I tried a 2 and 3 MSA) whatever the modulation used (SSB or FM) and even with 1 or 2ghz difference between the central frequency of the RX and TX. Not sure it is an SdrAngel problem, it may be linked to the PlutoSDR (rf leakage, poor isolation between TX and RX)
