### ISSUE TITLE
bonjour j ai un probleme avec record 

### ISSUE THREAD

**Issue by gaspar1987** [f4exb/sdrangel#416]
j ai le logiciel qui enregistre   pas le audio des radiotéléphone et je pas dorissier R1 SDR IQ . dit moi pour quoi ca marche pas mon pc .
![Capture](https://user-images.githubusercontent.com/13591469/65248641-c8f5bf00-daf2-11e9-9ad1-3f90bb452ce7.PNG)
![Capture2](https://user-images.githubusercontent.com/13591469/65248647-cc894600-daf2-11e9-8d2f-32f1036be8b5.PNG)

**Comment by f4exb** [comment]
See doc here: https://github.com/f4exb/sdrangel/tree/master/plugins/samplesource/fileinput
You have to select the file by clicking on (4).
The doc link is missing in the Wiki so maybe you missed it.
