### ISSUE TITLE
importing bookmarks does not work if there's no bookmark already

### ISSUE THREAD

**Issue by Antanide** [f4exb/sdrangel#447]
Linux, git commit acd0892 (v 4.12.1).

Fresh installation with no bookmarks.

You press the "import bookmarks" button and nothing happens.
Workaround: create a random temporary bookmark. Then the button works.

**Comment by f4exb** [comment]
What is that you do not understand in "Import preset from file in the current group". Then you need to have a group defined (of course).

Useless to keep this issue opened.
