### ISSUE TITLE
Entry point not found 

### ISSUE THREAD

**Issue by g4bao** [f4exb/sdrangel#449]
Very new to Github. Hope I'm doing this right! 

![image](https://user-images.githubusercontent.com/57603872/69670013-e44cef80-108a-11ea-98f2-3e101d2f471f.png)

I'm getting the above error on startup, Clicking OK seems to run the program OK

**Comment by Vort** [comment]
It may happen because non-compatible library is found in your system PATH variable.
You can try temporary rename that PothosSDR folder and check if error will happen again.

**Comment by g4bao** [comment]
I renamed the PothosSDR folder as you suggested and the error does not occur. When returning the folder to its original name., the error message reoccurs. As the folder was created by the Pothos Windows installer, I'm not sure what the next step is.
John

**Comment by Vort** [comment]
Do you need that PATH modifications for other software?
Looks like they can be disabled while installing PothosSDR:
https://i.imgur.com/pC9uKY6.png

**Comment by g4bao** [comment]
Perfect! I removed the Path to PothosSDR/bin and the error does not now occur. Pothos continues to work correctly! 
Thanks for the help
