### ISSUE TITLE
Transmitting in SSB not filtering the other half of the side band.

### ISSUE THREAD

**Issue by cinosh07** [f4exb/sdrangel#450]
I'm using HackRF for transmitting with SSB Mode, with the settings correctly configured, the signal sent is still transmit on both side of the band. The DSB/SSB toggle button is in the right position for ssb. It's remain the same in  SSB and USB Mode. It's almost like a regular AM modulation on my spectrum Analyser.

**Comment by f4exb** [comment]
Cannot reproduce.
