### ISSUE TITLE
Missing dependency checks

### ISSUE THREAD

**Issue by ka6s** [f4exb/sdrangel#46]
I'm building SDRAngel for the first time on debian and ran into the following issue.

I needed to have the boost development library - but cmake didn't tell me that.

Please add a check in the configuration.

Note also that I have librtlsdr in place already - so I assume it is compiling for that environment.

Thanks!

Steve KA6S

**Comment by f4exb** [comment]
https://github.com/f4exb/sdrangel/blob/master/CMakeLists.txt at line 56:
find_package(Boost)

I suppose this should be:
find_package(Boost REQUIRED)

**Comment by f4exb** [comment]
Fix now on dev branch

**Comment by f4exb** [comment]
Fixed in v3.6.0
