### ISSUE TITLE
DATV video stream using Pluto SDR

### ISSUE THREAD

**Issue by khan2018** [f4exb/sdrangel#461]
Hi

I am transmitting using Pluto SDR
![WhatsApp Image 2019-12-30 at 4 27 39 PM](https://user-images.githubusercontent.com/29824411/71583914-6cf2fb80-2b21-11ea-948b-bc6b8f965859.jpeg)

and receiving using Pluto SDR
![image](https://user-images.githubusercontent.com/29824411/71583802-0ff74580-2b21-11ea-9729-e6e0dba28ca3.png)

but unable to see any video stream. 

![image](https://user-images.githubusercontent.com/29824411/71584031-ed196100-2b21-11ea-8ca4-6b8fa496079b.png)

All checkboxes indicate the video is decoded.

Thanks

**Comment by f4exb** [comment]
This is displayed in your second screenshot

**Comment by khan2018** [comment]
I was using my android camera over the network using an app so DATV Express can take as an input. The video resolution said RGB in the end is it because of that I receive this green screen instead of the camera video ?

**Comment by khan2018** [comment]
I want to save raw I/Q data and I use the toggle button to record.
![image](https://user-images.githubusercontent.com/29824411/71631117-f684f500-2c17-11ea-9bf8-6507b8aa743c.png)
Where is the output file being saved?

Thanks!

**Comment by khan2018** [comment]
Is it possible to save .wav format ?

**Comment by f4exb** [comment]
File is saved in the directory where sdrangel is run and has a `.sdriq` extension. This is raw 2x16 or 2x32 integer samples (depends on sample size) and has a 32 bytes header described here: https://github.com/f4exb/sdrangel/tree/master/plugins/samplesource/fileinput.

File name is in the form rec<device#>_<timestamp>.sdriq. For example: `rec0_2020-01-02T17_33_17_191.sdriq`

**Comment by khan2018** [comment]
In windows 10, no such file is made in the installation directory...
