### ISSUE TITLE
I don't code well DRM

### ISSUE THREAD

**Issue by PedroJSaavedra777** [f4exb/sdrangel#465]
Hi. Thank you for your wonderful program. I have a problem with DRM decoding. When I put the module I can hear the broken voices and I can't hear his voice well. Am I doing something wrong? Because it can be? I also see that my DSD Demulator module does not have the Discriminator. Why? Thank you 😉

**Comment by PedroJSaavedra777** [comment]
Please! :_(

**Comment by f4exb** [comment]
RTF(abulous)M and you will know the purpose of the DSD demodulator...

**Comment by PedroJSaavedra777** [comment]
Thank you for your help and also for your arrogance.

**Comment by PedroJSaavedra777** [comment]
Thanks for your help. Yes, I have no idea, and researching and asking is the best way to learn.
