### ISSUE TITLE
SDRDaemon plugin is not in main build anymore

### ISSUE THREAD

**Issue by F5OEO** [f4exb/sdrangel#47]
Fresh install and see in the documentation, SDRDaemon plugin is missing from build..or I miss something. A commity is about to make some strike with a heavy slogan "Get Daemon back !". Feedback to solve the issue is more than welcome !

**Comment by f4exb** [comment]
Hello my friend!
SDRdaemon plugin has specific dependencies that if not met will prevent the build. These are:
  - libnanomsg (get it from distribution)
  - cm256cc (get it from https://github.com/f4exb/cm256cc)
Let us know if this solves the problem

**Comment by F5OEO** [comment]
Linux users are finally lazy ones...Even documented, general usage seems to be copy/paste of commandlines. In that concept, there are some missing parts.

**Comment by f4exb** [comment]
So is it working now?

**Comment by F5OEO** [comment]
"Yes captain" : Compiling cm256cc does the trick (RTFM)
