### ISSUE TITLE
Soapy support is not included in binary linux distributions

### ISSUE THREAD

**Issue by superfr0** [f4exb/sdrangel#472]
Checked the last few releases, I don't see any soapy files in the plugins dir, nor in the plugins view in the ui, and obviously it doesn't see my soapy device.  e.g.  sdrangel_4.13.0-1_amd64.deb.  

Is soapy support only available by source ?

I'm trying to run with an ettus device.  SoapySDRUtil --find see's it, so does gqrx.  There were previous reports that this should work via soapy.

**Comment by f4exb** [comment]
I just checked external/CMakeLists.txt and I can confirm this is not part of the Linux binary packages. I suppose there were good reasons for this and I do not want to venture again in the packaging hell.

So yes I confirm this is only available when compiling from source.
