### ISSUE TITLE
Could not start sample source [Solved]

### ISSUE THREAD

**Issue by magellan-13016** [f4exb/sdrangel#479]
Hi,
I'm David and I just discovered this software today. I'm using Linux Mint 19.3 and genuine RTL-SDR RTL2832U v3. All is OK with GQRX but I can't start it with SDRAngel.

I always get the error "Could not start sample source".

I have done the "export LD_LIBRARY_PATH=/usr/lib/sdrangel" command before but there is no way to start the dongle.

I'm using the last stable release : sdrangel_4.13.0-1_amd64.deb

Could you help me ?

Thanks, David.

**Comment by magellan-13016** [comment]
Solved ! Not working on Linux Mint 19.3 and my SDR Key. That's all.

**Comment by f4exb** [comment]
Due to the unwillingness of the logger to provide useful information other than "it does not work" this issue can indeed be closed.

**Comment by f4exb** [comment]
We had a very hot debate with the logger and now he banned my address from his mailing system so no direct contact is possible anymore. However on the positive side and for the larger public this made me reconsider a few things. I recognize my responsibility in what was not made clear. So I will consider these action points at the earliest:
  
  - make it clear what I consider as the fair use of this software
  - make it clear what is expected when posting issues
  - reconsider the distribution of binary artifacts. They tend to make you think that things are given for granted (I have this inclination too so I know it well). This is definitely what is NOT meant by Open Source (TBD in the "fair use" listed above):
    - remove artifacts from the releases section (done).
    - at least to be nice to the loyal users put it place a CI/CD system to build artifacts so that the build procedure is made clear, controlled and open to contributions

**Comment by k2extreme** [comment]
Hello,
I have similar problem but the problem appear when I'm trying to use two RTL-SDR RTL2832U v3 simultaneously. OS: Fedora 36. Edouard would you consider to solve the problem?

**Comment by f4exb** [comment]
you probably have the same serial ids for both. You need to change it with
rtl-sdr tools

**Comment by k2extreme** [comment]
Thank you very much for your help. I considered something wrong with ID's of dongles. So I will try the solution. Thank you. I will post info about result.

**Comment by k2extreme** [comment]
The solution is working:
Linux terminal command to define SN of RTL-SDR is:

rtl_eeprom -s nnnn 

this command works if only one of devices is connected to PC.
Thank you :)

**Comment by maximilien1990** [comment]
i have the same problem on arch with my hackrf. any suggestions?

**Comment by OskarZyg** [comment]
For anyone else stumbling upon this (I am on macOS 15.5, but this should apply to all platforms)
It appears the input device changes by itself. Navigate to the tab where you select the tuner settings (not sure what this is officially called), then press this:

![Image](https://github.com/user-attachments/assets/266abcf6-9ddd-4df2-bcda-506057af2d70)

You should then be able to select your RTL-SDR.

Sorry for reviving the dead post but I figured it's better to save someone the effort.
