### ISSUE TITLE
Windows eradication

### ISSUE THREAD

**Issue by f4exb** [f4exb/sdrangel#48]
Discontinue Windows support and remove all related files.

**Comment by F5OEO** [comment]
General strike ... why not ?

**Comment by f4exb** [comment]
In the end I cannot spend time on problems that are not with my software but with the O/S.

**Comment by f4exb** [comment]
This is also me getting angry at totally loosing my laptop installation due to a Win10 update walking over grub although it was not on the same volume.

Anyway at least Windows support is under close observation. In fact I was trying to run the latest version of SDRangel on Win10 because some problems were reported. Indeed a lot of plugins are not there without a valid reason since on Win7 everything worsk fine.

Sure I don't want to spend time on this kind of issue and move on to more feature and real bug fixes.

**Comment by f4exb** [comment]
After a full reinstall on the Win10 Vbox machine things look a lot better. I can even run SDRangel inside the Win10 Vbox machine which used to break at OpenGL init time.

**Comment by f4exb** [comment]
The same build works on my Win7 box so I think it is going to be the deal.
