### ISSUE TITLE
CM256CC

### ISSUE THREAD

**Issue by loewal** [f4exb/sdrangel#492]
Hi f4exb...sir,
Why do I have to comment out this line to be able to compile under macos?

if(CM256CC_FOUND)
#    add_subdirectory(remotesource)
endif(CM256CC_FOUND)
in CMakeLists.txt under sdrangel-master/plugins/channeltx ?

**Comment by f4exb** [comment]
I will downgrade dunctionality for Mac OS removing remotesource and remotesink if __APPLE__

**Comment by loewal** [comment]
Perfect!
And the compilationproblems with capitals/non-capitals in filenames?

**Comment by loewal** [comment]
et.....Chapeau!

**Comment by f4exb** [comment]
To be retrofitted in v4

**Comment by f4exb** [comment]
Implemented in v5.3.2 and v4.14.2

**Comment by ra1nb0w** [comment]
sdrangel with cm256cc works fine on macOS; see https://ports.macports.org/port/SDRangel/summary
