### ISSUE TITLE
Direct audio input/output sample device plugin

### ISSUE THREAD

**Issue by f4exb** [f4exb/sdrangel#496]
Following https://groups.io/g/sdrangel/topic/sdrangel_as_audio_spectrum/72473800 this ticket is opened to create an input and an output plugin to deal with audio stereo input and output as a sample source and sink plugin.

**Comment by hiperiondev** [comment]
Some notice of this enhancement?

**Comment by f4exb** [comment]
Output plugin done here: https://github.com/f4exb/sdrangel/commit/87d8816881d146d73a55368759af0c437ef0a8d2

**Comment by f4exb** [comment]
Audio Output implemented in v6.1.0
