### ISSUE TITLE
Adding device sink with virtual cable crashes SDRangel

### ISSUE THREAD

**Issue by loewal** [f4exb/sdrangel#499]
Hi,
Using Macos and before long Soundsource as a virtual cable. Under Catalina Soundsource didn't work anymore, so installed Blackhole (Github), also a virtual cable kext and normally running fine.
But helas, not with SDRangel. Both versions 4 and 5 (the latest) crash on adding a device sink.
Is doesn't matter what audio I selected.
Uninstalled Blackhole ;( and everything worked fine again

Not a regular situation perhaps, but is there an answer perhaps....?
Grtz. Loe

**Comment by f4exb** [comment]
Right "not a regular situation" and Mac O/S is not supported. However you may seek help from some Mac users that have managed to produce a workable software from the sources. See: https://groups.io/g/sdrangel
