### ISSUE TITLE
Compilation on Unbuntu 20

### ISSUE THREAD

**Issue by loewal** [f4exb/sdrangel#511]
Using the same sourcecode on Macos, which compiled well, on Ubuntu I get this:

/home/loe/Downloads/sdrangel-5.4.0/plugins/channeltx/modatv/atvmodsource.cpp: In member function ‘void ATVModSource::pullVideo(Real&)’:
/home/loe/Downloads/sdrangel-5.4.0/plugins/channeltx/modatv/atvmodsource.cpp:319:66: error: ‘CV_BGR2GRAY’ was not declared in this scope
  319 |                   cv::cvtColor(colorFrame, m_videoframeOriginal, CV_BGR2GRAY);
      |                                                                  ^~~~~~~~~~~
/home/loe/Downloads/sdrangel-5.4.0/plugins/channeltx/modatv/atvmodsource.cpp:446:75: error: ‘CV_BGR2GRAY’ was not declared in this scope
  446 |                     cv::cvtColor(colorFrame, camera.m_videoframeOriginal, CV_BGR2GRAY);
      |                                                                           ^~~~~~~~~~~
/home/loe/Downloads/sdrangel-5.4.0/plugins/channeltx/modatv/atvmodsource.cpp: In member function ‘void ATVModSource::openImage(const QString&)’:
/home/loe/Downloads/sdrangel-5.4.0/plugins/channeltx/modatv/atvmodsource.cpp:651:56: error: ‘CV_LOAD_IMAGE_GRAYSCALE’ was not declared in this scope
  651 |     m_imageFromFile = cv::imread(qPrintable(fileName), CV_LOAD_IMAGE_GRAYSCALE);
  
Somebody any idea?
Thanx

**Comment by f4exb** [comment]
Apparently it is possible to make OpenCV related code compatible for OpenCV versions both on Ubuntu 18.04 and 20.04

Implemented in v4.14.5 and v5.5.0
