### ISSUE TITLE
ATV demodulator Video window does not update

### ISSUE THREAD

**Issue by Davidi74** [f4exb/sdrangel#513]
Hi. 
In version 4.14.5 running on windows 10 1809, using the ATV demodulator, the video output does not update. If I move the ATV modulator window off the edge of the screen and back on again, it updates while I'm moving the window.

I did test it on 2 quite different PC's getting the same result.

Hoping you could help :)

**Comment by f4exb** [comment]
![atv](https://user-images.githubusercontent.com/6192319/80956028-ab1a6780-8e00-11ea-8a8d-fed767806b67.png)
Sorry this works perfectly
