### ISSUE TITLE
Upgrade to Ubuntu 20.04

### ISSUE THREAD

**Issue by f4exb** [f4exb/sdrangel#521]
Now 20.04 image is available in Appveyor. It is also present in Docker hub for amd64 and arm64. So all lights are green for an upgrade.

**Comment by f4exb** [comment]
Not possible yet because of XTRX incompatibility:
```
#60 105.3   Could NOT find PythonInterp (missing: PYTHON_EXECUTABLE) (Required is at
#60 105.3   least version "2.7")
```
https://github.com/xtrx-sdr/liblms7002m/blob/91b5107a11eb5335bbaf02ac0c744ea58d2a0b74/CMakeLists.txt#L44

**Comment by f4exb** [comment]
Other blocking point: sudo always asks for passwords despite the correct configuration in `/etc/sudoers`

**Comment by f4exb** [comment]
Updated XTRX version in my Github: https://github.com/f4exb/images
Using this version of XTRX I was able to compile and run in a 20.04 VM

**Comment by f4exb** [comment]
My changes in XTRX have been merged so this blocking point is lifted. Opened issue in Appveyor that has been classified as "bug" so expecting fix in next image release: https://github.com/appveyor/ci/issues/3434

**Comment by f4exb** [comment]
Problem with Appveyor has been fixed so it could be possible to release a 20.04 package at the next release.

**Comment by BX2ABT** [comment]
Problem when compiling:

```
CMake Error at /usr/lib/x86_64-linux-gnu/cmake/Qt5/Qt5Config.cmake:28 (find_package):
  Could not find a package configuration file provided by "Qt5Multimedia"
  with any of the following names:

    Qt5MultimediaConfig.cmake
    qt5multimedia-config.cmake

```
Problem is that there is no libqt5multimedia-dev in either Ubuntu 20.04 or 19.10.

**Comment by f4exb** [comment]
I guess you are trying to install 18.04 .deb on a 20.04 system. This will not work.

**Comment by f4exb** [comment]
Problem out of scope. `Qt5Multimedia` is not referenced in any of the cmake files.

**Comment by f4exb** [comment]
Since v4.14.10 the .deb packages in the release section are exclusively based on 20.04. Converting the dev environment to make sure everything is fine with 20.04 is the last step

**Comment by f4exb** [comment]
After trying Lubuntu 20.04 for some time I must say I am quite dissatisfied and disappointed with it. There are many bugs and too much details I don't like. Now considering Debian Buster + LXDE.

**Comment by f4exb** [comment]
After some trial period and despite a remaining issue with AirspyHF+ the new reference environment is now Ubuntu 20.04. This has been specified in the Wiki. This issue can be closed.
