### ISSUE TITLE
DVB-S2 frozing every 2 Seconds

### ISSUE THREAD

**Issue by dominik0815** [f4exb/sdrangel#525]
Hey Guys,

I want to use the DVB-S2-Mode for decoding QO-100 Satellite and test own transmissions localy. When I start decoding DVB-S it run really good, but when changing the protocoll to DVB-S2, it freeze the QPSK signal diagram every two seconds.

PC-Specs: Win10(64), AMD Ryzen 7, 32GB Ram, Vers. 4.14.7

It would be really nice to use SDR to receive Ham Satellite on PC.

Greetings, Dominik
![Unbenannt](https://user-images.githubusercontent.com/64140671/82461842-22b3ec00-9abb-11ea-896b-3a0e729e1541.gif)

**Comment by f4exb** [comment]
DVB-S2 is not workable for QO-100 as you need at least 15dB and preferably 20dB S/N to make it work.  

This behavior is normal and due to the processing that produces constellation points at a relatively slow rate particularly if it does not find synchronization which is the case with QO-100.

**Comment by dominik0815** [comment]
Sure, the Signal is to low. My Problem is, that the decoding does´nt run very smothely when the signal is strong enough.
![Unbenannt](https://user-images.githubusercontent.com/64140671/82555579-4e40e000-9b68-11ea-911f-fb2ac9c3df1f.gif)

**Comment by f4exb** [comment]
Question answered
