### ISSUE TITLE
SDR angle on window 10

### ISSUE THREAD

**Issue by virendera** [f4exb/sdrangel#527]
There is some layout issue on window 10.  Waterfall is not showing properly and sdrangle window not resizing. I know sdrangle is works better in linux although it is good on window also.

Thanks

**Comment by f4exb** [comment]
"Waterfall is not showing properly" => You have a graphics driver or some sort of graphics acceleraton issue. SDRangel is Qt based and Qt on Windows uses what it calls "Qt Angle": https://wiki.qt.io/Qt_5_on_Windows_ANGLE_and_OpenGL. You still need a recent enough version f DirectX. Nothing to be done on SDRangel code.

**Comment by f4exb** [comment]
Question answered
