### ISSUE TITLE
Funcube Dongle Pro+

### ISSUE THREAD

**Issue by loewal** [f4exb/sdrangel#528]
Qthid and Audacity were the hints...but helas, until now I haven't been able to let SDRangel (4 and 5) recognize my adapter.
Can anyone please?

**Comment by f4exb** [comment]
I suppose you run on Mac O/S and Mac O/S is not officially supported so please look for help from other Mac O/S users in the discussion group rather than opening an issue on Github: https://groups.io/g/sdrangel

**Comment by loewal** [comment]
Yes and no!
I'am running on Macos ánd Lubuntu.
The same issue. Not possible to recognize Funcube Donge Pro+.
And yes, qthid works and sees it and so does Audacity.
So......what else can I do.
Besides that, found nothing on the fora.

**Comment by f4exb** [comment]
Sorry but this works. Hence closed.
