### ISSUE TITLE
Allow more than 10MHz range on tuning dials

### ISSUE THREAD

**Issue by v0l** [f4exb/sdrangel#531]
Hi,

Could you please allow for more than 10MHz tuning range on channels and also on center frequency?

If the sample rate is > 20MS/s its not possible to tune lower or higher than 10MHz on any channels.

This is obviously not high priority but it would be nice to have.

![Screenshot from 2020-06-02 22-33-04](https://user-images.githubusercontent.com/1172179/83533164-cb356780-a521-11ea-8b1d-a0eed0acb73a.png)

**Comment by f4exb** [comment]
Well... it depends on the demodulator (or modulator). For narrowband FM as shown on the screenshot it is not sensible to use it on such a large baseband in the first place. This could be considered for channels that may use relatively large bandwidths like Wide FM, Broadcast FM, ATV, DATV.

**Comment by f4exb** [comment]
So... OK for wideband channel plugins.

**Comment by f4exb** [comment]
Implemented in v4.14.14 and v5.7.6
