### ISSUE TITLE
Bias-T for RTL-SDR v3

### ISSUE THREAD

**Issue by febs** [f4exb/sdrangel#533]
Here's another feature request.

The most modern RTL-SDR (version 3) is capable of providing 4.5 volts "via" bias-tee, which can be enabled "entirely in software" [https://www.rtl-sdr.com/rtl-sdr-blog-v-3-dongles-user-guide/](https://www.rtl-sdr.com/rtl-sdr-blog-v-3-dongles-user-guide/)

It would be super cool to be able to toggle it via sdrangel, just as it can be done with the hackrf nowadays.

Thanks,

**Comment by f4exb** [comment]
It shouldn't be too difficult provided the function is available in mainstream. It looks like something like this: `rtlsdr_set_bias_tee(dev, enable_biastee);`

**Comment by febs** [comment]
Just tested with a multimeter and it works great. Thanks!

**Comment by f4exb** [comment]
Thanks for confirming I have no v.3 available.
