### ISSUE TITLE
Freezes Shortly After Start - WIndows 7

### ISSUE THREAD

**Issue by mirskym** [f4exb/sdrangel#538]
Just installed SDRAngel for first time. Have a Windows 7 64 bit computer. Used the .exe install. After srtating I get the main panel showing but then immediately freezes and says at the top of the Window "not responding".

I updated all my drivers. My grahpics card is Radeon HD 4200 and OPENGL is working.

What can I do?

**Comment by mirskym** [comment]
I also have Visual C++ installed. The processor is an AMD.

**Comment by f4exb** [comment]
The .exe is built on a Windows 10 machine (VM on Appveyor) so there are no assumptions that it would work on Windows 7. So sorry no support can be provided here.
