### ISSUE TITLE
High side transverter LO

### ISSUE THREAD

**Issue by dl3yc** [f4exb/sdrangel#539]
Hi, is there a possibility to use a high side lo? e.g. 10368 MHz translates to 2312 MHz with an LOF of 12680 MHz, so i need a spectrum inversion and a change in transverter lo handling? (sdr freq = abs(freq - lo_freq))
How to implement this?

**Comment by f4exb** [comment]
Yes it is possible in the transverter settings. With the shift set as 0 Hz it will also be possible to simply invert the spectrum. An issue is already opened for this here: https://github.com/f4exb/sdrangel/issues/493

**Comment by f4exb** [comment]
Closed as #493 is closed
