### ISSUE TITLE
 private

### ISSUE THREAD

**Issue by gaspar1987** [f4exb/sdrangel#540]
Hello, I wanted to know how to make the p.
Go active.
The private one.
From.
Small locker. If it had to put it in 99 to listen to the sound perfectly in.
But without the sound.
Fifty. I don't know, I'd like a little help.
I'll take the picture for you.
To explain my body.
yes, I don't know what to do.
![image](https://user-images.githubusercontent.com/13591469/84751090-729fa900-afbc-11ea-8fcb-d87264a0e7b3.png)

**Comment by f4exb** [comment]
This is the basic privacy index from 0 (no BP active) to 255. Just flip through until you hear something readable or (better as you are not supposed to break privacy ;-) ) set it to the value given by the service.

**Comment by gaspar1987** [comment]
J'ai testé avec mon petit walki mais ça ne font pas le mode manuel le son
est un peu n'est pas clair. C'est pour cela que je ne comprends pas
pourquoi il est en mode Manuel le BP au lieu aussi d'être automatique je ne
comprends pas.

**Comment by markcarter00** [comment]
how can i get sdrangel with bp softwear for windows download my emaill is myscanner22@hotmail,com
