### ISSUE TITLE
Feature request : dPMR and NXDN descrambler

### ISSUE THREAD

**Issue by TheDefender44** [f4exb/sdrangel#548]
Hello,
First of all, thank you very much for the great work you are doing on this software.

Just like the recently implemented BP feature in SDRAngel, do you have any consideration in implementing a similar dPMR and NXDN 15-bit descrambler feature to the software through DSDcc?

It would be great if the user could directly enter a known key out of the 32767 existing ones. 

The scrambling format is well documented for both modes on the ETSI technical specifications, and is not technically too complicated to implement.

Thank you in advance for your response.

**Comment by f4exb** [comment]
There are already too many issues with DMR BP so I am not going to implement any kind of encryption in any mode any way
