### ISSUE TITLE
Build fail on Raspian Jessie

### ISSUE THREAD

**Issue by bferrell** [f4exb/sdrangel#55]
[  7%] Building CXX object CMakeFiles/sdrbase.dir/sdrbase/audio/audiooutput.cpp.o
/usr/local/src/sdrangel/sdrbase/audio/audiooutput.cpp: In member function ‘bool AudioOutput::start(int, int)’:
/usr/local/src/sdrangel/sdrbase/audio/audiooutput.cpp:93:56: error: ‘qInfo’ was not declared in this scope
             qInfo("AudioOutput::start: audio format OK");
                                                        ^
CMakeFiles/sdrbase.dir/build.make:274: recipe for target 'CMakeFiles/sdrbase.dir/sdrbase/audio/audiooutput.cpp.o' failed
make[2]: *** [CMakeFiles/sdrbase.dir/sdrbase/audio/audiooutput.cpp.o] Error 1
CMakeFiles/Makefile2:137: recipe for target 'CMakeFiles/sdrbase.dir/all' failed
make[1]: *** [CMakeFiles/sdrbase.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by f4exb** [comment]
qInfo is declared in QtGlobal and is one of the base headers of Qt so I think you installation of Qt is not correct.

Anyway there is no hope to have SDRangel working correctly in Raspbian Jessie even on a RPi3.
