### ISSUE TITLE
Is Sdrangel tested against xtrx PCIe or xtrx USB ?

### ISSUE THREAD

**Issue by OhSoGood** [f4exb/sdrangel#551]
Hi,

I was wondering on what platform XTRX owners were testing : with the USB version and/or the PCIe version? A friends and I have the XTRX-CS on PCIe (not the XTRX Pro) and whatever we do (under gnuradio, soapy, sdrangel, we always get flat spectrum, even when the sdr is connected by SMA cable to a signal generator. With other SDR (blade or usrp), everyhting is fine. So, could it be that none of you tested the same combination as us - ie XTRX-CS on PCIe (which looks unlikely), or that our xtrx are simply dead ? Or would you see blattant mistake in our settings of SDRAngel?

We have tried to ask Fairwaves, but these unfair guys never answer. Worst, the co-founder and main software/firmware developer has just left the company.

Here is what we get under Ubuntu 20.04, with a version compiled as of today:
![SDRAngel XTRX](https://user-images.githubusercontent.com/1809098/85765744-b0b46f80-b716-11ea-9687-a61d76f36fdb.png)

**Comment by f4exb** [comment]
I can confirm that I only test against XTRX USB. I don't have a PCIe and not aware of differences in handling. Apparently there might be...

**Comment by f4exb** [comment]
I think this answers the question. I have not the appropriate hardware to develop a PCIe version if this is any different. This cannot be carried on further.
