### ISSUE TITLE
SDRangel compile macOS Big Sur

### ISSUE THREAD

**Issue by loewal** [f4exb/sdrangel#552]
Until now I could compile flawlessly, but now with errors:
[ 28%] Building CXX object sdrbase/CMakeFiles/sdrbase.dir/websockets/wsspectrum.cpp.o
[ 28%] Building CXX object sdrbase/CMakeFiles/sdrbase.dir/mainparser.cpp.o
make[2]: *** No rule to make target `/usr/lib/libm.dylib', needed by `lib/libsdrbase.dylib'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[ 28%] Building CXX object sdrbase/CMakeFiles/sdrbase.dir/sdrbase_autogen/3YJK5W5UP7/qrc_webapi.cpp.o
make[1]: *** [sdrbase/CMakeFiles/sdrbase.dir/all] Error 2
make: *** [all] Error 2

As mentioned: running under "Big Sur"....somebody??

**Comment by f4exb** [comment]
Issues regarding Mac OS are not supported here. You may however seek help from Mac users who managed to run SDRangel on Mac in the discussion group: https://groups.io/g/sdrangel
