### ISSUE TITLE
Initialisation of AM Demod consumes 2.7 GB of RAM

### ISSUE THREAD

**Issue by Vort** [f4exb/sdrangel#554]
Class `AMDemodSink` contains field `m_audioSampleRate`, which is not initialised at constructor `AMDemodSink::AMDemodSink()`.
Because of this, when `AMDemodBaseband` is created inside `AMDemod::AMDemod(DeviceAPI *deviceAPI)`, `AMDemodSink::applySettings(const AMDemodSettings& settings, bool force)` function executes line:
https://github.com/f4exb/sdrangel/blob/9c05329bb3dc12b828f065e7aa7d00ed84b3de1f/plugins/channelrx/demodam/amdemodsink.cpp#L286
And if accidently `m_audioSampleRate` contains large value, huge array becomes allocated:
![amdemod_oom](https://user-images.githubusercontent.com/1242858/86012969-4c035880-ba27-11ea-9b15-fc55a2e99eb5.png)

**Comment by f4exb** [comment]
That's right thanks for pointing out. It is in fact used all over the place. It will eventually be set through the rest of the application but it can create a lot of intermediate havoc. It can be initialized with an arbitrary value like 48000.

**Comment by f4exb** [comment]
I will also chase this bug in other plugins having audio that may be affected in a similar way.

**Comment by febs** [comment]
I guess this is why SDRangel hang indefinitely when adding an audio plugin in the Docker image.

**Comment by f4exb** [comment]
It depends... if you look at the above commit you will see that not all plugins are affected.
