### ISSUE TITLE
c est quand le  noveau  dsdcc .

### ISSUE THREAD

**Issue by gaspar1987** [f4exb/sdrangel#558]
![Capture](https://user-images.githubusercontent.com/13591469/86815737-49d27700-c083-11ea-9392-f0cf35322621.PNG)
Acteur.
Qui a créé des sdrangel.
Je voulais vous dire que il manque quelque chose pour améliorer votre.
Votre sdr .
Il me manque.
Le BP n ai pas mode automatique.
Non.
Le problème, c'est que ça ne fonctionne pas.
Quand je le fais manuellement.

**Comment by f4exb** [comment]
?

**Comment by f4exb** [comment]
What is that you do not understand in my comments in https://github.com/f4exb/sdrangel/issues/540
Please stop polluting this board
