### ISSUE TITLE
PlutoSDR Tx support

### ISSUE THREAD

**Issue by f4exb** [f4exb/sdrangel#56]
Opened to complete PlutoSDR support without delaying the PlutoSDR Rx support.

**Comment by f4exb** [comment]
This will also include refactoring to better split between model and view. For LimeSDR for example when a change occurs on one side (Rx, Tx) the necessary changes on the other side are propagated through the GUI which is a very bad design in view of the future headless version. A similar mechanism is necessary for PlutoSDR Rx/Tx propagation.

**Comment by rgetz** [comment]
I have been playing with PlutoSDR Rx, and this seems to work pretty well (Thanks for the work).

You are correct - while the LOs are completely independent - the ADC and the DAC interface clock rates are linked. Which isn't super intuitive to someone not familiar with the underlying chips.

If you have questions - please let me know.

**Comment by f4exb** [comment]
Implemented in v3.7.1
