### ISSUE TITLE
ATV Demod: Incorrect initialization of sample rate

### ISSUE THREAD

**Issue by Vort** [f4exb/sdrangel#560]
Steps to reproduce:
1. Download and unpack [hacktv_dec5.7z.zip](https://github.com/f4exb/sdrangel/files/4888801/hacktv_dec5.7z.zip) (7-zip + zip).
2. Start sdrangel.
3. Select FileInput source.
4. Select `hacktv_dec5.sdriq` as signal source file.
5. Add ATV Demodulator.
6. Set parameters: AM, HSync, VSync, Inv.
7. Press "Start" button.

<details>
  <summary>Result looks like this:</summary>
  
  ![image](https://user-images.githubusercontent.com/1242858/86883482-b9377d80-c0fa-11ea-8487-490d2a675d79.png)
  
</details>

This happens because of incorrect initialization.
At some time samplerate of 48k is fed into ATVDemodBaseband object.
<details>
<summary>Hackfix looks like this:</summary>
  
```patch
diff --git a/plugins/channelrx/demodatv/atvdemodbaseband.cpp b/plugins/channelrx/demodatv/atvdemodbaseband.cpp
index 750fd1a1b..cd1323f73 100644
--- a/plugins/channelrx/demodatv/atvdemodbaseband.cpp
+++ b/plugins/channelrx/demodatv/atvdemodbaseband.cpp
@@ -127,6 +127,8 @@ bool ATVDemodBaseband::handleMessage(const Message& cmd)
     {
         QMutexLocker mutexLocker(&m_mutex);
         DSPSignalNotification& notif = (DSPSignalNotification&) cmd;
+        if (notif.getSampleRate() == 48000) // oh really?
+            return true;
         qDebug() << "ATVDemodBaseband::handleMessage: DSPSignalNotification: basebandSampleRate: " << notif.getSampleRate();
         m_sampleFifo.setSize(SampleSinkFifo::getSizePolicy(notif.getSampleRate()));
         m_channelizer->setBasebandSampleRate(notif.getSampleRate()); 
```

</details>

But, of course, proper solution should be implemented.

**Comment by f4exb** [comment]
Maybe a more general issue with the file input because the actual sample rate is not known before the file is opened but at that time maybe the actual sample rate is not propagated correctly. Until the file is open as some objects need to be initialized an arbitrary sort of making sense sample rate must be given.

I think the ATV plugin should work if you use an actual transmitter with the file as a file source.

**Comment by Vort** [comment]
ATV plugin initializes correctly if I hit "Start" before adding ATV Demodulator.
I guess the problem is related to this 48k value:
![image](https://user-images.githubusercontent.com/1242858/86892386-da9f6600-c108-11ea-8b52-5aaf3a9948b9.png)
File is opened, header is read, I thinks FileInput have all needed information to initialize it correctly.
By the way, why there are two sample rates in UI?
Also, AM demod have no such problem (but maybe because AM demod works differently).

**Comment by f4exb** [comment]
Indeed this inconsistency in the UI may be the indication of more inconsistencies and leads me to think the root cause is in the File Input plugin.

**Comment by f4exb** [comment]
Done in v4.14.16 and v5.7.10
