### ISSUE TITLE
SoapySDR: Connect to a SoapyRemote

### ISSUE THREAD

**Issue by 7Grok** [f4exb/sdrangel#583]
Hi

For the life of me I can't figure out how to make and use the equivalent of a connection string. If my laptop is on the same network as the SopayRemote sever Everything Just Works™, but I would like the ability to enter the remote address. Is there an equivalent of `soapy=0,driver=remote,remote=tcp://server:port`

As an FYI I compiled sdrangel on Mac OS by following the wiki. The only change I made was disabling devices that I don't have and it all works. My Bladerf via local usb and via SopayRemote works. Love the program and the docs any thoughts on setting up a pipeline to verify Mac OS compile?

--
Thanks
André

**Comment by 7Grok** [comment]
Progress .. at least with the custom device menu. I no receive an error that says cant open device, but not much in the debug logs.

**Comment by synthead** [comment]
Did you ever find a solution to this issue?

**Comment by 7Grok** [comment]
No. Sorry. I found an old issue that explains why if you feel like digging.
