### ISSUE TITLE
plutosdr: v0.32 and sdrangel on windows/linux -- rx audio stutter; tx not tested.

### ISSUE THREAD

**Issue by roelandjansen** [f4exb/sdrangel#589]
I have recently installed sdrangel 4.14.20 on windows and compiled from source on linux the same version.
I also updated the f/w to 0.32. Flashing takes pretty long compared to 0.31 (as in, maybe 4x longer?)

Anyways, 0.32 gives a stuttering sound ; reverting back to 0.31 gives a smooth sound.

Not sure if this is sdrangel related or v0.32 related or both.

**Comment by roelandjansen** [comment]
https://github.com/analogdevicesinc/plutosdr-fw/issues/53

**Comment by f4exb** [comment]
Just pulled out my Pluto with older firmware and I cannot make it work. It strangely displays the maximum possible frequency and cannot be moved from there. Not sure this is the same issue.

**Comment by f4exb** [comment]
I confirm that after upgrade to FW 0.32 Pluto does not work properly with SDRangel even with latest libiio (v0.21).

**Comment by f4exb** [comment]
It seems not to be in control of the code in SDRangel or something has changed that would require an update but only possile with guidance of the Pluto/libiio team. So for the time being stay with FW 0.31 on the Pluto.

**Comment by f4exb** [comment]
Closed in favor of #604
