### ISSUE TITLE
I have a problem with the recorder

### ISSUE THREAD

**Issue by gaspar1987** [f4exb/sdrangel#591]
Hello sir, I have a problem with the recorder.
I don't know why it doesn't work if you can put it all back to 0 for mode.
Mode.
Put it back to 0. That's it, I'd like to know thank you.
Mr.
Your web developer is great.
I.
Listen to the radio every day with it.
Nice day.

**Comment by f4exb** [comment]
Understandable... Anyway the file recording feature is being reworked completely.

**Comment by f4exb** [comment]
I/Q file recording is now handled via the FileSink plugin: https://github.com/f4exb/sdrangel/tree/master/plugins/channelrx/filesink
