### ISSUE TITLE
QT virtual keyboard

### ISSUE THREAD

**Issue by hiperiondev** [f4exb/sdrangel#595]
I'm using sdrangel on a touch screen device.
The problem is that is not possible to change frequency without a physical keyboard .
In others programs (like kterm) I use QT_IM_MODULE=qtvirtualkeyboard to start on screen keyboard but in sdrangel doesn't work

**Comment by Vort** [comment]
I was able to make keyboard appear, but:
1. It works only for main window and not for popup windows (clicks on keys do nothing there).
2. It not appears when I click on frequency controls (maybe they are custom and have no support for virtual keyboard).

**Comment by Vort** [comment]
Looks like I was able to make it work.
@hiperiondev, do you know how to test patches? Can you look if this change is ok: https://github.com/Vort/sdrangel/commit/73b221f05515ca8257db854bae974bc8231d312d ?

**Comment by hiperiondev** [comment]
I'll try to recompile sdrangel this afternoon

**Comment by hiperiondev** [comment]
Doesn't work and can't change dial with physical keyboard now

**Comment by hiperiondev** [comment]
No start virtual keyboard on dial.

**Comment by Vort** [comment]
> No start virtual keyboard on dial.

Do it shows with another UI controls?
Like server address in KiwiSDR input plugin.

**Comment by hiperiondev** [comment]
My bad!!! Sorry.
Yes, it's working on dial and others UI controls

**Comment by Vort** [comment]
@f4exb did not reviewed the fix yet, so no need to close report yet.

**Comment by Vort** [comment]
I made pull request for this fix: #598.
