### ISSUE TITLE
I/Q audio sink with SoapyAudio?

### ISSUE THREAD

**Issue by hiperiondev** [f4exb/sdrangel#596]
Is it possible to send the signal in transmission through the audio card to drive a cheap sdr transmitter? maybe through SoapyAudio?

**Comment by Vort** [comment]
Looks like transmission support in SoapyAudio is broken :(
_(but, maybe, I am trying to use it in a wrong way, do not know)_
<details>
<summary>Screenshot of SoapySDRUtil output</summary>

![soapyaudio](https://user-images.githubusercontent.com/1242858/90099954-4e561380-dd44-11ea-965d-9a754503e2a6.png)

</details>

**Comment by f4exb** [comment]
Soapy being not a that great option this ticket was open for direct Audio support: https://github.com/f4exb/sdrangel/issues/496
So it is in the plans...

**Comment by f4exb** [comment]
To be superseded by #496
