### ISSUE TITLE
Send i/q signals to local process

### ISSUE THREAD

**Issue by hiperiondev** [f4exb/sdrangel#606]
Is it possible to send the modulated i/q signals of a sink?
I think that a local output would be correct but it is not clear in the documentation how to indicate the process or pipe and what data would be received

**Comment by hiperiondev** [comment]
This question is associated with the need to output these signals by audio while waiting for the full implementation to take place (perhaps with gnu-radio for now).
In my case I have a sdr-rtl for reception and two sound cards, one will be used for audio and microphone and the other for the output to the sdr

**Comment by f4exb** [comment]
As the name implies "local" stays local to the SDRangel instance and these plugins can be used for transfer between device sets (i.e. tabs in the GUI).
  - LocalOutput in one tab -> LocalSource in another tab (for Tx)
  - LocalSink in one tab -> LocalInput in another tab (for Rx)

**Comment by f4exb** [comment]
Question answered
