### ISSUE TITLE
Rollup Widget collapse section issue

### ISSUE THREAD

**Issue by dmtrbm** [f4exb/sdrangel#608]
When collapsing device pane by clicking the triangle - it disappears completely, making it impossible to expand again. 
![devices](https://user-images.githubusercontent.com/70113934/90988935-4ea1aa80-e59f-11ea-8bcd-177d7d6a6363.jpg)
Versions v4.14.20/v5.8.5 work as expected. Linux, qt-5.15.0.

Thank you.

**Comment by f4exb** [comment]
Nothing to do with Qt or glibc versions it happens with Qt 5.12.8. I suspect a side effect of commit d80d050992e87e30f5a4ad560a5d06a6b921442e

**Comment by f4exb** [comment]
A quick check confirms that reverting this commit fixes the issue. This does not change the fact that the original change was supposed to make things better when a dialog is opened from this widget. The RollupWidget base design is bad. This can be covered in another more specific issue.
