### ISSUE TITLE
ATV Demod Line and H Pulse sliders missing in 4.15.2

### ISSUE THREAD

**Issue by srcejon** [f4exb/sdrangel#618]
In SDRangel 4.15.2, it seems the ATV Demodulator Line and H Pulse sliders are missing:

![ATVDemod](https://user-images.githubusercontent.com/57259258/91349757-a6c5f000-e7dd-11ea-9b49-756753d20cab.PNG)

They are there in the 4.15.0 release.

Without being able to adjust Line timing, I can't receive a stable image, as it seems Line always needs to be adjusted slightly from the default value. (I'm transmitting with SDRangel ATV modulator. E.g. 625 5FPS PAL625 needs adjusting from 320us to 315us)

**Comment by srcejon** [comment]
I just noticed the 4.15.1 release note relating to the ATV Demod changes, states "Some controls and displays became obsolete". If the Line slider is intentionally obsolete, why might I not be receiving an image correctly? Here's a screenshot showing both Mod and Demod settings. 

![ATVTXRX](https://user-images.githubusercontent.com/57259258/91353039-995f3480-e7e2-11ea-9e64-d321d09d593d.PNG)

Thanks.

**Comment by f4exb** [comment]
Sorry it works and line length tweaking is completely useless this is why it was removed.

You have to check your setup or use different hardware. 

Tx is HackRF wti same sample rate:
![image](https://user-images.githubusercontent.com/6192319/91492407-e52ede00-e8b5-11ea-8784-60a5c63dd951.png)

Rx is Lime mini same sample rate:
![image](https://user-images.githubusercontent.com/6192319/91492508-11e2f580-e8b6-11ea-8f19-6a7310612391.png)

**Comment by srcejon** [comment]
Thanks f4exb, seeing all of your settings have helped getting it working. For anyone else that might read this, the settings that needed to be adjusted from defaults were:

Uniform level luminance 50 -> 100
Sync 150mV -> 100mV
