### ISSUE TITLE
Client server architecture

### ISSUE THREAD

**Issue by sysardex** [f4exb/sdrangel#621]
As I understand it, sdrangel supports client-server architecture. But somehow strange. For example, when using the remote sink plugin, I cannot change the frequency on the client side. Is it possible to use full server control from the graphical client?

**Comment by f4exb** [comment]
This is not the design that has been chosen. Control of the server is done via its http REST API by an external application. This  can be done for example with the SDRangelcli web application: https://github.com/f4exb/sdrangelcli

**Comment by f4exb** [comment]
Question answered
