### ISSUE TITLE
Question on the functioning of the "UDP Sample Sink" plugin

### ISSUE THREAD

**Issue by choupette-change** [f4exb/sdrangel#623]
Hello everyone, when I press the "Toggle audio input" button of the UDP Sample Sink plugin, set to NFM or NFM Mono, I do not perceive any sound (the squelch is green, sq gate 0 ms) while it is working on other plugin ( NFM demodulator eg), can you help me get it working? (same for the button "Toggle mono / stereo audio input which remains gray).

**Comment by f4exb** [comment]
This is an audio return path from the process you send the UDP samples to.

**Comment by choupette-change** [comment]
Thank you for your answers even if I did not understand everything ... I am a beginner

**Comment by f4exb** [comment]
Question answered
