### ISSUE TITLE
segfault after stopping then restarting acquisition

### ISSUE THREAD

**Issue by srcejon** [f4exb/sdrangel#626]
Hi,

If I run SDRangle, select TestSource as sampling device, with no demodulators, then press:

start acquisition
stop acquisition
start acquisition

I seem to repeatedly get a segfault.

Testing SDRangel 4.15.0 and .2 on both Ubuntu 20 and Windows 10.

It can also happen when Soapy UHD source is selected as well.

**Comment by f4exb** [comment]
The `TestSourceWorker` is created and deleted at each start/stop sequence this apparently is causing the trouble. If it is created in the constructor of `TestSourceInput` and deleted in its destructor then the problem does not happen.

**Comment by f4exb** [comment]
Implemented in v4.15.5 and v5.10.1
