### ISSUE TITLE
v3.7.1 gain slider is inactive with RTL-SDR source.

### ISSUE THREAD

**Issue by kovinesinsila** [f4exb/sdrangel#63]
Hi, as the title says, gain slider is not draggable. Linux, Qt 5.9.1.

**Comment by f4exb** [comment]
It appears that since 3.7.1 the gains do not get back from the device handler to the GUI

**Comment by f4exb** [comment]
The way the gains get retrieved does not work anymore with the new source and its GUI life cycle. The gains should be reported the GUI as soon as the GUI queue pointer is set in the source.

**Comment by f4exb** [comment]
Fixed in v3.7.2
