### ISSUE TITLE
Feature plugin: simple PTT

### ISSUE THREAD

**Issue by f4exb** [f4exb/sdrangel#635]
This is to re-implement [the PTT script](https://github.com/f4exb/sdrangel/blob/master/swagger/sdrangel/examples/ptt.py) in a feature plugin with more or less the same functionality (may be less to keep it "simple"). Its first purpose is to exercise and tune the feature plugins framework with a very simple plugin.

**Comment by Radiomix2000** [comment]
It would be really cool to add some hardware PTT functinality as well (using serial COM port for PTT is the most simplest way). So using PTT pedal will become again actual :)

**Comment by f4exb** [comment]
But this is not "simple" anymore so I will keep this one under the KISS rule. Later on all sort of crap could be added to a "complex" PTT.

**Comment by f4exb** [comment]
Implemented for v5 branch in v5.12.0

**Comment by f4exb** [comment]
Done in v4.18.0
