### ISSUE TITLE
PPM slider's "polarity" is reversed with soapysdr source.

### ISSUE THREAD

**Issue by dmtrbm** [f4exb/sdrangel#641]
Select RTL-SDR source, set correction to 0, tune to continuous signal.
Moving slider left and right moves the signal to the left and right respectively.
With SoapySDR source it's reversed and also opposite of "CORR freq" dial's behavior.

**Comment by f4exb** [comment]
The "LO ppm" slider is a soft correction on the top of other corrections. The actual frequency is shifted from the face value. Possibly the calculation is done the wrong way for SoapySDR Input.

**Comment by f4exb** [comment]
Fixed in v4.17.0
