### ISSUE TITLE
Add RX channel adds a TX channel instead

### ISSUE THREAD

**Issue by srcejon** [f4exb/sdrangel#645]
Hi,

Using SDRangel 4.16.1. If I:

- Run SDRangel
- Select menu Device Sets > Add sink device set
- In the channels panel, select R0 to view RX channels
- Press the new Add Channels + button
- Select Broadcast FM Demodulators
- Press apply
- Nothing appears in the RX channels 
- Instead, a modulator will have appeared in the TX channels (in my case a File Source modulator, because that it third on the list like the Broadcast FM Demodulator)

Also looks to be a problem if you have multiple source device sets.

**Comment by f4exb** [comment]
Yes issue is here: https://github.com/f4exb/sdrangel/blob/master/sdrgui/mainwindow.cpp#L1825
This is not `tabInputsView` but `tabChannels` that should be used.
