### ISSUE TITLE
Error compiling bladeRF with gcc10

### ISSUE THREAD

**Issue by hiperiondev** [f4exb/sdrangel#666]
In fedora 32 with gcc (GCC) 10.2.1 20201016 (Red Hat 10.2.1-6) compilation breaks with:
/var/tmp/SDRANGEL/SRC/bladeRF/host/libraries/libbladeRF/src/board/bladerf1/bladerf1.c: En la función ‘bladerf1_open’:
/var/tmp/SDRANGEL/SRC/bladeRF/host/libraries/libbladeRF/src/board/bladerf1/bladerf1.c:841:38: error: implicit conversion from ‘enum <anónimo>’ to ‘enum <anónimo>’ [-Werror=enum-conversion]
  841 |     dev->flash_arch->status          = STATE_UNINITIALIZED;

This error was corrected in lastest release:
https://www.mail-archive.com/debian-bugs-rc@lists.debian.org/msg568788.html

**Comment by f4exb** [comment]
Fedora is unsupported.
