### ISSUE TITLE
compile SoapyHackRF breaks old libhackrf

### ISSUE THREAD

**Issue by hiperiondev** [f4exb/sdrangel#667]
compile SoapyHackRF breaks with:
--   Reading /opt/install/libhackrf/include/libhackrf/hackrf.h...
CMake Error at CMakeLists.txt:25 (file):
  file failed to open for reading (No such file or directory):

    /opt/install/libhackrf/include/libhackrf/hackrf.h

CMake Error at CMakeLists.txt:28 (message):
    libhackrf too old, missing hackrf_device_list API

-- Configuring incomplete, errors occurred!

**Comment by f4exb** [comment]
Please check https://github.com/f4exb/sdrangel/wiki/Compile-from-source-in-Linux#hackrf
In particular this line:
`git reset --hard "v2018.01.1"`
