### ISSUE TITLE
NFM demod issue

### ISSUE THREAD

**Issue by kasper93** [f4exb/sdrangel#674]
Hi,

I noticed that filtering is quite weak. I constantly hear CTCSS tone.

Recorded audio (CTCSS 156.7Hz, different recordings, but it doesn't matter), few seconds of signal with some silence: 
High-pass filter enabled:
![image](https://user-images.githubusercontent.com/1126053/97513005-53ae1c00-198b-11eb-8955-f1735350f77d.png)

High-pass filter disabled:
![image](https://user-images.githubusercontent.com/1126053/97513175-ce773700-198b-11eb-8186-f0d8f71c1bad.png)

While filtering is working the tone is still very audible, it makes little difference to actual output audio. Also I have set AFBW to 3k. Could we improve this situation? 

For reference SDR# (without any filtering, just demod) produces perfectly clear audio without any noticeable sigh of this tone, look at this 300Hz cut-off:
![image](https://user-images.githubusercontent.com/1126053/97514472-13e93380-198f-11eb-8714-bf87d48fd24b.png)

And small GUI issue, CTCSS tone frequency is not displayed. It always stays at `--`. Squelch works fine if I select different freq, so just the current value doesn't seem to be passed to GUI.

**Comment by f4exb** [comment]
Very obviously SDR# uses a FFT boxcar filter. Indeed there is a GUI feedback issue.

**Comment by kasper93** [comment]
I fixed all things that bothered me. Will send PR later and we can discuss it further.

**Comment by f4exb** [comment]
Fix on-going on my side along with extension of CTCSS codes (Issue #664)

**Comment by kasper93** [comment]
Since I had some changes already done I pushed them. Feel free to do the changes your way :) Mostly minor adjustments in fact, but as I was debugging I refactored some parts also.

**Comment by kasper93** [comment]
I guees, it is fixed now.

**Comment by f4exb** [comment]
Implemented in v4.21.1 and 5.15.1
