### ISSUE TITLE
IQ correction average window size

### ISSUE THREAD

**Issue by kasper93** [f4exb/sdrangel#692]
I bumped averaging window, but I don't know what values might be optimal and if it isn't too much.

167.000 MHz is center frequency.

## Correction off:
![image](https://user-images.githubusercontent.com/1126053/98456829-e451dc80-2181-11eb-8749-b60cb7059f9d.png)

## DC+IQ correction (default values):
Notice overshoot DC correction and mirrored image. 
![image](https://user-images.githubusercontent.com/1126053/98456875-0c414000-2182-11eb-88d7-26aeec72df42.png)

## DC+IQ correction (10024 averaged samples):
![image](https://user-images.githubusercontent.com/1126053/98456895-29760e80-2182-11eb-9fee-da2a50d7e02e.png)

I simply bumped number of averaged samples, not sure it is correct fix. I could adjust the values, but would need better testing methodology...
``` diff
diff --git a/sdrbase/dsp/dspdevicesourceengine.h b/sdrbase/dsp/dspdevicesourceengine.h
index 83a92c582..64bd25f8d 100644
--- a/sdrbase/dsp/dspdevicesourceengine.h
+++ b/sdrbase/dsp/dspdevicesourceengine.h
@@ -97,26 +97,26 @@ private:
 	bool m_iqImbalanceCorrection;
 	double m_iOffset, m_qOffset;
 
-	MovingAverageUtil<int32_t, int64_t, 1024> m_iBeta;
-    MovingAverageUtil<int32_t, int64_t, 1024> m_qBeta;
+	MovingAverageUtil<int32_t, int64_t, 1024 * 10> m_iBeta;
+	MovingAverageUtil<int32_t, int64_t, 1024 * 10> m_qBeta;
 
 #if IMBALANCE_INT
     // Fixed point DC + IQ corrections
-    MovingAverageUtil<int64_t, int64_t, 128> m_avgII;
-    MovingAverageUtil<int64_t, int64_t, 128> m_avgIQ;
-    MovingAverageUtil<int64_t, int64_t, 128> m_avgPhi;
-    MovingAverageUtil<int64_t, int64_t, 128> m_avgII2;
-    MovingAverageUtil<int64_t, int64_t, 128> m_avgQQ2;
-    MovingAverageUtil<int64_t, int64_t, 128> m_avgAmp;
+    MovingAverageUtil<int64_t, int64_t, 1024 * 10> m_avgII;
+    MovingAverageUtil<int64_t, int64_t, 1024 * 10> m_avgIQ;
+    MovingAverageUtil<int64_t, int64_t, 1024 * 10> m_avgPhi;
+    MovingAverageUtil<int64_t, int64_t, 1024 * 10> m_avgII2;
+    MovingAverageUtil<int64_t, int64_t, 1024 * 10> m_avgQQ2;
+    MovingAverageUtil<int64_t, int64_t, 1024 * 10> m_avgAmp;
 
 #else
     // Floating point DC + IQ corrections
-    MovingAverageUtil<float, double, 128> m_avgII;
-    MovingAverageUtil<float, double, 128> m_avgIQ;
-    MovingAverageUtil<float, double, 128> m_avgII2;
-    MovingAverageUtil<float, double, 128> m_avgQQ2;
-    MovingAverageUtil<double, double, 128> m_avgPhi;
-    MovingAverageUtil<double, double, 128> m_avgAmp;
+    MovingAverageUtil<float, double, 1024 * 10> m_avgII;
+    MovingAverageUtil<float, double, 1024 * 10> m_avgIQ;
+    MovingAverageUtil<float, double, 1024 * 10> m_avgII2;
+    MovingAverageUtil<float, double, 1024 * 10> m_avgQQ2;
+    MovingAverageUtil<double, double, 1024 * 10> m_avgPhi;
+    MovingAverageUtil<double, double, 1024 * 10> m_avgAmp;
 #endif
 
     qint32 m_iRange;
```

**Comment by f4exb** [comment]
Two things you may also want to look at:
  - you may want to look at performance hit vs better result. "better" could be in terms of DC overshoot reduction and mirror remnant suppression in dB terms. Digital like analog lives with compromises. I was thinking of performance in terms of processing and I don't remember exactly how this moving average is done. It may have no other impact that taking a bit more memory which is usually not a big deal in the environments this software targets. Worth to check it anyway.
  - may be more interestingly you tested with a continuous signal. What happens with pulsed signals? I am thinking here that elongating the average span could have an adverse effect on this type of signals. Again compromises...
