### ISSUE TITLE
CMD windows open in when start the Sdrandgel Apps.

### ISSUE THREAD

**Issue by mcyclone** [f4exb/sdrangel#693]
4.21.2 released had open cmd prompt windows when start app, if we closed the CMD windows the apps will be closed as well
![image](https://user-images.githubusercontent.com/4027160/98458520-767ed280-21cc-11eb-913e-f613af2f11f3.png)

**Comment by kasper93** [comment]
Wasn't it always like that? :) I didn't even notice, this windows is usefully sometimes. Fix is in #694

**Comment by f4exb** [comment]
No... it was not like that but I welcomed the change as I find the console very useful when things go wrong. But having it as an option would I think satisfy all.
