### ISSUE TITLE
Appveyor automatic deployment upon new tag fails with malformed name

### ISSUE THREAD

**Issue by srcejon** [f4exb/sdrangel#700]
After pulling latest git master, when building with ninja, I get:

ninja: error: build.ninja:65: bad $-escape (literal $ must be written as $$)

Which is refering to:

-DSDRANGEL_VERSION=\"4.21.3sdrangel-v$(appveyor_build_version)-19-gdc4075532\"

This version string appears to be generated by sdrangel/CMakeLists.txt:

git describe --tags

Which returns:

sdrangel-v$(appveyor_build_version)-19-gdc4075532

Due to this tag here:

https://github.com/f4exb/sdrangel/releases/tag/sdrangel-v%24(appveyor_build_version)

**Comment by f4exb** [comment]
Tag deleted

**Comment by srcejon** [comment]
Thanks. Even after fetching/pulling and 'git fetch --tags --all' I was still getting the same response from git describe --tags. It seems it needs to be deleted locally as well, with:

git tag -d sdrangel-v$(appveyor_build_version)

**Comment by f4exb** [comment]
I tried this locally but no matter what it things that $(appveyor_build_version) is a command. Eventually I had to remove it from `.git/ref/tags` simply with `rm` command

**Comment by srcejon** [comment]
That was the command I used in a cmd.exe shell which has different variable expansion. For Linux, it's:

git tag -d sdrangel-v\$\(appveyor_build_version\)

**Comment by f4exb** [comment]
There could be a glitch in `appveyor.yml` when processing tags and auto deployment in Github releases. It could be nice to get this working however I would normally run this manually from the `master` version.

**Comment by f4exb** [comment]
I am going to drop this one
