### ISSUE TITLE
sdrangel-6.0.0-win64 crash

### ISSUE THREAD

**Issue by mcyclone** [f4exb/sdrangel#705]
it can start normally, crash when select hackrf as the source.

**Comment by f4exb** [comment]
This one liner explanation deserves a one liner reply: "it works". See feedback here: https://groups.io/g/sdrangel/topic/pluto_sounds_like_a/78231409?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,78231409
