### ISSUE TITLE
Add DMR TX?

### ISSUE THREAD

**Issue by ElijahHamilton** [f4exb/sdrangel#730]
Can you add software DMR TX support to sdrangel?

Using mbeenc from dudestar?

https://github.com/nostar/dudestar

**Comment by f4exb** [comment]
Interesting... it is the first time I see AMBE encoding in software.

**Comment by f4exb** [comment]
I also take note of their use of "Flite" for synth voice that could be interesting to implement for some use cases.

**Comment by audriusb** [comment]
Hi, any plans to implement this? Not sure if reddit is a trusted source, but i've read AMBE patent has expired, but the newer version is still protected. P. S. The author of dudestar has moved the repo and combined to https://github.com/nostar/DroidStar
