### ISSUE TITLE
Remote source and sink channel plugins are not available.

### ISSUE THREAD

**Issue by greengit-05** [f4exb/sdrangel#734]
The CM256cc library was installed in /opt/install/cm256cc. For installing SDRangel I have specifed the include and library paths on the cmake command line: I added -DCM256CC_DIR=/opt/install/cm256cc to the cmake command. But Remote source and sink channel Plugins are not available after installing. Am I doing something wrong? I am using Linux raspberrypi.

**Comment by f4exb** [comment]
Which version of Rasperry is it? ARM support is only for amrv8 i.e. Raspberry 3B and 4.

**Comment by f4exb** [comment]
Question answered
