### ISSUE TITLE
Unable to render spectrum waterfall and scale mark in Windows

### ISSUE THREAD

**Issue by mxi-box** [f4exb/sdrangel#736]
[
![Capture](https://user-images.githubusercontent.com/35442369/102014738-9177d000-3d92-11eb-8db2-948c889188a0.PNG)
](url)

I can't see any diagram except waveform while this program running. My GPU is Intel HD Graphics 3000 which supports OpenGL 3.0 and 3.1.
The running log is presented here : [https://paste.ubuntu.com/p/xBmf54wdbH/](url)

**Comment by f4exb** [comment]
It works normally

**Comment by srcejon** [comment]
Try setting the environment variable QT_OPENGL to software
