### ISSUE TITLE
Channel Analyzer / DSD Demodulator Crashes Program (Win 8.1)

### ISSUE THREAD

**Issue by vsboost** [f4exb/sdrangel#75]
Hi,
Using this on Windows 8.1 and when selecting the Channel analyzer or Channel analyzer NG or DSD Demodulator crashes the program.

Cheers

![image](https://user-images.githubusercontent.com/11001973/31589815-45344548-b253-11e7-99e4-7e506cc9d202.png)

**Comment by vsboost** [comment]
Forgot to add, other modes work i.e. NFM / AM  / SSB

**Comment by f4exb** [comment]
It seems all plugins using the scope UI are affected. It may have something to do with a specific OpenGL instruction. Unfortunately it is not possible to handle every configuration in Windows. Generally it works in Windows 7 and 10.
