### ISSUE TITLE
Packet demodulator: improve decoding performance?

### ISSUE THREAD

**Issue by dmtrbm** [f4exb/sdrangel#750]
Add packet demodulator channel, change its settings, save/load the preset, settings are reverted to defaults.

**Comment by srcejon** [comment]
Yep, confirmed bug. I'll take a look, thanks.

Is it working for you otherwise? Always useful to get some  feedback, and I'm working on more features for it.

**Comment by srcejon** [comment]
Thanks. It's a pretty simple demodulator at the moment, so not entirely unexpected. 

If you're able to use the FileSink plugin to record an sdriq file for packets it can't receive, I can try to improve it (there's hardly any real activity near me, so have only been testing with the PacketMod!)

**Comment by f4exb** [comment]
Bug corrected in v6.5.1. Keeping it open waiting for some .sdriq material

**Comment by xplanefan** [comment]
Per discussion here:
https://groups.io/g/sdrangel/topic/83619787#1780
This sdriq file linked below has a few APRS pulses, some too quiet and others at what should be sufficient power levels to decode the packets. None of the packets are being successfully decoded by the Packet Demodulator.

[aprs.2021-06-21T15_44_50_023.sdriq.zip](https://github.com/f4exb/sdrangel/files/6687893/aprs.2021-06-21T15_44_50_023.sdriq.zip)

**Comment by f4exb** [comment]
It looks like the AFSK 1200 is a little bit out of specs:
![image](https://user-images.githubusercontent.com/6192319/122830914-5928ef80-d2e9-11eb-9c22-3deaa65107f7.png)
This is the spectrum of demodulated audio. Standard frequencies are 1200 and 2200 Hz. There is a 500 Hz tolerance on the mid point but the ~1450 Hz difference between the two audio peaks could be an issue.

**Comment by f4exb** [comment]
However the output of the NFM demod seems more in line:
![image](https://user-images.githubusercontent.com/6192319/122831608-685c6d00-d2ea-11eb-8938-da5af8153f85.png)

**Comment by srcejon** [comment]
I think the problem there may be just with the interaction between the Packet  Demod and Demod Analyzer. The Packet Demod's channel is at 38400, whereas the Demod Analyzer seems to be assuming 48000. Note, if I change the Audio sample rate for the NFM demod to 38400, then the Spectrum appears the same as for the Packet Demod. 

Is there a way for the channel to tell the Analyzer what the sample rate is?

Also, for the DAB demod, is there a way to pass both left and right audio channels to the Demod Analzyer?

**Comment by f4exb** [comment]
> I think the problem there may be just with the interaction between the Packet Demod and Demod Analyzer. ...

Yes, I see and I will open another issue for this. It should be possible anyway to set the sample rate manually and possibly be able to synchronize with the source.

> Also, for the DAB demod, is there a way to pass both left and right audio channels to the Demod Analzyer?

This is a different issue and concerns the data type identification. For now audio is assumed mono.

**Comment by srcejon** [comment]
With the above fix, 5 packets are now demodulated from @xplanefan's testcase.

**Comment by xplanefan** [comment]
Confirmed. I applied this fix to v6.13 (because neither current master nor v6.14 compiled successfully) and all APRS packets are being successfully demodulated.
