### ISSUE TITLE
How add or remove devices - recompile options

### ISSUE THREAD

**Issue by pa2eon** [f4exb/sdrangel#758]
What is the best way to recompile ( add or remove hardware devices ).
First I compiled the base program .. after reading the manual I see that I have to install also the ' soapy devices'.
I have to recompile the software .. what will be the best way to do (running on Linux Mint 20.x)?
For me the pluto-SDR .. how can I add this hardware as ' sampling device' , I can not find this in the latest version, just clear compiled today.
vy '73, Eric

**Comment by srcejon** [comment]
https://github.com/f4exb/sdrangel/wiki/Compile-from-source-in-Linux

See section Pluto SDR. Have you compiled libiio first?

**Comment by f4exb** [comment]
Question answered
