### ISSUE TITLE
Is still possible to disable SSE4_1 and SSE4_2?

### ISSUE THREAD

**Issue by liviorecchia** [f4exb/sdrangel#763]
I can't find a way to disable SSE4_1 and SSE4_2 on new versions.
In the older ones just changing a makefile solved the problem.
I've tried with:
find ./ -type f -exec sed -i 's/-DUSE_SSE4_1//g' {} \;
find ./ -type f -exec sed -i 's/-DUSE_SSE4_2//g' {} \;
but compiled sdrangel works only on my other computer (an Intel i5) while not on this one anymore (an Intel Atom N455).
Both have Debian GNU/Linux 10.

**Comment by f4exb** [comment]
No, SDRangel will not work anymore on pre-Nehalem processors. Bear in mind that Nehalem was introduces some 10 years ago.

**Comment by f4exb** [comment]
Question answered.
