### ISSUE TITLE
Spectrum markers resolution

### ISSUE THREAD

**Issue by srcejon** [f4exb/sdrangel#774]
Hi,

It seems the spectrum markers have a resolution lower than the spectrum. For example, at low sample rates, the delta can read 0, even when surrounding a peak. E.g:

![DeltaMarkersAtLowSampleRate](https://user-images.githubusercontent.com/57259258/107962648-19e73c80-6f9f-11eb-8ecf-3776ce51c984.PNG)

If you increase the delta - it seems the next step up from 0 is 16Hz, then 32Hz.

(This example is obviously just a test case - actual usage was trying to measure a small amount of Doppler shift from the Moon)

**Comment by f4exb** [comment]
X axis to frequency correspondence is done via the frequency scale: https://github.com/f4exb/sdrangel/blob/master/sdrgui/gui/glspectrum.cpp#L2057

Screen resolution has probably a role to play here.

**Comment by f4exb** [comment]
When the zooming is in place (soon...) you will be able to get something like this:
![image](https://user-images.githubusercontent.com/6192319/108106559-65c4df00-708e-11eb-9470-914a3e381043.png)

**Comment by srcejon** [comment]
Nice :)

**Comment by f4exb** [comment]
Now on `master` see #773

**Comment by f4exb** [comment]
Enhancing spectrum markers as real markers like channel markers attached to a frequency and moving with it will be covered as one of the topics of #768. Hence this one is closed in favor of #768
