### ISSUE TITLE
Broadcast FM Demodulator:  Demod Shift Frequency

### ISSUE THREAD

**Issue by NanoTechnol** [f4exb/sdrangel#78]
Hi, De-mod Shift Frequency of the Broadcast FM De modulator seems no longer to be working.  Stations can only be tuned when tuned to center frequency.

**Comment by f4exb** [comment]
Did you try with the latest (v3.7.4) version?

**Comment by f4exb** [comment]
To be more precise: the center frequency moves in the GUI but is not effective in shifting frequency in the core plugin. It seems the channel configuration message is not sent or does not get through. Problem is still present in v3.7.4

**Comment by f4exb** [comment]
Problem fond: channel configuration message was not handled. Fix is now on dev branch.

**Comment by f4exb** [comment]
Fixed in v3.7.5
