### ISSUE TITLE
FileSink does not record if start recording pressed before start acqusition

### ISSUE THREAD

**Issue by srcejon** [f4exb/sdrangel#782]
It seems FileSink will only record if the start recording button is pressed when acquisition is already running.

If, with acquisition stopped, you press start record button in the file sink, the record button will turn red indicating it is recording, but then when pressing start acquisition, no recording will be made.

I think it makes sense to allow the start recording button to be pressed first, but if not, it probably shouldn't turn red if acquisition is not already running.

**Comment by f4exb** [comment]
SigMFFileSink has similar issues that can be resolved the same way.
