### ISSUE TITLE
DATV: display MER and CNR

### ISSUE THREAD

**Issue by f4exb** [f4exb/sdrangel#784]
This issue is opened following comments on #18 to implement display of MER and possibly CNR in the GUI. The data appears to be available but its display has never been implemented.

**Comment by darksidelemm** [comment]
I've seen the new meters for this, and they look great! 
Is there any chance of getting a windows build for this soon? We're doing a balloon launch next weekend, and we have a lot of stations setup using SDRangel on Windows ready to receive. It would be great if they were able to report back on MER levels during the flight!

**Comment by f4exb** [comment]
The link to the Windows build in Appveyor is here: https://ci.appveyor.com/project/f4exb/sdrangel/builds/37902890/job/148ifipx45bpym7l/artifacts

**Comment by darksidelemm** [comment]
Brilliant, thanks!

**Comment by f4exb** [comment]
Implemented in v6.6.0
