### ISSUE TITLE
Can't enable Audio

### ISSUE THREAD

**Issue by FFY00** [f4exb/sdrangel#79]
I seem not to be able to enable the Audio in Preferences->Audio. I'm using sdrangel compiled from source and up-to-date with the latest master branch.

**Comment by f4exb** [comment]
You should be able to see something like this:
![image](https://user-images.githubusercontent.com/6192319/31849475-e1aa0118-b642-11e7-82e5-0e1707fd56b7.png)

Make sure ALSA is working properly and that you have pulseaudio set correctly. See: https://github.com/f4exb/sdrangel#notes-on-pulseaudio-setup

**Comment by KC7NOA** [comment]
i have the same issue with Armbian ....

fresh install , recent kernel ... sound on web pages work ...
pulseaudio 8.0
i just get the default listing and no other devices

**Comment by KC7NOA** [comment]
Gateware version mismatch!
  Expected gateware version 2, revision 11
  But found version 2, revision 8
  Follow the FW and FPGA upgrade instructions:
  http://wiki.myriadrf.org/Lime_Suite#Flashing_images
  Or run update on the command line: LimeUtil --update

Reference clock 30.720 MHz
RX LPF configured
AudioOutput::start: using default device 
AudioOutput::start: 48000 Hz S16_LE audio format not supported. New rate: -1
AudioOutput::start: Audio device (  ) failed

**Comment by f4exb** [comment]
Non issue

**Comment by FFY00** [comment]
This is a issue. I have everything set up as it is supposed to and I don't have sound.

**Comment by jctual** [comment]
same problem for me.
No sound on Ubuntu 17/10
Works perfectly with other applications but not with SDRangel.
I tried all inputs proposed in Preferences/audio menu.
Yes this is an issue !

**Comment by voxmeus** [comment]
Install pavucontrol. It is included in most distributions for example:
Ubuntu/Debian: sudo apt-get install pavucontrol
openSUSE: sudo zypper in pavucontrol

Open pavucontrol and open the last tab (rightmost) called 'Configuration'
get sound set up here, select your signal source, select the type of demod, then press the '+' button to add the channel, click the Go button and you should hear sound when you have a signal.
