### ISSUE TITLE
Satellite tracking

### ISSUE THREAD

**Issue by hiperiondev** [f4exb/sdrangel#794]
Is possible to add a new feature for satellite tracking in map? Something like Gpredict integrated to sdrangel.

**Comment by f4exb** [comment]
Where have you been recently? https://github.com/f4exb/sdrangel/releases/tag/v6.6.0

**Comment by f4exb** [comment]
However it is true that it is not yet in the Wiki

**Comment by hiperiondev** [comment]
I'll check it.
Txs!

**Comment by f4exb** [comment]
OK, I'll keep it open until Wiki is updated.

**Comment by f4exb** [comment]
Done:
  - https://github.com/f4exb/sdrangel/wiki/Channel-Rx-plugins#apt-demod-plugin
  - https://github.com/f4exb/sdrangel/wiki/Feature-plugins#satellite-tracker-feature-plugin
