### ISSUE TITLE
Wiki Audio source/sink

### ISSUE THREAD

**Issue by hiperiondev** [f4exb/sdrangel#801]
I can't find Audio source and sink in wiki page.

May be is missing?

**Comment by f4exb** [comment]
yes missing indeed

**Comment by f4exb** [comment]
Done:
  - Audio input: https://github.com/f4exb/sdrangel/wiki/Sample-source-plugins-(Rx-devices)#audio-input
  - Audio output: https://github.com/f4exb/sdrangel/wiki/Sample-sink-plugins-(Tx-devices)#audio-output
