### ISSUE TITLE
MacOS cmake -fno-fat-lto-objects 

### ISSUE THREAD

**Issue by 7Grok** [f4exb/sdrangel#807]
MacOS - 10.15.7
clang: 12.0.0 (clang-1200.0.32.29)
Target: x86_64-apple-darwin19.6.0
CMAKE - 3.19.6
Homebrew: 3.0.5-42-ge3b451c

**Error**
`cc1plus: error: '-fno-fat-lto-objects' are supported only with linker plugin`

**Fix**
https://gitlab.kitware.com/cmake/cmake/-/issues/21696

I manually patched my install, I am not a _cmake_ expert, but if someone wants to provide a proper _cmake_ way to fix this that would be awesome

**Comment by f4exb** [comment]
Disabling interprocedural optimization for Mac can easily be done here: 
https://github.com/f4exb/sdrangel/blob/master/cmake/Modules/CompilerOptions.cmake#L5
