### ISSUE TITLE
DATV Demod can crash SDRangel when closed

### ISSUE THREAD

**Issue by srcejon** [f4exb/sdrangel#827]
In SDRangel 6.7.0, if you close the DATV Demod channel, SDRangel can sometimes crash.

2021-03-31 20:53:33.653 (D) DATVDemod::~DATVDemod
2021-03-31 20:53:33.653 (D) DSPDeviceSourceEngine::removeSink:  DATVDemod
2021-03-31 20:53:33.653 (D) DSPDeviceSourceEngine::handleSynchronousMessages:  DSPRemoveBasebandSampleSink
--Type <RET> for more, q to quit, c to continue without paging--

Thread 1 "sdrangel" received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) up
#1  0x00007fffb6b885bf in DATVDemodGUI::~DATVDemodGUI (this=<optimized out>, this=<optimized out>)
    at /opt/build/srcejon/sdrangel/plugins/channelrx/demoddatv/datvdemodgui.cpp:271
271	    m_objDATVDemod->stop();

Have seen it happen on both Windows and Linux.

**Comment by f4exb** [comment]
`m_objDATVDemod->stop();` should not be called in GUI destructor because this is already invoked in `~DATVDemod`
