### ISSUE TITLE
Feature - APRS: Make the Altitude switchable

### ISSUE THREAD

**Issue by df6dbf** [f4exb/sdrangel#829]
Its more convinient if the Altitude is switchable between Meter and Feet.

![image](https://user-images.githubusercontent.com/19621920/113399367-67c5d180-93a0-11eb-8655-0a3775eff59c.png)

73s Holger

**Comment by srcejon** [comment]
Yeah, Speed is in knots and temperatures in F should also be adjustable.

**Comment by f4exb** [comment]
Released in v6.8.0
