### ISSUE TITLE
Problem with frquency in Remote output plugin

### ISSUE THREAD

**Issue by hiperiondev** [f4exb/sdrangel#832]
I'm trying to create a minimal API replication of remote output for use rpitx like TX.
When  select remote output in sink my program respond:

channelType "UDPSink"
direction  1
UDPSinkReport  { 
    outputPowerDB  1
    channelPowerDB  1
    squelch 1
    inputSampleRate 48000
}

and Sdrangel set status to API OK.
Play start to send over UDP but can't change frequency.

**Comment by f4exb** [comment]
No you can't and this is by design. You have to control the frequency of the remote instance with its own API.

**Comment by f4exb** [comment]
I will still make more clear that UI controls are for information only
