### ISSUE TITLE
AGC for NFM / AM

### ISSUE THREAD

**Issue by texasyojimbo** [f4exb/sdrangel#84]
AGC for SSB demodulator was added as enhancement in release 3.5.3 (issue #40 ).

Would be nice to have this for NFM also, and possibly also for AM.

**Comment by f4exb** [comment]
NFM does not need AGC since we're interested in the phase of the signal.
I have to check for AM. I though there was some kind of AGC already.

**Comment by texasyojimbo** [comment]
OK, perhaps it's just a PEBKAC issue. It seems like when I am using NFM the audio is distorted and overdriven, even when I adjusted RF and audio BW and signal gain.

**Comment by f4exb** [comment]
The RF bandwidth is tied to the expected FM deviation by a static correspondence. This is the parameter you should tinker with in FM. It is working OK for me on most signals and I use NFM quite a lot.

**Comment by texasyojimbo** [comment]
Thanks. I have also identified part of the problem as the DC spike. I was listening to APRS traffic on 144.39 and when I filtered out the DC spike, it stopped sounding so strange.

**Comment by f4exb** [comment]
There is an AGC with AM and the NFM issue was related to the DC spike so I think this issue can be closed
