### ISSUE TITLE
Doppler correction in Satellite Tracker Feature

### ISSUE THREAD

**Issue by Valstee** [f4exb/sdrangel#840]
Hi F4exb,
I use SDRangel 6.8.0-11-g30c2c519d Qt 5.14.2 x86_64 on Ubuntu 20.10.
In Satellite tracker feature, I can't check a channel to enable Doppler correction:

![Capture d’écran du 2021-04-12 18-47-11](https://user-images.githubusercontent.com/77800144/114431633-0253bb00-9bc0-11eb-959d-0349bcfee95a.png)

An idea to solve this issue ?
Thanks,
Valentin (from Antibes)

**Comment by f4exb** [comment]
What is the issue?

**Comment by srcejon** [comment]
The check boxes next to the channel names are missing - which should allow the doppler correction to be enabled/disabled per channel.

They appear on Windows with qt 5.15 for me, but are missing on Ubuntu with Qt 5.14 for me also, so I'll see if it can be done differently.

**Comment by f4exb** [comment]
I see... same thing for me on Ubuntu 20.10 and Qt 5.14.2

**Comment by Valstee** [comment]
Thanks a lot for your response.
Same thing for me : They appear on Windows with qt 5.15, but are missing on Ubuntu with Qt 5.14 (that's how I saw the "issue")

**Comment by srcejon** [comment]
Works in kubuntu 21.04 which has Qt 5.15.2 - so presumably an issue with Qt 5.14. Can't find a work around. Perhaps this dialog would be clearer if it used tabs (one per device set) with a more standard form layout, rather than a table anyway.

**Comment by f4exb** [comment]
We still need compatibility down to 5.12.8 for the Ubuntu 20.04 package. I recently upgraded the base image of the Docker build to Debian bullseye therefore lifting the 5.11 compatibility.

**Comment by srcejon** [comment]
With the above path, I've rearranged the GUI to use tabs rather than a tab. Now works for me on Ubuntu with Qt 5.14 and Windows.

**Comment by Valstee** [comment]
Thanks a lot for the modifications !
