### ISSUE TITLE
Devices use AirspyHfSettings in WebAPIAdapters

### ISSUE THREAD

**Issue by srcejon** [f4exb/sdrangel#842]
Most of the sample source / sink plugins have the following code, which uses AirspyHFSettings rather than the corresponding device settings (E.g Lime in this case):

int LimeSDROutputWebAPIAdapter::webapiSettingsGet(
        SWGSDRangel::SWGDeviceSettings& response,
        QString& errorMessage)
{
    (void) errorMessage;
    response.setAirspyHfSettings(new SWGSDRangel::SWGAirspyHFSettings());
    response.getAirspyHfSettings()->init();
    LimeSDROutput::webapiFormatDeviceSettings(response, m_settings);
    return 200;
}

I presume that's a bug?

**Comment by f4exb** [comment]
Yes it is... I presume it went unnoticed because this part of the code is used only for presets serialization via API which is rarely used.
