### ISSUE TITLE
DATV modulator doesn't see FIFO special files  (also called named pipes)  - Request

### ISSUE THREAD

**Issue by computer-wizard** [f4exb/sdrangel#843]
The DATV modulator doesn't see FIFO special files. (Sdrangel 6.9.0-1  Linux version)
At the moment the DATV modulator doesn't see these if I try to open a file. (it sees only transport files) . FIFO's are very  handy to use as a buffer when streaming a live transport stream from an application, so if should be very convenient if the DATV modulator could open them.

**Comment by srcejon** [comment]
While it's easy to add support for displaying them in the file selector, currently the modulator uses seek operations and also needs to re-read the file, so named pipes can't be used.

**Comment by computer-wizard** [comment]
I understand.

**Comment by f4exb** [comment]
question answered
