### ISSUE TITLE
Wrong Win Executable (v6.8 instead of v6.9)?

### ISSUE THREAD

**Issue by df6dbf** [f4exb/sdrangel#846]
Hello Edouard,
very happy to see that the SDRs from SDRplay now supported. But it seems there is the wrong executable.

https://github.com/f4exb/sdrangel/releases/download/v6.9.0/sdrangel-6.8.0-win64.exe

73s Holger, DF6DBF

**Comment by f4exb** [comment]
Indeed... now fixed!
