### ISSUE TITLE
Spurs in transmitted signal

### ISSUE THREAD

**Issue by sh123** [f4exb/sdrangel#848]
When transmitting single tone or CW in SSB modulator output signal has spurs, when signal is amplified it becomes real problem. Any hints? Can it be somehow "tuned out" or needs some fixes in software?

![image](https://user-images.githubusercontent.com/1933302/114843519-9309e100-9de2-11eb-918a-518ea2e640e3.png)

![image](https://user-images.githubusercontent.com/1933302/114844063-1d524500-9de3-11eb-816f-114306d4a1c8.png)

**Comment by f4exb** [comment]
This is -60 dBc and you cannot expect better with this technology. The SSB modulator is based on audio sample rate which is usually 48 kHz. To minimize spurs you can use an integer multiple of this sample rate in the baseband (96, 192, 384, ... kS/s)

There is no action to be taken hence closing this issue.

**Comment by sh123** [comment]
@f4exb , I think this problem somehow related to interpolation, when I'm using interpolation of 64 then this issue exists, when I'm using interpolation of 32 and less then this issue does not exist.
