### ISSUE TITLE
Datv modulator UDP port not  reachable

### ISSUE THREAD

**Issue by computer-wizard** [f4exb/sdrangel#852]
SDRangel 6.9.0-1 O/S: Ubuntu 20.04

Datv modulator udp port not reachable.

Example:  127.0.0.1  port 5004  (and others at 127.0.0.1)
A ICMP packet is received with, udp port not unreachable.

127.0.0.1 > 127.0.0.1: ICMP 127.0.0.1 udp port 5004 unreachable

Sdrangel  doesn't show up when the 'netstat' command is executed.

**Comment by f4exb** [comment]
![image](https://user-images.githubusercontent.com/6192319/115169777-49a9e200-a0bf-11eb-9861-6c1f8bc726ab.png)

```
sudo netstat -anlpu                                                                                                                                                               
Active Internet connections (servers and established)                                                                                                                                                                                       
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name                                                                                                                                            
udp        0      0 0.0.0.0:9091            0.0.0.0:*                           806489/sdrangel                                                                                                                                             
...
udp        0      0 127.0.0.1:5004          0.0.0.0:*                           825484/./sdrangel                                                                                                                                           
...
udp6       0      0 :::6666                 :::*                                2510/qlipper          
```

**Comment by computer-wizard** [comment]
Yes, I did here also but it is not listed
netstat -anlpu 
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
udp        0      0 0.0.0.0:8554            0.0.0.0:*                           40427/obs           
udp        0      0 0.0.0.0:57733           0.0.0.0:*                           -                   
udp        0      0 0.0.0.0:45649           0.0.0.0:*                           -                   
udp        0      0 0.0.0.0:631             0.0.0.0:*                           -                   
udp        0      0 0.0.0.0:53915           0.0.0.0:*                           -                   
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           -                   
udp        0      0 0.0.0.0:2049            0.0.0.0:*                           -                   
udp        0      0 0.0.0.0:51724           0.0.0.0:*                           -                   
udp        0      0 0.0.0.0:40834           0.0.0.0:*                           -                   
udp        0      0 10.0.3.1:53             0.0.0.0:*                           -                   
udp        0      0 10.42.0.1:53            0.0.0.0:*                           -                   
udp        0      0 127.0.0.53:53           0.0.0.0:*                           -                   
udp        0      0 0.0.0.0:67              0.0.0.0:*                           -                   
udp        0      0 0.0.0.0:67              0.0.0.0:*                           -                   
udp        0      0 0.0.0.0:67              0.0.0.0:*                           -                   
udp        0      0 192.168.2.10:68         192.168.2.1:67          ESTABLISHED -                   
udp        0      0 192.168.0.15:68         192.168.0.1:67          ESTABLISHED -                   
udp        0      0 0.0.0.0:69              0.0.0.0:*                           -                   
udp        0      0 0.0.0.0:111             0.0.0.0:*                           -                   
udp        0      0 0.0.0.0:37027           0.0.0.0:*                           -                   
udp6       0      0 fe80::53ac:d2c1:144:546 :::*                                -                   
udp6       0      0 :::58199                :::*                                -                   
udp6       0      0 :::50052                :::*                                -                   
udp6       0      0 :::54194                :::*                                -                   
udp6       0      0 :::5353                 :::*                                -                   
udp6       0      0 :::34186                :::*                                -                   
udp6       0      0 :::58831                :::*                                6628/skypeforlinux  
udp6       0      0 :::1716                 :::*                                6443/kdeconnectd    
udp6       0      0 :::2049                 :::*                                -                   
udp6       0      0 ::1:35514               ::1:48250               ESTABLISHED -                   
udp6       0      0 :::43825                :::*                                -                   
udp6       0      0 ::1:48250               ::1:35514               ESTABLISHED -                   
udp6       0      0 :::57142                :::*                                -                   
udp6       0      0 :::69                   :::*                                -                   
udp6       0      0 :::111                  :::*            

![image](https://user-images.githubusercontent.com/7777935/115174085-962cf780-a096-11eb-9896-1193bccc3c4a.png)

**Comment by computer-wizard** [comment]
It also doesn't show in the just release version  6.10.0-1
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
udp        0      0 0.0.0.0:57733           0.0.0.0:*                           -                   
udp        0      0 0.0.0.0:45649           0.0.0.0:*                           -                   
udp        0      0 0.0.0.0:631             0.0.0.0:*                           -                   
udp        0      0 0.0.0.0:53915           0.0.0.0:*                           -                   
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           -                   
udp        0      0 0.0.0.0:2049            0.0.0.0:*                           -                   
udp        0      0 0.0.0.0:51724           0.0.0.0:*                           -                   
udp        0      0 0.0.0.0:40834           0.0.0.0:*                           -                   
udp        0      0 10.0.3.1:53             0.0.0.0:*                           -                   
udp        0      0 10.42.0.1:53            0.0.0.0:*                           -                   
udp        0      0 127.0.0.53:53           0.0.0.0:*                           -                   
udp        0      0 0.0.0.0:67              0.0.0.0:*                           -                   
udp        0      0 0.0.0.0:67              0.0.0.0:*                           -                   
udp        0      0 0.0.0.0:67              0.0.0.0:*                           -                   
udp        0      0 192.168.2.10:68         192.168.2.1:67          ESTABLISHED -                   
udp        0      0 192.168.0.15:68         192.168.0.1:67          ESTABLISHED -                   
udp        0      0 0.0.0.0:69              0.0.0.0:*                           -                   
udp        0      0 0.0.0.0:111             0.0.0.0:*                           -                   
udp        0      0 0.0.0.0:37027           0.0.0.0:*                           -                   
udp6       0      0 fe80::53ac:d2c1:144:546 :::*                                -                   
udp6       0      0 :::58199                :::*                                -                   
udp6       0      0 :::50052                :::*                                -                   
udp6       0      0 :::54194                :::*                                -                   
udp6       0      0 :::5353                 :::*                                -                   
udp6       0      0 :::34186                :::*                                -                   
udp6       0      0 :::58831                :::*                                6628/skypeforlinux  
udp6       0      0 :::1716                 :::*                                6443/kdeconnectd    
udp6       0      0 :::2049                 :::*                                -                   
udp6       0      0 ::1:35514               ::1:48250               ESTABLISHED -                   
udp6       0      0 :::43825                :::*                                -                   
udp6       0      0 ::1:48250               ::1:35514               ESTABLISHED -                   
udp6       0      0 :::57142                :::*                                -                   
udp6       0      0 :::69                   :::*                                -                   
udp6       0      0 :::111                  :::*                                -                   
![image](https://user-images.githubusercontent.com/7777935/115176084-58ca6900-a09a-11eb-9a51-cb3318bd9fc9.png)

**Comment by f4exb** [comment]
Errmm.. you should select "UDP" there...
![image](https://user-images.githubusercontent.com/6192319/115203547-d83a5580-a0f7-11eb-8498-32d6daee04eb.png)

**Comment by computer-wizard** [comment]
eh...ooooooooooooooops!
