### ISSUE TITLE
DRM demodulator

### ISSUE THREAD

**Issue by nmaster2042** [f4exb/sdrangel#867]
What about a DRM demodulator as plugin in sdrangel ?

Dream DRM seems not to be maintained any more, so it may be a nice feature to add ? Like the new DAB demodulator.

**Comment by f4exb** [comment]
Have you checked #106 ?

**Comment by nmaster2042** [comment]
Oh Sorry, didn't saw it.

**Comment by f4exb** [comment]
Well, it is old I know ...
