### ISSUE TITLE
Division by Zero whilst switching between Presets

### ISSUE THREAD

**Issue by IrishCoffee17** [f4exb/sdrangel#868]
Windows 10, SDRangel v6.10.1
Switched between presets, each having a single Broadcast FM decoder. 
Approx. one out of 20 times the app closes with a division by zero.
Seems to be independent of the selected demods, did also happen with NFM and DSD demods in preset.

![grafik](https://user-images.githubusercontent.com/82844579/115984366-18418280-a5a7-11eb-90de-86774b5682d6.png)

**Comment by f4exb** [comment]
Logically you cannot read or write from a FIFO of size 0 so read/write operations should check size and return immediately if zero.
