### ISSUE TITLE
une erreur sur le SDRANGEL 

### ISSUE THREAD

**Issue by gaspar1987** [f4exb/sdrangel#873]
![image](https://user-images.githubusercontent.com/13591469/116280254-c8baac80-a788-11eb-91ed-ad5e9695d589.png)
Bonjour j'ai eu un problème avec une erreur sur le SDRANGEL Pouvez-vous me donner la solution pour le réparer?

**Comment by f4exb** [comment]
Insufficient description.

**Comment by gaspar1987** [comment]
Pourquoi ça ne fonctionne pas il faudrait que vous remettez moins de fichiers le fichier est 100 % lourd en sur les mémoire . Réduire démodulateur certains sont unity ne fonctionne pas même j'ai testé avec des antennes spécialisées et les amplificateurs et des réducteurs donc ça ne fonctionne pas c'est pour cela que je voudrais que vous faisais un logiciel version la nouvelle version meilleur que ça je ne vous critique pas mais j'espère une bonne qualité de sdranger que je puisse le faire marcher faire marcher avec la grande clé h Acker one il fonctionne bien quand on appelle avec mais le nouveau est bloqué parce que j'ai pris une version plus ancienne de 4.0 .c'est pour ça que je voudrais que le fichier soit moins lourd pour que on puisse utiliser en toute sécurité sans problème. Merci bonne journée

**Comment by f4exb** [comment]
Qu'est-ce que c'est que ce galimatias incompréhensible? Ecoutez... si SDRangel ne vous convient pas tel qu'il est ou que vous n'y comprenez rien utilisez donc SDR# ou SDRconsole et fichez nous la paix. Merci!
