### ISSUE TITLE
Cannot play DAB service with German Umlaut

### ISSUE THREAD

**Issue by andimik** [f4exb/sdrangel#874]
In Austria there is a DAB radio service called "jö.live" (with German Umlaut). 

This is the only service which sdrangel doesn't want to play after a click on it.

https://www.digitalbitrate.com/dtv.php?mux=5D&liste=1&live=164&lang=en

![grafik](https://user-images.githubusercontent.com/24510556/116292832-71233d80-a796-11eb-8fbe-83e975c44e7b.png)

**Comment by srcejon** [comment]
Is this on Windows or Linux? There are a few unicode issues to resolve on Windows, which may be related.

**Comment by andimik** [comment]
It's Windows 10 64bit

**Comment by andimik** [comment]
Well, I tried under Ubuntu 20.04 and this does **not** play as well. So it is not only Windows-related.

**Comment by srcejon** [comment]
Ok, that should be fixed in the next release. Let me know if you see any other problems.
