### ISSUE TITLE
Possible memory leak in Satellite Tracker

### ISSUE THREAD

**Issue by f4exb** [f4exb/sdrangel#877]
There is a possible memory leak in the Satellite Tracker feature plugin. Here is the memory usage graph before and after restarting SDRangel. Before with the plugin and after without:
![image](https://user-images.githubusercontent.com/6192319/116400473-5dc1b200-a82a-11eb-8028-2a89fe29ace2.png)
This is the instance of SDRangel that I routinely use and let run to monitor the local UHF and VHF repeaters traffic. It always has the same setup but before restart I had added the Satellite Tracker to occasionally keep an eye on what's going on there. This seems to designate a possible memory leak issue in the Satellite Tracker.

**Comment by srcejon** [comment]
I'll take a look - did you have the map open?

**Comment by srcejon** [comment]
I can see it rising without the map. Perhaps this was the problem when I thought there might be a leak in the APT demod.

**Comment by srcejon** [comment]
I see one leak. Easy enough to fix.

**Comment by f4exb** [comment]
OK good! And I confirm that no map was open.

**Comment by f4exb** [comment]
looks like a fix. I had a doubt but this was due to Zoom and Firefox. I'll keep watching a little bit.

**Comment by f4exb** [comment]
I think it is OK now:
![image](https://user-images.githubusercontent.com/6192319/116510960-0a04a680-a8c6-11eb-907e-a63989af7ccc.png)

**Comment by f4exb** [comment]
Deployed in v6.10.3
