### ISSUE TITLE
Spurs on transmit when using interpolation of 64

### ISSUE THREAD

**Issue by sh123** [f4exb/sdrangel#884]
When trying to transmit tone and using interpolation of 64 output spectra has lots of spurs, when using interpolation of 32 and less spurs do not exist. Opened similar issue before, but now managed to narrow this problem down to 64. Just close this item if these spurs are expected.

Screenshot from the receiver side:

![image](https://user-images.githubusercontent.com/1933302/116997343-57797d00-ace5-11eb-8402-f2b05cb2cfd7.png)

**Comment by f4exb** [comment]
Any idea of the level of these spurs? It is normal to have spurs since in digital technology you cannot perform calculations with infinite precision.

**Comment by sh123** [comment]
@f4exb , some people complained about it when tried to transmit over QO-100, so yes, they are noticeable, but looks like they are visible when using interpolation of 64.

**Comment by f4exb** [comment]
"visible", "noticeable"... is not a measurement.

**Comment by sh123** [comment]
![image](https://user-images.githubusercontent.com/1933302/117001458-0b313b80-aceb-11eb-8f1d-9543425b3567.png)

**Comment by f4exb** [comment]
OK it seems consistent with what is observed using the TestSink plugin (thus just pure "computation"). Modulating signal is an unmodulated AM CW signal (-6dB) it has no artifacts even down to -100 dBc:
![image](https://user-images.githubusercontent.com/6192319/117003391-1a14ef80-ace5-11eb-97e2-a0e9f37dcdd6.png)

Output at interpolation of 32 (and down to 32 it is about the same). Spurs are about -80 dBc thus perfectly acceptable
![image](https://user-images.githubusercontent.com/6192319/117003054-a5da4c00-ace4-11eb-8f09-ff342230134c.png)

Now at interpolation of 64 spurs are up to about -20 dBc close to the carrier and significantly widespread all over the band. Indeed this is not normal.
![image](https://user-images.githubusercontent.com/6192319/117003116-bee2fd00-ace4-11eb-8de8-a281fd90f45f.png)

**Comment by sh123** [comment]
Yes, also did some better measurement

32 seems to be OK

![image](https://user-images.githubusercontent.com/1933302/117004259-89dba800-acee-11eb-8c7c-078ffbdbc4a9.png)

64 has some spurs

![image](https://user-images.githubusercontent.com/1933302/117004308-96600080-acee-11eb-8017-c8fbcb70c7b2.png)

**Comment by f4exb** [comment]
The waveform is indeed consistent with what is sent to the device. There is some filtering in hardware that reshapes it a bit but the many spurs in what looks like a sinc function are clearly visible. I guess there is a bug in the calculation that does some wrong sample swapping somewhere. I'll have a closer look.

**Comment by f4exb** [comment]
It is obviously missing the offsets from +110 to +127 at the end of the iteration here: https://github.com/f4exb/sdrangel/blob/master/sdrbase/dsp/interpolators.h#L1238

**Comment by sh123** [comment]
@f4exb , yes, works fine now, clean signal on qo-100, thank you.
