### ISSUE TITLE
GUI: doesn't remember window's position and size

### ISSUE THREAD

**Issue by Radiomix2000** [f4exb/sdrangel#89]
When you close and then reopen app, window size and position are reset.

**Comment by f4exb** [comment]
Can you be more specific? I don't see any problem.

**Comment by f4exb** [comment]
Maybe this could be implemeted for dependent widgets at least the source/sink? http://doc.qt.io/qt-4.8/qwidget.html#saveGeometry

**Comment by Radiomix2000** [comment]
Strange. I have this problem on W7 x64.
When I start the application and just maximize the window and close application, then again start the app, and now the window is not maximized. I will try to capture the screen, if need for explaining.

**Comment by gm8arv** [comment]
I see the same issue on Win-10/64.  I like to have the window slightly larger than the default, and on the right-hand of my two monitors.  Neither the position (monitor) or the size are remembered across invocations.

**Comment by f4exb** [comment]
Tried the save geometry thing but this does not make any difference. Seems to be a Qt issue so it cannot be fixed.
