### ISSUE TITLE
Scope - trace offset

### ISSUE THREAD

**Issue by srcejon** [f4exb/sdrangel#892]
The trace offset (11) in the Scope doesn't appear to work as I'd expect when the scope is not running. I'd expect to be able to use it to scroll through the waveform.  The horizonal axis labels seems to work, but not the waveform.

For example, here's an initial captured waveform with offset of 0, where I'm just viewing first 50ms of 500ms.

![Scope1](https://user-images.githubusercontent.com/57259258/117551714-5460f280-b03f-11eb-96e8-8d650f36c159.PNG)

If I increase the offset by 25ms, I'd expect the waveform to move to the left 25ms, so I can see 25ms-75ms. However, it seems the first 25ms of the waveform is zeroed, with the second half remaining as 25ms-50ms. The horizontal axis labels do show 25ms-75ms though.

![Scope2](https://user-images.githubusercontent.com/57259258/117551751-9722ca80-b03f-11eb-84c4-093412f93fe5.PNG)

**Comment by srcejon** [comment]
It looks like the offset works if set before the waveform is captured - but would be nice to capture, then scroll through the waveform.

**Comment by f4exb** [comment]
Yes, will be covered in #898
