### ISSUE TITLE
Sat Tracker does not always stop APT demod automatically at LOS

### ISSUE THREAD

**Issue by choupette-change** [f4exb/sdrangel#893]
Satellite tracking (decoding) starts automatically at AOS time but does it also stop at LOS time or must we stop it manually (start-stop decoding button) as with Wxtoimg for example (it stops automatically at the end of the pass) ? Thanks for your feedback. (Google traduction)

**Comment by srcejon** [comment]
It should stop automatically,  but there is a bug that means it isn't always stopping properly.

**Comment by choupette-change** [comment]
thank you for your feedback, I noticed that it never stopped automatically

**Comment by f4exb** [comment]
Changed title to track the actual issue
