### ISSUE TITLE
Rollup widget doesn't appear to support vertical expanding policy.

### ISSUE THREAD

**Issue by srcejon** [f4exb/sdrangel#897]
It's seems like the rollup widget doesn't support the vertical expanding policy. I think it would be useful if it did, so that various features and (perhaps some specific channels), would expand to fill the available space. E.g:

![image](https://user-images.githubusercontent.com/57259258/117797823-5ea20d00-b248-11eb-805a-aef96d21e7c7.png)

The table and map should really fill the available space so that max amount of data is visible. Horizontal expansion seems to work. It could be I haven't set some property correctly, of course. But I think I have expanding set in all of the AIS widgets.

**Comment by f4exb** [comment]
Possibly related to the container of the widgets. I am not very proficient in Qt GUI framework. This is how things are organized:
![image](https://user-images.githubusercontent.com/6192319/117853892-37b7fb00-b289-11eb-973a-5c3811003927.png)

**Comment by f4exb** [comment]
The height of the children sis made bottom up in the `arrangeRollups` from the child intrinsic height regardless of the container available space. It is going to be difficult to change this.

**Comment by srcejon** [comment]
Perhaps I could just not use the rollup widget for the main data display area - just keeping that for the settings.

**Comment by f4exb** [comment]
That's a possibility. If the top widget is a standard `QWidget` with a `RollupWidget` containing only the collapsable sections and then another standard `QWidget` or Qt standard derivative for the expandable content.

It could be effectively rather difficult to change the `RollupWidget` because its size is calculated bottom up from the instrinsic size of its children regardless of the space available around the `RollupWidget`.

**Comment by srcejon** [comment]
It seems it doesn't matter what I have for the top widget in the .ui file, it ends up as a RollupWidget. I suspect this is because FeatureGUI inherits from RollupWidget.

**Comment by f4exb** [comment]
I have tried on my side and went to the same conclusion...

**Comment by f4exb** [comment]
And we are stuck with this `RollupWidget` because it is all over the place.

**Comment by f4exb** [comment]
The result is ugly

**Comment by srcejon** [comment]
Yep. Can the video area not expand?

**Comment by f4exb** [comment]
It is apparently not possible to choose which plugins are able to expand and which must stay fixed or maximum.

**Comment by srcejon** [comment]
It should be. Just set the rollup widget size policy to be minimum or expanding.

E.g. GS232 controller feature stays fixed, whereas Map feature expands.

I set DATV to expand, so hopefully the video area can be made bigger. If not, just set the widgets for that back to minimum/preferred rather than expanding.

**Comment by f4exb** [comment]
Unfortunately this is what is obtained:
![image](https://user-images.githubusercontent.com/6192319/139555539-290b99e2-6679-43a6-8260-ee6fe6f3eec6.png)

**Comment by srcejon** [comment]
Ok, I'll take a look

**Comment by f4exb** [comment]
I tried also on my side it seems the sub-widgets have to be set to "Maximum" also. That is "tabWidget", "¨datvTab" and "videoTab". Thus I can obtain the previous behaviour.

**Comment by f4exb** [comment]
Well, there is still an issue when it is stacker vertically with a large widget triggering vertical scrolling
![image](https://user-images.githubusercontent.com/6192319/139557800-fdb7417e-0ba0-4d86-b895-02f80a9e9233.png)

**Comment by f4exb** [comment]
It seems the vertical scrolling does not take place even if the plugin window is larger vertically:
![image](https://user-images.githubusercontent.com/6192319/139559982-c4864fa1-63e2-459f-9909-5f569defa9ca.png)

**Comment by srcejon** [comment]
RollupWidget::arrangeRollups() asks for the minimum size the tabWidget needs and it is returning 125 - which is how high it is in your screenshot. The question is where that 125 comes from, as it doesn't seem to be from the .ui file.

**Comment by srcejon** [comment]
Not sure where the 125 comes from, but it seems if we set a minimum size on the the videoTab, not just tabWidget, then arrangeRollups() sees it, as in: https://github.com/f4exb/sdrangel/pull/1027

**Comment by srcejon** [comment]
The 125 is the minimum size to display the tabs - whereas the previous minimum size for the videoTab was 0. It seems the tabWidget uses the minimum of those - rather than the minimum size set for the tabWidget.

**Comment by f4exb** [comment]
Yes it works! Possibly other plugins will have to be updated the same way.

**Comment by srcejon** [comment]
I had a quick look and they seemed ok, but let me know of any other problems.

**Comment by f4exb** [comment]
Commit f04741d692a9d70154f4b18d44309c74be94dcff fixes some issues mostly in the "chirp chat" modulator and demodulator.
