### ISSUE TITLE
RTL-SDR: cannot start sample source

### ISSUE THREAD

**Issue by f4exb** [f4exb/sdrangel#90]
In version 3.8.1: trying to start RTL-SDR pops up a "Could not start sample source" message and streaming does not start

**Comment by f4exb** [comment]
It seems to be a problem with my local build however librtlsdr has evolved since last pulling (v 0.7.0) and bias tee control has been added.

**Comment by f4exb** [comment]
See: https://github.com/f4exb/sdrangel/blob/master/librtlsdr/CMakeLists.txt
This option should be added in the cmake command when compiling librtlsdr:
`-DDETACH_KERNEL_DRIVER=ON`

The new functionalities of rtl-sdr will be implemented in a different issue

**Comment by gaspar1987** [comment]
![image](https://user-images.githubusercontent.com/13591469/66255354-bcc06180-e782-11e9-8549-78096543bb1a.png)
hello I have a problem with the rtl sdr could not start sample source.

**Comment by gaspar1987** [comment]
to get the problem back?
