### ISSUE TITLE
AIS decoder crops messages to UDP stream

### ISSUE THREAD

**Issue by magnuan** [f4exb/sdrangel#903]
NMEA messages sent to UDP stream seems to be cut short.
First part of message seems correct, but the message gets cut short (leaving an corrupt NMEA message) in the output UDP stream.
It seems to be related to "0" in the message, although it is not happening every time a "0 " is encountered.

Here are a few messages as shown in SDRangel, AIS demodulator, received messages:
```
!AIVDM,1,1,,,13mU5G0P0hPgV1DTC4mS??wf06al,0*04
!AIVDM,1,1,,,1CmFAD001T0cI0TTJB=0ePWd0000,0*77
!AIVDM,1,1,,,1Cm@d30P00PcoUJTMco>4?wh2000,0*71
!AIVDM,1,1,,,1CmEJ`0OiO0cH=`TKGL050;h0000,0*7a
!AIVDM,1,1,,,13m6@7P0000gOd4TBtSt6h=j0<0n,0*7f
```

The same messages read out from UDP stream:
```
!AIVDM,1,1,,,13mU5G0P0hPgV1DTC4mS??wf,0*0f
!AIVDM,1,1,,,1CmFAD0,2*09
!AIVDM,1,1,,,1Cm@d30P,0*0f
!AIVDM,1,1,,,1CmEJ`0OiO0cH=`TKGL,2*1e
!AIVDM,1,1,,,13m6@7P,2*1b
```

I am using 6.12.1 built with the sdrangel-docker container.

**Comment by f4exb** [comment]
Implemented in v6.13.0
