### ISSUE TITLE
Segmentation error caused by AIS Demodulator

### ISSUE THREAD

**Issue by Valstee** [f4exb/sdrangel#925]
Hi, I use sdrangel 6.14 on Ubuntu 20.10.
The opening of Ais demodulator causes a segmentation error.
Here are the logs :
- (W) QMetaObject::connectSlotsByName: No matching signal for on_scope_sampleRateChanged(int)
- (W) QMetaObject::connectSlotsByName: No matching signal for on_scope_traceSizeChanged(uint32_t)
- (W) QMetaObject::connectSlotsByName: No matching signal for on_scope_preTriggerChanged(uint32_t)
I had no problem with version 6.12 and 6.13
Do you have an idea of the problem?
Thanks,
Valentin

**Comment by choupette-change** [comment]
I have the same issue with Ubuntu 21 04 with AIS demodulator. 
Other issue with plugin : Noise figure (cf print screen)
![image](https://user-images.githubusercontent.com/68333247/122103898-68a2c700-ce17-11eb-87ff-9eaba701c415.png)

**Comment by f4exb** [comment]
@choupette-change no AIS demodulator here...

**Comment by f4exb** [comment]
@choupette-change please open another issue for the Noise Figure and let's keep this one for the original issue.

**Comment by srcejon** [comment]
I see an exception: vector subscript out of range

In: 

void GLScopeGUI::settingsTraceChange(const GLScopeSettings::TraceData& traceData, uint32_t traceIndex)
{
    m_settings.m_tracesData[traceIndex] = traceData;
}

traceIndex is 0.

Stack is:

![image](https://user-images.githubusercontent.com/57259258/122119329-f59e4e00-ce20-11eb-8c0a-eeb9a32d2017.png)

Calling line is AISDemod is:

ui->scopeGUI->addTrace(traceDataQ);

**Comment by f4exb** [comment]
Yes it is probably due to the recent changes in the scope. It looks like it does not start with one trace already defined.

**Comment by f4exb** [comment]
Corrected again: issue was actually in `GLScopeGUI::setBuddies` and not the plugin(s) that call it. The previous fix results in one extra trace or trigger created. Changes in plugin have been reverted.
