### ISSUE TITLE
 issue with plugin : Noise figure 

### ISSUE THREAD

**Issue by choupette-change** [f4exb/sdrangel#926]
Other issue with plugin : Noise figure (cf print screen)
![image](https://user-images.githubusercontent.com/68333247/122119795-e8399180-ce29-11eb-99c6-1661472a8182.png)

**Comment by srcejon** [comment]
The noise figure plugin requires a calibrated noise source? Do you have one? If so, which one?

The noise source needs to have it's power switched on and off. By default, it assumes a 346B type device and so it tries to do this via a programmable power supply connected via USB using the VISA library. This error is saying it can't communicate with the power supply. If you have one, you need to enter the correct VISA address for it in the Control dialog. If you don't, you can use a program or script to control the power supply / enable the noise source instead.

**Comment by f4exb** [comment]
Assuming @choupette-change has not the proper equipment.

**Comment by f4exb** [comment]
Question answered
