### ISSUE TITLE
RIG control

### ISSUE THREAD

**Issue by mrjzuniga** [f4exb/sdrangel#93]
have you add some rig control for external power amplfiers or activate when Transmit mode
thanks

**Comment by f4exb** [comment]
There are so many ways to activate or be activated by external triggers that I don't want to add some definite support like Hamlib or the like. In fact this should be handled via scripting/macros and a ticket is already opened for this: #49 So I will consider this one as duplicate

**Comment by f4exb** [comment]
Released in v4.0.0
