### ISSUE TITLE
improvement request : DAB decoder

### ISSUE THREAD

**Issue by choupette-change** [f4exb/sdrangel#933]
to decode the DAB transmitter identification information (TII) of all transmitters contributing to a multiplex and display the position (icons) of the transmitters on the map.

**Comment by srcejon** [comment]
Interesting idea - I'll take a look.

**Comment by srcejon** [comment]
I can receive the TII for an ensemble, which identifies a transmitter (E.g. specifies MainId and SubId). The question is how to map that to a position?

In ETSI EN 300 401 V1.4.1, section 8.1.9 describes the Transmitter Identification Information (TII) database, that maps MainId to Latitude and Longitude, using data in FIG0/22. However, in the latest version of the DAB spec, ETSI EN 300 401 V2.1.1, this section has been removed, and I don't see FIG0/22 being broadcast.

Might be able to get the data from https://www.fmlist.org/

**Comment by srcejon** [comment]
I've added this for the UK, using transmitter data from Ofcom:

![image](https://user-images.githubusercontent.com/57259258/217366391-6cbbba1e-5056-4308-87c6-8407478e033e.png)

But will need transmitter locations for other countries.

**Comment by choupette-change** [comment]
Thank you, I will look to adapt it for my country if I find royalty-free
information.
