### ISSUE TITLE
ATV Crash when adding demodulator

### ISSUE THREAD

**Issue by MMSSolutions** [f4exb/sdrangel#940]
Version 6.14.0

Currently have an issue where I go to add an ATV demodulator, but SDRAngel crashes immediately. This is a fresh install on a fresh install of windows.  Other demodulators work fine.

Any recommendations to fix or is this a current bug?

I have also tried to run as admin, but no luck, still crashes.

I have tried Pluto and Airspy devices.

Thanks
Matt

**Comment by srcejon** [comment]
Quite possibly related to the Scope issue: https://github.com/f4exb/sdrangel/issues/925 that has been fixed, as the ATV includes the scope.

**Comment by f4exb** [comment]
You can try the installer that you will find here: https://ci.appveyor.com/project/f4exb/sdrangel/builds/39754826/job/6phchv69ogl72ocb/artifacts

**Comment by MMSSolutions** [comment]
Thanks! That works fine.

**Comment by f4exb** [comment]
Fix deployed in v6.15.0
