### ISSUE TITLE
Web API update for "Satellite Radio Control" tabs in "Satellite Tracker" feature

### ISSUE THREAD

**Issue by Valstee** [f4exb/sdrangel#953]
Hi @f4exb, @srcejon, 
Is it possible to PATCH "Satellite Radio Control" settings (in the Satellite tracker feature) using the web API ?
It will be perfect to control my small "raspberry ground station" with sdrangel server !
Thanks a lot for your answer,
Valentin

**Comment by srcejon** [comment]
Not at the moment.  The radio control settings aren't yet accessible.

**Comment by Valstee** [comment]
Ok ! Thanks for your answer @srcejon, it could be great  ;-)

**Comment by srcejon** [comment]
This should now work. You can add settings with something like:

    curl -X PATCH "http://127.0.0.1:8091/sdrangel/featureset/0/feature/0/settings" -d '{"featureType": "SatelliteTracker",  "SatelliteTrackerSettings": {  "deviceSettings": [ {  "satellite": "ISS",  "deviceSettings": [ { "deviceSet": "R0", "doppler": [0], "frequency": 0, "presetDescription": Sat", "presetFrequency": 145.825, "presetGroup": "ISS Digi", "startOnAOS": 1, "startStopFileSinks": 1, "stopOnLOS": 1}] } ] }}'

**Comment by Valstee** [comment]
Yes really good! I confirm you that it works! A huge thanks! 🥇 
Can I close the issue or are there still things to do? (because you said "start to add")

**Comment by srcejon** [comment]
Yep, you can close - another patch was needed - but I forgot to tag it with this issue number.
