### ISSUE TITLE
Display problem with the pager demodulator

### ISSUE THREAD

**Issue by choupette-change** [f4exb/sdrangel#961]
![image](https://user-images.githubusercontent.com/68333247/125769192-b5bfa5a7-ca7d-4a75-9246-4c7d7b0719b5.png)
If I use only one demodulator, I have access to all the settings of the "waveforms" part.

![image](https://user-images.githubusercontent.com/68333247/125769781-cb671e5c-76ea-4f8c-87bb-04bdef682675.png)
If I use several (at least 2 simultaneously), I no longer have access to all the possible settings of the "waveforms" window of the demodulator ?? Same problem with Windows and ubuntu 21 04 versions.
Can you help me ?

**Comment by choupette-change** [comment]
Same problem with AIS Demodulator. An another question : Is it possible to plan to configure (different color) the scrolling bars, they are difficult to distinguish in strong light or penumbra?

**Comment by srcejon** [comment]
The above patch should fix it for Pager, AIS and Radio Clock.

If you want different themes, I'd suggest opening a new issue.
