### ISSUE TITLE
No RTL-SDR in Ubuntu 20.04

### ISSUE THREAD

**Issue by Pablo849** [f4exb/sdrangel#965]
I have installed the software on Ubuntu and I cannot see RTL-SDR in the list of sampling devices. I have tried both installing the DEV file and compiling the source code. I have also defined the LD_LIBRARY_PATH. Any suggestion? Thank you.

**Comment by Pablo849** [comment]
I solved issue with 
`sudo apt-get install -y rtl-sdr`
I propose to add this step to the documentation.

**Comment by f4exb** [comment]
Pls check this: https://github.com/f4exb/sdrangel/wiki/Compile-from-source-in-Linux
