### ISSUE TITLE
DRM-30 Modem Request 

### ISSUE THREAD

**Issue by CasualArclamp** [f4exb/sdrangel#979]
It would be a great asset to add a DRM-30 Modem int sdr angel. Also in the way of codecs, it would need to have xHE-AAC and the current Version of Dream DRM doesn't support it and the modded version crashes at low SNR.

**Comment by CasualArclamp** [comment]
@f4exb what do you think?

**Comment by f4exb** [comment]
I think this has been requested before: https://github.com/f4exb/sdrangel/issues/106 and I have no time to deal with it so you are very welcome to contribute.
