### ISSUE TITLE
AUTO Domain resolving for kiwisdr radio

### ISSUE THREAD

**Issue by CasualArclamp** [f4exb/sdrangel#982]
its real annoying to use windows ping to resolve ip's for the sdrangel reciver

**Comment by f4exb** [comment]
It works already ...
![image](https://user-images.githubusercontent.com/6192319/128722276-cf789eaa-dcea-4741-b1ae-26c9850f96a1.png)

**Comment by CasualArclamp** [comment]
ah, wasn't working for me before. ill try it again

**Comment by f4exb** [comment]
question answered
