### ISSUE TITLE
Build instruction for janus server

### ISSUE THREAD

**Issue by Valstee** [f4exb/sdrangel#989]
Just a proposal in the compilation [instructions](https://github.com/f4exb/sdrangel/wiki/Networking-audio#build-install)
Since libsrtp has been upgraded to version 2.3.0. you have to add this flag when compiling janus server in accordance with this [update](https://janus.conf.meetecho.com/docs/FAQ#aesgcm) : `./configure --prefix=/opt/install/janus --disable-aes-gcm`
Valentin

**Comment by f4exb** [comment]
Done: https://github.com/f4exb/sdrangel/wiki/Networking-audio#build-install
