### ISSUE TITLE
API - Invalid JSON request for APT Demodulator

### ISSUE THREAD

**Issue by Valstee** [f4exb/sdrangel#995]
Hi @f4exb, 
I've got an issue with APT Demodulator and the API.
API request **PATCH or PUT** `/sdrangel/deviceset/{deviceSetIndex}/channel/{channelIndex}/settings` returns a **Error 400 : Invalid JSON request.** with APT Demodulator
even with the default/exemple values.
Do you have the same issue ?
Thanks,
Valentin

**Comment by f4exb** [comment]
Quite possibly this is a bug and the APT Demodulator reference is missing in this map: https://github.com/f4exb/sdrangel/blob/master/sdrbase/webapi/webapiutils.cpp#L24

**Comment by f4exb** [comment]
Implemented in v6.16.5
