### ISSUE TITLE
Crashes / where is the config?

### ISSUE THREAD

**Issue by sgofferj** [f4exb/sdrangel#999]
I'm having a problem with the latest release under Ubuntu 20.04. I have a channel analyzer channel open and when I try to close it, sdrangel crashes. I would like to wipe the config but I couldn't find where sdrangel stores its config data.
Please advise.

**Comment by srcejon** [comment]
$HOME/.config/f4exb/SDRangel.conf I think

**Comment by sgofferj** [comment]
Indeed, there it is... Thanks!

**Comment by sgofferj** [comment]
Wiping the config solved the immediate issue but I tried again and at least on my system, when I add a channel analyzer, I can't get rid of it any more. When I close it, SDRA crashes and after re-opening, the channel analyzer is back. Using latest release on Ubuntu 20.04 LTS.

**Comment by srcejon** [comment]
It works for me.

You could try:

$ sudo apt-get install gdb
$ gdb /opt/install/sdrangel/bin/sdrangel
(gdb)run

Then after it crashes:
(gdb) info stack

And post the output here.
